### ISSUE TITLE
barrels/crates/bookshelf chests don't show name in GUI, barrel item doesn't keep name when block is broken

### ISSUE THREAD

**Issue by WarlordWossman** [svenhjol/Charm#101]
In vanilla naming a chest in an anvil results in its GUI displaying the custom name:
![chest_name](https://user-images.githubusercontent.com/16925725/59984938-70677080-962e-11e9-8e6d-1119bfd6cbb5.PNG)

In charm the bookshelf chest/crate/barrel doesn't have that feature.
Additionally only a named crate broken in the world will return an item that keeps the name, the barrels lose their naming when broken in the world.
Bookshelf chest I couldn't test because of #100 

All in all minor issue, your call if we need this.

**Comment by svenhjol** [comment]
Scheduled for 1.2.0
