### ISSUE TITLE
[Enhancement] More robust composter

### ISSUE THREAD

**Issue by hgsbsn** [svenhjol/Charm#103]
Might be nice for the composter to accept rotten flesh and spider eyes? flesh-to-bone meal is a good early game use for dead zombies.

**Comment by svenhjol** [comment]
You can add it to the charm config if you want to customize it. For example:
```
# These items have a 50% chance of adding a level of compost.
        S:"Items with 50% chance" <
            [...]
            minecraft:rotten_flesh
         >
```
