### ISSUE TITLE
[1.2.0 alpha1] some structure maps have tooltip in villager UI

### ISSUE THREAD

**Issue by WarlordWossman** [svenhjol/Charm#105]
For this map I can get a rough idea where the desert temple is before trading for the map:

![2019-06-27_17 21 12](https://user-images.githubusercontent.com/16925725/60279969-58c80a80-9902-11e9-890d-4229e50f71f9.png)

This one seems to work properly tho:

![2019-06-27_17 21 45](https://user-images.githubusercontent.com/16925725/60280072-7b5a2380-9902-11e9-895c-de389a3d3714.png)

Did you just forget the nbt to make the map unknown in the UI?
Anyways you probably agree that it shouldn't be visible at that stage :D

**Comment by WarlordWossman** [comment]
Oh it happens when you have the same map in your inventory, same thing happens with quark.
I guess this is not an issue then and can be closed?

**Comment by svenhjol** [comment]
Yep, I think this behavior is ok for now.
