### ISSUE TITLE
[Bug/crash] Placed Beacons cause server side crash.

### ISSUE THREAD

**Issue by Akitori** [svenhjol/Charm#107]
Hi. I placed a beacon in the world before installing charm. Upon launching the server, this crash happens.

https://pastebin.com/niLn00nk

Disabling Charm ASM Beacon allows me to access world. Do i need to replace beacon? Thanks in advance!

**Comment by svenhjol** [comment]
Thanks for report, I'll look into it

**Comment by yrsegal** [comment]
https://github.com/svenhjol/Charm/blob/master/src/main/java/svenhjol/charm/base/CharmClassTransformer.java#L227-L232

These need to have obfuscation checks. See my implementations in Quark ASM for reference. You should not access fields in ASM if you can avoid it; do it in your compiled code instead.

**Comment by svenhjol** [comment]
This hasn't been forgotten, I've just been busy with RL. Will schedule an update of all the ASM so it matches Quark.
