### ISSUE TITLE
some filled crates stack

### ISSUE THREAD

**Issue by WarlordWossman** [svenhjol/Charm#109]
![2019-07-05_09 30 38](https://user-images.githubusercontent.com/16925725/60706325-8536e480-9f09-11e9-9f15-1beb611ff980.png)

Seems like some full crates still stack, would probably be best if crates that are anything but empty would never stack.

**Comment by svenhjol** [comment]
Thanks for logging this, I completely forgot about it!

**Comment by WarlordWossman** [comment]
Something about them is off in general, now got 2 of them empty (with the same default name) that don't stack. For barrels I just had one that was placed in the world once and one that was not and they didn't stack but I thought that was the "keeping the name" change, seems like the 2 crates I have now have both been placed and broken but still don't stack even if empty and same name :D

**Comment by svenhjol** [comment]
Cheeky to just set crate stack size to 1?

**Comment by WarlordWossman** [comment]
It's kinda how shulkerboxes work at the moment as well, I would like both empty crates and empty shulkerboxes to stack eventually but that's really comming from a lategame perspective where you know you will need good storage sollutions for a whole lot of items, ending up with 10 doublechests just for empty crates defeats the purpose imo.

So yeah I feel like it would be better to keep them stacking because they are a utility in the first place.

**Comment by svenhjol** [comment]
I'll have to spend more time on this after 1.2 is out.

**Comment by svenhjol** [comment]
Reverted stack size "fix" for now, so this bug will remain in the next minor version. After 1.2.0 I'll do some proper investigation. I seem to remember Immersive Engineering crates stack when empty but not when filled so I'll use that as the starting point :)
