### ISSUE TITLE
Golem spawn rate is dramatically high

### ISSUE THREAD

**Issue by duely** [svenhjol/Charm#11]
I couldn't find a way to configure this.

Here's a few screenshots of the first village that I came across after installing Charm: ![](https://i.imgur.com/PMfkD43.jpg)

![](https://i.imgur.com/RBv2QDB.jpg)

I'm not sure if Muon is perhaps interacting strangely, but I also noticed issues with Mushrooms having halves moved from the actual mushroom structure down into the ground. I noticed there is an issue specifically for outer village decoration configuration; I greatly look forward to that next time I try Charm.

**Comment by svenhjol** [comment]
Thanks for logging this. muon seems really nice, I can't believe I haven't come across this mod already! 

I'm working on making outer deco gen configurable as part of the next release (see #10) and will reduce golem spawn in that too. 

Also I'll install muon and have a play.

**Comment by duely** [comment]
Muon is an amazing mod! It makes me super-sad that it seems to have not much in the way of active development, but the benefits that it brings to improving pathing and placement of entrances is really nice. I've very, very rarely had an issue where some vertical/mountain-like planes nearby ended up ... partially disintegrated -- and I haven't had it outside of that one first time, which could've been ANYTHING.

**Comment by svenhjol** [comment]
If the original author isn't up for continuing, I'd like to see this get merged into Charm or at least get I would like to get involved in more active development.  By the way I found an additional bug that was spamming the same type of mob (in some cases, golems) because of using the wrong kind of random seed. Alpha5 should sort it out.
