### ISSUE TITLE
filling cauldron deletes rest of water bottle stack

### ISSUE THREAD

**Issue by WarlordWossman** [svenhjol/Charm#110]
Clicking with a stack>1 of water bottles on a cauldron (to fill it) deletes the rest of the stack, this is probably a quirk that wasn't found/tested when water bottles were tweaked to stack to 16!

You also have to keep in mind that with unstackable water bottles there will always be the space of the water bottle you used on a cauldron free for the empty bottle in vanilla, so if the rest of the inventory is full and there is no space it should probably drop the empty bottles on the floor just like water bottles do when you fill them and have no space in your inventory!

**Comment by svenhjol** [comment]
Yeah this kind of thing happened with brewing stand too before I patched it.
