### ISSUE TITLE
Change Composter Collision to be like the cauldron

### ISSUE THREAD

**Issue by SirSquidly** [svenhjol/Charm#112]
Collision as in being able to enter it like the cauldron, with the walls around ya'

**Comment by svenhjol** [comment]
Could you confirm whether this happens in the vanilla 1.14 composter? I haven’t got the chance to check that for a few days

**Comment by SirSquidly** [comment]
It absolutely does. Also, just to clarify, the collision doesn't change by the level.

**Comment by svenhjol** [comment]
Will be in next version 1.1.15. Thanks for the report
