### ISSUE TITLE
Improve Rotten Flesh Block texture

### ISSUE THREAD

**Issue by SirSquidly** [svenhjol/Charm#113]
The current Flesh Block texture is very compressed and high contrast, almost near the levels of the April fools day "perfected textures".

Here's an example I threw together for something which might look slightly better:
![2019-07-05_20 48 31](https://user-images.githubusercontent.com/13826553/60751183-5a2eae00-9f66-11e9-8eef-bc5b7febc7d3.png)
A little ugly, but Rotten Flesh itself is ugly.

**Comment by WarlordWossman** [comment]
Looks very desaturated imo, almost reminds me of texture packs where they use light grays and browns for all the blocks. I don't dislike the idea but I feel like it's very light and could use a bit more contrast.

**Comment by svenhjol** [comment]
Can we see a version with more contrast and slightly darker so it matches the item a bit more?

**Comment by SirSquidly** [comment]
How's something like this?

![2019-07-08_14 35 57](https://user-images.githubusercontent.com/13826553/60844330-cf2ffc80-a18d-11e9-82ce-9ea1df5b11ce.png)

**Comment by svenhjol** [comment]
Contrast is definitely better, but I think the diagonal repeating pattern might be a bit too obvious now. Sorry to be annoying.

**Comment by SirSquidly** [comment]
This looks slightly better?

![2019-07-08_15 48 49](https://user-images.githubusercontent.com/13826553/60847577-eecc2280-a197-11e9-856d-e944fe1648a2.png)

**Comment by svenhjol** [comment]
Yeah, I like it. @WarlordWossman  ?

**Comment by WarlordWossman** [comment]
Sure let's give this one a try next alpha, gotta see it ingame :D

**Comment by SirSquidly** [comment]
Here's the texture itself.

![rotten_flesh_block](https://user-images.githubusercontent.com/13826553/60852182-6fe0e500-a1ab-11e9-9eee-b57382fa283a.png)

**Comment by svenhjol** [comment]
Thanks, will bake into alpha3

**Comment by svenhjol** [comment]
![2019-07-09_16 37 31](https://user-images.githubusercontent.com/26497903/60907103-39b56b00-a268-11e9-9963-6231a119203d.jpg)

**Comment by svenhjol** [comment]
Looks pretty sweet

**Comment by SirSquidly** [comment]
Sorry to necro this as it's already closed, but here's an update image for your website

![BOP OP](https://user-images.githubusercontent.com/13826553/61318070-0ff4ca80-a7b9-11e9-9b27-6c45c3bf5301.png)
