### ISSUE TITLE
[Version 1.1.13] Sometimes jungle villages generate made out of oak wood.

### ISSUE THREAD

**Issue by DeadPigman17** [svenhjol/Charm#114]
Not all of them generate made out of oak, but some of them do. Here's a screenshot: 
![2019-07-07_13 54 50](https://user-images.githubusercontent.com/22800252/60767945-3d59be00-a0bf-11e9-8cd4-08fc3546b317.png)

**Comment by svenhjol** [comment]
What’s the seed and coordinates please?

**Comment by QuantumStatement** [comment]
It happens when village occasionally generates in River biome
![2019-07-09_13 20 59](https://user-images.githubusercontent.com/35406698/60880499-6f4c5b00-a24c-11e9-9171-0a755b064110.png)

**Comment by svenhjol** [comment]
Vanilla village generation will start at the well and take whatever the biome is at those co-ordinates. As you said this will happen occasionally and to change this behavior (for example taking the biome that most buildings generate within and then altering all the wood) would be too much development effort. If you're finding that none of the villages in jungles are generating with jungle wood then please re-open this issue and I'll investigate. Thanks
