### ISSUE TITLE
Village Decoration Config is Ignored

### ISSUE THREAD

**Issue by Tetrajak** [svenhjol/Charm#119]
Forge Build: 2831
Mod Version: 1.2.0

I've altered the village decorations section of the config several times in an attempt to reduce the frequency of some features, even going so far as to turn VillageDecorations to false, but all the decorations still spawn at the default frequencies.

**Comment by WarlordWossman** [comment]
Are you sure you reset the world or at least loaded new villages after changing the config?

**Comment by Tetrajak** [comment]
Yes, every time I changed the config I restarted Minecraft then created a new world. Does it make a difference that I was recreating the same world with the same seed every time?

**Comment by WarlordWossman** [comment]
No, that should have been fine since you repopulated the chunks.
Sorry for asking that many basic questions but did you make sure to save the config file and restart the game in between?
I have tried around with the config a bit and it seemed to work, that's why I am asking rather specifically.

**Comment by svenhjol** [comment]
@Tetrajak please could you send your charm.cfg and I'll test it locally. Thanks!

**Comment by Tetrajak** [comment]
Turns out I was using an old config. After deleting the configs and letting them regenerate, changing the village decoration related settings works.
