### ISSUE TITLE
jei layer in charm containers

### ISSUE THREAD

**Issue by WarlordWossman** [svenhjol/Charm#12]
It seems like JEI takes priority over tooltips in charm containers, any other inventory has it the other way around, easier to see with a few screenshots:

![2019-04-12_15 39 31](https://user-images.githubusercontent.com/16925725/56041875-1008a880-5d3a-11e9-9314-ba43d98564f7.png)
![2019-04-12_15 41 23](https://user-images.githubusercontent.com/16925725/56041877-126b0280-5d3a-11e9-91fb-68b780c8c398.png)

As a reference, here is a vanilla chest, where the tooltips are always the highest layer:
![2019-04-12_15 39 20](https://user-images.githubusercontent.com/16925725/56041966-49d9af00-5d3a-11e9-82c3-9615e2b5dc04.png)

**Comment by svenhjol** [comment]
Good spot, thanks
