### ISSUE TITLE
can't check charm containers in spectator mode

### ISSUE THREAD

**Issue by WarlordWossman** [svenhjol/Charm#120]
Mainly a reminder that charm containers cannot be clicked in spectator mode unlike some vanilla inventories like chests, hoppers, brewing stands etc. Quark chests do work if a reference is needed.

Pretty sure vanilla calls another method when the player is in spectator mode since it also doesn't play the sound or triggers the chest opening animation.

**Comment by svenhjol** [comment]
There is a check for spectator mode; I'll check how Quark is doing this. Incidentally loot isn't generated in abandoned crates until broken so I guess we'll need the "Loot not generated yet" message that you get as a spectator looking at dungeon/mineshaft chests.
