### ISSUE TITLE
Crates Spawn Everywhere in Superflat

### ISSUE THREAD

**Issue by aimbait** [svenhjol/Charm#125]
New chunks loaded with Charm have Crates literally everywhere. Can you disable their generation in superflat worlds?

**Comment by svenhjol** [comment]
I just kicked off a new superflat world and I'm struggling to find any abandoned crates. Can you let me know what version of Charm you're using as there may have been a fix for crate generation

**Comment by svenhjol** [comment]
Please reopen this issue if it continues to do so, with the version of Charm and any other steps to reproduce.
