### ISSUE TITLE
Possable mod intigration into charm

### ISSUE THREAD

**Issue by SpGilbert** [svenhjol/Charm#128]
https://www.curseforge.com/minecraft/mc-mods/time-arrow 
a neat mod that you could possibly integrate into Charm.
I have messaged the creator on curseforge and they have stopped updating it.

**Comment by svenhjol** [comment]
I don't understand the point of this based on the mod's description. What is the function?

**Comment by SpGilbert** [comment]
it's an arrow that when you shoot it freezes in place and when you press the v button it fires.
I think it could be an extremely rare arrow that does not work with infinity.

**Comment by svenhjol** [comment]
Sorry, it’s not a good fit for Charm. Maybe another developer will pick it up
