### ISSUE TITLE
"Improving recycling" don't work properly with modded furnaces

### ISSUE THREAD

**Issue by QuantumStatement** [svenhjol/Charm#132]
Minecraft 1.12.2
Charm 1.2.2

"Improving recycling" function only works properly with vanilla furnace. With modded furnaces (for example from IndustrialCraft 2 or Galacticraft) it always give maximum amount of nuggets regardless of item damage

Vanilla furnace
![2019-08-01_22 59 47](https://user-images.githubusercontent.com/35406698/62323718-8deeec00-b4b0-11e9-9e82-bd065b991e7d.png)

Iron furnace (IC2)
![2019-08-01_23 02 12](https://user-images.githubusercontent.com/35406698/62323734-9515fa00-b4b0-11e9-8fa4-2d84b8d03d4b.png)

**Comment by WarlordWossman** [comment]
I think it would be rather impossible to be compatible with every modded furnace when it comes to this feature and it's not like you can generate iron or gold from nothing with this.
We will wait what svenhjol has to say but I am 99% sure that's something you might have to live with.

**Comment by svenhjol** [comment]
You can check if Charm mod is present, then wrap around the `FurnacesRecycleMore` feature class, calling `changeSmeltingResult()` with your input item. The output will be the correct number of nuggets based on the item damage. I understand that it's not ideal to call this method directly for now until I build an API for it, but that's the only suggestion that I have for now.
