### ISSUE TITLE
Trees in villages sometimes spawns with cocoa beans

### ISSUE THREAD

**Issue by QuantumStatement** [svenhjol/Charm#133]
Minecraft 1.12.2
Charm 1.2.2

Villages' oak trees with vines sometimes spawns with cocoa beans on logs
![2019-07-19_16 20 30](https://user-images.githubusercontent.com/35406698/62324181-9693f200-b4b1-11e9-8c94-31e19d82c639.png)

**Comment by svenhjol** [comment]
This is vanilla nonsense. When the tree generator runs, and vines are enabled (configurable in charm), there's a chance it will generate a cocoa bean. There's nothing I can really do about it at the moment without some kind of hack or creating a new generator, so if the cocoa beans are something you want to prevent then vines should be set to false.
