### ISSUE TITLE
Positive feedback in enchanted book trades, leading to infinite emeralds

### ISSUE THREAD

**Issue by KnightMiner** [svenhjol/Charm#134]
In the Charm World Villager Trade feature, you add three enchanted book related trades:

* 2-4 emeralds for Curse Break
* 2-4 emeralds for Salvage
* Any enchanted book for 1-4 emeralds

The problem with this is with a cheap Curse Break/Salvage trade and a good enchanted book trade, you can easily get the following scenario:

* 2 emeralds to buy one enchanted book (either Curse Break or Salvage works)
* Sell that enchanted book for 4 emeralds
* Net gain of 2 emeralds with no other cost

We have been abusing this loop on Vazkii's patreon server, but it really should be patched as it trivializes all emerald production. My main suggestion is to make the Curse Break and Salvage trades consistent with vanilla by charging both a book and emeralds for the enchanted book, but you should probably also increase the cost of Curse Break and Salvage.

Using Charm 1.2.2 for Minecraft 1.12.2

**Comment by WarlordWossman** [comment]
Yeah this sounds like it should be fixed, also like the idea to make the trades take a book for consistency.

**Comment by svenhjol** [comment]
A bug and an enhancement? :)

**Comment by WarlordWossman** [comment]
Bug as in it's not intended to get free emeralds and an enhancement as in "let's make the trades consistent with vanilla" :^)
