### ISSUE TITLE
Force enable barrels were never added

### ISSUE THREAD

**Issue by Gavintime** [svenhjol/Charm#135]
On charm 1.2.2 there is no force enable barrel option in the config file

this was said to be built into charm 1.2 in #117

**Comment by WarlordWossman** [comment]
![barrel](https://user-images.githubusercontent.com/16925725/62364034-cfb77b00-b520-11e9-9469-2f2b19cd3145.PNG)

It's there for me, at the bottom of the "CharmCrafting" section in the config. can you confirm if it doesn't appear there for you?

**Comment by Gavintime** [comment]
I double checked, its not there. Here's my config file https://pastebin.com/r6nAf2jR

**Comment by WarlordWossman** [comment]
In that pastebin you have the barrel set to false, you might have to set it to true and launch with that setting for the config to generate the extra option, as in having the barrel on false "aborts" the config for it adjusting but only a guess.

**Comment by Gavintime** [comment]
I re-enabled the barrel option and launched the game, nothing was changed or added to the config file

**Comment by WarlordWossman** [comment]
Sorry to be annoying about it but do you have future MC installed? Maybe launch without it if so? That's the only thing I could think of, otherwise this might be a bug somehow :D

**Comment by Gavintime** [comment]
Disabling Future MC and launching minecraft made the option appear.

**Comment by WarlordWossman** [comment]
Thanks for testing, glad it was just that!

**Comment by Gavintime** [comment]
If FutureMC is re enabled after the setting is created, it is ignored and charms barrels are never added to the game. Also, shouldn't the setting be generated in the config file regardless if futuremc is installed or not? Since the option is made specifically for use with futuremc or similar?

**Comment by WarlordWossman** [comment]
Oof so it doesn't work at all...
Not sure about the config stuff, might have to wait what svenhjol has to say about it.

**Comment by svenhjol** [comment]
Fixed in 1.3.0 as part of config overhaul

**Comment by svenhjol** [comment]
Should be deployed in 1.3.0 - 1.3.1. If still not working please reopen.
