### ISSUE TITLE
[Feature Request] JEI support for cakes

### ISSUE THREAD

**Issue by Zygus42** [svenhjol/Charm#139]
You add flavored cakes, and they show up in JEI, but the method for making them does not.  Would be nice if it did.

**Comment by WarlordWossman** [comment]
Many things that happen in the world have no JEI explanation like concrete powder touching water converting to solid concrete. I think one of those info texts might be good for flavored cakes where it tells you to rightclick a cake in the world with an extended potion or using a dispenser to do it.

**Comment by Zygus42** [comment]
I'm building a mod pack, and there's no way that anyone playing is going to know to do that and it's most unlikely that they'll go and look it up - they might, but i doubt it.  A tiny, easily-coded tooltip, and it goes from a pointless feature to something great that people will miss if it's not there anymore.

**Comment by WarlordWossman** [comment]
If anything the JEI info box makes more sense than a tooltip, if you want one for your modpack anyways I can suggest adding one with crafttweaker, it's really easy.

**Comment by WarlordWossman** [comment]
@Zygus42 thoughts on something like this?
![flavored_cakes_jei](https://user-images.githubusercontent.com/16925725/63111106-43c83900-bf8d-11e9-90b7-f4bd26dae324.PNG)
Should be clear enough I would say.

**Comment by Zygus42** [comment]
excellent

**Comment by svenhjol** [comment]
Done in 1.3.5
