### ISSUE TITLE
bookshelf chest texture problem in villages

### ISSUE THREAD

**Issue by WarlordWossman** [svenhjol/Charm#14]
I noticed that bookshelf chests spawn in villages but it seems like they only ever display the "empty" texture until the player clicks on them once which refreshes the texture to adjust to the slots being filled.
This is rather minor but could be misleading in a sense that people think nothing is in them.

**Comment by svenhjol** [comment]
I know. This one really annoys me and I never got to the bottom of it, I'm doing something wrong with the block updates somehow and I will have another hack at it.
