### ISSUE TITLE
Crash with Rats

### ISSUE THREAD

**Issue by mxnmnm** [svenhjol/Charm#140]
https://paste.dimdev.org/ivinuwaguq.mccrash

I was just chillin in a new world and boom crash should I post this on the rats github?

**Comment by svenhjol** [comment]
Thanks for the feedback. This is the same problem as issue #141 and will be addressed in a few hours. For now I recommend the previous version 1.2.2 or temporarily disable “Abandoned Crates” feature in config.

**Comment by svenhjol** [comment]
I would be grateful if you could test this build before I publish to CF.
https://github.com/svenhjol/Charm/releases/download/1.12.2-1.3.1/Charm-1.12.2-1.3.1.jar

**Comment by mxnmnm** [comment]
I think that fixed it
