### ISSUE TITLE
[Charm 1.12.2-1.3.1] Nether Gold Deposits don't respect config

### ISSUE THREAD

**Issue by TeetoKaziim** [svenhjol/Charm#143]
Setting 
```
    # Gold deposits spawn in the Nether that can be broken to receive gold nuggets.
    B:NetherGoldDeposits=false
```
And starting up with:
Forge 14.23.5.2838
Charm 1.12.2-1.3.1
Just Enough items 1.12.2-4.15.0.287
The One Probe 1.12-1.4.28

They still show up in JEI
And deposits still show up in the nether.

**Comment by svenhjol** [comment]
Confirmed happening with at least NetherGoldDeposits

**Comment by svenhjol** [comment]
Thanks for report, fixed in https://github.com/svenhjol/Charm/releases/download/1.12.2-1.3.2/Charm-1.12.2-1.3.2.jar
