### ISSUE TITLE
Duplication bug with Magnetic enchantment

### ISSUE THREAD

**Issue by yagomont** [svenhjol/Charm#147]
Using the Magnetic enchantment on Multiplayer (sponge server) will sometimes cause the item to duplicate many times, and flat out spawn unrelated items (breaking grass, for example, spawns torches and rails.)

**Comment by yagomont** [comment]
This can be reproduced the following way: Using the drop key, drop an item from your inventory
The item will fail to drop. You can press the drop key many more times to stack this drop, which will be spawned into the world as duplicated items as soon as a block is mined with the Magnetic tool.

**Comment by svenhjol** [comment]
I knew this was coming. The implementation I borrowed looked problematic in multiplayer but I didn't get chance to test it thoroughly. I recommend disabling magnetic in the config until we sort out a fix.

**Comment by yagomont** [comment]
Thing is, disabling magnetic on the server makes it so clients cannot connect.

**Comment by svenhjol** [comment]
Clients will need to disable it in their config as well, because of enchantment IDs.

**Comment by svenhjol** [comment]
Please test https://github.com/svenhjol/Charm/releases/download/1.12.2-1.3.3beta1/Charm-1.12.2-1.3.3-beta1.jar

**Comment by svenhjol** [comment]
It's been released, please let me know if you have any more issues by reopening this ticket.

**Comment by MeowingInsanely** [comment]
Hello, It seems to be reworking with Spongeforge 7.4.7 Charm mod version: **Charm-1.12.2-1.4.1**
