### ISSUE TITLE
some crates get a name nbt without anvil

### ISSUE THREAD

**Issue by WarlordWossman** [svenhjol/Charm#148]
While crates are mostly working as intended now there still seems to be a special case where they save the name in the nbt when they shouldn't (the crate was never renamed in an anvil).

I think what I did was placing a newly crafted crate, broke it, then placed it in another spot and put items in, broke again and it had a name nbt.
The other crates I only placed and filled directly didn't get named "oak crate" after I broke them, so something still automatically saves the name in the nbt when the crates have no anvil name to begin with.

**Comment by svenhjol** [comment]
Check this is the case for shulkerboxes too. I think it is.

**Comment by WarlordWossman** [comment]
Just tested, not the case for shulkerboxes.

**Comment by svenhjol** [comment]
If it's the "name" as part of the "BlockEntityTag", this is intentional. All Charm TEs have a name tag, it's different from "displayName"

**Comment by svenhjol** [comment]
![displayname - on anvil](https://user-images.githubusercontent.com/26497903/62887773-74aa3300-bd2d-11e9-88dc-aa764b229ec1.png)
![name - internal](https://user-images.githubusercontent.com/26497903/62887774-74aa3300-bd2d-11e9-904a-3f31c3fd3188.png)

**Comment by svenhjol** [comment]
display: {Name: "Oak Crate11"} is the nbt added by the anvil, and is what will be displayed in GUI etc.
BlockEntityTag: {name: ""} is an internal name that is given to all TEs in charm, and should not cause a conflict and can be ignored.
