### ISSUE TITLE
PlayerTicking?

### ISSUE THREAD

**Issue by Zarvera** [svenhjol/Charm#155]
I'm honestly not sure if it's even Charm, the only reason i'm reporting here is because it started right after i've made a few Lanterns and started changing torches for them, VanillaFix suspecting Charms and the fact that removing the mod stops the crash from happening
Apparently it happens whenever i enter any poorly lit area, or so it seems, though i don't think i have mods with Grue-like stuff
Here's pastebin: https://pastebin.com/5ARSgy2N

I'm retarted, says "haunting" right there. Disabling structure haunting stopped the crashes

**Comment by svenhjol** [comment]
Thanks, I'll look into it.

**Comment by svenhjol** [comment]
What is `at com.mrburgerUS.betaplus.beta_plus.ChunkGeneratorBeta.getNearestStructurePos(ChunkGeneratorBeta.java:217)` ? It's part of the stacktrace.
