### ISSUE TITLE
quark cakes register if quark is not present

### ISSUE THREAD

**Issue by WarlordWossman** [svenhjol/Charm#161]
Just tested and loading charm without quark being there still generated the 4 cakes for the quark potions. Sure taking it out of the config does fix it but it would be better if they don't register without quark in the first place so people can keep the default config and if they later decide to install quark they would still be around.

**Comment by svenhjol** [comment]
Should be fixed in 1.3.6 https://github.com/svenhjol/Charm/releases/download/1.12.2-1.3.6/Charm-1.12.2-1.3.6.jar
