### ISSUE TITLE
Abandoned Crates doesn't generate in JED's dimensions

### ISSUE THREAD

**Issue by Yldales** [svenhjol/Charm#163]
Hello,

I'm using a mod called [Just Enough Dimensions](https://www.curseforge.com/minecraft/mc-mods/just-enough-dimensions) to create a secondary world for gathering ressources. Sadly, the Abandoned Crates from the World Module doesn't seem to generate in this secondary world (note: Village decorations works well).

I'm using **Charm 1.3.4** for Minecraft 1.12.2, with **Forge 14.23.5.2838**.

charm.cfg: https://pastebin.com/raw/Kcnnhg8A
dimensions.json (from JED): https://pastebin.com/raw/WNTuP84L

**Comment by svenhjol** [comment]
The Abandoned Crates only generate in dimension 0 (overworld) at the moment. At some point in the future there will be a configuration option for this.

**Comment by svenhjol** [comment]
Added to roadmap board here: https://trello.com/c/08MIpvXf
Please track on this board, closing this ticket.
