### ISSUE TITLE
Crash when strongholds are disabled

### ISSUE THREAD

**Issue by comp500** [svenhjol/Charm#165]
When using Customised world generation and turning off Strongholds, the Spectre Haunting feature causes the game to crash when it tries to look for a Stronghold. I think the crash only occurs when the player gets close to a structure, like a mineshaft (although this may have just been coincidental, when I went into the mineshaft the light level at my position decreased).

Crash Log: https://paste.ee/p/uJ1yu

Minecraft 1.12.2
Forge 14.23.5.2838
Charm 1.12.2-1.3.5

**Comment by svenhjol** [comment]
Thanks for the report, will look into it.

**Comment by svenhjol** [comment]
Please test this release (using the same world or conditions) and let me know if the problem occurs.
https://github.com/svenhjol/Charm/releases/download/1.12.2-1.3.6/Charm-1.12.2-1.3.6.jar

**Comment by comp500** [comment]
The same error still occurs: https://paste.ee/p/1iGbq
I think the bug might be in `getNearestStructurePos` (vanilla code), as turning off Strongholds with a Customized world breaks the `/locate` command.

**Comment by svenhjol** [comment]
And when you turn off strongholds, you mean turning structures off, is that right?

**Comment by comp500** [comment]
No, I mean changing the world type to Customized, then turning off Strongholds in the first settings window.

**Comment by svenhjol** [comment]
I've re-uploaded the jar file here: https://github.com/svenhjol/Charm/releases/download/1.12.2-1.3.6/Charm-1.12.2-1.3.6.jar

Please could you test this version? Potion of Ender Sight was also crashing in a customized world because of the same issue, and this also appears to work now.

**Comment by comp500** [comment]
That does seem to be fixed, thanks!

**Comment by RyanCR03** [comment]
What is spectre Haunting?
