### ISSUE TITLE
variable redstone lamp issues

### ISSUE THREAD

**Issue by WarlordWossman** [svenhjol/Charm#166]
Variable redstone lamp seems to be messed up, you can instantmine it by hand in survival and it drops a regular redstone lamp. It also uses stone sounds instead of the glass ones, really strange stuff going on.

**Comment by svenhjol** [comment]
Should be fixed in 1.3.6 https://github.com/svenhjol/Charm/releases/download/1.12.2-1.3.6/Charm-1.12.2-1.3.6.jar
