### ISSUE TITLE
Item with "salvage" enchantment drop a copy when placed in frames

### ISSUE THREAD

**Issue by MazzoPowah** [svenhjol/Charm#167]
When placing an item that includes the "salvage" enchantment in any item frame, a copy of the item is dropped at the player's feet.
The item is an exact copy of the placed item, but the durability is reduced to 1 health.
Hitting the frame to recover the original item works as intended (the item is recovered with the durability points not altered).

Versions used:
Minecraft: 1.12.2
Forge: 14.23.5.2838
Charm: 1.12.2-1.3.5

Let me know if you require further information.

**Comment by svenhjol** [comment]
Thanks for the report, I'll look into it.

**Comment by SandwichHorror** [comment]
Seconded, this bug still persists in the current version.
