### ISSUE TITLE
Crash with Mystcraft

### ISSUE THREAD

**Issue by BrisingrAerowing** [svenhjol/Charm#17]
[Crash Log](https://paste.dimdev.org/rawidibiko.mccrash)

Mystcraft was in the middle of profiling when this happened.

Charm Alpha 3.

**Comment by svenhjol** [comment]
Is this still an issue with alpha4? I was able to successfully create a mystcraft age with villages and find them without any issues. The original problem was down to the method I used to locate the nearest village not working in a mystcraft dimension.

**Comment by BrisingrAerowing** [comment]
It's fixed. I noticed alpha 4 shortly after I posted.
