### ISSUE TITLE
Crash within hunting dimension

### ISSUE THREAD

**Issue by JWTHDYTWA** [svenhjol/Charm#170]
Staying in [**Hunting Dimension**](https://www.curseforge.com/minecraft/mc-mods/hunting-dimension) causes server crash. Here is [**Crashlog**](https://gist.github.com/Warrock3280/e9288a27225c42212e20f63a0c9a0d27).
Charm: 1.3.6
Hunting Dimension: 1.0.39

**Comment by Warrock3280** [comment]
Same problem with RFTools Dimensions.

**Comment by nephatrine** [comment]
Same problem with Lost Cities. I'm just disabling Spectre Haunting for the time being and that seems to prevent the issue.

**Comment by zauberparacelsus** [comment]
I am also having problems with crashes on RFTools Dimensions.

Crash logs:
https://paste.dimdev.org/efuhubozew.mccrash
https://paste.dimdev.org/petubafiwe.mccrash
https://paste.dimdev.org/lovedafelu.mccrash

@nephatrine This issue is caused by spectres?

**Comment by hron84** [comment]
It's still an issue.

**Comment by tsssp** [comment]
Same problem with RFTools Dimensions.

**Comment by Ced7032** [comment]
2 years later still an issue

**Comment by ThePrawnstar** [comment]
What is spectre hunting? Another reply said to disable it, but no google searches have revealed what it is or where to find it
(I'm having an issue with the lost cities)
