### ISSUE TITLE
[Bug] No rats from the Rats mod can be damaged while no tamed animal damage is on

### ISSUE THREAD

**Issue by DWX12** [svenhjol/Charm#171]
Charm-1.12.2-1.3.6
rats-2.0.0

While the config option for no tamed animal damage is on, no rat, regardless of it being wild or actually tamed, takes any damage from players. However, this isn't always the case since I've been able to kill them and other times I've done no damage to them. If the pied piper is controlling rats, rats cannot be damaged.

The issue might be from rats going in and out of hostile mode, but that's just a guess. Turning off no damage to tamed animals seems to work so far for damaging and killing rats.

**Comment by WarlordWossman** [comment]
It sounds like rats is using some of the taming mechanics to their advantage to me, I am not sure if there is much that can be done, you might have to keep that feature turned off or report the issue to the rats author.
