### ISSUE TITLE
support oredict in the composter config

### ISSUE THREAD

**Issue by Malrama** [svenhjol/Charm#173]
Hello :)

I am using the most current version of charm for minecraft 1.12.2 and I noticed that the composter only accepts vanilla seeds but not seeds added from other mods e.g. Flax seeds from actually additions. Now I am not sure if that is an error on my end and a configuration thing but I would like to report this.
I am not sure if you guys have to add support for every single seeds out there (which is impossible) or if there is something like a generic "seeds" object thing so that the composter can use seeds and plant parts for every mods.

Thank you very much

**Comment by nickjackson-ff** [comment]
Agreed. Composter with oredict support would be incredible (ex. "ore:seed", "ore:listAllFood", etc.)

**Comment by WarlordWossman** [comment]
You can add items in the charm config and there is also a wildcart system for metadata, but I can see how oredict would be nice to have. Svenhjol is currently busy so it might take a while!

**Comment by williambl** [comment]
I'll make a PR that adds oredict support as part of [Hacktoberfest](https://hacktoberfest.digitalocean.com/), if you're okay with that :D (I'd also like to make a PR to make nether gold deposit drops configurable if you want [#176]) @WarlordWossman

**Comment by WarlordWossman** [comment]
Feel free to make both those PRs if you like but they will sadly not make it into a build until Svenhjol returns, I am mostly helping out with the mod, assembling builds for release is tied to him as of now.

**Comment by williambl** [comment]
Ok, thanks.

**Comment by WarlordWossman** [comment]
@williambl thanks for the PRs, just talked to Svenhjol and he will probably return in november!
