### ISSUE TITLE
Magnetic and Salvage enchantment can be applied multiple times in Quark's Enchanting Matrix

### ISSUE THREAD

**Issue by Tohricat** [svenhjol/Charm#174]
For some reason, you can receive 'Magnetic' and 'Salvage' more than once when using Quark's new enchantment mechanics. This results in a wasted 'tetris piece' because you can't upgrade them if you already have one.

**Comment by WarlordWossman** [comment]
That's odd, I am pretty sure the enchanting matrix shouldn't act like this for level 1 enchantments. There might not be much that can be done on Charm's end and Quark seems to focus on porting to 1.14 at the moment.
Could you maybe check if other mods add level 1 enchantments that act up in the same way to find out if it's something specifically happening to Charm's enchantments?
