### ISSUE TITLE
Incompatibility with FutureMC

### ISSUE THREAD

**Issue by Tohricat** [svenhjol/Charm#175]
When FutureMC's barrels or lanterns (any conflicting items, really) are loaded, Charm disables its barrels (which is really neat). However, if I disable FutureMC's barrels or lanterns in its config, Charm still disables its barrels/lanterns. This is frustrating, as Charm's barrels are a lot better than FutureMCs!

**Comment by Tohricat** [comment]
Turns out this can be overridden in the config.

**Comment by Tohricat** [comment]
Looks like the config option doesn't work.

**Comment by WarlordWossman** [comment]
I just tested this myself with both Charm and Future MC and by turning off barrels and lanterns in the config of Future MC and enabling the Charm configs to force barrels and lanterns I ended up with Charm barrels and lanterns.
Can you please test it again and report back? It seems to work fine for me.
