### ISSUE TITLE
Nether Gold Deposit gives too little gold 

### ISSUE THREAD

**Issue by Tohricat** [svenhjol/Charm#176]
The original Nether Gold Deposit mod (which I think is what you are basing it off of as the textures are very similar/the same) dropped clusters of golden nuggets, while these only drop one. This makes NGPs significantly less useful than they are in the original mod.

**Comment by WarlordWossman** [comment]
I am pretty sure dropping 1 nugget is intended, but maybe a config to define the number (or possibly even a range) could be added.
