### ISSUE TITLE
QoL: Mod Menu Config

### ISSUE THREAD

**Issue by IdrisQe** [svenhjol/Charm#177]
Hi! I adore this mod, it's one of my must-haves for quality of life and misc improvements/additions!
That said, there's _one_ issue I have. Unlike the majority of mods these days, Charm's config can't be altered by going into the Mod Menu ingame. This would be fine, except that Charm has one of the longest, most in-depth configs I've seen, and staring at it in a text editor makes my head go numb. I'm not sure how much work it would be to do, but it'd be great if you could enable the ability to access the config through the ingame menu!

**Comment by WarlordWossman** [comment]
I am not sure if it's worth the effort, personally I feel like it's easier to go through large configs in a text editor, make sure to use a search function to directly jump to keywords.
That said it's not impossible that something like this could be added, currently Svenhjol is busy and on a break tho!
