### ISSUE TITLE
[1.12] Multiplayer Crate Dupe Bug

### ISSUE THREAD

**Issue by MasterEnderman** [svenhjol/Charm#178]
Charm: 1.3.6
Minecraft: 1.12.2
Forge: 14.23.5.2847

In Multiplayer if a player places a crate and another one opens it, the first player can break the crate again and the GUI doesn't close for the second player. that way you can dupe the contents of the crate.

**Comment by svenhjol** [comment]
Looking for help with fixing this as I can't see an obvious way to solve the problem.

**Comment by svenhjol** [comment]
Should be fixed in latest version:
https://www.curseforge.com/minecraft/mc-mods/charm/files/2934951
