### ISSUE TITLE
Right-clicking mobs causes the offhand to swing

### ISSUE THREAD

**Issue by floral-qua-floral** [svenhjol/Charm#179]
Right-clicking mobs with any item that doesn't have a valid right-click action on that mob causes the offhand to swing. This is strange and can make things like using a shield look incredibly doofy as it swings all over the place.

I'm testing with Charm 1.3.5 on Forge 1.12.2-14.23.5.2838. There are no other mods loaded and the config has been freshly generated. A screenshot of my left arm (offhand) swinging while I right-click a Creeper is attached.

![2019-09-30_11 11 40](https://user-images.githubusercontent.com/49110090/65904316-14ba2b00-e373-11e9-9045-7e9104e9adcb.png)

**Comment by WarlordWossman** [comment]
Interesting, can you test if this is the case in 1.3.6 too?

**Comment by floral-qua-floral** [comment]
Ah, I didn't realize I was a version behind. Just updated and tested and getting the same issue, happens with any mob. One strange thing I'm noticing - it does not occur when right-clicking armor stands, but _does_ with paintings. After testing this, I also tried with the latest version of Forge (14.23.5.2847), and the issue still occurs.

**Comment by WarlordWossman** [comment]
It's a good find tho, might be a while until the next version but thanks for reporting!
