### ISSUE TITLE
Allow the Gold Lantern to be Waterlogged

### ISSUE THREAD

**Issue by WenXin20** [svenhjol/Charm#182]
`Minecraft v1.14.4`
`Forge v28.1.44`
`Charm v1.3.4`

Currently, the Gold Lantern cannot be waterlogged. Allowing this would add more immersion to the game.
![2019-10-12_01 45 47](https://user-images.githubusercontent.com/12000593/66696496-23b5ad00-ec92-11e9-9420-d4276c0e499f.png)

**Comment by svenhjol** [comment]
This will be developed in an upcoming version. Thanks for the suggestion.

**Comment by Coranthes** [comment]
This feature is coming in version 1.5.9
