### ISSUE TITLE
Can't combine higher tier enchanted books with apotheosis

### ISSUE THREAD

**Issue by dont-hate-me** [svenhjol/Charm#184]
I am currently trying to use apotheosis along with charm but when both of them are enabled I can't combine higher tiers of books in an anvil which apotheosis adds, for example with apotheosis I should be able to combine two unbreaking 3 books to get an unbreaking 4 book and so on. but this doesn't happen when charm is enabled.

I have tried both the 1.14 version and the 1.12 version and the problem persists on both versions.
Versions:
1.12:
Charm-1.12.2-1.3.6
Placebo-1.12.2-1.6.0
Apotheosis-1.12.2-1.10.5
1.14:
Charm-1.14.4-1.3.4
Placebo-1.14.4-2.3.1
Apotheosis-1.14.4-2.4.2

**Comment by dkmk100** [comment]
It appears to work in 1.15.2, was this fixed?
