### ISSUE TITLE
Sticky Pistons to regular pistons when powered

### ISSUE THREAD

**Issue by Reggit6182** [svenhjol/Charm#185]
As the title says my sticky pistons turn into regular pistons when powered, they were placed in the world and powered before I installed the mod onto the server. Both the client and the server are running the same version, and both have quark installed.

**Comment by Wotzinator** [comment]
mine dont turn into regular pistons but act like them

**Comment by svenhjol** [comment]
Thanks for the report. Fixed in 1.4.1 https://www.curseforge.com/minecraft/mc-mods/charm/files/2828290
