### ISSUE TITLE
[suggestion] Tamable hostile mobs are still harmable when untamed option.

### ISSUE THREAD

**Issue by fuzzyweapon** [svenhjol/Charm#186]
Problem lies in the fact that hostile mobs which can be tamed, such as Quark's foxhounds in the nether become invincible and a real pain.

This has caused me to have to turn off this feature in Charm. :(

**Comment by svenhjol** [comment]
Thanks for the report, I'll look into this.

**Comment by svenhjol** [comment]
Should be fixed in 1.4.2 (https://www.curseforge.com/minecraft/mc-mods/charm/files/2831913). Please reopen if this is still an issue.
