### ISSUE TITLE
[suggestion] Allow option for player damage to tamed animals while in creative.

### ISSUE THREAD

**Issue by fuzzyweapon** [svenhjol/Charm#187]
This would allow for operators to help players easily kill unwanted tamed animals, say, if, someone got out of control or tamed one too many, or just wants to cut down.

**Comment by svenhjol** [comment]
Yep, makes sense. I'll make it so that creative players don't get the feature.

**Comment by svenhjol** [comment]
This has been added to 1.4.2 (https://www.curseforge.com/minecraft/mc-mods/charm/files/2831913). Thanks for the suggestion!
