### ISSUE TITLE
[1.14.4] Disabling RemovePotionGlint still causes glints to be removed.

### ISSUE THREAD

**Issue by fuzzyweapon** [svenhjol/Charm#188]
I don't know if this has anything to do with it, but I launched the server and client first with RemovePotionGlint enabled.

Then I changed the setting to `false` on both the server and the client, restarted, and the glints are 
still removed.

----

MC - 1.14.4
Forge - 28.1.61
Charm - 1.4.0

**Comment by svenhjol** [comment]
Thanks for the report.

**Comment by svenhjol** [comment]
Yep, oops. This bug probably extends to other feature disabled checks. This will be fixed in 1.4.2.

**Comment by svenhjol** [comment]
Should be fixed in 1.4.2 (https://www.curseforge.com/minecraft/mc-mods/charm/files/2831913). Please reopen if this is still an issue.
