### ISSUE TITLE
Crash on Startup

### ISSUE THREAD

**Issue by cbright117** [svenhjol/Charm#191]
[crash-2019-11-16_16.08.34-client.txt](https://github.com/svenhjol/Charm/files/3854720/crash-2019-11-16_16.08.34-client.txt)

Just downloaded the newest version

**Comment by svenhjol** [comment]
Please try Forge 28.1.90

**Comment by cbright117** [comment]
I believe that fixed it, thanks :)
Ill let you know if anything else comes up. Thanks for the cool mod!

**Comment by svenhjol** [comment]
You're welcome, thanks for the report and testing!
