### ISSUE TITLE
[1.12.2] A Spectre Hit You! Subtitle always showing

### ISSUE THREAD

**Issue by Mar3xgg** [svenhjol/Charm#196]
How to replicate: turn on subtitles, join a world. You'll see "a spectre hit you!" repeatedly, despite no spectre being nearby, even if you're in peaceful.
Version: seems to not matter.

**Comment by svenhjol** [comment]
Thanks for the report.

**Comment by aaronhowser1** [comment]
Any update on this?

**Comment by Ozzymud** [comment]
Can confirm still happening in version Charm-1.12.2-1.4 included in FTB University.
