### ISSUE TITLE
Disabling RandomAnimalTextures doesn't work

### ISSUE THREAD

**Issue by WenXin20** [svenhjol/Charm#197]
`Minecraft v1.14.4`
`Forge v28.1.92`
`Charm v1.4.1`

Setting `RandomAnimalTextures` to `false` for wolves doesn't seem to work. I tried changing it to false in both the `charm.toml` and the `charm-common.toml` files.

This is so that I can get the mod Let Sleeping Dogs Lie to work, unless support can be added for that mod.

**Comment by svenhjol** [comment]
Should be fixed in 1.4.2 (https://www.curseforge.com/minecraft/mc-mods/charm/files/2831913). Please reopen if this is still an issue.

**Comment by WenXin20** [comment]
The config still doesn't seem to be working.
