### ISSUE TITLE
Dispenser incorrectly handling splash potions

### ISSUE THREAD

**Issue by BeyondElemental** [svenhjol/Charm#199]
Versions tested on:
Minecraft 1.14.4
Forge 28.0.87 and 28.1.96
Charm 1.4.2

Dispensers are dropping splash potions instead of properly launching them. I suspect it has to do with the potions stacking, but was unable to confirm due to `"StackablePotions enabled" = false` in the config file being ignored.

**Comment by svenhjol** [comment]
There are two problems here. I didn't notice that the modules to change vanilla stack sizes were not being respected by config so that's going to be "fixed" as part of this.
