### ISSUE TITLE
flavored cake ghost effects / pickblock

### ISSUE THREAD

**Issue by WarlordWossman** [svenhjol/Charm#2]
Rightclicking flavored cakes in the world with a full hunger bar gives you a "ghost" effect that is displayed in the inventory and top right corner but doesn't do anything.
The timer counts down to 0:00 but the effect doesn't disappear and even drinking a bucket of milk doesn't seem to remove said ghost effect.

![2019-04-10_07 36 45](https://user-images.githubusercontent.com/16925725/55853948-74254400-5b63-11e9-8ffd-ed8ae13024b3.png)

Another small thing I noticed is that pickblock will return a regular cake instead of the right flavored cake that is placed in the world.

**Comment by svenhjol** [comment]
Disabled the effect when not hungry, can you let me know if you still see the ghost effect?

**Comment by WarlordWossman** [comment]
The ghost effect seems to be fixed, nice work!

There are some minor issues with flavored cake that you _might_ want to look into:
1. block placing/breaking sound is currently stone when the vanilla cake uses the wool sound
2. pickblock returns a vanilla cake
3. mods like waila and top also register the flavored cakes in the world as the vanilla cake so you cannot really tell which cake you are looking at without using F3 screen

**Comment by svenhjol** [comment]
Sorted those three in alpha5... I hope :)
