### ISSUE TITLE
there appears to be some incompatibility between charm and lollipop

### ISSUE THREAD

**Issue by gravysamich** [svenhjol/Charm#201]
lollipop is a library from zeroneye. i wanted to use a mod of his but his latest update of this library seems to be causing issues for charm. 

here is my crash report - https://pastebin.com/kuhedwvB

i already reported the issue to zeroneye as the issue only started when i updated his mod. he is claiming the issue is on your end so now i am here.

if you need any additional information i can give, please let me know.

**Comment by gravysamich** [comment]
please close this, the issue was that lollipop was incompatible with the version of forge i was using. 

i figured this mod dev had no idea what he was saying by pointing me at you. i apologize for wasting your time.

**Comment by WenXin20** [comment]
Actually, Charm crashed instead of allowing Minecraft to display the screen that would have told you that Forge was outdated. So the Lillipop mod and dev is not at fault.

**Comment by svenhjol** [comment]
There is an issue with the ASM in Charm that I'm going to look at. Thanks for this report.
