### ISSUE TITLE
Disabling RandomAnimalTextures still doesn't work

### ISSUE THREAD

**Issue by WenXin20** [svenhjol/Charm#202]
`Minecraft v1.14.4`
`Forge v28.1.92`
`Charm v1.4.2`

Setting `RandomAnimalTextures` to `false` for wolves still doesn't seem to work. I tried changing it to false in the `charm-common.toml` file to allow the mod Let Sleeping Dogs Lie to work.

**Comment by svenhjol** [comment]
Thanks for the report, missing check and needed some other infrastructure to load config early. Please reopen if it continues.
