### ISSUE TITLE
[Suggestion] Ice skates

### ISSUE THREAD

**Issue by yukinagatosc2** [svenhjol/Charm#205]
Basically a pair of "boots" that allow you to travel much faster on ice.  It seems like it would fit the vanillaish theme pretty well and being as it's getting cold out, immersive as well

**Comment by svenhjol** [comment]
I like it! To keep it within the theme of vanilla, I'd probably make it an enchantment that you apply to boots rather than create a new item. Idea for name?

**Comment by yukinagatosc2** [comment]
Not sure tbh.  All I can think of is that you have to have pretty solid ankles to skate well- maybe something to do with that somehow.  Anyway are all the new features 1.14+ only or is there a chance of 1.12 support?

**Comment by svenhjol** [comment]
Once all the 1.14 bugs have been fixed and I've finished my other mod, I'll look at backporting. Time is really limited right now but I want to support 1.12.

**Comment by dkmk100** [comment]
A ice speed improvement enchantment for the mod sounds great! will it be in 1.15.2 as well?
