### ISSUE TITLE
Config not working

### ISSUE THREAD

**Issue by five0five** [svenhjol/Charm#207]
I have a load of stuff disabled, but most of it seems to still be present in game. I'm seeing all the disabled items/potions in jei and creative tabs and can craft them too. List of stuff below:
- block of redstone sand 
- coffee 
- bookshelf chests
- gold lantern
- composters giving mushrooms
- emerald block opening trades
- end portal runes
- villages in more biomes
- wolf variants 
- totems in inventory
- more barrels 
- crates
- flavoured cake 
- curse break

**Comment by svenhjol** [comment]
Thanks for the report. What version of Charm are you using?

**Comment by five0five** [comment]
latest 1.14 ver from curse

**Comment by svenhjol** [comment]
Fixed in 1.4.4 which will be released either tonight or tomorrow.
