### ISSUE TITLE
Freezup with Charm (1.14.4) Unexpected Error

### ISSUE THREAD

**Issue by DatrixTHLK** [svenhjol/Charm#208]
Minecraft: 1.14.4
Forge: 28.1.106
Charm: 1.4.3

My game seems to freezup at this point and I waited for my game to load for about an hour, I doubt I should have to wait that long. In any case thanks for the mod! I like aethsetic mods. The error has something to do with 

> svenhjol.charm.base.CharmAsmHooks.handleMusicTick

Crash Log: https://gist.github.com/DatrixTHLK/58470fb674b66ac6aa9d59acb36230c4

**Comment by Miner239** [comment]
I got the same error, so I went and checked latest.log. Turns out an unrelated mod (in this case, Industrial Foregoing) has missing dependency. Fixing that doesn't give me this error and lets me play.

**Comment by DatrixTHLK** [comment]
Hmm, I see so that's what the issue was. I don't play on 1.14.4 anymore as I'm on 1.15.2 now, but thanks for the response and the helpful information. I shall close this.
