### ISSUE TITLE
Crate UI persists after breaking when one player has the UI open and the other breaks the crate. Done with 2 players, can be used to duplicrate items

### ISSUE THREAD

**Issue by daddybing** [svenhjol/Charm#214]

**Comment by svenhjol** [comment]
Duplicrate :)
What version of Charm is this happening in?

**Comment by daddybing** [comment]
> Duplicrate :)
> What version of Charm is this happening in?

Charm-1.12.2-1.3.6

**Comment by svenhjol** [comment]
Duplicate of #178, will be fixed in next 1.12 version

**Comment by svenhjol** [comment]
Should be fixed in latest version:
https://www.curseforge.com/minecraft/mc-mods/charm/files/2934951
