### ISSUE TITLE
Unable to reduce repair cost with golden tool?

### ISSUE THREAD

**Issue by Yourname942** [svenhjol/Charm#217]
Minecraft: 1.12.2
Forge: 14.23.5.2847
Charm: Charm-1.12.2-1.3.6.jar 
My config file settings: https://pastebin.com/UtFHKS8e 
My modlist: https://pastebin.com/9Zr4G4Bp

Issue: I'm not sure why I am unable to combine my gold pickaxe with a golden shovel to reduce the cost of repairing. I am using a vanilla anvil, a diamond pickaxe in the left slot, and a gold pickaxe on the right slot, but I cannot "repair" it? How do you use the gold version of a tool to reduce your repair cost?

**Comment by svenhjol** [comment]
You're doing it correctly. I'll have a look into it, thanks for the report.
