### ISSUE TITLE
[feature request] Compatabilty with upgrade aquatic

### ISSUE THREAD

**Issue by dkmk100** [svenhjol/Charm#220]
Will you please add compatability for upgrade aquatic driftwood? I mean make variants of the wooden items for driftwood that are enabled if upgrade aquatic is installed. https://www.curseforge.com/minecraft/mc-mods/upgrade-aquatic/

**Comment by svenhjol** [comment]
Nice mod! Yes, I'll schedule this into an upcoming version.

**Comment by Excaliburning** [comment]
I'm so glad to know about this ! UA is incredible, and so is Charm, I'm happy to know you've got your eyes into adding compatibility to it !

**Comment by svenhjol** [comment]
Ok, this will be handled as part of ticket #244. Please follow the progress there.
