### ISSUE TITLE
Charm disables "Better Animations 2 Collection's" dog animation

### ISSUE THREAD

**Issue by Ratriq** [svenhjol/Charm#222]
While I love this mod, as the title says, this mod for some reason overwrites and disables the animation for dogs that "Better Animation 2 Collection" add.
This shouldn't happen if I'm correct? Since Charm shouldn't modify the dogs model in any way, even if I disable the added texture randomizer that Charm adds to wolfs so it's completely untouched it still keeps disabling the animations.

With Charm installed:
![image](https://user-images.githubusercontent.com/62155563/76651384-b968a780-6564-11ea-86e3-d495aa77df73.png)

Without Charm installed:
![image](https://user-images.githubusercontent.com/62155563/76651470-e6b55580-6564-11ea-8d46-29bc255e30a1.png)

For the record, it's the latest 1.12.2 version on both mods.

**Comment by svenhjol** [comment]
I'm not sure. It's possibly the renderer. The only thing I can do is disable Charm's feature if it detects this mod.
