### ISSUE TITLE
Leather Armor doesn't become Invisible.

### ISSUE THREAD

**Issue by D-Bigboy-302** [svenhjol/Charm#226]
When using a potion of invisibility, mobs can still detect the player. Leather armor does not become invisible as well. I am using the latest 1.14.4 version.

**Comment by svenhjol** [comment]
You're right about the mob detection and that has now been patched for the upcoming version. However, leather armor is definitely invisible for me. Are you using any graphics mods like optifine?

**Comment by svenhjol** [comment]
It's visible on 1.15.2 so that's a bug, but 1.14.4 is still ok for me.

**Comment by D-Bigboy-302** [comment]
Yes I'm using optifine with with Silder's enhanced default shaders. That part hadn't even factored into my mind. 

Thanks for looking into this, absolutely love your mod!

**Comment by svenhjol** [comment]
Thanks! Ok I'll test it out with shaders and let you know what I find. The next version will have a fix for mob detection though, so even if the rendering is still problematic it will be functional.

**Comment by D-Bigboy-302** [comment]
Awesome! Thank you I appreciate all your work!
