### ISSUE TITLE
Music ASM issue might be back (1.15.2)

### ISSUE THREAD

**Issue by svenhjol** [svenhjol/Charm#228]
See https://pastebin.com/xjHWw9EA

**Comment by Dakedres** [comment]
I'm getting this too on 1.14.4 with forge 28.2.1

**Comment by svenhjol** [comment]
Please test this release and let me know if it happens:

1.14: https://github.com/svenhjol/Charm/releases/download/1.14.4-1.5.5/Charm-1.14.4-1.5.5.jar
1.15: https://github.com/svenhjol/Charm/releases/download/1.15.2-1.5.5/Charm-1.15.2-1.5.5.jar

**Comment by Dakedres** [comment]
No crash this time! Awesome job.

**Comment by DoCharlcate** [comment]
Was just coming here to report the same crash but indeed the 1.14 does fix it. :)

**Comment by Excaliburning** [comment]
Hello !
I don't know if my crash log can help you solve this definitively but here it is :
- [client crashlog](https://gist.github.com/Excaliburning/e6f1b385ae65ba24e9246241e9c5bb28)

My client crashed with Charm, the 1.5.5 version you provided solved the issue immediately.
