### ISSUE TITLE
Something's wrong

### ISSUE THREAD

**Issue by slard3** [svenhjol/Charm#229]
MC version: 1.15.2
Forge version: 31.1.35
Charm version: 1.5.4
Strange version: 1.0.0 beta 1

https://gist.github.com/slard3/06ea04502bd94701f1a7770ca6c38837

But hey, if I disable everything thru the config, Minecraft does start
![image](https://user-images.githubusercontent.com/55768134/78466145-cabc5400-76cb-11ea-9558-9c4c82699214.png)

Something's wrong, tomorrow I will try to narrow it down to exactly what, right now I'm going to bed

**Comment by svenhjol** [comment]
Do you have Charm 1.14.4 installed instead of Charm 1.15.2?

**Comment by svenhjol** [comment]
Closing. Please reopen if you have an issue with this.
