### ISSUE TITLE
[1.15.2] Incompatibility with Anvil Tweaks: Pig Iron doesn't do anything.

### ISSUE THREAD

**Issue by ridjack** [svenhjol/Charm#231]
As title. Anvil Tweaks ( https://www.curseforge.com/minecraft/mc-mods/anvil-tweaks ) seems to cause Pig Iron Nuggets to not work; putting them in an anvil with a damaged item shows that it will repair it (the item displays in the output slot), but attempting to remove the item does nothing. Removing Anvil Tweaks restores Pig Iron functionality. 

Let me know if this is an issue with Charm or Anvil Tweaks and I can report it to that mod instead; at the moment, I mostly just wanted to make sure you were aware of the issue in case it has conflicts with anything else.

**Comment by svenhjol** [comment]
I haven't checked compatibility with that mod yet, so I'll give it a shot when I get the time.

**Comment by svenhjol** [comment]
Bit of background info:
Charm patches the default vanilla RepairContainer to allow XP costs of zero. Without this patch, vanilla minecraft doesn't let you extract an item from the anvil without at least 1 level of XP. 

Looks like Anviltweaks implements its own RepairContainer over the vanilla one, and as a result, I am not willing to patch it.

You have two solutions:
* ask the author of AnvilTweaks to allow zero XP anvil transactions (`event.setCost(0)`)
* disable the Charm feature called `NoAnvilMinimumXp`; this will allow pig iron to work again, but each piece of pig iron will require 1 level of player XP.
