### ISSUE TITLE
[Feature Request] Bring back End Portal Runes but with crystals

### ISSUE THREAD

**Issue by Epic312** [svenhjol/Charm#232]
In 1.14 I really liked the End Portal Runes feature - it was a creative approach for vanilla+ teleportation, and gave the Quark crystals a practical use. Of course Quark removed runes in 1.15 so the feature was disabled, but I think it would be cool to bring this feature back by having it just use crystal blocks instead of runes.

**Comment by svenhjol** [comment]
I plan on bringing it back! I won't be depending on Charm's crystals, but I have a plan to use a special kind of colored crystal found in the End.

**Comment by svenhjol** [comment]
And it's back :)
