### ISSUE TITLE
Compatibility Request

### ISSUE THREAD

**Issue by FynnWaelsing** [svenhjol/Charm#234]
Would it be possible to get crates/barrels/bookshelf chests for some of the woods in other mods? Thinking specifically of Autumnity (Maple), Atmospheric (Rosewood, Yucca, Kousa, Aspen), Bloomful (Wisteria), Upgrade Aquatic (Driftwood), but I'm sure you could think of others as well. Would very much appreciate it! Love the mod!

**Comment by Epic312** [comment]
A couple more Abnormals mods that I'd love to see variants for: Buzzier Bees (Hive), The Endergetic Expansion (Poise), Bamboo Blocks (Bamboo)

**Comment by svenhjol** [comment]
It's in the backlog, stay tuned :)

**Comment by svenhjol** [comment]
Please see issue #244 for latest!
