### ISSUE TITLE
No illusioner and vindicators spawning in modpacks (1.12)

### ISSUE THREAD

**Issue by Benji357k** [svenhjol/Charm#236]
Playing this mod (1.12 version) in a medium sized modpack (60-70 mods) doesn't allow Illusioners and Vindicators to spawn in roofed forests. I tried in a small modpack (around 7 mods) and they spawn. Maybe a conflict with another mod?

**Comment by svenhjol** [comment]
Thanks for the report. Not enough information to go on. Divide your modpack into four sets of mods, test the bug, and if it occurs then keep dividing until you find the culprit. Then let me know what's responsible and I'll debug it.

**Comment by Benji357k** [comment]
Done! I play the 1.3.6 Charm version for 1.12, and the problem seems to be related to Custom mob spawner (version 3.11.5) or MoCreatures (12.0.5). I ran the whole modpack without these two mods and the two illagers spawned regularly. Hope you can fix this!

**Comment by svenhjol** [comment]
Great! I should be working on 1.12 issues next week, after I've finished up the current 1.14 problems, so I'll look at the compatibility issues then.
