### ISSUE TITLE
Duplication bug with Crates

### ISSUE THREAD

**Issue by kil0byt3** [svenhjol/Charm#237]
All documentation here:

https://github.com/CalaMariGold/Rebirth-Of-The-Night/issues/148

using Charm-1.12.2-1.3.6

Let me know if there's any other info I can provide to assist, or if this is already fixed in dev

**Comment by svenhjol** [comment]
Duplicate of #178

**Comment by svenhjol** [comment]
Fixed in https://www.curseforge.com/minecraft/mc-mods/charm/files/2934951
