### ISSUE TITLE
Golden Lantern texture issue

### ISSUE THREAD

**Issue by thedarkcolour** [svenhjol/Charm#24]
The Golden Lantern has a red line on the side on a frame of its animation. [This is what it looks like](https://imgur.com/a/XFc1v4r)

**Comment by thedarkcolour** [comment]
It also has a weird AABB hitbox when hanging.

**Comment by svenhjol** [comment]
Looks like I might have screwed up the texture a bit in the last commit. No the weird hitbox is just me being stupid. Thanks for the report :)
