### ISSUE TITLE
server crash on start 1.15

### ISSUE THREAD

**Issue by IchigoGames** [svenhjol/Charm#241]
crash on start but not all the time random 
Minecraft 1.15.2
Forge 31.1.43
Charm-1.15.2-1.5.5
crash report https://pastebin.com/gt9zcFDb

**Comment by IchigoGames** [comment]
it's happening pretty often

**Comment by IchigoGames** [comment]
could be a mod compatibility issue as is happening in my modpack

**Comment by svenhjol** [comment]
Can you send your charm-common.toml please?

**Comment by IchigoGames** [comment]
this is the one from config folder was unable to add file so i coppy and past to pastbin 
https://pastebin.com/x5X9B5VC

**Comment by svenhjol** [comment]
Thanks. Did you make any changes to the default charm config file in your modpack?

**Comment by IchigoGames** [comment]
no changes.

**Comment by svenhjol** [comment]
Thanks for pasting the config. Unfortunately there isn't enough information available for me to debug this, so it could be some kind of incompatibility with one of the mods.

**Comment by IchigoGames** [comment]
idk if this shows any more info then last one https://pastebin.com/LkWBe3s3

**Comment by IchigoGames** [comment]
i do also have the same issue with pams mods same error and crash so maybe its a incompatibility with pams

**Comment by IchigoGames** [comment]
it happens with this mod xlfoods and pams fruit tree each crash and random give same crash report https://github.com/mariot7/XL-Food-Mod/issues/65

**Comment by Insane96** [comment]
This happens for lots of mods, like Quark & Autumnity too. This random crash at the start. Both on game startup and server startup
