### ISSUE TITLE
Bad Treasure Map Crash

### ISSUE THREAD

**Issue by TheWitherlord** [svenhjol/Charm#242]
As soon as you find a buried treasure map and put in your hand the game crashes and gives this crash report.

---- Minecraft Crash Report ----
// You're mean.

Time: 4/12/20 8:51 PM
Description: Ticking player

java.lang.NullPointerException: Ticking player
	at com.google.common.base.Preconditions.checkNotNull(Preconditions.java:770) ~[guava-21.0.jar:?] {}
	at com.google.common.collect.RegularImmutableMultiset.<init>(RegularImmutableMultiset.java:68) ~[guava-21.0.jar:?] {}
	at com.google.common.collect.ImmutableMultiset.copyFromEntries(ImmutableMultiset.java:218) ~[guava-21.0.jar:?] {}
	at com.google.common.collect.Multisets.copyHighestCountFirst(Multisets.java:1137) ~[guava-21.0.jar:?] {}
	at net.minecraft.item.FilledMapItem.func_77872_a(FilledMapItem.java:192) ~[?:?] {re:classloading}
	at net.minecraft.item.FilledMapItem.func_77663_a(FilledMapItem.java:336) ~[?:?] {re:classloading}
	at net.minecraft.item.ItemStack.func_77945_a(ItemStack.java:414) ~[?:?] {re:classloading,xf:fml:charm:ItemStack,xf:fml:quark:add-spacing-for-stack}
	at net.minecraft.entity.player.PlayerInventory.func_70429_k(PlayerInventory.java:265) ~[?:?] {re:classloading}
	at net.minecraft.entity.player.PlayerEntity.func_70636_d(PlayerEntity.java:505) ~[?:?] {re:classloading,pl:accesstransformer:B,xf:fml:charm:PlayerEntity}
	at net.minecraft.entity.LivingEntity.func_70071_h_(LivingEntity.java:2104) ~[?:?] {re:classloading,pl:accesstransformer:B,xf:fml:charm:LivingEntity}
	at net.minecraft.entity.player.PlayerEntity.func_70071_h_(PlayerEntity.java:233) ~[?:?] {re:classloading,pl:accesstransformer:B,xf:fml:charm:PlayerEntity}
	at net.minecraft.entity.player.ServerPlayerEntity.func_71127_g(ServerPlayerEntity.java:361) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.network.play.ServerPlayNetHandler.func_73660_a(ServerPlayNetHandler.java:183) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:228) ~[?:?] {re:classloading}
	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:135) ~[?:?] {re:classloading}
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:866) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:784) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:114) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:637) [?:?] {re:classloading,pl:accesstransformer:B}
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_51] {}

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at com.google.common.base.Preconditions.checkNotNull(Preconditions.java:770)
	at com.google.common.collect.RegularImmutableMultiset.<init>(RegularImmutableMultiset.java:68)
	at com.google.common.collect.ImmutableMultiset.copyFromEntries(ImmutableMultiset.java:218)
	at com.google.common.collect.Multisets.copyHighestCountFirst(Multisets.java:1137)
	at net.minecraft.item.FilledMapItem.func_77872_a(FilledMapItem.java:192)
	at net.minecraft.item.FilledMapItem.func_77663_a(FilledMapItem.java:336)
	at net.minecraft.item.ItemStack.func_77945_a(ItemStack.java:414)
	at net.minecraft.entity.player.PlayerInventory.func_70429_k(PlayerInventory.java:265)
	at net.minecraft.entity.player.PlayerEntity.func_70636_d(PlayerEntity.java:505)
	at net.minecraft.entity.LivingEntity.func_70071_h_(LivingEntity.java:2104)
	at net.minecraft.entity.player.PlayerEntity.func_70071_h_(PlayerEntity.java:233)

-- Player being ticked --
Details:
	Entity Type: minecraft:player (net.minecraft.entity.player.ServerPlayerEntity)
	Entity ID: 501
	Entity Name: Witherlord00
	Entity's Exact location: -400.82, 59.00, 78.70
	Entity's Block location: World: (-401,59,78), Chunk: (at 15,3,14 in -26,4; contains blocks -416,0,64 to -401,255,79), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
	Entity's Momentum: 0.00, -0.01, 0.00
	Entity's Passengers: []
	Entity's Vehicle: ~~ERROR~~ NullPointerException: null
Stacktrace:
	at net.minecraft.entity.player.ServerPlayerEntity.func_71127_g(ServerPlayerEntity.java:361)
	at net.minecraft.network.play.ServerPlayNetHandler.func_73660_a(ServerPlayNetHandler.java:183)
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:228)

-- Ticking connection --
Details:
	Connection: net.minecraft.network.NetworkManager@43c23115
Stacktrace:
	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:135)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:866)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:784)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:114)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:637)
	at java.lang.Thread.run(Thread.java:745)

-- System Details --
Details:
	Minecraft Version: 1.15.2
	Minecraft Version ID: 1.15.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1575069064 bytes (1502 MB) / 6442450944 bytes (6144 MB) up to 6442450944 bytes (6144 MB)
	CPUs: 12
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx6G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	ModLauncher: 5.0.0-milestone.4+67+b1a340b
	ModLauncher launch target: fmlclient
	ModLauncher naming: srg
	ModLauncher services: 
		/eventbus-2.0.0-milestone.1-service.jar eventbus PLUGINSERVICE 
		/forge-1.15.2-31.1.41.jar object_holder_definalize PLUGINSERVICE 
		/forge-1.15.2-31.1.41.jar runtime_enum_extender PLUGINSERVICE 
		/accesstransformers-2.0.4-shadowed.jar accesstransformer PLUGINSERVICE 
		/forge-1.15.2-31.1.41.jar capability_inject_definalize PLUGINSERVICE 
		/forge-1.15.2-31.1.41.jar runtimedistcleaner PLUGINSERVICE 
		/forge-1.15.2-31.1.41.jar fml TRANSFORMATIONSERVICE 
	FML: 31.1
	Forge: net.minecraftforge:31.1.41
	FML Language Providers: 
		javafml@31.1
		minecraft@1
		kotlinforforge@1.1.0
	Mod List: 
		QuarkOddities-1.15.2.jar Quark Oddities {quarkoddities@1.15.2 DONE}
		torchslabmod-1.15.1_v1.6.5.jar Torch Slab Mod TEST {torchslabmod@1.6.4 DONE}
		flamboyant-2.0.1.jar Flamboyant {flamboyant@2.0.1 DONE}
		Variant16x-1.15-v0.9.2.1_beta.jar Variant16x {variant16x@0.9.2.1_beta DONE}
		mining-helmet-1.15.2-1.0.8.jar Mining Helmet {mining_helmet@1.0.8 DONE}
		oreveins-forge-1.15.2-5.1.0.jar Realistic Ore Veins {oreveins@5.1.0 DONE}
		bambooblocks-1.15.2-1.3.jar Bamboo Blocks {bambooblocks@1.2.11 DONE}
		jei-1.15.2-6.0.0.2.jar Just Enough Items {jei@6.0.0.2 DONE}
		futuremc-1.15.2-1.0.0.jar Future MC {futuremc@1.15.2-1.0.0 DONE}
		buzzierbees-1.4.jar Buzzier Bees {buzzierbees@1.4 DONE}
		AttributeFix-1.15.2-7.0.2.jar AttributeFix {attributefix@7.0.2 DONE}
		goblintraders-1.2.0-1.15.2.jar Goblin Traders {goblintraders@1.2.0 DONE}
		Mekanism-1.15.2-9.9.19.411.jar Mekanism {mekanism@9.9.19 DONE}
		Upgrade-Aquatic-1.15.2-v1.5.1.jar Upgrade Aquatic {upgrade_aquatic@1.5.1 DONE}
		SilentMechanisms-1.15.2-0.7.0+50.jar Silent's Mechanisms {silents_mechanisms@0.7.0+50 DONE}
		BetterStorageToo-1.15.2-5.0.1.0.jar BetterStorageToo {betterstorage@1.15.2-5.0.1.0 DONE}
		bloomful-1.15.2-1.3.2.jar Bloomful {bloomful@NONE DONE}
		Waystones_1.15.2-6.0.1.jar Waystones {waystones@6.0.1 DONE}
		Placebo-1.15.2-3.0.2.jar Placebo {placebo@3.0.2 DONE}
		Powah-1.15.2-1.1.12.jar Powah {powah@1.1.12 DONE}
		decorative_blocks-6d.jar Decorative Blocks {decorative_blocks@1.6 DONE}
		MutantBeasts-1.15.2-1.0.4.jar Mutant Beasts {mutantbeasts@1.15.2-1.0.4 DONE}
		Bookshelf-1.15.2-5.3.9.jar Bookshelf {bookshelf@5.3.9 DONE}
		Reliquary-1.15.2-1.3.4.960.jar Reliquary {xreliquary@1.15.2-1.3.4.960 DONE}
		The-Endergetic-Expansion-1.15.2-v1.2.5.jar The Endergetic Expansion {endergetic@1.2.1 DONE}
		u_team_core-1.15.2-2.11.0.156.jar U Team Core {uteamcore@2.11.0.156 DONE}
		ProgressiveBosses-2.1.5-mc1.15.2.jar Progressive Bosses {progressivebosses@2.1.5-mc1.15.2 DONE}
		mapperbase-1.15.2-1.0.0.1.jar Mapper Base {mapperbase@1.15.2-1.0.0.1 DONE}
		starciliummod-1.15.2- 0.1.5.jar Starcilium Mod {starciliummod@0.1.3 DONE}
		MekanismGenerators-1.15.2-9.9.19.411.jar Mekanism: Generators {mekanismgenerators@9.9.19 DONE}
		Hwyla-forge-1.10.8-B72_1.15.2.jar Waila {waila@version DONE}
		SnowRealMagic-1.15.2-1.7.4.jar Snow! Real Magic! {snowrealmagic@1.7.4 DONE}
		Kiwi-1.15.2-2.6.5.jar Kiwi {kiwi@2.6.5 DONE}
		swampexpansion-1.15.2-1.5.1.jar Swamp Expansion {swampexpansion@NONE DONE}
		forge-1.15.2-31.1.41-universal.jar Forge {forge@31.1.41 DONE}
		xercamusic-1.15.2-1.0.jar Xerca's Music Mod {xercamusic@1.15.2-1.0 DONE}
		Variant16x-BiomesOPlenty-1.15-v0.9.2_beta_pre3.jar Variant16x: Biomes O' Plenty {variant16x_biomesoplenty@0.9.2_beta_pre3 DONE}
		forge-1.15.2-31.1.41-client.jar Minecraft {minecraft@1.15.2 DONE}
		cofh_core-1.15.2-0.3.2b.jar CoFH Core {cofh_core@0.3.2b DONE}
		ensorcellation-1.15.2-0.3.0b.jar Ensorcellation {ensorcellation@0.3.0b DONE}
		mcw-bridges-1.0.4fix-mc1.15.2.jar Macaw's Bridges {mcwbridges@1.0.4 DONE}
		industrial-foregoing-1.15.2-2.2.2-28d4a81.jar Industrial Foregoing {industrialforegoing@2.2.2 DONE}
		woolplates-1.15.1-v1.2.1.jar Wool Pressure Plates {woolplates@v1.2.1 DONE}
		EnchantmentDescriptions-1.15.2-2.0.5 (2).jar EnchantmentDescriptions {enchdesc@2.0.5 DONE}
		embellishcraft-1.15.2-2.1.0.1.jar EmbellishCraft {embellishcraft@1.15.2-2.1.0.1 DONE}
		titanium-1.15.2-2.3.6.jar Titanium {titanium@2.3.6 DONE}
		SilentLib-1.15.2-4.6.0+48.jar Silent Lib {silentlib@4.6.0+48 DONE}
		BiomesOPlenty-1.15.2-10.0.0.345-universal.jar Biomes O' Plenty {biomesoplenty@1.15.2-10.0.0.342 DONE}
		Lollipop-1.15.2-1.0.14.jar Lollipop {lollipop@1.0.14 DONE}
		ironfurnaces-1.15.2-2.0.1.jar Iron Furnaces {ironfurnaces@2.0.1 DONE}
		SilentGear-1.15.2-1.5.6+81.jar Silent Gear {silentgear@1.5.6+81 DONE}
		forbidden_arcanus-1.15.2-1.1.jar Forbidden & Arcanus {forbidden_arcanus@1.15.1-1.0-beta-1 DONE}
		movingelevators-1.2.4-mc1.15.jar Moving Elevators {movingelevators@1.2.4 DONE}
		masonry-1.15.2-0.3.4.jar Masonry {masonry@NONE DONE}
		hgp-1.15.2.jar Horizontal Glass Panes {hgp@1.15.2 DONE}
		simplefarming-1.15.2-1.2.7.jar Simple Farming {simplefarming@1.15.2-1.2.7 DONE}
		VanillaBreakfast-1.15.2-0.1.0.jar VanillaBreakfast {vanillabreakfast@0.1.0 DONE}
		QualityCotton-1.15.2-1.1.0.jar QualityCotton {qualitycotton@1.1.0 DONE}
		xercamod-1.15.2-1.0.jar Xerca Mod {xercamod@1.15.2-1.0 DONE}
		atmospheric-1.15.2-1.2.1.jar Atmospheric {atmospheric@1.2.1 DONE}
		curios-FORGE-1.15.2-2.0.2.jar Curios API {curios@FORGE-1.15.2-2.0.2 DONE}
		Botania+r1.15-382.jar Botania {botania@r1.15-382 DONE}
		Patchouli-1.15.2-1.2-31.jar Patchouli {patchouli@1.15.2-1.2-30 DONE}
		corail_woodcutter-1.1.1-1.15.2.jar Corail Woodcutter {corail_woodcutter@1.1.1 DONE}
		extendedmushrooms-1.2.0-1.15.2+.jar Extended Mushrooms {extendedmushrooms@1.2.0-1.15.2+ DONE}
		extlights-2.0.jar Extended Lights {extlights@2.0 DONE}
		autumnity-1.1.1-1.15.2.jar Autumnity {autumnity@1.1.1 DONE}
		AutoRegLib-1.5-40.jar AutoRegLib {autoreglib@1.5-40 DONE}
		Quark-r2.1-230.jar Quark {quark@r2.1-230 DONE}
		xercapaint-1.15.2-1.0.jar Joy of Painting {xercapaint@1.15.2-1.0 DONE}
		themidnight-0.5.6.jar The Midnight {midnight@0.5.6 DONE}
		obfuscate-0.4.1-1.15.2.jar Obfuscate {obfuscate@0.4.1 DONE}
		vehicle-mod-0.43.5-1.15.2.jar MrCrayfish's Vehicle Mod {vehicle@0.43.5 DONE}
		structurize-0.10.282-RELEASE (1).jar Structurize {structurize@0.10.282-RELEASE DONE}
		MekanismTools-1.15.2-9.9.19.411.jar Mekanism: Tools {mekanismtools@9.9.19 DONE}
		Transport-1.15.2-2.2.0.jar Transport {transport@1.15.2-2.2.0 DONE}
		furniture-7.0.0-pre16-1.15.1.jar MrCrayfish's Furniture Mod {cfm@7.0.0-pre16 DONE}
		mcw-furniture-1.0.1-mc1.15.1+1.15.2.jar Macaw's Furnitures {mcwfurnitures@1.0.1 DONE}
		ilikewood-1.15.2-2.2.1.0.jar I Like Wood {ilikewood@1.15.2-2.2.1.0 DONE}
		Aquaculture-1.15.2-2.0.13.jar Aquaculture 2 {aquaculture@1.15.2-2.0.13 DONE}
		SilentGems-1.15.2-3.5.1+84.jar Silent's Gems 3 {silentgems@3.5.1+84 DONE}
		CloudBoots-1.15.2-2.0.0.jar Cloud Boots Mod {cloudboots@2.0.0 DONE}
		BetterBurning-1.15.2-1.3.4.jar BetterBurning {betterburning@1.3.4 DONE}
		Charm-1.15.2-1.5.5.jar Charm {charm@1.15.2-1.5.5 DONE}
		Strange-1.15.2-1.0.0-beta.2.jar Strange {strange@1.15.2-1.0.0-beta.2 DONE}
		incubation-1.0.2-1.15.2.jar Incubation {incubation@1.0.2 DONE}
		bambootiful-1.15.2-1.1.3.jar Bambootiful {bambootiful@1.1.3 DONE}
	Kiwi Modules: 
		kiwi:contributors
		snowrealmagic:snowrealmagic
	Player Count: 1 / 8; [ServerPlayerEntity['Witherlord00'/501, l='Mythril Kingdom', x=-400.82, y=59.00, z=78.70]]
	Data Packs: vanilla, mod:aquaculture, mod:atmospheric, mod:attributefix (incompatible), mod:autoreglib (incompatible), mod:autumnity, mod:bambooblocks (incompatible), mod:bambootiful (incompatible), mod:betterburning (incompatible), mod:betterstorage (incompatible), mod:biomesoplenty, mod:bloomful (incompatible), mod:bookshelf (incompatible), mod:botania (incompatible), mod:buzzierbees, mod:cfm (incompatible), mod:charm (incompatible), mod:cloudboots, mod:cofh_core (incompatible), mod:corail_woodcutter, mod:curios (incompatible), mod:decorative_blocks, mod:embellishcraft (incompatible), mod:enchdesc (incompatible), mod:endergetic (incompatible), mod:ensorcellation (incompatible), mod:extendedmushrooms, mod:extlights, mod:flamboyant (incompatible), mod:forbidden_arcanus (incompatible), mod:forge (incompatible), mod:futuremc (incompatible), mod:goblintraders, mod:hgp (incompatible), mod:ilikewood, mod:incubation, mod:industrialforegoing (incompatible), mod:ironfurnaces (incompatible), mod:jei (incompatible), mod:kiwi, mod:lollipop (incompatible), mod:mapperbase, mod:masonry, mod:mcwbridges, mod:mcwfurnitures, mod:mekanism, mod:mekanismgenerators, mod:mekanismtools, mod:midnight, mod:mining_helmet (incompatible), mod:movingelevators, mod:mutantbeasts (incompatible), mod:obfuscate (incompatible), mod:oreveins (incompatible), mod:patchouli (incompatible), mod:placebo (incompatible), mod:powah (incompatible), mod:progressivebosses, mod:qualitycotton (incompatible), mod:quark, mod:quarkoddities, mod:silentgear (incompatible), mod:silentgems (incompatible), mod:silentlib (incompatible), mod:silents_mechanisms (incompatible), mod:simplefarming, mod:snowrealmagic, mod:starciliummod, mod:strange (incompatible), mod:structurize (incompatible), mod:swampexpansion (incompatible), mod:titanium (incompatible), mod:torchslabmod, mod:transport, mod:upgrade_aquatic (incompatible), mod:uteamcore, mod:vanillabreakfast, mod:variant16x, mod:variant16x_biomesoplenty, mod:vehicle (incompatible), mod:waila (incompatible), mod:waystones (incompatible), mod:woolplates (incompatible), mod:xercamod (incompatible), mod:xercamusic (incompatible), mod:xercapaint (incompatible), mod:xreliquary (incompatible)
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'forge'

**Comment by TheWitherlord** [comment]
latest charm version

**Comment by svenhjol** [comment]
Can you try it with just Charm and none of the other mods? I can't repeat it locally.

**Comment by TheWitherlord** [comment]
> Can you try it with just Charm and none of the other mods? I can't repeat it locally.

So, yes a mod other than this is causing a crash.    I loaded quark, strange, charm and oddities and I didn't get a crash.

**Comment by svenhjol** [comment]
I can test it if you narrow it down. Add back 10 mods at a time until it crashes, then remove one at a time until you find the one that is causing the problem.

**Comment by svenhjol** [comment]
See https://github.com/bageldotjpg/Atmospheric/issues/11
