### ISSUE TITLE
[1.15.2] Composter not producing extra outputs

### ISSUE THREAD

**Issue by FynnWaelsing** [svenhjol/Charm#243]
I noticed I wasn't getting the extra bone meals or mushrooms from the composter. Loaded up a fresh world with only Charm installed, and the problem kept happening. I fed it stacks of seeds, but I only got one bone meal every time. Haven't noticed any other issues.

Charm version: Charm-1.15.2-1.5.5
Forge version: 31.1.44
Latest log: https://pastebin.com/VBRAmeCQ
Charm config: https://pastebin.com/dsHkduDm

Not a big issue, but I hope this can be fixed. Love the mod!

**Comment by svenhjol** [comment]
Looks like the ASM isn't being applied. Good catch!

**Comment by svenhjol** [comment]
Fixed in 1.5.6
