### ISSUE TITLE
[Feature Request] Variants from mods on the "Quark Friends" Page

### ISSUE THREAD

**Issue by SalehGrey** [svenhjol/Charm#244]
https://quark.vazkii.net/#features

Could the wood variants from these mods of crates, barrels and bookshelf chests be added? 

Specifically these mods on curseforge: 

**Atmospheric:** https://www.curseforge.com/minecraft/mc-mods/atmospheric

**Autumnity:** https://www.curseforge.com/minecraft/mc-mods/autumnity

**Bamboo Blocks:** https://www.curseforge.com/minecraft/mc-mods/bamboo-blocks

**Bloomful:** https://www.curseforge.com/minecraft/mc-mods/bloomful

**Buzzier Bees:** https://www.curseforge.com/minecraft/mc-mods/buzzier-bees

**Swamp Expansion:** https://www.curseforge.com/minecraft/mc-mods/swamp-expansion

**Upgrade Aquatic:** https://www.curseforge.com/minecraft/mc-mods/upgrade-aquatic

**Endergetic:** https://www.curseforge.com/minecraft/mc-mods/endergetic

All of these mods add a few new types of wood, and all of them are on the **Quark Friends** page. I would even commission it! I'm a modpack developer and I'm in the midst of making a vanilla+ pack. Would be much appreciated.  

Also, I'd be perfectly content if no, but...

Potentially, could more wood variants be available? Not just for barrels, but potentially for the crafting table, cartography table, fetching table, smithing table, loom, lectern, and the writing desk from Strange?

**Comment by svenhjol** [comment]
Looking for artist. Happy to provide original crate, bookshelf chest and barrels.

**Comment by svenhjol** [comment]
It's a thumbs up from MCVinnyq - he might be in touch. Watch this space :)

**Comment by Coranthes** [comment]
This hasn't been forgotten about!  The crates, barrels and bookshelves are coming.

**Comment by svenhjol** [comment]
Done in covalent. I'll link to the mod and then close when it's uploaded to Curseforge
