### ISSUE TITLE
[Suggestion] Make Parrots imitate mobs sounds less often

### ISSUE THREAD

**Issue by Insane96** [svenhjol/Charm#245]
I really don't know if this is possible as I've never touched ASM but would be a nice feature as I love Parrots but they're fricking annoying. I'm also suggesting this because in 1.16 they reduced that frequency, and I think was really needed.

**Comment by SalehGrey** [comment]
Perhaps this would be a better option to have in the configuration file? I think being able to fine tune how often it imitates them to your liking would be pretty cool!

**Comment by Insane96** [comment]
It should be definitely configurable like every other feature. I'm suggesting this because in 1.16 they reduced that frequency, and I think was really needed.

**Comment by svenhjol** [comment]
Should be doable.
