### ISSUE TITLE
Crash on start up with Endergetic Expansion

### ISSUE THREAD

**Issue by PancakeIdentity** [svenhjol/Charm#248]
When I have charm installed with the Endergetic Expansion, it gives a crash on startup. It says a spawn egg type is missing.

I ask the Endergetic team about it, and they said it was an issue with this mod calling the register color event early. I've attached a crash log as well.
[crash-2020-04-21_13.20.19-client.txt](https://github.com/svenhjol/Charm/files/4512855/crash-2020-04-21_13.20.19-client.txt)

**Comment by svenhjol** [comment]
Sorry, I don't think it's this mod. As far as I know, I'm not using the color event and there's nothing in that log that can help me understand what is causing it.
