### ISSUE TITLE
[1.15.2]Playerdata corrupted while holding a map

### ISSUE THREAD

**Issue by Giustitia** [svenhjol/Charm#251]
Hi there.
I've run into a bug and I think is Charm related. So, I was playing normally on my server until i grabbed a filled map, hold it in my hand, walked a little and suddenly I got kicked due to an error. Now I'm not able to login since as server start loading my playerdata it get an error. The other player kept playng normally. This is the crash, hope it help :/

https://pastebin.com/3XKqbdF6

PD: If is not Charm related I would love to know any idea about where the error could come from :D

**Comment by Giustitia** [comment]
Ok, I've performed some tests trying to get more information about what is actually crashing. Edited with NBTExplorer my player selectedItem value to prevent the crash on entering. Map works well until I reach some Z position (Y position on map) and I'm still out of it (more or less, if bottom-left corner of the map is 0 , 0 and without clamping values to 1 ,1, it crashes on 1.1 , 0.2 position). If I'm there and i select the map to be holded, server crash :D

**Comment by svenhjol** [comment]
You probably have Atmospheric. See this issue on their tracker: https://github.com/bageldotjpg/Atmospheric/issues/11

**Comment by Giustitia** [comment]
Thanks! Lets stay tuned

**Comment by Giustitia** [comment]
Truth is I was really near an Atmospheric biome when this happened, maybe I was even ON the biome. Thanks for the cue :)

**Comment by svenhjol** [comment]
Now fixed in Atmospheric, closing this
