### ISSUE TITLE
[1.14.4 - Version 1.5.7] Quark Double Door Opening broken

### ISSUE THREAD

**Issue by RockyWynter** [svenhjol/Charm#253]
Charm appears to break the double door opening of Quark. Both doors visually open however you will be pushed back if you try to enter through the door that wasn't clicked on.

**Comment by svenhjol** [comment]
Can you confirm that removing Charm restores the working doors?

**Comment by svenhjol** [comment]
Can't repeat, works fine with Quark and Charm here.
