### ISSUE TITLE
[1.12.2] Composter voids inputs from a hopper

### ISSUE THREAD

**Issue by RCaled** [svenhjol/Charm#254]
Using the version 1.3.7 of charm, items void when placed in a hopper inventory connected from the side or the top of a composter and a hopper underneath it.
There is no output or change on the composter, items just dissapear ,this happens using this mod on a fresh install and with default inputs.

**Comment by SanjivanM** [comment]
Using same Charm version, but for me, the items just don't go into the composter, they just stay in the input hopper.  I'm inputting items from the top, but haven't tried the sides.

**Comment by sealchan1** [comment]
I'm seeing Oak Saplings move from a Extra-Large Chest (Extra Utilities) into a Tinker's Construct Wooden Hopper which in turn connects to the side of the Compostere but the Sapling does not seem to enter the Composter...not sure what this is supposed to look like but decided in the end it was a bug and lo and behold...

I also tried using the Vanilla Hopper but same thing.  The saplings enter the hopper but disappear from the hopper once the last one arrives.  So perhaps the saplings are being pulled into the Composter block but nothing is happening as a result.

**Comment by sealchan1** [comment]
I took a look at the code, as a beginning modder, and I wonder if onBlockActivated is the method of the class BlockComposter that would handle the insertion of an item into its inventory.  If so it looks like only an item held in a player's hand would get counted: 

added = composter.addItem(player.getHeldItem(hand), player.isCreative());

Perhaps the solution is to add additional code logic which can recognize an item being inserted by a hopper.  I may look into this myself and offer a full fix.

**Comment by sealchan1** [comment]
Svenhjol, can't figure out how to contact you...wondering if you (or anyone who knows...) have instructions for setting up this mod in my own Eclipse environment.  I know the basics of how to use GitHub...best I could do was to clone this repository locally and then copy the contents of the src directory into a new eclipse workspace that I have setup.  It seems I am missing some dependencies for MC 1.12 branch...
