### ISSUE TITLE
Bookshelf chests does not use Quark's bookshelf variants

### ISSUE THREAD

**Issue by yezhiyi9670** [svenhjol/Charm#257]
When bookshelf variants are enabled in Quark, Charm still use oak bookshelves to craft bookshelf chests.

Charm has partial compatibility with Quark, and is inspired by Quark. So this should not be intentional. Also this is possible as crafting recipes can be safely changed even ingame in 1.13+.

![image](https://user-images.githubusercontent.com/39194383/80857288-aa0ffb80-8c83-11ea-8a2a-856fb47cb9fc.png)

**Comment by ridjack** [comment]
Done with #262 .
