### ISSUE TITLE
How is curse break supposed to work ?

### ISSUE THREAD

**Issue by MeowBlock** [svenhjol/Charm#264]
i am using a modpack that uses charm, i have a lot of items with the curse break enchantment but i don't know how to take advantage of it. i tried to apply the enchanted book to several cursed items but it never works... what am i doing wrong ?
![javaw_HYA590rqvG](https://user-images.githubusercontent.com/65407825/82061982-b5bee180-96c9-11ea-85c1-e366c00131d7.png)

**Comment by MeowBlock** [comment]
i forgot to mention that the enchantment can only be applied to books when using /enchant

**Comment by Insane96** [comment]
It is a treasure enchantment so it can only be found via trades and loot.
The pumpkin this might be a bug

**Comment by yezhiyi9670** [comment]
![image](https://user-images.githubusercontent.com/39194383/83930739-a6641d00-a7cb-11ea-8b17-d695e72245dc.png)

![image](https://user-images.githubusercontent.com/39194383/83930748-af54ee80-a7cb-11ea-8f8d-cfc339529432.png)

It works with me. How did you obtain the book you are using? Please inspect the NBT data to make sure the book is correct.

**Comment by dkmk100** [comment]
> ![image](https://user-images.githubusercontent.com/39194383/83930739-a6641d00-a7cb-11ea-8b17-d695e72245dc.png)
> 
> ![image](https://user-images.githubusercontent.com/39194383/83930748-af54ee80-a7cb-11ea-8f8d-cfc339529432.png)
> 
> It works with me. How did you obtain the book you were using? Please inspect the NBT data to make sure the book is correct.

he used /enchant so probably the one that doesn't work has it as an enchantment not a stored enchantment.
