### ISSUE TITLE
Mod config doesn't display in-game. [1.12.2]

### ISSUE THREAD

**Issue by Homicidal-Lemon** [svenhjol/Charm#266]
Earlier I complained that in the 1.12.2 version of Charm I really didn't like Nether Gold Ore (I won't waste your time again and explain why though) and I was told to disable it in the mod config. That being said, I do not appear to have a mod config. My Charm version is Charm-1.12.2-1.3.7 and as you can see here (https://cdn.discordapp.com/attachments/626838109962895385/712664618517921863/unknown.png) I have no mod config.

**Comment by ridjack** [comment]
You can make changes in Charm.cfg in the config folder of your Minecraft directory.

**Comment by Homicidal-Lemon** [comment]
My bad for not trying that, but the mod config not displaying in-game is still an issue.

**Comment by ridjack** [comment]
I don't disagree, and I don't have an answer for it. I'll leave it to @svenhjol to address.

**Comment by svenhjol** [comment]
There is no in-game config for Charm, by design. Please edit your charm.cfg and make changes there.
