### ISSUE TITLE
Crash between this mod and Foamfix

### ISSUE THREAD

**Issue by Sunconure11** [svenhjol/Charm#27]
https://paste.dimdev.org/unisekepag.mccrash

**Comment by svenhjol** [comment]
Thanks for the paste. Could you provide more information? The stack trace looks like there was some kind of village building generating that I’m not familiar with.

**Comment by Sunconure11** [comment]
It seems to be blaming Mowzie's Mobs, but that does not add anything to village gen. It does have some structures in world gen though.

**Comment by Sunconure11** [comment]
Ruins is also being blamed, which adds well, ruins to the world.

**Comment by svenhjol** [comment]
I love ruins, such a good mod. I’m gonna interrogate the bookshelf tile entity and see if I can understand what’s happening. Would you be able to send me a zip file of your mods folder?

**Comment by svenhjol** [comment]
@Sunconure11 please could you unzip this jar (github won't let me directly upload jar files), it has an extra check in the TileBookshelfChest code that checks for validity before trying to update itself. Repeat whatever it was you did and let me know if the same thing happens. Thank you!

[Charm-1.12.2-1.0-beta3-preview1.zip](https://github.com/svenhjol/Charm/files/3096488/Charm-1.12.2-1.0-beta3-preview1.zip)

**Comment by Sunconure11** [comment]
A lot of these crashes tend to be hard to replicate. I'll see what I can do over the weekend, though.

**Comment by thedarkcolour** [comment]
It looks like something tried to set a property for a stone block.

**Comment by svenhjol** [comment]
Yeah. I think some kind of building intersected with a bookshelf chest TE, causing it to try and update itself after dropping its inventory, but there wasn't a BlockBookshelfChest at that pos anymore - it was stone. Never seen this before but the version I attached above has an extra check on the blockstate to make sure it's a valid BlockBookshelfChest before trying to set metadata.

**Comment by codingQueries** [comment]
Just thought I would jump in and provide a crashreport here: https://paste.dimdev.org/openuzogox.mccrash that was a similar or same issue. When I was nearing a village I received this error. Understandably, there are a few other mods included that may be causing this too.

**Comment by codingQueries** [comment]
I tried out the beta3 download briefly on my map taht kept crashing, and it appears to have helped, but I won't be able to check further until tomorrow at least.

**Comment by Pival81** [comment]
The beta3 fixed the issue, will you release this soon?

**Comment by Rongmario** [comment]
This occured on breaking one of the TileEntityBookshelf I found in the midst of other bookshelves inside the library of a village. https://paste.dimdev.org/jawolufese.mccrash

**Comment by Sunconure11** [comment]
By all accounts, this appears to be fixed. Any plans for an update?

**Comment by svenhjol** [comment]
Yes, I will release beta3 now that #31 has been fixed - it was causing a serious problem with the latest version of Quark. Expect within 24 hours.
