### ISSUE TITLE
Crash when hovering over an crate item in the inventory

### ISSUE THREAD

**Issue by HerrBeef** [svenhjol/Charm#271]
Hi,

my game crashes when i hover over an crate, trying to show the tooltip. The crate was exploded with tnt and than picked up, every time i go in the inventory and hover over the crate i get a crash.

Can i turn tooltips off? 
Charm Version: 1.5.7
Quark Version: r2.1-240
Strange Version: 1.0.0-beta.3

I'm playing without Optifine and on Minecraft 1.15.2 with Forge 31.2.5

[crash-2020-06-02_23.15.56-client.txt](https://github.com/svenhjol/Charm/files/4719769/crash-2020-06-02_23.15.56-client.txt)

**Comment by yezhiyi9670** [comment]
Can you reproduce it? I can't reproduce the issue with Charm 1.5.9. Maybe you could try to update the mod.

*Note: I don't know why the latest version on CurseForge is 1.5.7, but you can download the source and build 1.5.9 by yourself.*

**Comment by svenhjol** [comment]
I put a patch in place for this in 1.5.9.  It's not a very good fix; it just prevents the actual issue from bringing down the game.   What you'll see is just an empty looking crate inventory when you hover, even though the crate is filled.  Currently happening when crates are populated with loot programmatically by the game (i.e. vaults and ruins in Strange).

I'll look into a proper solution for this so I'll leave the ticket open.
