### ISSUE TITLE
Bug: Crash when using Homing Enchantment on non-vanilla item

### ISSUE THREAD

**Issue by dkmk100** [svenhjol/Charm#272]
The title mostly explains it. When there is a non-vanilla item and you enchant it with homing, right-clicking with the item will cause the game to freeze.

**Comment by svenhjol** [comment]
Confirmed.

**Comment by dkmk100** [comment]
Please add a config option to support modded items, we can provide a block for each item to search for. Any item not from vanilla that isn't specified in the config should do nothing if it has the enchantment.

**Comment by svenhjol** [comment]
That will be an enhancement ticket. Currently in the process of fixing all bugs and getting things stable before starting new features.
