### ISSUE TITLE
[1.5.2] It seems like custom outputs from Composter don't work properly when using Hopper...

### ISSUE THREAD

**Issue by SpiderKolo** [svenhjol/Charm#273]
I wasn't testing - I noticed that when I put Hopper under Composter to grab items it Composts automatically, I didn't get my mushrooms or extra Bone Meal...
I would probably never notice if I didn't do it manually beforehand. I was just testing my modpack on survival and though I have a lot of stuff I can compost and I needed some Bone Meal to speed up farming of other few crops.
I did get Mushrooms relatively often when I was doing it manually, and if Input was automated, but not output, it was still fine, but when I automated output... it wasn't working as intended...

I wasn't tweaking custom recipes yet, but It's worth testing out those as well with hoppers.

I am on version 1.5.7 at the moment - I didn't noticed there just have been an update, but I didn't noticed in logs that you fixed the issue in newest version of the mod, so I'm assuming it's not fixed yet in newest version. I will be testing that later on to make sure.

**Comment by SpiderKolo** [comment]
Also, I tried to join to the Discord as I wanted potential contact or place where maybe I could give some ideas I had for mod, but it's not working when I checked.
I though I would mention it there because it's not worth it's own Issue page...

**Comment by Coranthes** [comment]
The link on curseforge for the discord is working now.

**Comment by svenhjol** [comment]
Ok, this is definitely happening. The hopper output in ComposterBlock is hardcoded and I would have to write some fairly intrusive ASM to make this automation work. I'm not going to do it for 1.5.10 as planned because it will delay things too much with 1.16 just around the corner. I will try and find time for this at some point in the near future.

**Comment by SpiderKolo** [comment]
What if... there was a perfect clone for Hopper but with that tweak? Or Composter?
Say that new Composter would put items in hidden slots, and if there would be no hopper underneath new composter it would throw items from block as normal?

OR add Hud for Composter where you can put items directly into specific slot from which composter takes items and few exit slots which would generate outcome - more Bonemeal, Mushrooms and other items we added in configuration file...
You could speed up the usage of composter  by allowing it to hold stack of items which would go through with relatively quickly until it get's filled up...

That would mean programing Composter from scratch and just using available models in game... but would let for custom recipes to work with automation.
