### ISSUE TITLE
Wolf texture inconsitency

### ISSUE THREAD

**Issue by NeverLoseGuy** [svenhjol/Charm#275]
Hi

I have noticed that the new wolf textures do not have "friendly" eyes akin to the default wolf when tamed. Is this intentional? If it isn't, would there be a fix for it?

**Comment by svenhjol** [comment]
It was dropped for timesaving, so the tame texture is the same as the untame texture. Currently we are working on bugs and stability so there's no capacity for doing this texture change, but if you'd like to have a go and submit a pull request I'd be happy to accept it.

The only one that has "tame" eyes is the texture called `amotwolf`.

The textures to change are here: [https://github.com/svenhjol/Charm/tree/master/src/main/resources/assets/charm/textures/entity/wolf]()

**Comment by NeverLoseGuy** [comment]
Hey so, I have made (or should I say, edited) a bunch of textures based on vanilla wolf, which should result in a whopping 25 variants of them. Do you want to add this into your mod?

https://www.curseforge.com/minecraft/texture-packs/more-wolf-variants

This mod is waiting for its approval, but you can check them at later time.

**Comment by svenhjol** [comment]
We'd be happy to review them for inclusion. Are you happy to create the variants in your Charm fork?
Btw, your PR was accepted and the tame textures will be going into 1.5.10. Thanks for doing this :)
