### ISSUE TITLE
Texture Inconsitencies

### ISSUE THREAD

**Issue by SaltSouls** [svenhjol/Charm#280]
This is less of a bug and more of a personal complaint when it comes to the textures of certain blocks. I feel like the crate and barrel blocks were done right the first time before the latest texture changes, and that with these not only does it not look like the barrel that minecraft already had(in my opinion it looks worse), but it also introduced an inconstancy. When the barrel is closed it has a really dark border around the lid and lip of the barrel, but when open that border is completely gone and it looks like it is just using the standard plank texture with a hole drawn in the center. The underside of the barrels also seem to be off and have some funky texturing issues. Maybe I'm unaware of the changes made with how the textures are being drawn, but I don't think they should be looking the way they do.
![2020-06-07 (1)](https://user-images.githubusercontent.com/36361103/83983699-6f822a00-a8e5-11ea-9483-a1402c646a27.png)
![2020-06-07 (2)](https://user-images.githubusercontent.com/36361103/83983700-71e48400-a8e5-11ea-977b-01f89b2c710a.png)
![2020-06-07](https://user-images.githubusercontent.com/36361103/83983702-7315b100-a8e5-11ea-91dd-086022ba2cca.png)
I love the mod, and I loved the original textures it had. It would be great if you brought them back.

**Comment by SaltSouls** [comment]
I would also like to make a suggestion to just remove the spruce barrel and just rename the vanilla barrel to spruce. It would be one less block for the mod to load and would remove a redundancy of what appears to be two spruce barrels.

**Comment by NeverLoseGuy** [comment]
I can confirm the "dark lid" issues, and I would like to point out that, these barrel variants do not show up in the creative menu (in decoration tab) as well, for whatever reason.

**Comment by svenhjol** [comment]
One for you to respond to, @Coranthes  :D

**Comment by SaltSouls** [comment]
If help is wanted with the artwork for blocks, I am more than willing to donate some of my time to make textures. I have done pixel art and textures for minecraft before, as well as a little bit of modeling. I would be more than willing to help out.

**Comment by Coranthes** [comment]
I agree the lid on the inside is a bit of an issue.  It is something I considered when designing them, but there was no good solution as to how to make them look good at the time.  I will look at it again and see what I can work out to keep it more consistent.  The textures on the bottom was simply intended to be something fun.  Again, something I will look at and likely change on at least some, if not all, of.  Not something I'm making any guarentees about, however.

**Comment by Coranthes** [comment]
Textures reworked on barrel top and bottoms in Covalent 1.0.2.  They will also be implemented in the next Charm release, 1.5.10.
