### ISSUE TITLE
[Suggestion] Change totem of shielding texture

### ISSUE THREAD

**Issue by PercyJames** [svenhjol/Charm#281]
![174px-Totem_of_Shielding_artifact](https://user-images.githubusercontent.com/65469481/83985665-afeea180-a8ff-11ea-83e9-c84d8d5f6c48.png)

so, this mod has a totem of shielding and so does minecraft dungeons. and the minecraft dungeons wiki has a sprite for the totem of shielding. i had the idea that you could use this sprite for the totem of shielding in your mod

**Comment by svenhjol** [comment]
Thanks, but we are going to keep the current one for consistency with Minecraft's Totem of Undying - the Dungeons item sprite is too different.
