### ISSUE TITLE
[1.15.2] Visual Glitch with Charm Barrels when opened.

### ISSUE THREAD

**Issue by SpiderKolo** [svenhjol/Charm#285]
Visual Glitch found on 1.15.2
Mod version: Charm-1.15.2-1.5.9.jar

![image](https://user-images.githubusercontent.com/62638498/84854929-23608380-b063-11ea-81aa-a533ec1c8e02.png)
I opened those barrels using Debug Stick.
The glitch is just visual and doesn't affect the game from what I was texting...

Interestingly enough, I didn't noticed any errors with barrels from Covalent.
![2020-06-17_06 27 42](https://user-images.githubusercontent.com/62638498/84855176-c2857b00-b063-11ea-9d12-0f2f96112337.png)

**Comment by Coranthes** [comment]
This has already been addressed and fixed as referenced [here](https://github.com/svenhjol/Charm/issues/280)

**Comment by SpiderKolo** [comment]
Oh, okay, I didn't noticed that...
Well, thanks for answer! :D
