### ISSUE TITLE
[1.15.2] Unable to craft Charm barrels from vanilla wood

### ISSUE THREAD

**Issue by FynnWaelsing** [svenhjol/Charm#288]
I just tried making an acacia barrel following this mod's recipe, but the result was a vanilla barrel. The acacia barrel item shows up in JEI with the correct ingredients, but when you arrange them it still produces the vanilla barrel. I double-checked this on a fresh install with just Charm installed, and I got the same result. The only barrel that functions properly is the Dark Oak barrel, though all their recipes show up in the vanilla recipe book. The items are acquirable through creative mode or using the JEI cheat function, but not through their normal recipes. See images below for further clarification.

![2020-06-19_13 11 15](https://user-images.githubusercontent.com/45303748/85162582-9e769500-b22f-11ea-976e-d739b2ef2a3b.png)
![2020-06-19_13 11 27](https://user-images.githubusercontent.com/45303748/85162584-9fa7c200-b22f-11ea-9172-82e99f0a989b.png)
![2020-06-19_13 11 40](https://user-images.githubusercontent.com/45303748/85162588-a0405880-b22f-11ea-8edb-1a5a84212505.png)
![2020-06-19_13 11 52](https://user-images.githubusercontent.com/45303748/85162590-a0d8ef00-b22f-11ea-9581-f4ab78b57e97.png)
![2020-06-19_13 12 04](https://user-images.githubusercontent.com/45303748/85162592-a20a1c00-b22f-11ea-8bf3-253506c1b3ad.png)
![2020-06-19_13 12 28](https://user-images.githubusercontent.com/45303748/85162593-a2a2b280-b22f-11ea-8a25-986ca9475210.png)
![2020-06-19_13 13 14](https://user-images.githubusercontent.com/45303748/85162598-a33b4900-b22f-11ea-884a-0037de1e1695.png)

**Comment by svenhjol** [comment]
Thanks for the report. What version of Charm?

**Comment by FynnWaelsing** [comment]
Ah, right. It's the latest version, Charm-1.15.2-1.5.9.
