### ISSUE TITLE
charged emerald dispenser behavior

### ISSUE THREAD

**Issue by WarlordWossman** [svenhjol/Charm#3]
Since the charged emeralds can be thrown by the player I expected dispensers to fire them as a projectile rather than just dropping the item, similar to how eggs work in vanilla.

I am aware that some items that have projectile behavior when thrown by the player (like enderpearls) cannot be fired as a projectile by the dispenser but for charged emeralds it would be nice to have similar mechanics to vanilla eggs for automation reasons!

**Comment by svenhjol** [comment]
Agreed.
