### ISSUE TITLE
[1.16.1-beta2] candle and gold bars not showing up in JEI

### ISSUE THREAD

**Issue by WarlordWossman** [svenhjol/Charm#303]
Quark is installed, config forces charm version of gold bars and candles - both of those are registered and there but for some reason they are not showing up in JEI, I can use a command to get them tho!

Edit: Beewax is there as an item but also not showing up in JEI.
Gold bars have a recipe, candles do not apparently!

**Comment by svenhjol** [comment]
Tested, config overrides now working
