### ISSUE TITLE
[1.16.1-beta2] most items have fuel values

### ISSUE THREAD

**Issue by WarlordWossman** [svenhjol/Charm#305]
All charm items except netherrite nuggets, endermite powder and bat in a bucket have a fuel value of 200 ticks (or 1.5 items potentially smelted), for a lot of the wooden items I would expect a fuel value but stuff like enderpearl blocks, redstone sand, lanterns, gold chains etc. seem like they shouldn't have fuel values at all.

Correction: The 3 items from #303 also don't have a fuel value.

**Comment by svenhjol** [comment]
Added back burntimes for wooden things.
