### ISSUE TITLE
[1.16.1-beta2] hoe harvesting or its config not working properly

### ISSUE THREAD

**Issue by WarlordWossman** [svenhjol/Charm#306]
Apparently hoe harvesting is not working, quark is present but all quark hoe features turned off, force enable in charm config turned on for hoe harvesting but it doesn't appear to work. 
Could be the feature itself not working or the config, I can investigate in a charm only instance if you want me to!

**Comment by svenhjol** [comment]
Fixed in https://github.com/svenhjol/Charm/commit/3557eea5d3be4552c62007397d51da22a645f14a
