### ISSUE TITLE
[1.16.1-beta2] hoppers/droppers can input blacklisted items into bookcases

### ISSUE THREAD

**Issue by WarlordWossman** [svenhjol/Charm#307]
The blacklist for items that you can store in bookcases doesn't appear to work when a hopper or dropper inserts the item into the bookcase:
![2020-08-10_14 18 36](https://user-images.githubusercontent.com/16925725/89781876-74956c80-db14-11ea-96ef-061b660ef5e5.png)

**Comment by svenhjol** [comment]
Also fixed shulkerboxes and crates
