### ISSUE TITLE
[1.16.1-beta2] mineshaft decorations can replace any block

### ISSUE THREAD

**Issue by WarlordWossman** [svenhjol/Charm#310]
The additional blocks spawned in mineshafts seem to be able to replace basically any block (although I am not sure about it, maybe fences and planks are indeed excluded).
I would suggest a blacklist for at least rails and spawners to not get replaced since that might be confusing and lead to things like this:
![2020-08-08_10 00 03](https://user-images.githubusercontent.com/16925725/89782489-aa872080-db15-11ea-97dd-f664b4db4832.png)

**Comment by svenhjol** [comment]
Removed slabs and emerald as discussed but not going to do additional position checks.
