### ISSUE TITLE
[1.16.1-beta2] endermite powder triggering late

### ISSUE THREAD

**Issue by WarlordWossman** [svenhjol/Charm#312]
If you rightclick endermite powder in the end dimension it does play the use animation on the main hand. However after roughly a second it does again and that's also when the sound plays and the particle effect spawns.
Is this just related to to searching for end city locations?

Edit: I would also suggest an item use cooldown like enderpearls have because spamming the enderpearl powder can get quite laggy.

**Comment by svenhjol** [comment]
Fixed in 26ee0e0f930426a7c46743ac14fb03137a5be474
