### ISSUE TITLE
[Charm 2.0 fabric] Nitwits are still appearing in the world

### ISSUE THREAD

**Issue by ridjack** [svenhjol/Charm#316]
I downloaded your 2-day-old shitmix repo and pressed build. There was a load of red text and your version number is wrong. Crates wouldn't appear in creative menu, can't even use commands to get them in. Also I still saw nitwits. Fix this!

**Comment by svenhjol** [comment]
I. Will. Kill. You.

**Comment by ridjack** [comment]
Issue fixed, amazing response time. Thanks!
