### ISSUE TITLE
[1.16.2 Fabric beta] Crouching when shift clicking into Charm inventories

### ISSUE THREAD

**Issue by FynnWaelsing** [svenhjol/Charm#319]
Charm version: charm-2.0.0-beta.1

Very, very minor bug with the latest fabric beta. When you hold down shift while in the GUI to send items into Charm inventories (bookcase, crate, etc.), after a brief moment the character crouches like when shifting normally outside a GUI. This does not happen with vanilla inventories like chests, including the new Charm chests.

Excited about the beta!

**Comment by svenhjol** [comment]
Thanks for the report. I'm struggling to repeat this. Are you using any other mods alongside?

**Comment by FynnWaelsing** [comment]
Only REI for the moment while I test things. I can get back on now and try to recreate it.

**Comment by svenhjol** [comment]
Can't think why that would cause an issue, but I'll spin up an instance in multimc and try it

**Comment by FynnWaelsing** [comment]
I just restarted mine and now it isn't doing it, haha. Silly me. You can close this if you like. I'll make a new issue if it pops up again. Thanks again for a great mod!

**Comment by svenhjol** [comment]
Do you discord?

**Comment by FynnWaelsing** [comment]
Yea, I mostly hang out on Vazkii's discord, but a few others as well. I'm ClintDK on there
