### ISSUE TITLE
Bookshelves in villages

### ISSUE THREAD

**Issue by Darkfiend009** [svenhjol/Charm#32]
Hey there!

Just wanted to follow up after testing Charm in my streaming community pack. I'm loving the content so far, amazing work!

I did want to let you know that i have run into some issues with bookshelves spawning awkwardly in villages.  I have a screenshot to demonstrate what i mean:

https://cdn.discordapp.com/attachments/367514014114381824/571494397892624389/unknown.png

If you are aware of it, cool. I just wanted to bring it to your attention while i as testing. Cheers!

**Comment by svenhjol** [comment]
That... is very very strange! Would you be able to paste the list of mods you use please?

**Comment by Darkfiend009** [comment]
Sure thing!

    Botania (by Vazkii)
    NetherEx (by LogicTechCorp)
    PlusTiC (by Landmaster_phuong0429)
    AbyssalCraft (by Shinoow)
    Surge (by Darkhax)
    Mantle (by mDiyo)
    Gendustry (by bdew)
    BdLib (by bdew)
    Mine Addons 2 (by iamshift__)
    Wings Horns & Hooves, the Ultimate Unicorn Mod (by KaneApollo)
    AutoRegLib (by Vazkii)
    Progressive Bosses (by Insane96)
    Brandon's Core (by brandon3055)
    Draconic Evolution (by brandon3055)
    Immersive Petroleum (by theFlaxbeard)
    Controlling (by jaredlll08)
    OpenComputers Drivers for Tinkers Construct (by BrisingrAerowing)
    Corail Tombstone (by Corail31)
    stimmedcow : NoMoreRecipeConflict (by Oliv1er)
    Better Railroads (by Creator126)
    Thaumic Additions: Reconstructed (by Zeitheron)
    Thaumcraft (by azanor)
    Thaumic Terminal (by DAsh0t)
    Cyclic (by Lothrazar)
    Cooking for Blockheads (by BlayTheNinth)
    Blood Magic (by WayofTime)
    AbyssalCraft Integration (by Shinoow)
    Lapis Stays in the Enchanting Table (by csb987)
    FTB Utilities (by FTB)
    Just Enough Items (JEI) (by mezz)
    Embers Rekindled (by BordListian)
    Decocraft2 (by RazzleberryFox)
    Toast Control (by Shadows_of_Fire)
    Guidebook (by gigaherz)
    Dungeon Mobs Reborn (by Sunconure11)
    Baubles (by azanor)
    Rustic (by mangoose3039)
    Tinkers Construct (by mDiyo)
    FTB Library (by FTB)
    Corail Pillar (by Corail31)
    Applied Energistics 2 (by AlgorithmX2)
    Inventory Pets (by Purplicious_Cow)
    Forge MultiPart CBE (by covers1624)
    Roguelike Dungeons (by Greymerk)
    Cyclops Core (by kroeser)
    Corail Pillar - Extension Quark & Botania (by Corail31)
    CodeChicken Lib 1.8.+ (by covers1624)
    Rustic Thaumaturgy (by Voxel_Friend)
    Astral Sorcery (by HellFirePvP)
    Neat (by Vazkii)
    Mystical Agradditions (by BlakeBr0)
    Worley's Caves (by super_fluke50036)
    Redstone Flux (by TeamCoFH)
    Just Enough Resources (JER) (by Way2muchnoise)
    Shadowfacts' Forgelin (by shadowfactsmc)
    Mekanism (by aidancbrady)
    Better Builder's Wands (by Portablejim)
    Mekanism Generators (by aidancbrady)
    Mekanism Tools (by aidancbrady)
    Immersive Tech (by ferroo2000)
    Charm (by svenhjol)
    Actually Additions (by Ellpeck)
    NotEnoughIDs (by fewizz)
    Woot (by Ipsis)
    Hammer (Lib) Core (by Zeitheron)
    Forestry (by SirSengir)
    ActuallyComputers (by canitzp)
    Chest Transporter (by CubeX2)
    WanionLib (by WanionCane)
    OpenPrinter (by MichiyoRavencroft)
    Construct's Armory (by theillusivec4)
    Random Things (by lumien231)
    NuclearCraft (by TLJGames)
    SimpleHarvest (by TehNut)
    ConnectedTexturesMod (by tterrag1098)
    EnderCore (by tterrag1098)
    Bookshelf (by Darkhax)
    Animus (by TeamDman)
    Ore Excavation (by Funwayguy)
    Pam's HarvestCraft (by MatrexsVigil)
    Chisel (by tterrag1098)
    OpenComputers (by SangarWasTaken)
    LibraryEx (by LogicTechCorp)
    Quark (by Vazkii)
    Immersive Engineering (by BluSunrize)
    Crafting Tweaks (by BlayTheNinth)
    SwingThroughGrass (by exidex)
    Tinkers' Tool Leveling (by bonusboni)
    UniDict (by WanionCane)
    RandomPatches (by TheRandomLabs)
    Chance Cubes (by turkey2349)
    Good Ol' Currency (by BeardlessBrady)
    Chunk Animator (by lumien231)
    Traverse (by ProfessorProspector)
    Inventory Tweaks (by Kobata)
    AppleSkin (by squeek502)
    Aquaculture (by Shadowclaimer)
    Multi Mob Library (by Daveyx0)
    Thaumic Periphery (by mangoose3039)
    Faster Ladder Climbing (by MadDachshund)
    Fast Leaf Decay (by Olafskii)
    Embersified (by TheRealp455w0rd)
    Mouse Tweaks (by YaLTeR97)
    BetterFps (by Guichaguri)
    Mystical Agriculture (by BlakeBr0)
    Cucumber Library (by BlakeBr0)
    Ender IO (by CrazyPants_MC)
    LLibrary (by iLexiconn)
    Clumps (by jaredlll08)
    Primitive Mobs (by Daveyx0)
    OpenModsLib (by OpenMods)
    OpenBlocks (by OpenMods)
    Blood Arsenal (by Arcaratus)
    Guide-API (by TehNut)
    Magic Bees (by MysteriousAges)
    Morpheus (by Quetzi)
    JourneyMap (by techbrew)
    Zoocraft Discoveries (by Pavoreality)
    NetherPortalFix (by BlayTheNinth)
    Fairy Lights (by pau101)
    Hwyla (by TehNut)
    FTB Utilities: Backups (by LatvianModder)
    Light Level Overlay Reloaded (by oldjunyi)
    Placebo (by Shadows_of_Fire)
    Tesla Core Lib (by Face_of_Cat)
    ViesCraft - Airships! (by Viesis_Gaming)
    PTRLib (by RazzleberryFox)
    Better Advancements (by Way2muchnoise)
    Fence Jumper (by TheRealp455w0rd)
    Waila Harvestability (by squeek502)
    Thaumic Computers (by jco2641)

**Comment by svenhjol** [comment]
Thanks for that, I'll see if there's anything likely to cause some compat issues

**Comment by svenhjol** [comment]
Hi - I've had a quick look through the descriptions of mods listed here that I haven't tested against, but it's taking too long. Can you add a zip of your mods folder to this ticket, and let me know what version of forge you're using? I'll test it locally. Thanks!

**Comment by Darkfiend009** [comment]
Certainly, it's actually hosted on curseforge:

https://minecraft.curseforge.com/projects/twitch-kittens-reforged

**Comment by svenhjol** [comment]
Ah - this one! Sorry, I didn't make the connection.

**Comment by svenhjol** [comment]
Update: took a long time to figure out, but it's **Actually Additions**.  The buildings that it generates overrides the library village house

https://github.com/Ellpeck/ActuallyAdditions/blob/b81a91d1d66ee593601b0096d806e330e5049a84/src/main/java/de/ellpeck/actuallyadditions/mod/gen/village/component/VillageComponentCustomCropField.java#L28

I'm going to put a workaround into beta4/rc1 and then close this.

**Comment by Darkfiend009** [comment]
Thank you for looking in to it!
