### ISSUE TITLE
Compatibity with Allure (Fabric 1.16)

### ISSUE THREAD

**Issue by vico93** [svenhjol/Charm#322]
Well, now with Charm officially released for Fabric 1.16 i want to know if it will work with Allure (a combination between Charm + some Quark features).

I already asked for Allure author how things (integration, possibly removing charm-specific features keeping Quark-based things integrated with Charm) will be after your release, and i'm asking here just in case.

**Comment by svenhjol** [comment]
Hi,

There isn't any mod compatibility with Allure or any other fabric mods at this time.  I haven't tested against Allure.

If you need to disable certain features so they don't overlap with Allure, then you can disable them in `charm.json`.

**Comment by vico93** [comment]
Alright! Thanks a lot for the information!
