### ISSUE TITLE
1.12.2 Crash with rftools

### ISSUE THREAD

**Issue by Basedgod199** [svenhjol/Charm#324]
Anytime i go into an rftools dimension, i crash after 2 seconds of being in the dimension

once i remove charm, the crash goes away.

mod versions:
charm-1.12.2-1.4
rftools-1.12.2-7.73
rftoolsdim-1.12-5.71

crash log:
https://pastebin.com/FXKFPBst

**Comment by svenhjol** [comment]
Can you try with this hotfix and see if the problem still happens? https://github.com/svenhjol/Charm/releases/download/1.12.2-1.4/Charm-1.12.2-1.4.1.jar

**Comment by Basedgod199** [comment]
Yep still happens

https://pastebin.com/JDp5D3wF

**Comment by Basedgod199** [comment]
okay its possible it is fixed, just that existing worlds still crash.. i'll test this more to confirm
