### ISSUE TITLE
[1.16.3] How to craft Hoppers if Charm replaces vanilla chest

### ISSUE THREAD

**Issue by LordRius** [svenhjol/Charm#326]
Hi!

How can I craft a hopper if I can't craft a vanilla chest?

Many thanks!

**Comment by svenhjol** [comment]
That is an extremely good point and the person responsible for this oversight will be punished.

**Comment by LordRius** [comment]
On the other hand, I'm also using Adorn mod and for some furniture crafting, it requires vanilla chest...

**Comment by svenhjol** [comment]
I'll figure something out
