### ISSUE TITLE
Stackable potions break brewing stand automation

### ISSUE THREAD

**Issue by Shados** [svenhjol/Charm#327]
Having `StackablePotions enabled` set causes brewing stands to accept **any** item in their potion slots, not merely (stacked) potions. This in turn means that feeding in blaze powder from one of the sides will result in blaze powder entering *both* the fuel slot **and** the potion slots, effectively breaking the ability to automate potion stands.

**Comment by svenhjol** [comment]
What version of Charm is this for?

**Comment by Shados** [comment]
`Charm-1.15.2-1.5.9`
