### ISSUE TITLE
[1.16.3] Barrels lose content on server restart

### ISSUE THREAD

**Issue by Watersfall** [svenhjol/Charm#332]
Charm barrels behave strangely on a server restart, they can be opened where they have their opens, but then when you leave the inventory, the barrel never "closes" (the "open" barrel texture sticks) until you right click it and then right click it again to open it. After it opens again it will be empty and then work normally until another server restart.

server log attached, although I didn't see anything unusual in it
[latest.log](https://github.com/svenhjol/Charm/files/5351440/latest.log)

**Comment by svenhjol** [comment]
I don't understand this. Can you send a video of it happening please?

**Comment by svenhjol** [comment]
Nevermind I just managed to get it to repeat what you saw

**Comment by svenhjol** [comment]
This was auto-closed by git. I pushed a potential fix for this to 2.0.3: 

https://github.com/svenhjol/Charm/releases/download/2.0.3-fabric/charm-fabric-1.16.3-2.0.3.jar

Please can you test this build? Seems to be solved on the server for me.

**Comment by Watersfall** [comment]
Seems to work for me too, thanks!

**Comment by svenhjol** [comment]
That's great, thanks for the report!
