### ISSUE TITLE
[1.16.3] Bookshelf sound registry error

### ISSUE THREAD

**Issue by Watersfall** [svenhjol/Charm#333]
After some amount of time of a server being up, I start being unable to connect because of a sound registry error. 
The issue goes away on a server restart but not on a client restart.

[client-latest.log](https://github.com/svenhjol/Charm/files/5354737/client-latest.log)
[server-latest.log](https://github.com/svenhjol/Charm/files/5354736/server-latest.log)

**Comment by svenhjol** [comment]
Hi, could you try with this build and see if it continues to happen?  Please take a backup of your world first.

https://github.com/svenhjol/Charm/releases/download/2.0.3-fabric/charm-fabric-1.16.3-2.0.3.jar

**Comment by Watersfall** [comment]
It hasn't happened since so I think it's fixed
