### ISSUE TITLE
Optifine + Optifabric Crash

### ISSUE THREAD

**Issue by CynicalShrew** [svenhjol/Charm#335]
The mod crashes on startup if Optifine is installed. 

[crash-2020-10-12_19.35.24-client.txt](https://github.com/svenhjol/Charm/files/5368621/crash-2020-10-12_19.35.24-client.txt)

**Comment by svenhjol** [comment]
I'm unlikely to support OptiFabric or OptiFine as it isn't a priority to chase down all the weird changes it makes to the code. If you're looking for something that can enhance performance, you could try Sodium. Charm plays nicely with it too.
