### ISSUE TITLE
[1.16.3] Slight Gui Modification Crash 

### ISSUE THREAD

**Issue by KeoxDS** [svenhjol/Charm#336]
If Slight Gui Modification is installed along with charm, the game crashes on startup
https://pastebin.com/mAzPMzAj

**Comment by svenhjol** [comment]
Thanks for the report. Please try this version and let me know if it works.
https://github.com/svenhjol/Charm/releases/download/2.0.3-fabric/charm-fabric-1.16.3-2.0.3-hotfix2.jar

**Comment by KeoxDS** [comment]
It works perfectly! Thank you for fixing it.
