### ISSUE TITLE
Added Cake for Fabric 

### ISSUE THREAD

**Issue by Miros77** [svenhjol/Charm#337]
here is the code

public class NameCakeBlock extends CakeBlock {
	public NameCakeBlock() {
		super(FabricBlockSettings.of(Material.CAKE).ticksRandomly().sounds(BlockSoundGroup.WOOL).nonOpaque());
	}

   public ActionResult onUse(BlockState state, World world, BlockPos pos, PlayerEntity player, Hand hand, BlockHitResult hit) {
      if (world.isClient) {
         ItemStack itemStack = player.getStackInHand(hand);
         if (this.tryEat(world, pos, state, player).isAccepted()) {
            return ActionResult.SUCCESS;
         }

         if (itemStack.isEmpty()) {
            return ActionResult.CONSUME; 
         }
      }

      return this.tryEat(world, pos, state, player);
   }

   public ActionResult tryEat(WorldAccess world, BlockPos pos, BlockState state, PlayerEntity player) {
      if (!player.canConsume(false)) {
         return ActionResult.PASS;
      } else {
         player.incrementStat(Stats.EAT_CAKE_SLICE);
         player.getHungerManager().add(6, 0.5F);
         int i = (Integer)state.get(BITES);
         if (i < 6) {
            world.setBlockState(pos, (BlockState)state.with(BITES, i + 1), 3);
         } else {
            world.removeBlock(pos, false);
         }

         return ActionResult.SUCCESS;
      }
   }
}

**Comment by svenhjol** [comment]
?

**Comment by Miros77** [comment]
> ?

add cakes!

**Comment by Miros77** [comment]
for Fabric

**Comment by Miros77** [comment]
you are not updating libraries?

**Comment by svenhjol** [comment]
Flavored cake is not being continued in Charm.
