### ISSUE TITLE
Incompat with OptiFabric/OptiFine.

### ISSUE THREAD

**Issue by EnderBro123** [svenhjol/Charm#338]
The launcher simply says

The game crashed whilst initializing game
Error: java.lang.RuntimeException: Could not execute entrypoint stage 'main' due to errors, provided by 'charm'!
Exit Code: -1

[crash-2020-10-18_21.39.34-client.txt](https://github.com/svenhjol/Charm/files/5399124/crash-2020-10-18_21.39.34-client.txt)

Mods are in the crash report. But the crash report DOES clearly say the issue is from Charm.

**Comment by Coranthes** [comment]
This crash was addressed in issue [#335](https://github.com/svenhjol/Charm/issues/335)  
See link for info.
