### ISSUE TITLE
Crate has no name

### ISSUE THREAD

**Issue by Sixdd6** [svenhjol/Charm#34]
The block charm:crate has no name, what I mean is the tooltip when you hover over it in your inventory just has a blank tooltip.
Here is a screenshot for reference: https://i.imgur.com/HGbir5Z.png

Minecraft 1.12.2
Forge 2836
Charm 1.0.0 beta 3

**Comment by svenhjol** [comment]
Thanks for the report. Could you provide more details? Did you craft the crate from scratch, find a crate in a village and break it, or grab it via creative/commands?

**Comment by svenhjol** [comment]
This has been fixed in next version. I'm attaching it to this ticket, feel free to try it out and if the problem comes back then open this comment.
[Charm-1.12.2-1.0.0-rc1.zip](https://github.com/svenhjol/Charm/files/3125684/Charm-1.12.2-1.0.0-rc1.zip)
