### ISSUE TITLE
[1.16.3 Fabric] Crash with Better Slabs

### ISSUE THREAD

**Issue by crysthala** [svenhjol/Charm#340]
Crashes before startup with exit code 0. Removing either this mod or [Better Slabs](https://www.curseforge.com/minecraft/mc-mods/better-slabs) allows the game to start. Reported to that dev [here](https://github.com/Eilux/BetterSlabs/issues/6).

[latest.log](https://github.com/Eilux/BetterSlabs/files/5426680/latest.log), no crash-report generated.
**Fabric Loader:** 0.10.1-209
**Fabric API:** 0.2.1-412
**Charm:** 2.0.3
**Better Slabs:** 1.1.1

Please let me know if there's anything I can do to help!

**Comment by svenhjol** [comment]
Thanks for the report. Please try this version alongside Better Slabs and let me know if it works.
https://github.com/svenhjol/Charm/releases/download/2.0.3-fabric/charm-fabric-1.16.3-2.0.3-hotfix2.jar

**Comment by crysthala** [comment]
Holy crap, that was quick. That file works. Many thanks!
