### ISSUE TITLE
Mod conflict with Builders blocks mod

### ISSUE THREAD

**Issue by RDKRACZ** [svenhjol/Charm#343]
Reported to TiphaineLAURENT too - https://github.com/TiphaineLAURENT/Builders-blocks/issues/7
crash report - does not generate
latest.log - https://hatebin.com/cuaiyvokth

**Comment by svenhjol** [comment]
Please check fixed in https://github.com/svenhjol/Charm/releases/download/2.0.3-fabric/charm-fabric-1.16.3-2.0.3-hotfix2.jar (also available on CF)

**Comment by RDKRACZ** [comment]
Same here as in Bookshelving mod issue.
