### ISSUE TITLE
[1.12.2] Crash issue caused by flying to planet Diona from MorePlanets, a Galacticraft addon.

### ISSUE THREAD

**Issue by Mysteriaa** [svenhjol/Charm#346]
Not sure if 1.12 is still supported but I keep getting this crash issue upon entering this planet. Was told it was likely for some kind of worldgen function. https://paste.ee/p/kLDGH#s=0&l=947

**Comment by svenhjol** [comment]
SpectreHaunting needs destroying in a fire
