### ISSUE TITLE
[1.16.3] Crash on startup with 2.0.3 Hotfix 2

### ISSUE THREAD

**Issue by RealSnowKid** [svenhjol/Charm#347]
Today I decided to add Charm to my slightly modded Minecraft play through. Unfortunately, it crashed on startup, saying it was `An unexpected critical error was encountered` with a mixin. And yes I was using the `harm-fabric-1.16.3-2.0.3-hotfix2.jar` verison that says it fixes some mixin issues.

Link to the [pastebin](https://pastebin.com/tyEnu6wx).

**Comment by svenhjol** [comment]
Thanks for the report. Please could you try this fix and let me know if the crash still occurs? https://github.com/svenhjol/Charm/releases/download/2.0.3-fabric/charm-fabric-1.16.3-2.0.3-hotfix3.jar

**Comment by RealSnowKid** [comment]
Unfortunately, it seems to have not fixed the issue.

Here's the new [pastebin](https://pastebin.com/EbZQWhWM).

**Comment by svenhjol** [comment]
Not sure then. Does it clash with another mod?

**Comment by RealSnowKid** [comment]
Okay, so I did a bit of investigating. Testing it with all the mods in my mods folder, I found out that the one it breaks with is [OptiFabric](https://www.curseforge.com/minecraft/mc-mods/optifabric). I tried using it with the newest updated files for their mod and it still produced the same crash, as far as I can tell.

In any case here's the latest [crash report](https://pastebin.com/cJ7KhwKe).

**Comment by FynnWaelsing** [comment]
Optifine tends to break everything, unfortunately, and there's not much that modders can do about it.

**Comment by svenhjol** [comment]
Thanks Fynn. I'll update the issue template with a notice about Optifine/Optifabric as it isn't supported by Charm at the moment.
