### ISSUE TITLE
Server Crash: Exception Ticking World

### ISSUE THREAD

**Issue by Darkfiend009** [svenhjol/Charm#35]
It looks like there may be some compatibility issues between Charm and Abyssalcraft. I can't tell for certain from the crashlog which side it may be on, but it happened when an Abyssalcraft biome generated and decorations from Charm were being added, namely the bookshelf. 

Here is the crashlog:

https://pastebin.com/7zygP18w

I will continue to keep testing things!

**Comment by svenhjol** [comment]
Please check again with beta3. This could be related to #27

**Comment by Darkfiend009** [comment]
I updated the pack and will be testing it tonight. Sorry if it was a duplicate bug. Twitch didn't have any updates showing for the mods in the pack so i wasn't aware i didn't have the latest version.

**Comment by svenhjol** [comment]
Sure no worries. Let me know how it goes

**Comment by svenhjol** [comment]
I think we're good. I tested for a bit and found a village in a Darklands biome, seed 7373622306136847485 location -968 100 776,  the library generated a bookshelf chest correctly as well as other village decoration appearing to be stable. See images.

![inside](https://user-images.githubusercontent.com/26497903/57051374-bfb5a400-6c70-11e9-9e4c-92fe55dbffa4.jpg)
![outside](https://user-images.githubusercontent.com/26497903/57051375-bfb5a400-6c70-11e9-94f3-170eabbb3fbb.jpg)

**Comment by Darkfiend009** [comment]
Yep everything is working with my new updated pack too! Thank you!
