### ISSUE TITLE
Redstone dust and flowers hit by a glow ball disappear.

### ISSUE THREAD

**Issue by RDKRACZ** [svenhjol/Charm#353]

**Comment by svenhjol** [comment]
Like #354 what should be the behavior here

**Comment by RDKRACZ** [comment]
Well, I don't think items should disappear. This doesn't make any sense, besides a snowball doesn't have such a behavior. Glow ball should just be destroyed in contact with items such as redstone dust or flowers, just like a snowball. What about the name? Currently it is "glow ball" with a space between words. It's ok but maybe consider "glowball".

**Comment by svenhjol** [comment]
Now drops glowstone dust if it can't be placed. It's also been renamed to "Glowball".
