### ISSUE TITLE
What are those?

### ISSUE THREAD

**Issue by RDKRACZ** [svenhjol/Charm#359]
[main/ERROR]: No data fixer registered for glow_ball
[main/ERROR]: No data fixer registered for coral_squid
[main/ERROR]: No data fixer registered for endermite_powder

**Comment by svenhjol** [comment]
Not sure yet. Happens in Quark too

**Comment by RDKRACZ** [comment]
Still don't know what is this? I'm trying to make mods spam less in the console.
