### ISSUE TITLE
Crash on startup 1.16.3 Fabric

### ISSUE THREAD

**Issue by TheGodlyChair** [svenhjol/Charm#362]
[crash-2020-11-11_18.00.42-client.txt](https://github.com/svenhjol/Charm/files/5527454/crash-2020-11-11_18.00.42-client.txt)

I am on version 1.16.3 of Minecraft using the Fabric launcher and every time I try to launch Minecraft, it crashes. The only mod I have that needs Charm is Charmonium, and I have tried all the versions of Charm 1.16.3 and none of them have worked.

**Comment by svenhjol** [comment]
Looks like you're using quite an old version of Charm (2.0.1).  The last stable version was 2.0.3-hotfix2 which you can find on Curseforge here: https://www.curseforge.com/minecraft/mc-mods/charm/files/3098196

**Comment by TheGodlyChair** [comment]
Thank you, but also did not work.

[crash-2020-11-11_18.12.24-client.txt](https://github.com/svenhjol/Charm/files/5527485/crash-2020-11-11_18.12.24-client.txt)

**Comment by svenhjol** [comment]
Try without Optifabric?

**Comment by TheGodlyChair** [comment]
Yeah, Optifabric was the problem but that also means if I want to play with Charm I have to play without Optifine which is fine so thank you for helping me.

**Comment by svenhjol** [comment]
That's fine. Optifabric/optifine compatibility will be considered in a future version, so keep checking curseforge for the latest versions.

**Comment by Coranthes** [comment]
Jellysquid's Phosphor is a great alternative to optifine.  His mod Sodium is also worth checking out.  https://www.curseforge.com/minecraft/mc-mods/phosphor.
