### ISSUE TITLE
[1.16.3 forge] Crash

### ISSUE THREAD

**Issue by Unhook** [svenhjol/Charm#363]
**Required - Versions**
* Charm version - 2.1.1
* Minecraft version - 1.16.3
* Loader - Forge

**Required - Description**
Game crashed when trying to view a recipe in JEI.

**Optional: Steps To Reproduce**
I disabled the keybinds for the portable crafting table & portable ender chest.

**Optional: Stacktrace/Screenshots**
https://pastebin.com/rEzARz5x

**Comment by svenhjol** [comment]
Thanks for the report. It's being looked into

**Comment by svenhjol** [comment]
Can you try this hotfix with the same disabled keybinds? https://github.com/svenhjol/Charm/releases/download/2.1.1/charm-forge-1.16.4-2.1.1-hotfix1.jar

**Comment by svenhjol** [comment]
This version has just been tested locally: https://github.com/svenhjol/Charm/releases/download/2.1.1/charm-forge-1.16.4-2.1.1-hotfix2.jar

**Comment by svenhjol** [comment]
New version deployed on CF: https://www.curseforge.com/minecraft/mc-mods/charm/files/3110768
