### ISSUE TITLE
Config not working in 1.16.4 2.1.1 fabric version. 

### ISSUE THREAD

**Issue by windows-virus** [svenhjol/Charm#365]
**Required - Versions**
* Charm version - 1.16.4 2.1.1
* Minecraft version - 1.16.3
* Loader - Fabric

**Required - Description**
Blocks/items disabled in the config can still be crafted, used and placed (This strangely excludes smooth glowstone which can be disabled without any issues). 

**Optional: Steps To Reproduce**
Mods: fabric-api-0.25.0+build.415-1.16, charmonium-fabric-1.16.4-2.0.2, charm-fabric-1.16.4-2.1.1
Disable a block/s or item/s in the config (I disabled variant bookcases and bookcases/bookshelves in general) 

**Optional: Stacktrace/Screenshots**
![image](https://user-images.githubusercontent.com/53756203/98997991-55e8ac80-252d-11eb-895d-cf6a0ad989fc.png)
Bookcases do not appear in creative inventory.
![image](https://user-images.githubusercontent.com/53756203/98998099-816b9700-252d-11eb-8de5-8baf0107df5d.png)
But appear in the crafting menu and can be crafted and placed.

**Comment by svenhjol** [comment]
Thanks for report. We're currently working out config issues in the beta release, hopefully should be ready by next version.
