### ISSUE TITLE
[1.16.3] Ticking entity

### ISSUE THREAD

**Issue by lulabyte** [svenhjol/Charm#366]
**Required - Versions**
* Charm version - e.g. 2.1.1
* Minecraft version - e.g. 1.16.3
* Loader - Forge 34.1.42

**Required - Description**
While on the server today, two of my players crashed. I looked at the log and the "Ticking entity" error seems (?) to be connected to Charm. This is the first day we installed it. See crash log. Thank you for your work!

**Comment by svenhjol** [comment]
There's a possibility it's related to a keybinding bug. Could you try this hotfix and see if it occurs? Thanks. https://github.com/svenhjol/Charm/releases/download/2.1.1/charm-forge-1.16.4-2.1.1-hotfix2.jar

**Comment by KKotik** [comment]
On last version same happening to me.
https://pastebin.com/f1bwhNaX

**Comment by svenhjol** [comment]
Ok, I think I found the problem. Please try this hotfix and let me know. https://github.com/svenhjol/Charm/releases/download/2.1.1/charm-forge-1.16.4-2.1.1-hotfix4.jar
