### ISSUE TITLE
Ctrl+v text input box crash

### ISSUE THREAD

**Issue by FesterHead** [svenhjol/Charm#367]
**Required - Versions**
* Charm version - `charm-forge-1.16.4-2.1.1.jar` from https://www.curseforge.com/minecraft/mc-mods/charm/files/3109092
* Minecraft version - `1.16.3`
* Loader - `Forge 34.1.42`
* Launcher - `GDLauncher`

**Required - Description**
Instance crashes when using Ctrl+v to paste information into the Singleplayer or Multiplayer text input boxes such as world name, seed, server name, or server address.

**Optional: Steps To Reproduce**
* Enable Charm 2.1.1
* Launch instance
* Start a new Singleplayer world
* Issue a Ctrl+v keystroke combo in the world name (or other text input box)
* Instance crashes

The instance crash occurs when the portable chest or ender chest is enabled (the default).  Setting these to false results in a correct Ctrl+v operation.
Also tried the hotfix jar from #363 and get the same instance crash result when the portable chest or ender chest is enabled.
Success or crash is not affected by the keybind booleans.

**Optional: Stacktrace/Screenshots**
Attached are two crash logs, one with `PortableCraftingClient` and one with `PortableEnderChestClient`.  
[crash-2020-11-13_08.24.40-client.txt](https://github.com/svenhjol/Charm/files/5538884/crash-2020-11-13_08.24.40-client.txt)
[crash-2020-11-13_08.35.30-client.txt](https://github.com/svenhjol/Charm/files/5538885/crash-2020-11-13_08.35.30-client.txt)

**Comment by svenhjol** [comment]
Thank you. This was caused because the bound keys were still trying to send a network packet that expected the world + player to be present, therefore crashing when not in game. Please try this hotfix and let me know: https://github.com/svenhjol/Charm/releases/download/2.1.1/charm-forge-1.16.4-2.1.1-hotfix2.jar

**Comment by FesterHead** [comment]
Confirmed the hotfix2 jar resolves the issue!

**Comment by svenhjol** [comment]
Thanks for testing it out. I'll release this on CF soon.

**Comment by svenhjol** [comment]
Deployed

**Comment by FesterHead** [comment]
Well done, thank you.
