### ISSUE TITLE
[Forge 1.16.4] 

### ISSUE THREAD

**Issue by MoreKerosine** [svenhjol/Charm#368]
Versions:
Charm 2.1.1-hotfix
* Minecraft version - 1.16.4
* Loader - Forge

Description
The inventory crafting menu opens while typing in the command/chat menu

**Comment by svenhjol** [comment]
Thanks, looking at it now

**Comment by svenhjol** [comment]
This should fix it, please let me know: https://github.com/svenhjol/Charm/releases/download/2.1.1/charm-forge-1.16.4-2.1.1-hotfix3.jar
