### ISSUE TITLE
This one is still not fixed

### ISSUE THREAD

**Issue by RDKRACZ** [svenhjol/Charm#369]
https://github.com/svenhjol/Charm/issues/358

**Comment by svenhjol** [comment]
Thanks. Since it's not causing a crash I'll fix it up in 2.1.2.

**Comment by svenhjol** [comment]
This should be ok in latest version: https://github.com/svenhjol/Charm/releases/download/2.1.3/charm-fabric-1.16.4-2.1.3.jar
