### ISSUE TITLE
Please add a 1.16.3 forge version

### ISSUE THREAD

**Issue by Animelabose** [svenhjol/Charm#370]
I have a big modpack with 27 mods and I would really like to add this mod to my modpack, but the mods are all in 1.16.3 and forge. I would really love a forge version of 1.16.3 Charm mod so I can add it to my modpack please.

**Comment by svenhjol** [comment]
The 1.16.4 version of Charm for Forge also works in 1.16.3

**Comment by svenhjol** [comment]
I have updated the tag on the latest forge version on Curseforge. The file is this one: https://www.curseforge.com/minecraft/mc-mods/charm/files/3111048
