### ISSUE TITLE
Forge 1.16.3, hotfix3 build - Crash with portable crafting

### ISSUE THREAD

**Issue by TacoSundae84** [svenhjol/Charm#371]
Opening my inventory in survival with the portable crafting table enabled causes a crash. This doesn't happen if i use the hotkey to open the inventory/crafting screen. The crash log seems to indicate it has to do with drawing the icon for opening inventory / crafting screen?

Crash report - https://pastebin.com/HGM6DFiU

**Comment by svenhjol** [comment]
This is an odd one. Could you try this hotfix please? https://github.com/svenhjol/Charm/releases/download/2.1.1/charm-forge-1.16.4-2.1.1-hotfix4.jar

**Comment by TacoSundae84** [comment]
Works!
