### ISSUE TITLE
Mod Conflict with ''Roughly Enough Items'' for Fabric

### ISSUE THREAD

**Issue by Aflaungos** [svenhjol/Charm#372]
**Versions**
Charm version - 2.1.1
Minecraft version - 1.16.3
Loader - Fabric

**Description**
Enabling both mods gives an error about Mixin from charm

**Steps To Reproduce**
Download both mods and see it crash

**Stacktrace/Screenshots**
_https://pastebin.com/vnJLPaay_

**Comment by svenhjol** [comment]
It's not an error with REI, it's with another mod you have there called `noexpensive`. Charm alters the anvil in order to remove the "Too expensive!" message when trying to enchant, and so does the other mod. It's probably safe to just use Charm's version if this is the functionality you want.

**Comment by Aflaungos** [comment]
Ohh, you're absolutely right!
After uninstalling "Too expensive" and enabling the mod, it worked like a "Charm".
Thank you very much!

**Comment by svenhjol** [comment]
+1 for the charming response
