### ISSUE TITLE
Charm-fabric + NoExpensive incompatibility crash

### ISSUE THREAD

**Issue by garyhopple** [svenhjol/Charm#377]
https://paste.gg/p/anonymous/23f10105ddb747b1b3fcf1275cb78b4b

Charm version: Charm-fabric-1.16.4-2.1.1-hotfix1
Minecraft version: 1.16.4
Loader: Fabric

Charm-fabric-1.16.4-2.1.1-hotfix1 (latest fabric release as of 21/11/2020) is incompatible with NE-1.16.4-1.1.4 (No-Expensive).

**Comment by svenhjol** [comment]
#372

Removal of "Too Expensive!" is already handled by Charm. There's no point in having both mods
