### ISSUE TITLE
Crash using latest Fabric loader (0.10.8 for 1.16.4)

### ISSUE THREAD

**Issue by vico93** [svenhjol/Charm#378]
**Versions**
* Charm version - `charm-fabric-1.16.4-2.1.1-hotfix1`
* Minecraft version - `1.16.4`
* Loader - `Fabric (Loader v0.10.8-1.16.4 / API v0.26.0+1.16)`

**Description**
After updating FLoader to 0.10.8, my came can't boot anymore. Crash report [here](https://gist.github.com/vico93/4adcd4c1ef35c6f5d9184786bc4dd1db).

**Comment by svenhjol** [comment]
Seems related to curious-armor-stands, looking at your crash log. Don't know why it's saying that it is Charm's fault, other than that I also target the same accessor method.

The problem is that their mod probably needs to change `@Invoker()` to `@Invoker("addFeature")`.

**Comment by vico93** [comment]
Thanks for the report @svenhjol , i will report on Curios side.

**Comment by vico93** [comment]
@svenhjol Just FYI, Florens (Curios Armor Stands author) pointed me the issue is caused by this bug on Mixin:

https://github.com/SpongePowered/Mixin/issues/430
