### ISSUE TITLE
[Crash] Ender Sight crash with Hexlands

### ISSUE THREAD

**Issue by DWX12** [svenhjol/Charm#38]
I'm using a custom modpack with Hexlands, Biomes O Plenty, and BiomeTweaker world generation without most structures spawning and came across with crash when getting the ender sight effect:

https://paste.dimdev.org/imehehebel.mccrash

Let me know if you need any more info that what is provided in the crash report.

**Comment by svenhjol** [comment]
Thanks. Was this in the overworld?

**Comment by svenhjol** [comment]
Closing this. Let me know if you're still getting crashes with 1.0.1+

**Comment by DWX12** [comment]
Sure thing, just haven't taken the time to test out the new build. If there's any further development on this issue I will be sure to post about.

Thanks again.
