### ISSUE TITLE
Can't seem to access bookcase's GUI via right clicking

### ISSUE THREAD

**Issue by kihgy** [svenhjol/Charm#382]
**Read me first!**
1. We don't support Optifine or Optifabric. Please check that the problem still occurs if you remove Optifine/Optifabric from your mods.
2. Don't use the bug report to suggest new features or behavior.

**Required - Versions**
* Charm version - charm-forge-1.16.4-2.1.1-hotfix3.jar
* Minecraft version - 1.16.4
* Loader - Forge

**Required - Description**
Can access every other block that have an inventory minus the bookcases

**Optional: Steps To Reproduce**
Provided above

**Optional: Stacktrace/Screenshots**
By adding a stacktrace (e.g. pastebin link) and/or screenshots it helps us understand and fix the problem.

**Comment by svenhjol** [comment]
Should be fixed in 2.1.3
