### ISSUE TITLE
Suggestion: Allow light level of glowball to be configurable like firework rockets

### ISSUE THREAD

**Issue by Greg-J** [svenhjol/Charm#383]
It would be great to have the ability to control the light level of a glowball the way that we control duration of a firework with the number of gunpowder.

So, 1 snowball + 1 glowstone = gowball light level 8.
So, 1 snowball + 2 glowstone = gowball light level 9.
So, 1 snowball + 3 glowstone = gowball light level 10.
So, 1 snowball + 4 glowstone = gowball light level 11.
So, 1 snowball + 5 glowstone = gowball light level 12.
So, 1 snowball + 6 glowstone = gowball light level 13.
So, 1 snowball + 7 glowstone = gowball light level 14.
So, 1 snowball + 8 glowstone = gowball light level 15.

**Comment by svenhjol** [comment]
The glowball is meant to have a low-medium light level and I don't want to add extra items or itemtags. Thanks for suggestion though

**Comment by Greg-J** [comment]
"This feature is meant to be arbitrary and improving it doesn't interest me" is a strange response, but okay. Because why make things useful, right?

**Comment by svenhjol** [comment]
Thanks for the suggestion though
