### ISSUE TITLE
Error upon startup (Fabric, Charm 2.1.1-hotfix 1)

### ISSUE THREAD

**Issue by Sindavar** [svenhjol/Charm#385]
What exactly is going wrong here, and is there a way to fix this?
[crash-2020-11-27_22.25.04-client.txt](https://github.com/svenhjol/Charm/files/5610024/crash-2020-11-27_22.25.04-client.txt)
-
[This](https://github.com/FabricMC/fabric/pull/1097) could be related?

**Comment by svenhjol** [comment]
It's crashing because it's a hack that was in place to get around immutable biome spawns and structures, and I guess it's colliding with another mod in your modpack. I think the only way to fix it is to use the biome API you linked to, but that will take some time to rework.

**Comment by Sindavar** [comment]
> 
> 
> It's crashing because it's a hack that was in place to get around immutable biome spawns and structures, and I guess it's colliding with another mod in your modpack. I think the only way to fix it is to use the biome API you linked to, but that will take some time to rework.

I see, thanks so much for the quick response!

**Comment by svenhjol** [comment]
The biome API was introduced in 2.1.3. Can you test this version: https://github.com/svenhjol/Charm/releases/download/2.1.3-forge-hotfix1/charm-forge-1.16.4-2.1.3-hotfix1.jar

**Comment by svenhjol** [comment]
Fabric Biome API used in latest versions: please try this: https://github.com/svenhjol/Charm/releases/download/2.1.3/charm-fabric-1.16.4-2.1.3.jar

**Comment by svenhjol** [comment]
Please reopen if the latest versions don't work for you
