### ISSUE TITLE
Squid Super Over Spawn

### ISSUE THREAD

**Issue by Hazerden** [svenhjol/Charm#386]
I found a coral area not far from my base in singleplayer and in a mater of seconds there where hundreds of different color squids everywhere few seconds more and game is now unplayable as the lag from the literal Hundreds of squid that have spawned i tried to screen shot this but i was unable to

**Comment by svenhjol** [comment]
Has been fixed in next version, awaiting testing

**Comment by svenhjol** [comment]
Should be solved in the latest 2.1.3 version
