### ISSUE TITLE
The buttons for Ender Chest and Crafting Table in the inventory overlap

### ISSUE THREAD

**Issue by aaronhowser1** [svenhjol/Charm#387]
**Required - Versions**
* Charm version - `2.1.2`
* Minecraft version - `1.16.4`
* Loader - `Forge`

**Required - Description**
![image](https://user-images.githubusercontent.com/15698722/100584874-51085480-32b2-11eb-9859-bc28169d8e9a.png)
![image](https://user-images.githubusercontent.com/15698722/100584892-549bdb80-32b2-11eb-94a2-11ca5f2368ea.png)
Clicking this shows me
![image](https://user-images.githubusercontent.com/15698722/100584905-59f92600-32b2-11eb-8557-ee93cf248ff6.png)

**Comment by svenhjol** [comment]
This should be fixed in latest version of Charm. Please reopen if still an issue

**Comment by aaronhowser1** [comment]
I don't see a new version on curseforge

**Comment by aaronhowser1** [comment]
There... still isn't a new version on curseforge
