### ISSUE TITLE
enchantments remove crush

### ISSUE THREAD

**Issue by Nazguliki** [svenhjol/Charm#388]
**Charm** version - 2.1.2
**Minecraft** version - 1.16.4
**Loader** - Forge -  35.1.0

 **Description**
Crush while using Grindstone to remove enchantments. I run the server for me and my friend. Rebuilding server with same mods didnt help.

 **Steps To Reproduce**
Run a server via forge 35.1.0. Then, create any enhanced tool. Then, place the tool into first clot of Grindstone, and the empty book - into another. Then, you press on the book that appear in the third slot - boom, instant crush.

**Server mods list**
https://pastebin.com/TW8HD6XJ

**logs**
[latest.log](https://github.com/svenhjol/Charm/files/5615078/latest.log)
[debug.log](https://github.com/svenhjol/Charm/files/5615079/debug.log)

**Comment by Nazguliki** [comment]
Will try to provide more info or test if needed.

**Comment by svenhjol** [comment]
Hi, thanks the bug was spotted. I'm going to attach a link to the next version - if you could test that out and confirm it's fixed, that would be great.

**Comment by svenhjol** [comment]
https://github.com/svenhjol/Charm/releases/download/2.1.3/charm-forge-1.16.4-2.1.3.jar

**Comment by Nazguliki** [comment]
> https://github.com/svenhjol/Charm/releases/download/2.1.3/charm-forge-1.16.4-2.1.3.jar

Wow! It fixes the problem.
Removing enhancement is works on my server now :o
Thanks, it was super fast.
