### ISSUE TITLE
server crash

### ISSUE THREAD

**Issue by ItzEnderYT0** [svenhjol/Charm#39]
i don't know why every time i open my world. the game crashes
[crash-2019-05-05_05.07.00-server.txt](https://github.com/svenhjol/Charm/files/3145397/crash-2019-05-05_05.07.00-server.txt)

**Comment by svenhjol** [comment]
Related to #36  - please update your forge version to 2836, 2832-2835 have TE-related crashes that are impossible to track down.

**Comment by svenhjol** [comment]
Closing this.
