### ISSUE TITLE
Tinted Enchantment Book drops on every block that you break.

### ISSUE THREAD

**Issue by IAnon** [svenhjol/Charm#390]
**Required - Versions**
* Charm version - `2.1.3`
* Minecraft version - `1.16.4`
* Loader - `Forge`

**Required - Description**
Breaking any block in Minecraft causes an enchanted book of Tinted to drop every time.

**Optional: Stacktrace/Screenshots**
Mod List
![Mods](https://user-images.githubusercontent.com/44418423/100794568-9b80f280-33d2-11eb-9b5c-1ca6c51aac08.png)

**Comment by svenhjol** [comment]
Please try this hotfix and let me know if it fixes the issue. https://github.com/svenhjol/Charm/releases/download/2.1.3-forge-hotfix1/charm-forge-1.16.4-2.1.3-hotfix1.jar

**Comment by FesterHead** [comment]
Confirmed that charm-forge-1.16.4-2.1.3-hotfix1.jar resolves the issue.

**Comment by svenhjol** [comment]
That's been uploaded to Curseforge now. Thanks for your help with testing.
