### ISSUE TITLE
Opening and closing the recipe book when equipped with a Quark's backpack misplaces the buttons

### ISSUE THREAD

**Issue by Insane96** [svenhjol/Charm#391]
**Required - Versions**
* Charm version - `2.1.3-hotfix1`
* Minecraft version - `1.16.4`
* Loader - `Forge`

**Required - Description**
When equipped with a Quark's Backpack, opening and closing the recipe book misplaces the buttons.

**Optional: Stacktrace/Screenshots**
https://gyazo.com/197ac008408f6c0f6b079ce46c8711ce

**Comment by svenhjol** [comment]
I think this is fixed in the latest version, please let me know: https://github.com/svenhjol/Charm/releases/download/2.1.6/charm-forge-1.16.4-2.1.6.jar

**Comment by svenhjol** [comment]
Please reopen if still an issue
