### ISSUE TITLE
Can't open any world. Errors from datapacks

### ISSUE THREAD

**Issue by Insane96** [svenhjol/Charm#392]
**Required - Versions**
* Charm version - `2.1.3-hotfix3`
* Charmomium version - `2.1.3`
* Minecraft version - `1.16.4`
* Loader - `Forge`

**Required - Description**
Upon entering any world I'm not able to join it without safe mode. Logs show errors with Charm datapacks.
Removing Charm and Charmomium I can enter worlds again.

**Optional: Stacktrace/Screenshots**
https://gist.github.com/Insane96/23c73e1b21f17635875983348286b7d4

**Comment by SkullHunter55** [comment]
Ive got the same issue please fix this!

**Comment by svenhjol** [comment]
The problem seems to be Charmonium, which has been temporarily archived on curseforge. Please try with just Charm for the moment.

**Comment by svenhjol** [comment]
Ref: https://github.com/svenhjol/Charmonium/issues/8

**Comment by svenhjol** [comment]
Please try these versions to test the datapack error and let me know if it's resolved:
* https://github.com/svenhjol/Charm/releases/download/2.1.4/charm-forge-1.16.4-2.1.4.jar
* https://github.com/svenhjol/Charmonium/releases/download/2.1.4/charmonium-forge-1.16.4-2.1.4.jar

**Comment by Insane96** [comment]
Fixed in 2.1.4
