### ISSUE TITLE
Beekeeper houses in desert biomes

### ISSUE THREAD

**Issue by SlimF** [svenhjol/Charm#393]
The beekeeper houses look awesome and I love them, but I don't think they fit desert villages. It just seems weird to have grass in the desert 😀

**Comment by Coranthes** [comment]
Let me think on this and talk it out. I wanted to do it differently without grass but that doesn't work and we wanted all villagers to spawn in each biome type.  So I want to discuss with the others

**Comment by Coranthes** [comment]
I don't want to get rid of them altogether as it's nice having that continuity across all biomes, so what I decided to do instead is a bit of a remodel.  The bee area is more enclosed and hidden now in the desert houses so the grass won't stand out much at.  Feels like a good way to balance it.  They're not in the most recent release, but should be implemented in the next.

**Comment by SlimF** [comment]
Sounds good to me, can't wait to check them out!
