### ISSUE TITLE
Giving yourself anything Netherite related creates a client side item

### ISSUE THREAD

**Issue by Insane96** [svenhjol/Charm#395]
**Required - Versions**
* Charm version - `2.1.3-hotfix1`
* Minecraft version - `1.16.4`
* Loader - `Forge`

**Required - Description**
Giving yourself any Netherite Item creates a ghost item. 

**Optional: Steps To Reproduce**
`/give @p charm:netherite_nugget`

**Optional: Stacktrace/Screenshots**
![2020-12-02_15 46 39](https://user-images.githubusercontent.com/7185104/100887991-e45da780-34b5-11eb-892e-a611c7066daf.png)

**Comment by svenhjol** [comment]
Seems that Forge fires the "ItemExpireEvent" on `/give`. I have no idea why that is, but we'll try and find a workaround in due course

**Comment by Insane96** [comment]
Doesn't `event.getWorld().isRemote` work?

**Comment by svenhjol** [comment]
Please try https://github.com/svenhjol/Charm/releases/download/2.1.6/charm-forge-1.16.4-2.1.6.jar

**Comment by svenhjol** [comment]
Should be fixed in latest version. Please reopen if not
