### ISSUE TITLE
bookshelf-chest dupe contents with redstone++

### ISSUE THREAD

**Issue by WarlordWossman** [svenhjol/Charm#4]
Moving the bookshelf-chest with quarks moveable tile entities feature makes it dupe contents that get spit out as item entities.

![2019-04-10_09 00 11](https://user-images.githubusercontent.com/16925725/55858179-4fcf6480-5b6f-11e9-957d-33f1f04df914.png)

Would be nice if it would be moveable and didn't dupe items but otherwise could pull request it being blacklisted in the default config that ships with quark. (Normally I don't expect mod authors to check for that feature but since charm has a lot of quark cross mod compat anyways I wanted to mention it!)

**Comment by svenhjol** [comment]
Thanks so much for testing this out in its early stages, really appreciate the bug reports.

**Comment by WarlordWossman** [comment]
No problem, I only messed around for 30 minutes so far, so there is more to come!

I guess you mainly want your things to be tested for now right? Always got a lot of ideas for small changes that would fit mods like quark or charm, don't want to flood your GH with suggestions tho :D

**Comment by svenhjol** [comment]
Yep I'm keen to get everything in the current release tested, stable, and out the door. Suggestsions for future releases definitely welcome, I'll find something where we can get ideas listed that isn't GH.  Maybe trello?

**Comment by svenhjol** [comment]
Hey dude, having trouble repeating your issue.  This is with Quark r1.5-146, AutoRegLib 1.3-27.

Integrated server:
![CLIENT](https://user-images.githubusercontent.com/26497903/55964602-8935cc00-5c64-11e9-9d95-3e50aae28225.gif)

Local server:
![SERVER](https://user-images.githubusercontent.com/26497903/55964634-95218e00-5c64-11e9-9b49-fa82a5b05e38.gif)

**Comment by WarlordWossman** [comment]
Weird, I am trying to single out the issue at the moment.
I thought it might have been redstone++ but even without that mod it still happens, gonna test a few more predictions but otherwise I will try to reproduce in a clean instance.
One thing I noticed is that autoreglib 1.3-27. is not on CF, I am using 26

**Comment by WarlordWossman** [comment]
Update: On a clean instance it doesn't happen, it must be some mod interaction :(
This is gonna be really tough to find, all the mods that change piston mechanics didn't fix the issue so it could be anything as far as I know.

Would a log help?

**Comment by svenhjol** [comment]
Yeah log would be useful, if you can get me a list of all the mods I'll set them up locally and run the whole lot in debugger

**Comment by WarlordWossman** [comment]
Okay, this is my mod list:
https://hastebin.com/urapegowet.nginx

And here is a log:
[latest.log](https://github.com/svenhjol/Charm/files/3070151/latest.log)

**Comment by WarlordWossman** [comment]
Alright, did more testing and it seems to be a redstone++ issue. It only happens with the bookshelf-chest, the barrels and crates seem to be fine. I tried adding it to the redstone++ config that says "If you are having a problem with inventory blocks that lose their items when being pushed by pistons, add them to this list" but that made no difference.
It's kinda hard to tell (as a user anyways) since quark and redstone++ overlap when it comes to moveable TEs.

**Comment by WarlordWossman** [comment]
After further testing it just seems like the config can't do anything, not sure if it's because it's not 100% compatible with quark, I tried making it immoveable to prevent the dupe in both quark and redstone++ config but it doesn't work :/
