### ISSUE TITLE
Tinted ench. books EVERYWHERE

### ISSUE THREAD

**Issue by eudalia** [svenhjol/Charm#401]
First noticed something weird when the entire loot table for the stronghold's library ws replaced for a single book of the Tinted enchantment.
Then, when i made a full elementium armor + fairy ring from botania, almost everytime one of the pixies was killed (instead of landing a hit and disappearing), a Tinted book dropped. At the end of a gaia fight my inventory was a mess, with 3 or more stacks of 16 books.
The latest weird thing was with the refined obsidian from the mod, wich no matter what pickaxe i used, always dropped a Tinted enchantment book.

**Comment by svenhjol** [comment]
This was fixed in 2.1.4, please try that version

**Comment by svenhjol** [comment]
Should be fixed in latest version, please reopen if still an issue
