### ISSUE TITLE
Bug/Suggestion: Charm's Crates aren't working

### ISSUE THREAD

**Issue by Akitori** [svenhjol/Charm#402]
**Versions**
* Charm version 2.14
* Minecraft version 1.16.4
* Loader - Forge

**Description**
Trying to look/preview any barrel has the crate either: not show anything at all, or in the case of creative mode breaking the crate, have double inventories. Ie: two previews of the same crate.

**Steps To Reproduce**
1. Get crate
2. Put items in crate.
3. Break crate.
4. Look in inventory.

Creative mode.
Repeat steps 1-4

Also, can there be a list option, like shulkers? That tells the amount of the item inside the crate?

**Comment by svenhjol** [comment]
Could you provide screenshots or video for this? I don't know what you mean

**Comment by Akitori** [comment]
Video of oddness/bugs!

https://youtu.be/gDtJSJz44Vs

**Comment by Akitori** [comment]
soo this seems to be effecting more than just crates. Its only charm, cause I tested with solely charm.

![2020-12-09_15 46 59](https://user-images.githubusercontent.com/24502131/101693073-b983ce00-3a36-11eb-83c5-1bbb3952dddd.png)

**Comment by svenhjol** [comment]
Please try this version and let me know if the problems persist: https://github.com/svenhjol/Charm/releases/download/2.1.6/charm-forge-1.16.4-2.1.6.jar

**Comment by Akitori** [comment]
Update: it fixed the bugs.

I am curious why the beehives aren't working when placed tho. It says there are bees inside, i place beehive and break it. No bees pop out.

**Comment by svenhjol** [comment]
Glad it fixed the tooltip issue.
I'm not sure what you mean about the bees though. Charm doesn't make any changes to beehives.

**Comment by svenhjol** [comment]
I've just been informed it is probably about the Beehive Starter Pack that the beekeeper village sells. Is that right?

**Comment by Akitori** [comment]
Yes that is correct!

**Comment by svenhjol** [comment]
I'm going to open a new ticket for checking out the Beehive issue, and closing this as a crate issue.

**Comment by svenhjol** [comment]
https://github.com/svenhjol/Charm/issues/419
