### ISSUE TITLE
Suspicious Stew via Moobloom Bug (results in loss of bowls)

### ISSUE THREAD

**Issue by garyhopple** [svenhjol/Charm#403]
**Required - Versions**
* Charm version - 2.1.4
* Minecraft version - 1.16.4
* Loader - `Fabric`

**Required - Description**
When you right click a moobloom with multiple bowls, you'll lose the amount of: x-(x-1).

e.g. If you have a stack of 16 bowls, and you right click a moobloom, the stack will disappear, giving you one (1) suspicious stew. Making you lose 15 bowls.

**Optional: Steps To Reproduce**
With _multiple bowls_, right click a moobloom. That's literally it.

**Comment by svenhjol** [comment]
Thanks, will be fixed in 2.1.6

**Comment by svenhjol** [comment]
Should be fixed in 2.1.6: https://github.com/svenhjol/Charm/releases/download/2.1.6/charm-fabric-1.16.4-2.1.6.jar, also now on curseforge. Please reopen if still occurring
