### ISSUE TITLE
Other Music Discs not in 1.16? 

### ISSUE THREAD

**Issue by Revelins** [svenhjol/Charm#404]
I noticed on 1.15.2, charm has a ton of additional music discs, while on 1.16.4, there doesn't seem to be any. Was this intentionally removed? I couldn't find much information on it anywhere, but I noticed on the 1.16.4 wiki it doesn't show the extra music discs as a tweak while it does on the 1.15.2 wiki.

**Comment by svenhjol** [comment]
Hi, they were removed because the volume of the music didn't decrease as you moved away from the jukebox. There are technical reasons as to why that is, but not something that was fixable within a reasonable amount of time, so the feature was dropped.
