### ISSUE TITLE
Soulspeed can't be moved from Boots to Book on 2.0.3 version of mod (Needs testing on newest version of mod)

### ISSUE THREAD

**Issue by SpiderKolo** [svenhjol/Charm#405]
Charm version - 2.0.3 (I checked newer versions change logs and it doesn't appear to be fixed, however moving the operation from Anvil to Grinder might have fixed it already - needs testing)
Minecraft version - 1.16.4
Loader - Fabric

Description:
When I put an iron boots with Soulspeed III in left slot and an empty book in the middle slot in anvil, there would not be an outcome with Book having Soul Speed. In fact, when I added Protection IV on top of the boots and tried to move the enchantment, only Protection IV appeared on book and no Soul Speed.

Steps To Reproduce:
This should be simple to reproduce... Put Soul Speed Boots in left slot and empty book in the center. You will not get an outcome on left side.

Might have been fixed with update which moved block you move enchantments to book from anvil to grindstone, but in case it wasn't it would be good idea to check if the bug persist when you try the same thing in Grindstone.
Can't sadly test it myself at the moment. When I get some time I will surely test it out.

**Comment by svenhjol** [comment]
This has been fixed in latest version. You're right, it's been moved to grindstone. Let me know how it works for you!

**Comment by svenhjol** [comment]
Closing this as it's working in latest version. Please reopen if still an issue
