### ISSUE TITLE
This was printed by Blame (Fabric) mod

### ISSUE THREAD

**Issue by RDKRACZ** [svenhjol/Charm#409]
****************** Blame Report 2.2.4 ******************

 Empty template pool found from : minecraft:village/plains/villager
 The path represented by this is:  data/minecraft/worldgen/template_pool/village/plains/villager
 The structure piece with a Jigsaw Block that is targeting an empty pool is: charm:village/plains/houses/plains_beejack_1
 Most common cause is that there is a typo in this path to the template pool which then points to a non-existent pool.
 Please let the mod author know about this so they can double check the path to make sure it is correct.

**Comment by Coranthes** [comment]
Thank you.  I'll take a look at it and see happened.

**Comment by RDKRACZ** [comment]
This could be something on my side now as I think about it. I will try to make sure later.

**Comment by RDKRACZ** [comment]
Another one

[00:56:10] [Worker-Main-30/ERROR]: 
****************** Blame Report 2.2.4 ******************

 Empty template pool found from : minecraft:village/desert/street
 The path represented by this is:  data/minecraft/worldgen/template_pool/village/desert/street
 The structure piece with a Jigsaw Block that is targeting an empty pool is: charm:village/desert/houses/desert_lumberjack_1
 Most common cause is that there is a typo in this path to the template pool which then points to a non-existent pool.
 Please let the mod author know about this so they can double check the path to make sure it is correct.

**Comment by Coranthes** [comment]
These will be fixed on the next release!

**Comment by svenhjol** [comment]
Assigning you Coranthes

**Comment by svenhjol** [comment]
Committed to 2.1.8

**Comment by ridjack** [comment]
Per the prior comment, this issue was resolved.
