### ISSUE TITLE
[1.1.0 beta1]effective tool for pistons doesn't work

### ISSUE THREAD

**Issue by WarlordWossman** [svenhjol/Charm#41]
Couldn't really notice any difference mining pistons with a pickaxe, I have not checked their hardness yet but a diamond pickaxe with eff5 seems to be the same speed as mining them by hand which is odd. Even haste 2 doesn't make a difference relative to handmining them with haste 2.

Tested for both sticky pistons and pistons.

**Comment by svenhjol** [comment]
Could there be another mod that influences this behavior? It seems to be working for me.

**Comment by WarlordWossman** [comment]
It's a redstone++ modcompat issue.
