### ISSUE TITLE
[Suggestion] More variant blocks

### ISSUE THREAD

**Issue by RDKRACZ** [svenhjol/Charm#411]
We have variant bookshelves, chests, barrels. The only thing left is variant crafting tables.

**Comment by svenhjol** [comment]
We aren't planning on adding variant crafting tables, but I think the mod `i-like-wood` does add them if you need them. Thanks for the suggestion though.

**Comment by RDKRACZ** [comment]
Uhh yes but I use fabric and looks like "I like wood" is for forge. Can I ask for a reason why You aren't planning on adding variant crafting tables? For me it just looks like an inconsistency but maybe I don't know about something.

**Comment by svenhjol** [comment]
Oops, I thought it was for both, my bad. We are discussing variant crafting tables today and I'll update the ticket

**Comment by RDKRACZ** [comment]
Hi, so what about this? I'm just curious.

**Comment by RDKRACZ** [comment]
Also what about variant torches, ladders? Like in "i like wood" mod.

**Comment by Coranthes** [comment]
Likely not going to be adding the crafting tables after all.  To do the graphics for something like you're talking about, not to mention all the code, is an immense amount of work. Keep in mind, integration is being added for both fabric and forge, which means two entirely separate mod sets.  Looking at just the barrels and crates, each wood has at least 8 textures.  On top of that, on average, each wood type has 20+ additional files associated with it.   Just "Biomes O' Plenty" and "Biomes You'll Go" have a total of 40 wood types.  That alone is over 1100 files.  And those aren't the only mods that Covalent will have compat for.    Those all have to be maintained with each update of Charm and Minecraft.  Add to that crafting tables (which have 3 textures each), tools, sticks, torches, ladders (which Charm already ladders for vanilla wood), could double that.  Then the question is, where do you stop?  As far as I can tell, "I Like Wood" only does vanilla and "Biomes O Plenty" wood.  
Additionally, there are 3 other mods in the Charm family.  Charm and Strange alone could be full time jobs.  There's so much that goes into these mods.  Covalent is small in comparison.    That being said, it's very unlikely these features will be added.  
Hope this gives you a glimpse of the amount of work that's already being put into Covalent, and why it's not realistic to take on something like you're talking about.

**Comment by RDKRACZ** [comment]
I understand. About textures, "I like wood" is MIT licensed so I think you could use them. There is a Fabric mod which adds crafting table variants and it's MIT licensed too. Maybe You could like talk with P3NG00 and idk include his mod into Yours? Here is a link.

Off topic question: will Strange ever be updated to 1.16 and ported to Fabric?

**Comment by Coranthes** [comment]
Strange has been updated, currently we're doing a lot of playtesting on the latest version.  At least for the foreseeable future, it will only be updated/maintained for fabric, actually.
