### ISSUE TITLE
Coral squids crash server

### ISSUE THREAD

**Issue by dridrop** [svenhjol/Charm#412]
Minecraft version 1.16.3
Mod version forge-1.16.4-2.1.1-hotfix3

When I run my 1.16.3 modded server with this, the coral squid crashes the server. Doesn't happen in singleplayer, It only crashes the server. My server logs also only mention the coral squid, mentioning "Entity's Vehicle: ~~ERROR~~ NullPointerException: null" at the end.

**Comment by svenhjol** [comment]
This version is very old, please update to 2.1.6 and reopen if still occurring
