### ISSUE TITLE
Hovering over a shield in inventory crashes the client

### ISSUE THREAD

**Issue by FesterHead** [svenhjol/Charm#413]
**Read me first!**
1. We don't support Optifine or Optifabric. Please check that the problem still occurs if you remove Optifine/Optifabric from your mods.
2. Don't use the bug report to suggest new features or behavior.

**Required - Versions**
* Charm version - e.g. `1.16.4-2.1.6`
* Minecraft version - e.g. `1.16.4`
* Loader - `Forge 35.1.13`

**Required - Description**
Hovering over a shield in inventory crashes the client.  Observed in a single player world.  Not tried on a server.

**Optional: Steps To Reproduce**
* Obtain a shield
* Open inventory
* Mouse over shield
* Game crashes

**Optional: Stacktrace/Screenshots**
Crash log attached.
[crash-2020-12-12_15.07.28-client.txt](https://github.com/svenhjol/Charm/files/5684023/crash-2020-12-12_15.07.28-client.txt)

Disabling the charm mod allowed me to move the shield out of my inventory to prevent additional crashes.
![2020-12-12_15 15 03](https://user-images.githubusercontent.com/1421244/102000602-2395b080-3c8d-11eb-87cd-550d9fb8f5ac.png)

**Comment by svenhjol** [comment]
Please try this version: https://github.com/svenhjol/Charm/releases/download/2.1.7/charm-forge-1.16.4-2.1.7.jar

**Comment by FesterHead** [comment]
Affirmative.  Mahalo.
