### ISSUE TITLE
Config not working.

### ISSUE THREAD

**Issue by Inpaladin** [svenhjol/Charm#414]
**Required - Versions**
* Charm version - 2.1.6
* Minecraft version - 1.6.4
* Loader - Forge

**Required - Description**
First noticed the issue when I tried reenabling potion glint and it didn't work.  Just to make sure it wasn't just that, I also tried disabling the tinted enchant and refined obsidian.  The obsidian recipe remained upon relaunching and the tinted enchant stayed visible in JEI.  I have not tested this with anything else, so it's possible the config isn't entirely broken, but these three features seem pretty disconnected from each other so I'd be surprised if anything else works.

**Comment by svenhjol** [comment]
Ok, tested in latest forge. I can't repeat the problem with the potion glint - disabling the feature makes the potion glint return.

What might be confusing is that all items and blocks get registered even though they're disabled in config. The config instructs the recipes not to load. So even though walls appear, there will be no crafting recipe for them.

The tinted enchantment is the same. It gets registered so it will appear in JEI but there's no way to actually get it in game (i.e. the loot tables don't load because the config instructs them not to).

You might also want to test this in the latest forge version (time of writing not committed to curseforge but getting feedback from players here): https://github.com/svenhjol/Charm/releases/download/2.1.7/charm-forge-1.16.4-2.1.7.jar

Let me know if you're still having trouble

**Comment by Inpaladin** [comment]
I did switch to that version of charm and it didn't fix it, It's worth noting that I am running quark with the mod as well.  Good to know the thing with the tinted enchant, I saw that the candle and wax items were hidden in JEI by default since I had quark installed so assumed that it'd do the same for the enchant.  That being said, I can 100% verify all of the things I mentioned are in fact broken as I was able to smelt obsidian with that disabled and found a book with tinted in a vanilla dungeon chest while exploring in creative.  I'll do some more testing tonight to try and see if I can find the root of the problem/see if other things are for sure broken and comment them here.

**Comment by svenhjol** [comment]
Are you editing the `charm-common.toml` file? Older versions of charm came with `charm.json` so I just want to make sure it's not the case

**Comment by Inpaladin** [comment]
I am editing the toml file.

**Comment by Inpaladin** [comment]
so here's an easy example of it not working, here's a screenshot I just took after launching the game with the config provided below, in the config I have variant squids disabled, but they are still spawning as such.  I'm going to first try launching with no mods enabled aside from charm to see if it's some wacko issue with my minecraft client, then start enabling mods one by one.
![image](https://user-images.githubusercontent.com/59532097/102152990-10b8e280-3e2b-11eb-95fb-41a6bea9e726.png)
https://pastebin.com/3iX2HeXp

**Comment by svenhjol** [comment]
I think I've found a way to recreate it. Seems to be happening on the server. I was just testing client singleplayer in the IDE.

**Comment by Inpaladin** [comment]
I've been testing all of this in singleplayer, but the solution to that could be the solution to this.

**Comment by Inpaladin** [comment]
still going to continue checking if it's a mod incompatibility issue.

**Comment by Inpaladin** [comment]
Alright so launched the game with just charm and with charm and optifine and on both the config appears to be working properly for the potion glint and beaconshealmobs, but squids are still spawning with multiple colors.

**Comment by Teacyn** [comment]
Can confirm this also happening for me. I have the Mineshaft changes disabled (as I use Repurposed Structures and prefer the biome mineshafts from that), and they still are active on freshly generated worlds.

**Comment by svenhjol** [comment]
Please test https://github.com/svenhjol/Charm/releases/download/2.1.8/charm-forge-1.16.4-2.1.8.jar

**Comment by Teacyn** [comment]
> 
> 
> Please test https://github.com/svenhjol/Charm/releases/download/2.1.8/charm-forge-1.16.4-2.1.8.jar

This does not seem to have worked, sadly.

![image](https://user-images.githubusercontent.com/12898157/102287686-f35a4600-3f08-11eb-8f31-c69c61955be8.png)
![image](https://user-images.githubusercontent.com/12898157/102287750-1127ab00-3f09-11eb-8620-f377c016484b.png)
![image](https://user-images.githubusercontent.com/12898157/102287763-171d8c00-3f09-11eb-876a-c1d7756148b1.png)
![image](https://user-images.githubusercontent.com/12898157/102287779-23094e00-3f09-11eb-9bd3-175609fa8508.png)

Possibly a mod conflict? wouldn't have any idea what though.

**Comment by Inpaladin** [comment]
discussed through dm, turned out it was an issue with charmonium.  It'll be fixed in the latest release of both mods
