### ISSUE TITLE
Crash when hovering over Apotheosis spawner

### ISSUE THREAD

**Issue by edmaas** [svenhjol/Charm#415]
**Read me first!**
1. We don't support Optifine or Optifabric. Please check that the problem still occurs if you remove Optifine/Optifabric from your mods.
2. Don't use the bug report to suggest new features or behavior.

**Required - Versions**
* Charm version -  `2.1.6`
* Minecraft version - e.g. `1.6.4`
* Loader - `Forge 35.1.0`

**Required - Description**
The game crashes when trying to display the tooltip of a monster spawner by the Apotheosis mod.
Bug only happens in charm 2.1.6, downgrading to 2.1.4 fixes the problem.
Possibly related to #413 

**Optional: Steps To Reproduce**
(Steps are given for creative, but it works with any found spawner in the world)
1) Create new creative world
2) Give yourself a spawner (this spawner won't crash the game, as it doesn't have extra data)
3) Place it in the world
4) Copy it with middle click
5) Open inventory and hover over the spawner with your mouse
6) Crash the game

**Optional: Stacktrace/Screenshots**
[crash-2020-12-13_20.24.03-client.txt](https://github.com/svenhjol/Charm/files/5685295/crash-2020-12-13_20.24.03-client.txt)
![2020-12-13_20 26 36](https://user-images.githubusercontent.com/21290404/102021797-c9771700-3d82-11eb-97f1-a92a398b1135.png)
The screenshot was taken with charm 2.1.4, doing the same in 2.1.6 crashes the game.

**Comment by svenhjol** [comment]
Hi please try this version: https://github.com/svenhjol/Charm/releases/download/2.1.7/charm-forge-1.16.4-2.1.7.jar

**Comment by edmaas** [comment]
That fixed it, thanks!
