### ISSUE TITLE
Is there a way to disable the new variant textures for mobs?

### ISSUE THREAD

**Issue by GhostpunchTV** [svenhjol/Charm#416]
Is there a way to disable the new variant textures for mobs? It doesn't look good with my texture pack. Also, texture packs can add mob variants on their own, so maybe create a separate texture pack rather than putting them inside the mod.

**Comment by svenhjol** [comment]
You can disable the variant textures by changing "Variant mob textures" to false in the charm.toml config file. This should stop any custom textures from being rendered. There are currently no plans to release a separate texture pack, but it is very easy to override the custom textures that Charm provides.

**Comment by svenhjol** [comment]
Please reopen if you need any more help with this or if the config is not working as expected
