### ISSUE TITLE
CTD when hover the cursor on the shield

### ISSUE THREAD

**Issue by Nazguliki** [svenhjol/Charm#417]
**Versions**
* Charm version - `2.1.6`
* Minecraft version - `1.16.4`
* Loader - `Forge`

**Description**
I play on my own server.
When i hover cursor on the colored shield with pattern, game (not the server) crushes. I got the shields long time ago on the dungeon from the **DungeonCrawl** mod.
Newly created shields fork fine, cant reproduce it with any other shields. I solved it out for myself by dumping shields into chest and destroying it with fire *_* I may do test with the shields on my backup save, if required.

**Stacktrace/Screenshots**
[debug.log](https://github.com/svenhjol/Charm/files/5690511/debug.log)
[latest.log](https://github.com/svenhjol/Charm/files/5690518/latest.log)
[crash-2020-12-14_19.29.18-client.txt](https://github.com/svenhjol/Charm/files/5690519/crash-2020-12-14_19.29.18-client.txt)
<a href="https://ibb.co/DLDK28n"><img src="https://i.ibb.co/9G9Y5Vj/20201214-185524.jpg" alt="20201214-185524" border="0"></a>

**Comment by Nazguliki** [comment]
If nobody interested to investigate it, i guess this report may be closed.

**Comment by svenhjol** [comment]
This was fixed in 2.1.7.  https://github.com/svenhjol/Charm/releases/download/2.1.7/charm-forge-1.16.4-2.1.7.jar

It hasn't been released to curseforge yet.

**Comment by Nazguliki** [comment]
Oh, grate ^_^
