### ISSUE TITLE
Portable Crafting Button keeps showing even if I turn off that feature [Fabric]

### ISSUE THREAD

**Issue by xXMolgadoGamer01Xx** [svenhjol/Charm#420]
Hi, I'm having a problem with Charm 2.1.6 for fabric.
I don't want the Portable Crafting or the Portable Enderchest features, so I disabled them in the config file, but, when I open my world the buttons are there. 
Is this a bug or it's supposed to be like that?
Here are some screenshots of the problem:
![2020-12-15_02 08 24](https://user-images.githubusercontent.com/24871116/102188420-e131c680-3e7a-11eb-8f02-cf84227587c5.png)
![image](https://user-images.githubusercontent.com/24871116/102188468-ee4eb580-3e7a-11eb-8fb0-69ae03707c39.png)

**Comment by svenhjol** [comment]
Well spotted. The button renderer is ignoring the config. I'll fix it up for next version :+1:

**Comment by svenhjol** [comment]
Please could you test this build and let me know if the problems is resolved: https://github.com/svenhjol/Charm/releases/download/2.1.8/charm-fabric-1.16.4-2.1.8.jar

**Comment by xXMolgadoGamer01Xx** [comment]
Yes, it works :D
Thank you
