### ISSUE TITLE
[Suggestion] Make cobwebs burn.

### ISSUE THREAD

**Issue by RDKRACZ** [svenhjol/Charm#421]
The only way to quickly get rid of cobwebs is by the sword. It a spider's web...why it can't burn?

**Comment by ridjack** [comment]
I've put this up for discussion on our internal channels. Closing the issue to reduce cluter, but we will be discussing it.

I'd say this is pretty unlikely, as it's a bit too large of a departure from vanilla mechanics and expectations.

By the way, you can also use a water bucket!
