### ISSUE TITLE
Crash Game

### ISSUE THREAD

**Issue by harmalom** [svenhjol/Charm#423]
* Charm version - 2.1.6
* Minecraft version -  1.16.4
* Loader - Forge 1.16.4-35.1.13

the game crashes when opening a chest or shulker with random objects, which apparently can't be rendered properly, related with charm

https://pastebin.com/DcLSyFrc

**Comment by FynnWaelsing** [comment]
Please test this again without Optifine. Optifine is known to cause many crashes related to rendering.

**Comment by harmalom** [comment]
I tried it without Optifine, and the crash still happens
https://pastebin.com/7U1HVhrF

**Comment by F43nd1r** [comment]
This is fixed in the latest version. You can get it here https://github.com/svenhjol/Charm/releases

**Comment by harmalom** [comment]
thanks
