### ISSUE TITLE
[Two suggestions] Creepers burn in daylight. Zombies don't.

### ISSUE THREAD

**Issue by RDKRACZ** [svenhjol/Charm#426]
Photoallergic creepers - something for those who want the days to be completely safe.
Why do zombies burn in daylight? I don't know too. This is the only game where zombies won't like sun. Why aren't they called vampires then?

**Comment by ridjack** [comment]
Charm is meant to enhance the vanilla experience, not make fundamental changes to it. This is outside the scope of either Charm or Strange.
