### ISSUE TITLE
[Suggestion] Add recipe for Elytra.

### ISSUE THREAD

**Issue by RDKRACZ** [svenhjol/Charm#428]
For those who will never go to the End dimension. I have a feeling nobody will like this Suggestion though...

 ![20201219_000301.jpg](https://user-images.githubusercontent.com/43277609/102669085-ef8b2580-418d-11eb-9ab8-1e4bf69f2adf.jpg)

I think netherite ingot instead of diamond would be better.

Bonus: what do You think about Trident recipe?

![20201219_000818.jpg](https://user-images.githubusercontent.com/43277609/102669233-5dcfe800-418e-11eb-81f7-af224ebb152d.jpg)

**Comment by Teacyn** [comment]
I'd probably do a netherite ingot instead of a diamond yeah. And for the trident, possibly a Heart of the Sea instead of a diamond? unsure.

**Comment by ridjack** [comment]
I've put these up for discussion and voting on our internal channels. Closing the issue to reduce clutter, but we will be discussing it.

I'd say the craftable Elytra is probably unlikely to happen. Craftable trident is possible, but no promises.
