### ISSUE TITLE
[Mod conflict - ATBYW] Crash on startup - mixin interference.

### ISSUE THREAD

**Issue by RDKRACZ** [svenhjol/Charm#429]
Charm conflict with All The Blocks You Want. https://github.com/Azagwen/ATBYW/issues/2

` [main/WARN]: @reDIrect conflict. Skipping charm.mixins.json:EnchantingTableBlockMixin->@reDIrect::hookRandomDisplayTick(Lnet/minecraft/class_2680;Lnet/minecraft/class_2248;)Z with priority 1000, already redirected by atbyw.mixins.json:EnchantingTableBlockMixin->@reDIrect::redirectIsOf(Lnet/minecraft/class_2680;Lnet/minecraft/class_2248;)Z with priority 1000`

**Comment by Azagwen** [comment]
#430

**Comment by Azagwen** [comment]
In relation with #430 and Azagwen/ATBYW#2
