### ISSUE TITLE
[Suggestion] Use Block tags for Blocks used as Bookshelves.

### ISSUE THREAD

**Issue by Azagwen** [svenhjol/Charm#430]
https://github.com/svenhjol/Charm/blob/86a7ad06e071630111f28243d902af9bfc657cdf/src/main/java/svenhjol/charm/base/helper/EnchantmentsHelper.java#L14

I noticed you used a Hard-coded list for Blocks that provide enchantment Power, which makes it harder to fix interference with Other mods that might wanna add Bookshelves.

so I'd suggest using Block tags instead

**Comment by ridjack** [comment]
I believe the issue this is referencing was already fixed. I'm gonna go ahead and close this; if your suggestion is still relevant, please respond here and we can take another look at it.
