### ISSUE TITLE
[Suggestion] Wood variants of sticks and tools.

### ISSUE THREAD

**Issue by RDKRACZ** [svenhjol/Charm#433]
Charm adds barrels, bookshelves etc. variants in vanilla wood but what about sticks and tools? There is no fabric mods for this, only for forge.
https://i.imgur.com/TRBKxBr.gif

**Comment by ridjack** [comment]
Categorically not going to happen. Too much work for too little benefit, and, quite frankly, I don't think anyone on the Charm team likes the idea.
