### ISSUE TITLE
zh_tw file

### ISSUE THREAD

**Issue by Pancakes0228** [svenhjol/Charm#434]
{
  "block.charm.acacia_barrel": "相思木木桶",
  "block.charm.acacia_bookcase": "相思木書架",
  "block.charm.acacia_bookshelf": "相思木書櫃",
  "block.charm.acacia_chest": "相思木儲物箱",
  "block.charm.acacia_crate": "相思木板條箱",
  "block.charm.acacia_ladder": "相思木梯子",
  "block.charm.acacia_trapped_chest": "相思木陷阱儲物箱",
  "block.charm.birch_barrel": "樺木木桶",
  "block.charm.birch_bookcase": "樺木書架",
  "block.charm.birch_bookshelf": "樺木書櫃",
  "block.charm.birch_chest": "樺木儲物箱",
  "block.charm.birch_crate": "樺木板條箱",
  "block.charm.birch_ladder": "樺木梯子",
  "block.charm.birch_trapped_chest": "樺木陷阱儲物箱",
  "block.charm.brain_prismarine": "腦海磷石",
  "block.charm.brain_prismarine_bricks": "腦海磷石磚"
  "block.charm.brain_sea_lantern": "腦海燈籠",
  "block.charm.brew_bottle": "Brew Bottle?!",
  "block.charm.bubble_prismarine": "氣泡海磷石",
  "block.charm.bubble_prismarine_bricks": "氣泡海磷石磚",
  "block.charm.bubble_sea_lantern": "氣泡海燈籠",
  "block.charm.candle": "蠟燭",
  "block.charm.crimson_barrel": "緋紅蕈木木桶",
  "block.charm.crimson_bookcase": "緋紅蕈木書架",
  "block.charm.crimson_bookshelf": "緋紅蕈木書櫃",
  "block.charm.crimson_chest": "緋紅蕈木儲物箱",
  "block.charm.crimson_crate": "緋紅蕈木板條箱",
  "block.charm.crimson_ladder": "緋紅蕈木梯子",
  "block.charm.crimson_trapped_chest": "緋紅蕈木陷阱儲物箱",
  "block.charm.dark_brain_prismarine": "暗腦海磷石",
  "block.charm.dark_bubble_prismarine": "暗氣泡海磷石",
  "block.charm.dark_fire_prismarine": "暗火海磷石",
  "block.charm.dark_horn_prismarine": "暗角海磷石",
  "block.charm.dark_oak_barrel": "黑橡木木桶",
  "block.charm.dark_oak_bookcase": "黑橡木書架",
  "block.charm.dark_oak_bookshelf": "黑橡木書櫃",
  "block.charm.dark_oak_chest": "黑橡木儲物箱",
  "block.charm.dark_oak_crate": "黑橡木板條箱",
  "block.charm.dark_oak_ladder": "黑橡木梯子",
  "block.charm.dark_oak_trapped_chest": "黑橡木陷阱儲物箱",
  "block.charm.dark_tube_prismarine": "暗管海磷石",
  "block.charm.ender_pearl_block": "終界珍珠方塊",
  "block.charm.fire_prismarine": "火海磷石",
  "block.charm.fire_prismarine_bricks": "火海磷石磚",
  "block.charm.fire_sea_lantern": "火海燈籠",
  "block.charm.fisherman_barrel": "漁夫木桶",
  "block.charm.glowball_blob": "螢光球",
  "block.charm.gold_bars": "金柵欄,
  "block.charm.gold_chain": "金鎖鍊",
  "block.charm.gold_lantern": "金燈籠",
  "block.charm.gold_soul_lantern": "金靈魂燈籠",
  "block.charm.gunpowder_block": "火藥方塊",
  "block.charm.horn_prismarine": "角海磷石",
  "block.charm.horn_prismarine_bricks": "角海磷石磚",
  "block.charm.horn_sea_lantern": "角海燈籠",
  "block.charm.jungle_barrel": "叢林木木桶",
  "block.charm.jungle_bookcase": "叢林木書架",
  "block.charm.jungle_bookshelf": "叢林木書櫃",
  "block.charm.jungle_chest": "叢林木儲物箱",
  "block.charm.jungle_crate": "叢林木板條箱",
  "block.charm.jungle_ladder": "叢林木梯子",
  "block.charm.jungle_trapped_chest": "叢林木陷阱儲物箱",
  "block.charm.kiln": "窯爐",
  "block.charm.oak_barrel": "橡木木桶",
  "block.charm.oak_bookcase": "橡木書架",
  "block.charm.oak_bookshelf": "橡木書櫃",
  "block.charm.oak_chest": "橡木儲物箱",
  "block.charm.oak_crate": "橡木板條箱",
  "block.charm.oak_ladder": "橡木梯子",
  "block.charm.oak_trapped_chest": "橡木陷阱儲物箱",
  "block.charm.redstone_lantern": "紅石燈籠",
  "block.charm.redstone_sand": "紅石沙",
  "block.charm.refined_obsidian": "精緻黑曜石",
  "block.charm.refined_obsidian_slab": "精緻黑曜石半磚",
  "block.charm.refined_obsidian_stairs": "精緻黑曜石階梯",
  "block.charm.refined_obsidian_wall": "精緻黑曜石牆",
  "block.charm.smooth_glowstone": "平滑螢光石",
  "block.charm.spruce_barrel": "杉木木桶",
  "block.charm.spruce_bookcase": "杉木書架",
  "block.charm.spruce_bookshelf": "杉木書櫃",
  "block.charm.spruce_chest": "杉木儲物箱",
  "block.charm.spruce_crate": "杉木板條箱",
  "block.charm.spruce_ladder": "杉木梯子",
  "block.charm.spruce_trapped_chest": "杉木陷阱儲物箱",
  "block.charm.sugar_block": "糖方塊",
  "block.charm.tube_prismarine": "管海磷石",
  "block.charm.tube_prismarine_bricks": "管海磷石磚",
  "block.charm.tube_sea_lantern": "管海燈籠",
  "block.charm.warped_barrel": "扭曲蕈木木桶",
  "block.charm.warped_bookcase": "扭曲蕈木書架",
  "block.charm.warped_bookshelf": "扭曲蕈木書櫃",
  "block.charm.warped_chest": "扭曲蕈木儲物箱",
  "block.charm.warped_crate": "扭曲板條箱",
  "block.charm.warped_ladder": "扭曲蕈木梯子",
  "block.charm.warped_trapped_chest": "扭曲蕈木陷阱儲物箱",
  "block.charm.woodcutter": "鋸木機",
  "container.charm.crate": "板條箱",
  "container.charm.kiln": "窯爐",
  "container.charm.portable_crafting_table": "行動工作台",
  "container.charm.portable_ender_chest": "行動終界箱",
  "container.charm.woodcutter": "鋸木機",
  "enchantment.charm.acquisition": "收穫",
  "enchantment.charm.tinted": "著色",
  "entity.charm.coral_squid": "珊瑚魷魚",
  "entity.minecraft.villager.charm.beekeeper": "養蜂人",
  "entity.minecraft.villager.charm.lumberjack": "伐木工",
  "filled_map.charm.trader_map": "%s Map",
  "gui.charm.recipebook.toggleRecipes.fireable": "顯示可燃性",
  "item.charm.atlas": "輿圖",
  "item.charm.bat_bucket": "蝙蝠桶",
  "item.charm.beeswax": "蜂蠟",
  "item.charm.coral_squid_spawn_egg": "珊瑚魷魚生怪蛋",
  "item.charm.endermite_powder": "終界蟎粉",
  "item.charm.fisherman_barrel": "漁夫木桶",
  "item.charm.glowball": "螢光球",
  "item.charm.netherite_nugget": "獄髓粒",
  "item.charm.populated_beehive": "蜂蜜新手包",
  "item.charm.raid_horn": "突襲號角",
  "item.charm.suspicious_brew": "可疑的燉湯",
  "key.charm.openCraftingTable": "打開行動工作台",
  "key.charm.openEnderChest": "打開行動終界箱",
  "structure.charm.desert_pyramid": "沙漠神殿",
  "structure.charm.igloo": "雪屋",
  "structure.charm.jungle_pyramid": "叢林神廟",
  "structure.charm.mineshaft": "廢棄礦坑",
  "structure.charm.ocean_ruin": "海底神殿",
  "structure.charm.pillager_outpost": "掠奪者前哨站",
  "structure.charm.ruined_portal": "廢棄的地獄門",
  "structure.charm.shipwreck": "沈船",
  "structure.charm.swamp_hut": "沼澤小屋",
  "structure.charm.village": "村莊"
}

**Comment by svenhjol** [comment]
Thank you for the contribution.
