### ISSUE TITLE
Charm Crash on common_setup phase related to quark BigDungeonStructure

### ISSUE THREAD

**Issue by Ragotha** [svenhjol/Charm#436]
Charm version - 2.1.6
Minecraft version - 1.6.4
Loader - Forge

Description
Crash on Startup

Optional: Stacktrace/Screenshots
https://pastebin.com/yPjGydzc

**Comment by F43nd1r** [comment]
Duplicate of #424

**Comment by Ragotha** [comment]
my bad, didn't spot that.
