### ISSUE TITLE
Idea for a feature.

### ISSUE THREAD

**Issue by RDKRACZ** [svenhjol/Charm#437]
Puddles, [like in this outdated forge mod](https://www.curseforge.com/minecraft/mc-mods/puddles). They would appear on solid blocks when it rains. You would be able to fill a glass bottle (this would play nicely with the Dehydration mod) from them and then a puddle would disappear. After rain and a few seconds/minutes they would vanish.

![image](https://user-images.githubusercontent.com/43277609/102789229-20dd3e80-43a4-11eb-9260-27e2404740c0.png)

**Comment by ridjack** [comment]
This suggestion has been considered and rejected.
