### ISSUE TITLE
creative tab distribution

### ISSUE THREAD

**Issue by WarlordWossman** [svenhjol/Charm#44]
This is a minor / quality of life "issue" and at the same time a suggestion. The idea is to line up creative tabs with how vanilla handles them so it's less confusing to find items without JEI. Including items from 1.1 beta2 as well, this would be my suggestion (some of the entries already have the right creative tab, if you want me to I can edit them out - let me know if that would help):

building blocks:
- charm:ender_pearl_block
- charm:gunpowder_block
- charm:rotten_flesh_block
- charm:nether_gold_deposit

decoration blocks:
- charm:barrel
- charm:bookshelf_chest
- charm:composter
- charm:iron_lantern
- charm:gold_lantern
- charm:crate
- charm:crate_sealed

redstone:
- charm:redstone_sand

transportation:
- charm:totem_of_returning

miscellaneous:
- minecraft:spawn_egg (the spectre one)
- charm:record_calm1
- charm:record_calm2
- charm:record_calm3
- charm:record_hal1
- charm:record_hal2
- charm:record_hal3
- charm:record_hal4
- charm:record_nuance1
- charm:record_nuance2
- charm:record_piano1
- charm:record_piano2
- charm:record_piano3
- charm:record_creative1
- charm:record_creative2
- charm:record_creative3
- charm:record_creative4
- charm:record_creative5
- charm:record_creative6
- charm:record_nether1
- charm:record_nether2
- charm:record_nether3
- charm:record_nether4
- charm:record_menu1
- charm:record_menu2
- charm:record_menu3
- charm:record_menu4
- charm:bat_bucket
- charm:charged_emerald
- charm:bound_compass

foodstuffs:
- charm:suspicious_soup

tools:
- minecraft:enchanted_book (curse break, curse of rusting, curse of clumsiness, curse of harming, homing, salvage)

combat:
- minecraft:tipped_arrow (coffee, decay, ender_sight)
- charm:totem_of_shielding
- minecraft:enchanted_book (curse break, curse of rusting, curse of clumsiness, curse of haunting, curse of harming, salvage)

brewing:
- minecraft:potion (coffee, decay, ender_sight)
- minecraft:splash_potion (coffee, decay, ender_sight)
- minecraft:lingering_potion (coffee, decay, ender_sight)
- charm:cake_speed
- charm:cake_strength
- charm:cake_jump_boost
- charm:cake_regeneration
- charm:cake_fire_resistance
- charm:cake_water_breathing
- charm:cake_invisibility
- charm:cake_night_vision

**Comment by svenhjol** [comment]
Cheers dude, I'll get on it :)

**Comment by svenhjol** [comment]
Done
