### ISSUE TITLE
Grinding stone xp dupe glitch

### ISSUE THREAD

**Issue by SylisMC** [svenhjol/Charm#442]
**Required - Versions**
* Charm version - charm-fabric-1.16.4-2.1.9
* Minecraft version - 1.16.4
* Loader - Fabric

**Required - Description**
shift-click the enchanted book give a massive explosion of free EXP.
With this dupe I can effectively gain an unlimited amount of exp just by destroying items I don't care about
(also you can duplicate an enchantment and that alone seems kinda cheaty but intentional?)

**Optional: Steps To Reproduce**
1) Place the enchanted item in the top slot of the grindstone
2) Place a **STACK** of 64 (assumably any number) in the bottom slot
3) SHIFT click the enchanted book to get a massive explosion of EXP
![2020-12-23_21 21 43](https://user-images.githubusercontent.com/19602662/103051613-42395880-4565-11eb-8040-15c49d03b32f.png)
![2020-12-23_21 21 47](https://user-images.githubusercontent.com/19602662/103051617-436a8580-4565-11eb-92c8-e05306f3abf9.png)
![2020-12-23_21 22 07](https://user-images.githubusercontent.com/19602662/103051621-45344900-4565-11eb-8b08-1ab3511c98a7.png)

**Comment by svenhjol** [comment]
Please check this version: https://github.com/svenhjol/Charm/releases/download/2.2.0/charm-fabric-1.16.4-2.2.0.jar

**Comment by SylisMC** [comment]
Fixes the EXP dupe but you still get the enchant for free by shift clicking (it still charges you if you dont shift click)

**Comment by SylisMC** [comment]
Also. it GIVES you a little exp if you shift click instead of charging you

**Comment by svenhjol** [comment]
This jar was re-released with the same name. Please could you download and test again? https://github.com/svenhjol/Charm/releases/download/2.2.0/charm-fabric-1.16.4-2.2.0.jar

**Comment by SylisMC** [comment]
Fixed
