### ISSUE TITLE
Charm (Forge) link busted on Curseforge Page

### ISSUE THREAD

**Issue by SephirothWS** [svenhjol/Charm#446]
--- snip

https://www.curseforge.com/minecraft/mc-mods/charm

The link in the description of this page points to

https://www.curseforge.com/minecraft/mc-mods/charm-reforged

That page cannot be found.

That said, is there truly a Forge version of the mod, or do you only support Fabric?

**Comment by svenhjol** [comment]
Curseforge are still reviewing the project, as it was only started yesterday. Check back soon

**Comment by ridjack** [comment]
CurseForge has now approved the Charm Reforged page and all links should work.
