### ISSUE TITLE
[Bug] Incompatibility with "All The Blocks You Want"

### ISSUE THREAD

**Issue by SylisMC** [svenhjol/Charm#448]
**Versions**
* Charm version - charm-fabric-1.16.4-2.2.0` (latest release offed in [issue 442](https://github.com/svenhjol/Charm/issues/442))
* ATBYW version - atbyw-1.16.4-1.3.4
* Minecraft version - 1.16.4`

**Description**
Bootup crash when loading with [All The Blocks You Want](https://www.curseforge.com/minecraft/mc-mods/atbyw) With [Charm](https://www.curseforge.com/minecraft/mc-mods/charm)
(crash before Mojang loading screen)
[latest.log](https://github.com/svenhjol/Charm/files/5742424/latest.log)

Also Uploaded on other mods issue tracker [HERE](https://github.com/Azagwen/ATBYW/issues/14)

**Comment by Azagwen** [comment]
it seems Charm's [EnchantingTableBlockMixin](https://github.com/svenhjol/Charm/blob/master/src/main/java/svenhjol/charm/mixin/EnchantingTableBlockMixin.java) and ATBYW's [EnchantingTableBlockMixin](https://github.com/Azagwen/ATBYW/blob/master/src/main/java/net/azagwen/atbyw/mixin/EnchantingTableBlockMixin.java) are trying to mixin into the same part of the same class.

**Comment by RDKRACZ** [comment]
It's a duplicate but it's my fault because I didn't mention the mod name in the issue title.
https://github.com/svenhjol/Charm/issues/429

**Comment by ridjack** [comment]
This issue has been resolved. Please try the 2.2.1 release ( https://github.com/svenhjol/Charm/releases/download/2.2.1/charm-fabric-1.16.4-2.2.1.jar ).

As a bonus, @svenhjol was also able to resolve a similar conflict with Better End, so all three of these mods should work together happily. If you continue to experience this issue, please re-open this ticket or start a new one.
