### ISSUE TITLE
Desert Villages Generate w/ Trees

### ISSUE THREAD

**Issue by WenXin20** [svenhjol/Charm#45]
Charm v1.0.1

I find it odd that trees can generate with desert villages. Is this intentional? 
I also found a tree that had generated on top of the village well.
Some torches also generated with dirt instead of sand underneath them.

![2019-05-15_20 59 27](https://user-images.githubusercontent.com/12000593/57821423-15507d00-7756-11e9-8b3a-39fb7ec44c0f.png)

**Comment by svenhjol** [comment]
I think this might have been fixed in 1.1 (not yet released, still being tested) so I will check and close this if so. Thanks for the report.

**Comment by svenhjol** [comment]
Fixed in 1.1.0
