### ISSUE TITLE
Incompatibility with Recipe Conditions - A library

### ISSUE THREAD

**Issue by YTG1234** [svenhjol/Charm#450]
This is a "sister issue" to YTG1234/fabric-recipe-conditions#2 .

## Fabric Recipe Conditions (FRC)
FRC is a library that I created that allows to conditionally loads recipes based on various things.<br/>

## Incompatible
Charm implements a condition system (or does it? Maybe it's a dependency, I can't find the code), which conflicts with FRC's one, because they both use the `"conditions"` key.

## Fix
I've suggested steps to fix it in the issue on my repo, I'll copy them over to here.

- Use `Identifier`s for modules instead of `String`s (`String`s still work but if you specify it in the `Identifier` format in the recipe, why not in the `Map`).
- If you do that, a recipe condition could look like this:
```java
Registry.register(RecipeConds.RECIPE_CONDITION, new Identifier("charm", "module_enabled"),
    RecipeCondsUtil.stringParam(module -> {
        Map<Identifier, CharmModule> modules = ModuleHandler.getLoadedModules();
        return modules.get(new Identifier(module)).enabled;
    });
);
```
- And recipes would look like this:
```json5
{
// ...
  "conditions": [
    {
      "charm:module_enabled": "charm:module_name"
    }
  ]
}
```

**Comment by YTG1234** [comment]
Fixed compat.

**Comment by ridjack** [comment]
Glad you fixed this; I think @svenhjol missed it. I'll point it out to him so he can see if he should implement your suggestion for the sake of better compatibility regardless.
