### ISSUE TITLE
[1.16.4 Forge] Crates delete their inventories

### ISSUE THREAD

**Issue by rabbitscreams** [svenhjol/Charm#453]
**Versions**
* Charm version - 2.1.9 forge
* Minecraft version - 1.16.4

**Description**
Items place in Charm crates eventually disappear, leaving crates empty. Crates created by players or generated naturally in structures as loot both do this, and loot crates generated by the world are empty.

**Steps To Reproduce:**
Take a Charm crate
Put items in crate
Wait a while. The amount of time seems variable between a few minutes to a few hours. I haven't yet tested to see if it has to do with the crates being unloaded in chunks, but I don't doubt it as both incidences where I've lost stuff has been when I've left for a while to do other things.
Open Charm crate to find anything stored inside having vanished into the abyss

**Comment by ridjack** [comment]
Update Charm.
