### ISSUE TITLE
[1.1.0 beta3]endermite powder not locating end city properly

### ISSUE THREAD

**Issue by WarlordWossman** [svenhjol/Charm#46]
![2019-05-19_15 32 52](https://user-images.githubusercontent.com/16925725/57982891-95732d00-7a4b-11e9-8627-f16713229cc4.png)

Just tested endermite powder and it leads to a place without end city.

I have a guess what's going on here: 
From what I heard the chorus flowers have a higher priority in chunk population than the end cities for some reason which means depending on the direction you come from the chunk population might cancel a city from generating because the chorus flowers now block the space the city should have generated in.
Afaik the same applies to the gateways that lead back to the main island.

If you want to look into this I can recommend using amidst to get a feel how end cities should spawn, I am pretty sure even in amidst some end cities only have a certain chance of spawning.
Wonder if this is something that could be fixed, I hope so :D

**Comment by WarlordWossman** [comment]
Oh and here is the best thing:
The vanilla /locate command sends you to the same spot.

**Comment by WarlordWossman** [comment]
Talked to masa about it, it's a longer story - we should discuss it on discord and then decide what to make out of this.

**Comment by svenhjol** [comment]
Probably an enhancement?

**Comment by WarlordWossman** [comment]
I mean if you want to look into making end cities non directional and just generate on every spot the locate command also predicts one you can close this issue and make a new one I guess.
Personally I would love to have that but dealing with vanilla bugs / weird behavior would be another realm the mod expands into and one could think about making this a seperate project even.

**Comment by ridjack** [comment]
Is this still an issue?
