### ISSUE TITLE
No data fixers for endermite_powder and glowballs

### ISSUE THREAD

**Issue by FewerFlaws** [svenhjol/Charm#461]
Versions
* Charm version `2.2.1`
* Minecraft version - `1.16.4`

Description
The log reports the following two errors:
```
[12:34:28] [main/ERROR]: No data fixer registered for endermite_powder
[12:34:28] [main/ERROR]: No data fixer registered for glowball
```

**Comment by ridjack** [comment]
Known issue, harmless error. Future versions will suppress them.

**Comment by FewerFlaws** [comment]
Awesome, thanks =D
