### ISSUE TITLE
Ender Chest access button in inventory crashes the server

### ISSUE THREAD

**Issue by Porcy** [svenhjol/Charm#462]
Read me first!
1. Is your issue about the Forge version of Charm? Please report your issue here: https://github.com/svenhjol/CharmForge/issues
2. We don't support OptiFabric! Please check that the problem still occurs if you remove OptiFabric from your mods.
3. Don't use the bug report to suggest new features or behavior.

Versions
* Charm version - 2.2.1
* Minecraft version - 20w51a

Description
Tried to click on the chest-shaped button in the inventory. Server crashed

Got this in the crash report:
"Description: Exception in server tick loop

java.lang.NoClassDefFoundError: net/minecraft/class_746
	at svenhjol.charm.module.PortableEnderChest.lambda$init$0(PortableEnderChest.java:35)
	at net.minecraft.class_3738.run(class_3738.java:18)
	at net.minecraft.class_1255.method_18859(class_1255.java:144)
	at net.minecraft.class_4093.method_18859(class_4093.java:23)
	at net.minecraft.server.MinecraftServer.method_24306(MinecraftServer.java:760)
	at net.minecraft.server.MinecraftServer.method_18859(MinecraftServer.java:157)
	at net.minecraft.class_1255.method_16075(class_1255.java:118)
	at net.minecraft.server.MinecraftServer.method_20415(MinecraftServer.java:742)
	at net.minecraft.server.MinecraftServer.method_16075(MinecraftServer.java:736)
	at net.minecraft.class_1255.method_18857(class_1255.java:127)
	at net.minecraft.server.MinecraftServer.method_16208(MinecraftServer.java:721)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:673)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:257)
	at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.ClassNotFoundException: net.minecraft.class_746
	at java.net.URLClassLoader.findClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at net.fabricmc.loader.launch.server.InjectingURLClassLoader.loadClass(InjectingURLClassLoader.java:56)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at net.fabricmc.loader.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:168)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	... 14 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 20w51a
	Minecraft Version ID: 20w51a
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_251, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 350249392 bytes (334 MB) / 1728577536 bytes (1648 MB) up to 3806855168 bytes (3630 MB)
	CPUs: 8
	JVM Flags: 0 total; 
	Fabric Mods: 
		charm: Charm 2.2.1
		com_electronwill_night-config_core: core 3.6.2
		com_electronwill_night-config_toml: toml 3.6.2
		com_moandjiezana_toml_toml4j: toml4j 0.7.2
		fabric: Fabric API 0.29.1+1.17
		fabric-api-base: Fabric API Base 0.2.0+eaafab808e
		fabric-biome-api-v1: Fabric Biome API (v1) 3.1.1+836e66a38e
		fabric-command-api-v1: Fabric Command API (v1) 1.0.9+9f7a74238e
		fabric-commands-v0: Fabric Commands (v0) 0.2.1+c67237118e
		fabric-containers-v0: Fabric Containers (v0) 0.1.9+bee3a8868e
		fabric-content-registries-v0: Fabric Content Registries (v0) 0.2.0+880269e68e
		fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.1.2+b7f9825d8e
		fabric-dimensions-v1: fabric-dimensions-v1 2.0.2+e1f1abb18e
		fabric-entity-events-v1: Fabric Entity Events (v1) 1.0.1+ce504de58e
		fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.3+9f7a74238e
		fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.0+9f7a74238e
		fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.5+c67237118e
		fabric-item-api-v1: Fabric Item API (v1) 1.2.1+9f7a74238e
		fabric-item-groups-v0: Fabric Item Groups (v0) 0.2.2+c67237118e
		fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 1.4.0+8f5b7a468e
		fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.0.3+0c3d83a58e
		fabric-mining-levels-v0: Fabric Mining Levels (v0) 0.1.2+9f7a74238e
		fabric-networking-api-v1: Fabric Networking API (v1) 1.0.1+c67237118e
		fabric-networking-blockentity-v0: Fabric Networking Block Entity (v0) 0.2.7+bee3a8868e
		fabric-networking-v0: Fabric Networking (v0) 0.3.1+96f0bfaa8e
		fabric-object-builder-api-v1: Fabric Object Builder API (v1) 1.10.2+9f7a74238e
		fabric-object-builders-v0: Fabric Object Builders (v0) 0.7.2+9f7a74238e
		fabric-particles-v1: Fabric Particles (v1) 0.2.3+c67237118e
		fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.7.4+836e66a38e
		fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.1.4+9f7a74238e
		fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.4.0+27f445e78e
		fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.1.3+9f7a74238e
		fabric-structure-api-v1: Fabric Structure API (v1) 1.1.3+c67237118e
		fabric-tag-extensions-v0: Fabric Tag Extensions (v0) 1.1.1+e1f1abb18e
		fabric-tool-attribute-api-v1: Fabric Tool Attribute API (v1) 1.2.7+9f7a74238e
		fabricloader: Fabric Loader 0.10.8
		minecraft: Minecraft 1.17-alpha.20.51.a
	Player Count: 2 / 10; [class_3222['Dodge34'/337, l='ServerLevel[world]', x=-415.32, y=68.00, z=139.72], class_3222['Kournin'/530, l='ServerLevel[world]', x=-180.42, y=36.00, z=138.73]]
	Data Packs: vanilla (incompatible), file/ModularHUD.zip (incompatible), file/Paint's+Anti-Junk+Loot+Tables+(v1.4+for+1.16.2).zip (incompatible), file/PlatyPack, file/fast leaf decay v2.0.3.zip (incompatible), file/graves v2.8.0.zip (incompatible), file/multiplayer sleep v2.5.2.zip (incompatible), file/Climbable_Chains_1.1.zip (incompatible), file/Crop_Harvesting_1.1.zip (incompatible), file/Enhanced+Wolves+b1.1.zip (incompatible), file/KourninPack, file/spegtunerpg.zip (incompatible), file/planks to logs (incompatible), file/sticks to planks (incompatible), file/anti enderman grief v1.1.0.zip (incompatible), file/anti ghast grief v1.1.0.zip (incompatible), file/anti-creeper-grief.zip (incompatible), file/double shulker shells v1.3.0.zip (incompatible), file/dragon drops v1.3.0.zip (incompatible), file/End_Ship_Beacons_1.1.zip (incompatible), file/Invisible_Item_Frames_1.1.zip (incompatible), file/armored elytra v1.0.3.zip (incompatible), Fabric Mods
	Is Modded: Definitely; Server brand changed to 'fabric'
	Type: Dedicated Server (map_server.txt)"

**Comment by svenhjol** [comment]
Fixed in 21w08b
