### ISSUE TITLE
Minecraft gave me when the game was loading up.

### ISSUE THREAD

**Issue by Niconoko** [svenhjol/Charm#465]
https://pastebin.com/upiVStyu
Not sure what's going on, here's a crash log.

**Comment by wolperite** [comment]
i have something similar https://pastebin.com/8qXJDwES , it appears to be an issue with one of quarks worldgen
Exception message: java.lang.ClassNotFoundException: vazkii.quark.world.gen.structure.BigDungeonStructure

**Comment by SoldierKucha** [comment]
Same https://pastebin.com/t3Z4x2Rz

**Comment by ridjack** [comment]
Duplicate of svenhjol/Charm#25 .
