### ISSUE TITLE
20w51a moving enchantments bug

### ISSUE THREAD

**Issue by Kisonu** [svenhjol/Charm#466]
Versions
* Charm version - e.g. `2.2.1`
* Minecraft version - e.g. `20w51a`

Description
Attempting to separate enchantments from a book with multiple enchantments works fine, however if more than 1 enchanted book is inserted with more than 1 enchantment, there is a loss. for example, if 2 books with infinity and punch are put into a grindstone with blank books (to separate them), the player receives 1 book with infinity and one book with punch, with a TOTAL loss of the other book.

![2021-01-02_13 32 12](https://user-images.githubusercontent.com/23608037/103465231-4e5cad00-4cff-11eb-8136-3eff10c028cc.png)
![2021-01-02_13 32 32](https://user-images.githubusercontent.com/23608037/103465236-59174200-4cff-11eb-99a4-203a0955a91e.png)
![2021-01-02_13 32 29](https://user-images.githubusercontent.com/23608037/103465237-59174200-4cff-11eb-983c-09ecbb299f6d.png)

**Comment by svenhjol** [comment]
Grindstone disenchanting doesn't work with an input stack size of greater than 1 in 21w08b, so I *think* this might be fixed. I couldn't repeat the problem when I followed your screenshots. If this is still an issue in the latest snapshot, please reopen this.
