### ISSUE TITLE
If another mod (like JEI) removes the recipe book button in the inventory, it gets re-added when you get a crafting table or ender chest in your inventory

### ISSUE THREAD

**Issue by aaronhowser1** [svenhjol/Charm#467]
Read me first!
1. Is your issue about the Forge version of Charm? Please report your issue here: https://github.com/svenhjol/CharmForge/issues
2. We don't support OptiFabric! Please check that the problem still occurs if you remove OptiFabric from your mods.
3. Don't use the bug report to suggest new features or behavior.

Versions
* Charm version - `charm-forge-1.16.4-2.1.9`
* Minecraft version - e.g. `1.16.4`

Description
![2021-01-03_05 08 11](https://user-images.githubusercontent.com/15698722/103477194-c8ce1100-4d81-11eb-92ed-710a77296f50.png)
![2021-01-03_05 08 18](https://user-images.githubusercontent.com/15698722/103477196-cb306b00-4d81-11eb-9a93-a95687bc7517.png)
then throwing it out
![2021-01-03_05 08 24](https://user-images.githubusercontent.com/15698722/103477200-d2577900-4d81-11eb-8e3e-5601f594cace.png)
the button goes away when you close and reopen the gui
![2021-01-03_05 08 36](https://user-images.githubusercontent.com/15698722/103477204-de433b00-4d81-11eb-84b8-c863970106fb.png)

**Comment by Coranthes** [comment]
Update to the latest version of Charm.  This was a known issue that has since been resolved.

**Comment by aaronhowser1** [comment]
@Coranthes I am using charm-forge-1.16.4-2.1.9.jar, which is the latest version that uses forge.
