### ISSUE TITLE
crates/shulkerboxes nesting

### ISSUE THREAD

**Issue by WarlordWossman** [svenhjol/Charm#47]
Crates might not go into crates and shulkerboxes might not go into shulkerboxes BUT crates go into shulkerboxes and shulkerboxes into crates. This means you can nest them infinitely which seems a little bit overpowered.
My suggestion would be to blacklist crates from the shulkerbox and blacklist shulkerboxes from the crate to prevent this behavior.

While we are talking about changes to crates: Would also be nice to have the tooltip list like shulkerboxes and maybe even have something similar to quarks shulkerbox tooltip for crates so you can see what's in it by hovering over it in item form!

**Comment by svenhjol** [comment]
Agreed. I'll work on the nesting issue first, and then add the tooltip feature to trello. Hopefully I can borrow the quark one :)

**Comment by WarlordWossman** [comment]
Just checked beta4, now you can no longer put (any) of the crates into shulkerboxes but the other way around it still works somehow.
Tested for all 16 shulkerboxes since they are on different IDs

**Comment by WarlordWossman** [comment]
After further testing this seems to be a general crate problem as you can currently put crates into crates as well.
