### ISSUE TITLE
Spectre missing lang file registration.

### ISSUE THREAD

**Issue by Blueberryy** [svenhjol/Charm#471]
I dunno why but language file missing "Spectre"

**Comment by Blueberryy** [comment]
![image](https://user-images.githubusercontent.com/36592509/104039652-7618ad00-51f8-11eb-9505-964063ff4545.png)

**Comment by ridjack** [comment]
Please update this bug report with more information, such as which versions you're using, which loader (Fabric or Forge), and the other basic information you can see in the template. Unless this info is added, this bug report will be closed.

**Comment by Blueberryy** [comment]
will do

**Comment by Blueberryy** [comment]
![image](https://user-images.githubusercontent.com/36592509/104185546-f4fb2900-5436-11eb-9015-d86cb53fdb3a.png)

**Comment by Blueberryy** [comment]
![image](https://user-images.githubusercontent.com/36592509/104185640-0d6b4380-5437-11eb-8fe9-7e6ab1e4ebc4.png)

**Comment by Blueberryy** [comment]
![Uploading javaw_ckC0eGL4bX.png…]()

**Comment by Blueberryy** [comment]
![javaw_ckC0eGL4bX](https://user-images.githubusercontent.com/36592509/104186064-ab5f0e00-5437-11eb-80a8-b909260b11f4.png)

**Comment by Blueberryy** [comment]
nvm. wrong version
