### ISSUE TITLE
Errors in log with Mythic Metals if supported mods aren't present

### ISSUE THREAD

**Issue by FewerFlaws** [svenhjol/Charm#477]
Versions
* Charm version - `2.2.2`
* Minecraft version - `1.16.4`

Description
There are hundreds of lines of error reports in the log when running charm alongside mythic metals but not other mods that mythic metals supports such as mechanix and tech reborn.  I suspect that this is related to the recipe unlocker, but disabling every single feature in the charm config does not resolve this issue.

Optional: Steps To Reproduce
  * Install charm, mythic metals, fabric API, cloth config, and auto config updated.
  * Run minecraft.
  * Create a new world.
  * Investigate the log.

Partial log:
https://pastebin.com/b9KDFicP
The two errors related to harvest scythes are internal to mythic metals.  All those that follow only appear when charm is installed alongside mythic metals.

Discussion so far:
https://github.com/Noaaan/MythicMetals/issues/21

**Comment by Noaaan** [comment]
Seems to be related to Mixin in RecipeManager. [Here](https://github.com/Noaaan/MythicMetals/blob/MASTER/src/main/java/nourl/mythicmetals/mixin/MixinRecipeManager.java)  is my class. 
I use it to surpress recipe errors whenever the missing mod is not loaded. My guess is it is being cancelled by the invoke.

**Comment by Noaaan** [comment]
I am still trying to figure out what your Mixin actually does. What does it do?  🤔

**Comment by svenhjol** [comment]
Hi there,

Apologies that it took a while to respond.

I have looked at your mixin, compiled your mod against Charm and incorporated a general fix for what you're trying to do into Charm's RecipeHandler.  The fix looks at *all* recipetypes and checks if the corresponding mod is loaded - if not, the recipe is removed from the registered recipe map.

https://github.com/svenhjol/Charm/blob/3c85afa79f2cb025c139ebb45deb71ea21824b18/src/main/java/svenhjol/charm/base/handler/RecipeHandler.java#L71

I'm attaching a snapshot build of Charm with this recipe filter applied for you to test against your mod and other mods that you have compatibility with. If it works, you don't need to change anything about your mixin.

[charm-fabric-1.16.4-2.3.1-SNAPSHOT1.zip](https://github.com/svenhjol/Charm/files/5825412/charm-fabric-1.16.4-2.3.1-SNAPSHOT1.zip)

**Comment by Noaaan** [comment]
Can confirm that this snapshot does fix the issues. Thank you!
