### ISSUE TITLE
Wander Trader random value ignored

### ISSUE THREAD

**Issue by Linguardium** [svenhjol/Charm#479]
https://github.com/svenhjol/Charm/blob/30c2f8cb3e9560ee25a0e58e718f479626c1c1ab/src/main/java/svenhjol/charm/mixin/WanderingTraderManagerMixin.java#L26

Rather than hardcoding 10, this should use the provided int argument

**Comment by F43nd1r** [comment]
Why? The provided int argument will always be 10.

**Comment by Linguardium** [comment]
unless another mixin modifies the 10 value

**Comment by svenhjol** [comment]
Done in 2.3.2
