### ISSUE TITLE
anvil consumes whole stack of enchanted books

### ISSUE THREAD

**Issue by WarlordWossman** [svenhjol/Charm#48]
Just tested applying enchanted books in the anvil with a stack of enchanted books in the right slot larger than 1 and the result was that all books get consumed.
I think it should only consume one book per item.

**Comment by WarlordWossman** [comment]
Update: extract XP also consumes the whole stack of enchanted books from the left slot!

**Comment by svenhjol** [comment]
I'm going to split these out into two separate issues
