### ISSUE TITLE
Double-blocks don't work with Acquisition

### ISSUE THREAD

**Issue by ridjack** [svenhjol/Charm#480]
MC 1.16.4, Charm 2.3.0

Doors and double-tall fauna don't quite work with Acquisition. Doors are only Acquired if broken on the bottom half; on the top half they're dropped on the ground.

Double-height flowers are a bit more broken; top half they're simply dropped, bottom half gets a flower in my inventory AND one dropped on the ground, effectively duplicating it.

Please feel free to contact me if you need additional info.

**Comment by Coranthes** [comment]
``Please feel free to contact me if you need additional info.``  Last time you said that, he had you coding lockers.

**Comment by Coranthes** [comment]
Yes, more info is needed please.  What mods are you playing with?  And are you on Fabric or Forge?
