### ISSUE TITLE
Game is crashing on launch

### ISSUE THREAD

**Issue by GhostpunchTV** [svenhjol/Charm#482]
The game crashed whilst initializing game
Error: java.lang.RuntimeException: Could not execute entrypoint stage 'main' due to errors, provided by 'charm'!
Exit Code: -1

[crash-2021-01-18_20.26.49-client.txt](https://github.com/svenhjol/Charm/files/5832084/crash-2021-01-18_20.26.49-client.txt)

Please help, I can't play on my survival map.

**Comment by F43nd1r** [comment]
Fix your config file. Your log says `Key is not followed by an equals sign on line 1`

**Comment by GhostpunchTV** [comment]
I'm sorry but how do I do that? I've been trying to do so but I couldn't figure it out.

**Comment by ridjack** [comment]
The easiest way would be to simply delete the config file, then start the game again. That will generate a new, working config. You can make any changes you need to after that.

**Comment by GhostpunchTV** [comment]
I'm just going to ask because I can't find it. Where exactly is the config file?

**Comment by ridjack** [comment]
There's a config folder in the same place as your mods folder. Charm.toml in that folder is what you're looking for.

**Comment by ridjack** [comment]
Please don't be afraid of asking dumb questions. Everyone brain-farts sometimes.

It feels odd to me that you've managed to find and post a log file, but need to ask where your config file is. Are you doing this through, like, Twitch or something odd?

**Comment by GhostpunchTV** [comment]
No, I was just looking for the config file in the mods folder and the charm mod itself.
I found it and it's working now. Thank you so much for your help, I hope you have a happy and wonderful next week!
