### ISSUE TITLE
Dark Oak Bookshelves are not working for Enchanting

### ISSUE THREAD

**Issue by ChickaChickaBoomBoom** [svenhjol/Charm#490]
Read me first!
1. Is your issue about the Forge version of Charm? Please report your issue here: https://github.com/svenhjol/CharmForge/issues
2. We don't support OptiFabric! Please check that the problem still occurs if you remove OptiFabric from your mods.
3. Don't use the bug report to suggest new features or behavior.

Versions
* Charm version - e.g. `2.2.1`
* Minecraft version - e.g. `1.6.14`

Description
Dark oak bookshelves are not increasing enchantment table level as they should.

**Comment by pjlasl** [comment]
I noticed that any charm:????_bookshelf outside of Minecraft:bookshelf does not work properly around enchantment tables.

**Comment by SebyakinAndrei** [comment]
@svenhjol Is there any progress regarding this issue?
