### ISSUE TITLE
[1.16.4] Charm breaking something with datapacks.

### ISSUE THREAD

**Issue by Calmxx** [svenhjol/Charm#497]
Every time I load Minecraft with Charm and then try to create a world I get an error that says "Datapack validation failed" or if I load a pre-existing world I get a similar error with datapacks. I know it is because of Charm because it works fine when I remove it. I have tried making a world with NO data packs and it still gives the error.

**Comment by svenhjol** [comment]
Please paste the error here.

**Comment by RDKRACZ** [comment]
This sounds like you modified Charm's internal datapack (if there is any). Were you editing config file?
