### ISSUE TITLE
Game crashes while opening [fabric] 1.16.5

### ISSUE THREAD

**Issue by RandomRandal** [svenhjol/Charm#498]
My friend has a server with this mod installed that our friend group has been playing on for about a week now, and it hasn't had any problems until today. I tried opening the launcher, and it couldn't complete it's updates, because Windows needed an update. I did that, and the launcher was able to update, but then fabric wouldn't start. It crashes, and gives the error "An unexpected issue occurred and the game has crashed. We're sorry for the inconvenience. Exit Code: 0" I checked in the game's output logs while starting up, and it says "Game crashed with exit code 1" I am certain that Charm is the issue, because the game crashes, even when Charm is the only mod installed, and all the other mods work when Charm is uninstalled. I should also say, my friends aren't having any issues with the mod. If anyone knows what the problem is, and how to fix it, I'd be happy to have the help.

**Comment by kubistonek** [comment]
fuck this mod, I spent 16 hours trying to fix it, turned out this piece of shit was the issue

**Comment by RandomRandal** [comment]
Okay, but did you figure out _how_ to fix it?

**Comment by svenhjol** [comment]
Hi,

Could you provide the following - it might help to track down the problem:

- launcher (vanilla mojang, twitch, multimc etc)
- fabric loader version
- fabric API version
- java version

Thanks!

**Comment by RandomRandal** [comment]
Sure thing, it's the vanilla mojang launcher, (my game is not cracked) fabric loader version 0.11.2, fabric API version 0.31.0, and java version 1.16.5.

**Comment by svenhjol** [comment]
Thanks. Your java version is not the same as Minecraft version. I think you can find it out by doing `java -version` in a command prompt.

https://www.wikihow.com/Check-Your-Java-Version-in-the-Windows-Command-Line

**Comment by RandomRandal** [comment]
Ah, okay. Is this it?

java version "1.8.0_271"
Java(TM) SE Runtime Environment (build 1.8.0_271-b09)
Java HotSpot(TM) 64-Bit Server VM (build 25.271-b09, mixed mode)

**Comment by svenhjol** [comment]
I'll fire up a windows instance with the versions of things you provided and see if I can repeat it.

**Comment by RandomRandal** [comment]
Okay, let me know the results when you can, please.

**Comment by RandomRandal** [comment]
Okay, so apparently it was having some conflict with Optifine and/or Optifabric, because when I deleted those, it worked. I don't understand why this issue didn't crop up until now though. They were working together just fine last week.

**Comment by astrobudder** [comment]
Has there been any development here cause I've been having the same issue

**Comment by svenhjol** [comment]
Yeah we don't support Optifine or OptiFabric as these mods make a ton of changes to the core game without any public source code for their changes.

**Comment by RandomRandal** [comment]
Damn. Well, so much for being able to spy on my friends with Optifine's zoom.

**Comment by RDKRACZ** [comment]
@RandomRandal you...you know there are zoom mods for fabric right?
