### ISSUE TITLE
Fabric tag?

### ISSUE THREAD

**Issue by Mysteriaa** [svenhjol/Charm#499]
Huge apologies for posting this to the GitHub of all places. Comments on the original curse page are disabled, PMs aren't being accepted, and there isn't a Discord link.
Would you mind adding a Fabric tag to this mod and Charmonium so that Fabric users can find it easily? Thank you!

**Comment by YumatanGames** [comment]
Also, a information about it not being compatible with optifine and optifabric would be nice too, since I believe there's a lot of people who are trying to run both and having issues.

**Comment by svenhjol** [comment]
When you say fabric tag, do you mean on the curseforge page?

**Comment by YumatanGames** [comment]
Exactly. By taggin it as a fabric mod, it will show up when people filter the page to only show mods for Fabric. Much easier to find. :)
