### ISSUE TITLE
[1.1.0 beta4]bookshelf-chest doesn't show up in creative inventory

### ISSUE THREAD

**Issue by WarlordWossman** [svenhjol/Charm#50]
Not sure if any other beta after the refactor of creative tabs had this issue but as the title suggests the bookshelf-chest doesn't show up in _any_ of the creative tabs and you can't even find it using the search bar.

![bookshelf_chest](https://user-images.githubusercontent.com/16925725/58353667-660b5880-7e6f-11e9-9f1e-5a554697b184.PNG)

**Comment by svenhjol** [comment]
This seems to be something to do with the oredict for "bookshelf". Reverting to use vanilla bookshelf for now

**Comment by svenhjol** [comment]
Nope, I just suck. Didn't register meta 0
