### ISSUE TITLE
Some modules do not auto-disable with Qark

### ISSUE THREAD

**Issue by dromedar17** [svenhjol/Charm#501]
Some of the modules that say that they disable themselves seem to still be enabled when quark is present. So far I've noticed this with inventory tidying and shulker box tooltips.

Forge 36.0.44 and charm 2.3.2

Edit: oops, I meant to post this on the forge version of charm.

**Comment by Klaaf** [comment]
That's also the case with Bookshelves, Ladders and Chests afaik

**Comment by svenhjol** [comment]
Link to Forge ticket with the same issue: https://github.com/svenhjol/CharmForge/issues/87
