### ISSUE TITLE
Charm Chests cannot be used in Modded recipes requiring wooden chests

### ISSUE THREAD

**Issue by IdrisQe** [svenhjol/Charm#502]
Versions
* Charm version - `2.3.2 (Fabric)`
* Minecraft version - `1.16.5`

Description
Quite simply, Charm chests can't be used to craft most modded items that require wooden chests.
An example being the backback from SimpleBackpack, which accepts BetterEnd chests.
SimpleBackpack uses a "c:chest" tag to determine what blocks are chests. Interestingly, SimpleBackpack's chest tag only checks for minecraft:chest and minecraft:trapped_chest, and I don't see SimpleBackpack integration anywhere in BetterEnd, so something BetterEnd is doing with how they implement their chests must be making them be detected as Vanilla Chests or something? I'm honestly not sure how, given my limited knowledge, but it may be worth looking into how BetterEnd does it for compatability. Granted, their chests aren't perfect, and it seems Vanilla recipes still need to be manually remade to use each chest.

**Comment by svenhjol** [comment]
Hi,

We can add a `c:chests` tag for compatibility in the next release.

**Comment by IdrisQe** [comment]
https://github.com/paulevsGitch/BetterNether/issues/317#issuecomment-790150812
This may be useful information. It seems BetterEnd uses a common chest tag that's included in Fabric itself now, so perhaps using that would be advisable.

**Comment by svenhjol** [comment]
Charm does use the `c` namespace for bookshelves, so it should be easy enough to add chests as well.

**Comment by Coranthes** [comment]
This has been taken care of for regular chests.  However, should trapped chests also be included?

**Comment by IdrisQe** [comment]
I think in vanilla Trapped Chests generally can't be used for most recipes? I don't know honestly since I don't think I've ever actually bothered to craft a Trapped Chest.

**Comment by Coranthes** [comment]
It's at least been a few years since I have, before the mechanics of chests were changed.  I'll just do regular chests then.
