### ISSUE TITLE
Charm appears to be incompatible with Optifabric 1.16.5

### ISSUE THREAD

**Issue by noclueumbreon** [svenhjol/Charm#503]
When started with Optifabric, it crashes before starting up at all. Seems to be an issue with Satin, but ultimately just marking it as an incompatibility would help?

**Comment by Coranthes** [comment]
At the top of a bug report, if you read the "Read Me First" section, it says, in part:
"2. We don't support OptiFabric! Please check that the problem still occurs if you remove OptiFabric from your mods."  
Doing things this way has worked well as for some people it seems to work, and some it doesn't.  Optifine/OptiFabric causes issues with many mods.
