### ISSUE TITLE
Any way to summon specific mob variants/textures?

### ISSUE THREAD

**Issue by Revelins** [svenhjol/Charm#507]
For example, if I wanted to summon a brown chicken, or a yellow moobloom, would there be any specific NBT tag I could use? I know in default minecraft, for cats, you can use {CatType:X}. I've tried many different things, though, and nothing seems to work. If it's entirely random then I understand! Thanks regardless.

**Comment by Coranthes** [comment]
I'm not sure about the mooblooms, we'll see what @svenhjol.  As far as the regular animal variants go (chickens, pigs, etc), they're completely random because we're ultimately just adding skins to them.  Minecraft separates cats by breeds, creating different types, not giving them random skins.

**Comment by svenhjol** [comment]
`/summon charm:moobloom ~ ~ ~ {Type:allium}` for example.

**Comment by svenhjol** [comment]
You can use the ID of the flower that you want.

**Comment by JairusSW** [comment]
Is there any way to like summon a golden chicken?

**Comment by Coranthes** [comment]
No, there's isn't.  All the decorative animal variants (which includes chickens, cows, pigs, regular squids and wandering traders), are completely random, and golden variants are quite rare.  You could keep summoning chickens until you get one...

**Comment by JairusSW** [comment]
Alright, thank you
