### ISSUE TITLE
composter lighting issues

### ISSUE THREAD

**Issue by WarlordWossman** [svenhjol/Charm#51]
![2019-05-24_22 09 33](https://user-images.githubusercontent.com/16925725/58354220-0c0b9280-7e71-11e9-82f0-92df5b85d8b8.png)
![2019-05-24_22 09 59](https://user-images.githubusercontent.com/16925725/58354221-0ca42900-7e71-11e9-8531-2a0dccc28c78.png)

It seems like the inside textures of the composter use the same lighting that would apply to the rendering of the outside textures of the same respective face/direction.
This is not really critical but does certainly look weird.

**Comment by svenhjol** [comment]
Having trouble repeating - what are your video settings? Using optifine?

**Comment by WarlordWossman** [comment]
Yeah those screenshots are with optifine, I will try without again in a bit.
(I usually play without OF, kinda feel dumb for not testing without now)

**Comment by WarlordWossman** [comment]
If you want to check but notice the composter is also not showing up in the creative inventory anymore (tested in beta4). Guess this should be another issue?

Anyways without OF it doesn't look similar but the inside lighting is still effected:
![2019-05-28_18 30 30](https://user-images.githubusercontent.com/16925725/58495088-e6cf9a80-8176-11e9-8e3a-de911be9a8de.png)
![2019-05-28_18 30 21](https://user-images.githubusercontent.com/16925725/58495156-0a92e080-8177-11e9-9e17-389ea925dbac.png)

Shouldn't only the lighting of the blockspace above the composter effect the lighting of the inside textures?

**Comment by svenhjol** [comment]
Something's off here. I need to see if the same thing is happening with vanilla 1.14
