### ISSUE TITLE
Tamed Animal Damage Config non functional

### ISSUE THREAD

**Issue by ZeburaBlack** [svenhjol/Charm#510]
charm-fabric-1.16.5-2.3.2.jar

#Tamed animals do not take direct damage from players.
"TamedAnimalsNoDamage Enabled" = true

Does not work on servers, and cannot be turned off to be able to use Respawnable Pets item

**Comment by codegavran** [comment]
Confirmed - this also creates a compatibility issue with Bewitchment which intercepts attack to get Taglocks from pets, and I haven't fully tested but I believe may also prevent breeding them, and if so potentially other tameable breedables.

**Comment by uwillnotbespared** [comment]
Addditionally creates compatibility issue with Mahou Tsukai. Unable to create a Morgan because it requires a player to kill tamed wolf of his.

**Comment by Triandot** [comment]
so uh, any way to fix it for 1.16.5? got an existing modpack server running so changing versions aint a possibility
