### ISSUE TITLE
Wraith RecipeManagerMixin Incompatability

### ISSUE THREAD

**Issue by Noaaan** [svenhjol/Charm#511]
Hello! I have recently discovered a compatability issue with Alloy Forgery.  

Versions
* Charm version - 2.3.2
* Minecraft version -1.16.5

Description
Alloy Forgery is a data driven mod, and as such we use the RecipeManagerMixin to dynamically generate recipes. Somewhere in this path Charm seems to remove the recipes upon launching a world.
https://github.com/LordDeatHunter/Alloy-Forgery/blob/master/src/main/java/wraith/alloy_forgery/mixin/RecipeManagerMixin.java  
I have linked our Mixin to give you an idea how it works.

**Comment by Noaaan** [comment]
I want to bump this issue as it keeps happening to more of our mods. This issue now extends to Waystones as well (https://github.com/LordDeatHunter/FabricWaystones/blob/master/src/main/java/wraith/waystones/mixin/RecipeManagerMixin.java). 
Multiple people have reported this issue to us in our Discord server, and disabling Charm has fixed it in most cases.

**Comment by wbsp9999** [comment]
Somehow missed this one when I was reporting my issue, will close mine as a duplicate: 
https://github.com/svenhjol/Charm/issues/617

**Comment by svenhjol** [comment]
Thanks for the patience on this issue. @Noaaan could you please test this attached experimental version of Charm alongside Waystones? Backup your `charm.toml` config file if you have made edits, and test in a brand new world. If you could attach the log output that would be great.

[charm-fabric-1.17-3.3.0-alpha1.zip](https://github.com/svenhjol/Charm/files/6754934/charm-fabric-1.17-3.3.0-alpha1.zip)

**Comment by Noaaan** [comment]
I put this in an instance which did not previously have Charm. The issue seems to have been fixed.
I have a log right here: https://paste.ee/p/OvMEk

**Comment by svenhjol** [comment]
Thanks for the log. I'm going to keep this issue open as I may need to test again before final release.

**Comment by GabrielXoxota** [comment]
> Thanks for the patience on this issue. @Noaaan could you please test this attached experimental version of Charm alongside Waystones? Backup your `charm.toml` config file if you have made edits, and test in a brand new world. If you could attach the log output that would be great.
> 
> [charm-fabric-1.17-3.3.0-alpha1.zip](https://github.com/svenhjol/Charm/files/6754934/charm-fabric-1.17-3.3.0-alpha1.zip)

I have the same issue but the archive is for 1.17 and i am on 1.16.5. could you please help me
