### ISSUE TITLE
/give command creates a ghost copy

### ISSUE THREAD

**Issue by Fourmisain** [svenhjol/Charm#515]
Using any give command like `/give @p netherite_sword` will create a "ghost" copy that is thrown on the ground.
It cannot be picked up and will persist through restarts, so it appears to not be a client-side thing.

Tested in singleplayer with Charm v2.3.2 and no other mods, happens in v2.3.1 as well.
![ghost](https://user-images.githubusercontent.com/8464472/112180902-3c9eed80-8bfc-11eb-9e6a-27c16bbca0c0.png)

**Comment by Fourmisain** [comment]
Aha!
It's not any item, it's netherite items and it doesn't happen when `"ExtendNetherite Enabled"` is set to `false`.

**Comment by svenhjol** [comment]
This bug has reappeared through regression. It's lower priority but will be looked at.
