### ISSUE TITLE
Issue with Water Bottles

### ISSUE THREAD

**Issue by SpiderKolo** [svenhjol/Charm#516]
**Versions**
**Mod Loader:** Fabric
**Charm version:** 2.2.2, but I didn't noticed anything mentioned about this glitch in 2.3.2 either
**Minecraft version:** 1.16.5

**Description:**
This glitch occurs on Survival (and Adventure I guess).
When filling cauldron with water using stacked Water Bottles (any amount from 2 to 16), all of the bottles gets used and you gain in return just one glass bottle.
Cauldron will gain just one more level of water regardless how much of water bottles you use on Cauldron.

**Steps To Reproduce:**
1. Get any amount of Water Bottles, needs to be more than one and all of them needs to be in the same stack
2. Get a Cauldron, can't be full of water, but can have some water.
3. Use Water bottles on empty/partially filled cauldron
4. ...
5. Not Stonks, actually.

**Comment by svenhjol** [comment]
Hi, could you confirm this is still happening on 2.3.2? Thanks

**Comment by SpiderKolo** [comment]
Just tested it - Yes it's still happening in 2.3.2 version.
