### ISSUE TITLE
Refined Obsidian does not drop any items

### ISSUE THREAD

**Issue by SpiderKolo** [svenhjol/Charm#517]
**Versions**
**Mod Loader:** Fabric
**Charm version:** 2.2.2, but I didn't noticed anything mentioned about this glitch in 2.3.2 either
**Minecraft version:** 1.16.5

Description:
Basically when mining Refined Obsidian with anything (doesn't matter if with Pickaxe, Diamond/Netherite Pickaxe, Hand or if enchanted with Silk Touch or not), blocks never drop.
Happens to full block, stairs, slabs and walls.

Not sure if it's intentional (I expect it not to be the case, thus reporting it), couldn't find anything about blocks not dropping intentionally anywhere.
In fact, I could not find anything about new Obsidian Variant in general. I might be just blind tho...

**Comment by svenhjol** [comment]
Will be fixed in next version. Thanks for report

**Comment by SpiderKolo** [comment]
Thanks for response!
