### ISSUE TITLE
[1.16.5][2.3.2] Crash after loading into a world

### ISSUE THREAD

**Issue by LeoNoawi** [svenhjol/Charm#522]
Versions:
Charm version - 2.3.2
Minecraft version - 1.16.5
Fabric loader - 0.11.3
Java version - 1.8.0_281

Desc:
Crashes almost immidietly after a world (existing and new) is loaded. I'm using the Adventure Pack modpack for Fabric with a few additional mods and some that i've updated but haven't touched their confings if it help any.
I've played with this setup a time or two before it started crashing so i'm not sure if it's a mod conflict ?
The Not Enough Crashes mod blames Charm for the crash, but i'm hopless with crashlogs.
Glad for any help.

Latest Log:      https://pastebin.ubuntu.com/p/69SFQW7tmB/

**Comment by pm065** [comment]
Happens to me too, here's the log: 
`---- Minecraft Crash Report ----
// You're mean.

Time: 3/29/21 10:57 AM
Description: Unexpected error

java.lang.NullPointerException: Unexpected error
	at Not Enough Crashes deobfuscated stack trace.(1.16.5+build.6)
	at net.minecraft.client.sound.SoundSystem.handler$bac000$onStopRecordSound(SoundSystem:561)
	at net.minecraft.client.sound.SoundSystem.stop(SoundSystem:157)
	at net.minecraft.client.sound.SoundManager.stop(SoundManager:265)
	at svenhjol.charm.client.MusicImprovementsClient.forceStop(MusicImprovementsClient.java:181)
	at svenhjol.charm.client.MusicImprovementsClient.handleTick(MusicImprovementsClient.java:151)
	at net.minecraft.client.sound.MusicTracker.handler$dkh002$hookTick(MusicTracker:524)
	at net.minecraft.client.sound.MusicTracker.tick(MusicTracker)
	at net.minecraft.client.MinecraftClient.tick(MinecraftClient:1564)
	at net.minecraft.client.MinecraftClient.render(MinecraftClient:1021)
	at net.minecraft.client.MinecraftClient.run(MinecraftClient:681)
	at net.minecraft.client.main.Main.main(Main:215)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:226)
	at net.fabricmc.loader.launch.knot.Knot.launch(Knot.java:146)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:28)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at link.infra.jumploader.Jumploader.onLoad(Jumploader.java:171)
	at cpw.mods.modlauncher.TransformationServiceDecorator.onLoad(TransformationServiceDecorator.java:53)
	at cpw.mods.modlauncher.TransformationServicesHandler.lambda$loadTransformationServices$11(TransformationServicesHandler.java:131)
	at cpw.mods.modlauncher.TransformationServicesHandler$$Lambda$58/1388278453.accept(Unknown Source)
	at java.util.HashMap$Values.forEach(HashMap.java:972)
	at cpw.mods.modlauncher.TransformationServicesHandler.loadTransformationServices(TransformationServicesHandler.java:131)
	at cpw.mods.modlauncher.TransformationServicesHandler.initializeTransformationServices(TransformationServicesHandler.java:56)
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:76)
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:66)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Affected level --
Details:
	All players: 1 total; [class_746['Pigman_Delta'/220, l='ClientLevel', x=-541.50, y=64.00, z=-205.50]]
	Chunk stats: Client Chunk Cache: 841, 529
	Level dimension: minecraft:overworld
	Level spawn location: World: (-540,63,-202), Chunk: (at 4,3,6 in -34,-13; contains blocks -544,0,-208 to -529,255,-193), Region: (-2,-1; contains chunks -64,-32 to -33,-1, blocks -1024,0,-512 to -513,255,-1)
	Level time: 63 game time, 63 day time
	Server brand: fabric
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.class_638.method_8538(class_638.java:449)
	at net.minecraft.class_310.method_1587(class_310.java:2239)
	at fudge.notenoughcrashes.mixinhandlers.InGameCatcher.handleClientCrash(InGameCatcher.java:28)
	at net.minecraft.class_310.modify$bgm000$onCrash(class_310.java:7412)
	at net.minecraft.class_310.method_1514(class_310.java:704)
	at net.minecraft.client.main.Main.main(Main.java:215)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:226)
	at net.fabricmc.loader.launch.knot.Knot.launch(Knot.java:146)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:28)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at link.infra.jumploader.Jumploader.onLoad(Jumploader.java:171)
	at cpw.mods.modlauncher.TransformationServiceDecorator.onLoad(TransformationServiceDecorator.java:53)
	at cpw.mods.modlauncher.TransformationServicesHandler.lambda$loadTransformationServices$11(TransformationServicesHandler.java:131)
	at cpw.mods.modlauncher.TransformationServicesHandler$$Lambda$58/1388278453.accept(Unknown Source)
	at java.util.HashMap$Values.forEach(HashMap.java:972)
	at cpw.mods.modlauncher.TransformationServicesHandler.loadTransformationServices(TransformationServicesHandler.java:131)
	at cpw.mods.modlauncher.TransformationServicesHandler.initializeTransformationServices(TransformationServicesHandler.java:56)
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:76)
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:66)
-- System Details --
Details:
	Minecraft Version: 1.16.5
	Minecraft Version ID: 1.16.5
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 2174181152 bytes (2073 MB) / 3652714496 bytes (3483 MB) up to 8351383552 bytes (7964 MB)
	CPUs: 8
	JVM Flags: 5 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx8960m -Xms256m -XX:PermSize=256m
	Mixins in Stacktrace: 
		net.minecraft.class_1140:
			svenhjol.charm.mixin.SoundSystemMixin (charm.mixins.json)
			eu.midnightdust.visualoverhaul.mixin.MixinSoundSystem (visualoverhaul.mixins.json)
			svenhjol.charm.mixin.accessor.SoundSystemAccessor (charm.mixins.json)
		net.minecraft.class_1144:
			svenhjol.charm.mixin.accessor.SoundManagerAccessor (charm.mixins.json)
			net.fabricmc.fabric.mixin.resource.loader.client.KeyedResourceReloadListenerClientMixin (fabric-resource-loader-v0.mixins.json)
		net.minecraft.class_1142:
			svenhjol.charm.mixin.MusicTrackerMixin (charm.mixins.json)
		net.minecraft.class_310:
			net.fabricmc.fabric.mixin.command.client.MinecraftClientMixin (fabric-command-api-v1.mixins.json)
			top.theillusivec4.polymorph.loader.mixin.core.MinecraftClientAccessor (polymorph.mixins.json)
			ladysnake.requiem.mixin.client.inventory.MinecraftClientMixin (mixins.requiem.client.json)
			ladysnake.requiem.mixin.client.remnant.MinecraftClientMixin (mixins.requiem.client.json)
			paulevs.betternether.mixin.client.MinecraftClientMixin (betternether.mixins.client.json)
			net.fabricmc.fabric.mixin.screen.MinecraftClientMixin (fabric-screen-api-v1.mixins.json)
			net.fabricmc.fabric.mixin.event.interaction.MixinMinecraftClient (fabric-events-interaction-v0.mixins.json)
			vazkii.patchouli.mixin.client.MixinMinecraftClient (patchouli.mixins.json)
			net.fabricmc.fabric.mixin.networking.accessor.MinecraftClientAccessor (fabric-networking-api-v1.mixins.json)
			com.terraformersmc.campanion.mixin.client.MixinMinecraftClient (campanion.mixins.json)
			svenhjol.charm.mixin.MinecraftClientMixin (charm.mixins.json)
			me.shedaniel.cloth.mixin.client.events.MixinMinecraftClient (cloth-client-events-v0.mixins.json)
			fudge.notenoughcrashes.mixins.client.MixinMinecraftClient (notenoughcrashes.mixins.json)
			com.minenash.seamless_loading_screen.mixin.MinecraftClientMixin (seamless_loading_screen.mixins.json)
			net.fabricmc.fabric.mixin.registry.sync.client.MixinMinecraftClient (fabric-registry-sync-v0.mixins.json)
			io.engi.fabricmc.lib.mixin.MixinMinecraftClient (engilib.mixins.json)
			com.rdvdev2.disablecustomworldsadvice.mixin.MixinMinecraftClient (disable_custom_worlds_advice.mixins.json)
			ladysnake.requiem.mixin.client.possession.MinecraftClientMixin (mixins.requiem.client.json)
			fudge.notenoughcrashes.mixins.client.CatchInitMInecraftClientMixin (notenoughcrashes.fabric.mixins.json)
			me.shedaniel.architectury.mixin.fabric.client.MixinMinecraft (architectury.mixins.json)
			svenhjol.charm.mixin.accessor.MinecraftClientAccessor (charm.mixins.json)
			io.github.foundationgames.sandwichable.mixin.MinecraftClientMixin (sandwichable.mixins.json)
			ladysnake.satin.mixin.client.event.MinecraftClientMixin (mixins.satin.client.json)
			appeng.mixins.MinecraftClientAccessor (appliedenergistics2.mixins.json)
			net.fabricmc.fabric.mixin.event.lifecycle.client.MinecraftClientMixin (fabric-lifecycle-events-v1.mixins.json)
		net.minecraft.client.main.Main:
			fudge.notenoughcrashes.mixins.client.MixinMain (notenoughcrashes.fabric.mixins.json)
			io.github.ultimateboomer.smoothboot.mixin.client.MainMixin (smoothboot.mixins.json)
	Suspected Mods: Charm (charm), Fabric Loader (fabricloader)
	Fabric Mods: 
		adorn: Adorn 1.13.0+1.16.5
		alloy_forgery: Alloy Forgery 1.0.8
		angerable-patch: Angerable Patch 1.1.0-1.16.4
		antiqueatlas: Antique Atlas 5.4.4-fabric
		appletreesrev: Apple Trees Revived 1.0
		appliedenergistics2: Applied Energistics 2 8.2.0-alpha.3
		architectury: Architectury 1.5.105
		artifacts: Artifacts 3.1.0+fabric
		artofalchemy: Art of Alchemy: Memoriam 1.0.0-rc4+1.16.4
		astromine: Astromine 1.11.5+fabric-1.16.5
		astromine-core: Astromine: Core 1.11.5+fabric-1.16.5
		astromine-discoveries: Astromine: Discoveries 1.11.5+fabric-1.16.5
		astromine-foundations: Astromine: Foundations 1.11.5+fabric-1.16.5
		astromine-technologies: Astromine: Technologies 1.11.5+fabric-1.16.5
		astromine-transportations: Astromine: Transportations 1.11.5+fabric-1.16.5
		autoconfig1u: Auto Config v1 Updated 3.3.1
		automated_crafting: Automated Crafting 1.3.21+MC1.16.2-1.16.5
		beaconoverhaul: Beacon Overhaul 1.3.0+1.16
		betterbiomeblend: Better Biome Blend 1.16.4-1.1.3-fabric
		bettercaves: YUNG's Better Caves 1.16.5-1.1
		bettermineshafts: YUNG's Better Mineshafts 1.16.4-1.0.1
		betternether: Better Nether 5.0.7
		biomemakeover: Biome Makeover 1.16.4-1.2.12
		biomepicker: Biome Picker 1.1
		bitsandchisels: BitsAndChisels 2.1.4
		blade: Blade 2.0.0
		bonappetit: Bon Appétit 0.8.5-3
		caelus: Caelus API 0.0.15-1.16.4
		campanion: Campanion 1.3.5
		cardinal-components-base: Cardinal Components API (base) 2.7.13
		cardinal-components-block: Cardinal Components API (blocks) 2.7.10
		cardinal-components-chunk: Cardinal Components API (chunks) 2.7.10
		cardinal-components-entity: Cardinal Components API (entities) 2.7.13
		cardinal-components-item: Cardinal Components API (items) 2.7.10
		cardinal-components-level: Cardinal Components API (world saves) 2.7.10
		cardinal-components-scoreboard: Cardinal Components API (scoreboard) 2.7.13
		cardinal-components-util: Cardinal Components API (utilities) 2.7.10
		cardinal-components-world: Cardinal Components API (worlds) 2.7.12
		chainmail: Chainmail 0.5.0
		charm: Charm 2.3.2
		cinderscapes: Cinderscapes 1.3.3
		cloth-basic-math: Cloth Basic Math 0.5.1
		cloth-client-events-v0: Cloth Client Events v0 1.5.47
		cloth-config2: Cloth Config v4 4.11.18
		cloth-datagen-api-v1: Cloth Datagen v1 1.4.9
		cloth-durability-bar-api-v1: Cloth Durability Bar API v1 1.4.9
		cloth-dynamic-registry-api-v1: Cloth Dynamic Registry API v1 1.2.1
		com_electronwill_night-config_core: core 3.6.2
		com_electronwill_night-config_toml: toml 3.6.2
		com_github_shevek_parallelgzip: parallelgzip master-SNAPSHOT
		com_moandjiezana_toml_toml4j: toml4j 0.7.2
		com_udojava_evalex: EvalEx 2.5
		cosmetic-armor: Cosmetic Armor 1.0.0
		cotton-config: Cotton Config 1.0.0-rc.7
		cotton-logging: Cotton Logging 1.0.0-rc.4
		creeperspores: Creeper Spores 1.5.0
		crowdin-translate: CrowdinTranslate 1.2
		ctm: ConnectedTexturesMod for Fabric 0.4.0
		cullleaves: Cull Leaves 2.1.0
		cullparticles: Cull Particles 2.0
		curioofundying: Curio of Undying 1.1.1-1.16.5
		curios: Curios API 0.0.13-1.16.5
		curiouselytra: Curious Elytra 1.1.1-1.16.5
		curiousshulkerboxes: Curious Shulker Boxes 1.1.1-1.16.5
		dawn: Dawn API 1.7
		desolation: Desolation 1.1.1
		direbats: Direbats 1.1.0+1.16.5-fabric
		disable_custom_worlds_advice: Disable Custom Worlds Advice 1.2
		dropz: Dropz 1.1.3
		dynamo_api: Dynamo API 1.0.0+1.16
		enchant_giver: Enchant Giver 1.0.3
		engilib: EngiLib 1.0.0+1.16.4
		expandedstorage: ExpandedStorage 5.6.33
		extraorigins: Extra Origins 1.16.5-10
		eymbra: Eymbra's Prehistoric Mod 1.0.0
		fabric: Fabric API 0.32.5+1.16
		fabric-api-base: Fabric API Base 0.2.1+9354966b7d
		fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.0.0+dc716ea17d
		fabric-biome-api-v1: Fabric Biome API (v1) 3.1.1+ca58154a7d
		fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.5+ca58154a7d
		fabric-command-api-v1: Fabric Command API (v1) 1.1.1+351679a77d
		fabric-commands-v0: Fabric Commands (v0) 0.2.2+ca58154a7d
		fabric-containers-v0: Fabric Containers (v0) 0.1.11+9354966b7d
		fabric-content-registries-v0: Fabric Content Registries (v0) 0.2.1+ca58154a7d
		fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.1.3+ca58154a7d
		fabric-dimensions-v1: fabric-dimensions-v1 2.0.6+9354966b7d
		fabric-entity-events-v1: Fabric Entity Events (v1) 1.0.3+ca58154a7d
		fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.2+ca58154a7d
		fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.1+ca58154a7d
		fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.6+ca58154a7d
		fabric-item-api-v1: Fabric Item API (v1) 1.2.1+ca58154a7d
		fabric-item-groups-v0: Fabric Item Groups (v0) 0.2.5+351679a77d
		fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.4+9354966b7d
		fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.1+ca58154a7d
		fabric-language-kotlin: Fabric Language Kotlin 1.5.0+kotlin.1.4.31
		fabric-language-scala: Fabric Language Scala 1.0.0
		fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 1.2.1+ca58154a7d
		fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.0.2+ca58154a7d
		fabric-mining-levels-v0: Fabric Mining Levels (v0) 0.1.3+ca58154a7d
		fabric-models-v0: Fabric Models (v0) 0.2.1+ca58154a7d
		fabric-networking-api-v1: Fabric Networking API (v1) 1.0.1+ca58154a7d
		fabric-networking-blockentity-v0: Fabric Networking Block Entity (v0) 0.2.8+ca58154a7d
		fabric-networking-v0: Fabric Networking (v0) 0.3.2+ca58154a7d
		fabric-object-builder-api-v1: Fabric Object Builder API (v1) 1.9.4+9354966b7d
		fabric-object-builders-v0: Fabric Object Builders (v0) 0.7.2+ca58154a7d
		fabric-particles-v1: Fabric Particles (v1) 0.2.4+ca58154a7d
		fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.7.4+ca58154a7d
		fabric-renderer-api-v1: Fabric Renderer API (v1) 0.4.1+ca58154a7d
		fabric-renderer-indigo: Fabric Renderer - Indigo 0.4.4+ca58154a7d
		fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 2.2.1+ca58154a7d
		fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.1.5+ca58154a7d
		fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 0.1.13+ca58154a7d
		fabric-rendering-v0: Fabric Rendering (v0) 1.1.2+ca58154a7d
		fabric-rendering-v1: Fabric Rendering (v1) 1.5.1+ca58154a7d
		fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.4.2+ca58154a7d
		fabric-screen-api-v1: Fabric Screen API (v1) 1.0.0+c045166c7d
		fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.1.5+9354966b7d
		fabric-structure-api-v1: Fabric Structure API (v1) 1.1.4+ca58154a7d
		fabric-tag-extensions-v0: Fabric Tag Extensions (v0) 1.1.1+ca58154a7d
		fabric-textures-v0: Fabric Textures (v0) 1.0.6+ca58154a7d
		fabric-tool-attribute-api-v1: Fabric Tool Attribute API (v1) 1.2.6+ca58154a7d
		fabricloader: Fabric Loader 0.11.3
		fallflyinglib: FallFlyingLib 1.1.0
		fermion: Fermion 2.1.191
		fermion-modkeys: Fermion Modifier Keys 1.10.218
		fiber: fiber 0.23.0-2
		fiber2cloth: Fiber To Cloth 3.1.0
		flamingo_ooo: Flamingo, oh, oh, oh... 1.0.4-MC1.16.3-fabric
		fluidphysics: Fluid Physics 1.4.0+fabric-1.16.4
		full_slabs: Full Slabs 2.0.0
		gbfabrictools: GBfabrictools 1.3.2+1.16.4
		geckolib3: Geckolib 3.0.27
		gentlefawn: GentleFawn 1.1.4-MC1.16.5-fabric
		gildednetherite: Gilded Netherite 1.0.0
		illuminations: Illuminations 1.4.6
		jankson: Jankson 3.0.1+j1.2.0
		java: Java HotSpot(TM) 64-Bit Server VM 8
		jumploader: Jumploader 2.1.3
		kirin: Kirin UI 1.7-1.16.2
		lazydfu: LazyDFU 0.1.2
		libblockattributes_core: LibBlockAttributes (Core) 0.8.7
		libblockattributes_fluids: LibBlockAttributes (Fluids) 0.8.7
		libblockattributes_items: LibBlockAttributes (Items) 0.8.7
		libcd: LibCapableData 3.0.3+1.16.3
		libgui: LibGui 3.3.3+1.16.5
		magna: Magna 1.4.3-1.16.2
		maybe-data: Maybe data 1.0.0-1.16.2
		mechanicaltech: Mechanical Tech 0.3.0+1.16
		micalibria: Micalibria 1.0.2
		minecraft: Minecraft 1.16.5
		mixintrace: MixinTrace 1.0.0
		moborigins: Mob Origins 1.3.1
		moretotems: More Totems 2.7.3
		mtca: More Totems Curios Addon 1.0.0
		multi_item_lib: Multi Item Lib 1.2.0
		mythicmetals: Mythic Metals 0.9.9
		netherite_plus: Netherite Plus Mod 1.4.2-1.16.5
		netheritehorsearmor: Netherite Horse Armor 0.4.3-1.16.3
		nomadbooks: Nomad Books 1.0.1
		notenoughcrashes: Not Enough Crashes 3.1.8
		org_apache_commons_commons-compress: commons-compress 1.19
		org_jetbrains_kotlin_kotlin-reflect: kotlin-reflect 1.4.31
		org_jetbrains_kotlin_kotlin-stdlib: kotlin-stdlib 1.4.31
		org_jetbrains_kotlin_kotlin-stdlib-jdk7: kotlin-stdlib-jdk7 1.4.31
		org_jetbrains_kotlin_kotlin-stdlib-jdk8: kotlin-stdlib-jdk8 1.4.31
		org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm: kotlinx-coroutines-core-jvm 1.4.2
		org_jetbrains_kotlinx_kotlinx-coroutines-jdk8: kotlinx-coroutines-jdk8 1.4.2
		org_jetbrains_kotlinx_kotlinx-serialization-core-jvm: kotlinx-serialization-core-jvm 1.1.0
		org_jetbrains_kotlinx_kotlinx-serialization-json-jvm: kotlinx-serialization-json-jvm 1.1.0
		org_joml_joml: joml 1.10.0
		org_tukaani_xz: xz 1.8
		origins: Origins 0.6.2
		origins-classes: Origins: Classes 1.1.1
		originsplus: Origins Plus 0.0.2
		oro_config: OroArmor Config 2.0.0
		patchouli: Patchouli 1.16.4-48-FABRIC
		pehkui: Pehkui 1.9.0+21w10a
		piglib: Piglib 1.0.1
		pigpoop: Pig Poop 1.1.3
		playerabilitylib: Pal 1.2.1
		pling: Pling 1.3.0
		polymorph: Polymorph 0.0.10-1.16.5
		potiondescriptions: Potion Descriptions fabric-1.1
		prehistoric: Prehistoric 1.0.0
		presencefootsteps: Presence Footsteps r29+1.16.4
		rayon: Rayon 1.1.4
		reach-entity-attributes: Reach Entity Attributes 1.1.1
		redbits: Red Bits 1.8.0
		repurposed_structures: Repurposed Structures 1.16.5-1.9.0
		requiem: Requiem 1.5.1
		requiemapi: Requiem-API 1.5.1
		riverredux: River Redux 0.1.6
		roughlyenoughitems: Roughly Enough Items 5.11.188
		roughlyenoughitems-api: REI (API) 5.11.188
		roughlyenoughitems-default-plugin: REI (Default Plugin) 5.11.188
		roughlyenoughitems-runtime: REI (Runtime) 5.11.188
		sakurarosea: Sakura Rosea 1.6.0-MC1.16.3-fabric
		sandwichable: Sandwichable 1.2-beta5
		satin: Satin 1.5.1
		seamless_loading_screen: Seamless Loading Screen 1.3.2
		seasons: Fabric Seasons 1.1.1-BETA
		simplyplatinum: Simply Platinum 2.2
		smithee: Smithee 0.2.3
		smoothboot: Smooth Boot 1.16.5-1.6.0
		smoothscrollingeverywhere: Smooth Scrolling Everywhere 3.0.3-unstable
		stacc: Stacc 1.0.1
		step-height-entity-attribute: Step Height Entity Attribute 1.0.0
		stepup: StepUp 1.16.5-fabric0.30.0-1.1
		stitchedsnow: Stiched Snow 1.0.1
		stoneholm: Stoneholm 1.1.0
		team_reborn_energy: Energy 0.1.1
		terraform-biome-builder-api-v1: Terraform Biome Builder API (v1) 1.0.4
		terraform-config-api-v1: Terraform Config API (v1) 1.0.3
		terraform-dirt-api-v1: Terraform Dirt API (v1) 1.1.3
		terraform-overworld-biome-extensions-api-v1: Terraform Overworld Biome Extensions API (v1) 1.0.3
		terraform-shapes-api-v1: Terraform Shapes API (v1) 1.0.4
		terraform-surfaces-api-v1: Terraform Surfaces API (v1) 1.0.3
		terraform-tree-api-v1: Terraform Tree API (v1) 1.0.5
		terraform-wood-api-v1: Terraform Wood API (v1) 1.0.3
		terrestria: Terrestria 2.2.0
		textile_backup: Textile Backup 2.1.0-prev-1.16.4
		the_bumblezone: The Bumblezone - Fabric 1.16.5-2.3.0
		things: Things 0.1
		transporter: Transporter 1.0.3
		traverse: Traverse 3.3.2
		trinkets: Trinkets 2.6.7
		untitledduckmod: Untitled Duck Mod 0.1.1
		vanguard: Vanguard 1.0.5
		veinmining: Vein Mining 0.0.7-1.16.5
		visualoverhaul: VisualOverhaul 3.1.0
		voyager: Voyager 1.0.0
		wild_explorer: Wild Explorer 1.3.2
		wrenchable: Wrenchable 1.0.0+1.16.1
		xlpackets: XLPackets 1.1
		yungsapi: YUNG's API 1.16.5-Fabric-2
	Patchouli open book context: 
		Open book: things:things_guide
		Current page spread: 0
	Launched Version: Jumploader
	Backend library: LWJGL version 3.2.2 build 10
	Backend API: Intel(R) UHD Graphics GL version 4.6.0 - Build 26.20.100.6911, Intel
	GL Caps: Using framebuffer using OpenGL 3.0
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'
	Type: Client (map_client.txt)
	Graphics mode: fancy
	Resource Packs: Fabric Mods, visualoverhaul/coloredwaterbucket, cullleaves/smartleaves, visualoverhaul/fancyfurnace, visualoverhaul/nobottles
	Current Language: English (US)
	CPU: 8x Intel(R) Core(TM) i7-10510U CPU @ 1.80GHz
	Client Crashes Since Restart: 1
	Integrated Server Crashes Since Restart: 0`

**Comment by pm065** [comment]
It seems to be something to do with sound? Possibly Charmonium related? (probably not tbh)
