### ISSUE TITLE
Do you plan to make decorative villages in 1.16 ?

### ISSUE THREAD

**Issue by Krampus69** [svenhjol/Charm#528]
Hello,
I love your mod. We've been playing with it for a long time with my friends on 1.12.2.
But now, we've updated to 1.16 and we don't see the decoration in villages. 
Are you planning to bring them back in 1.16 ?

**Comment by Coranthes** [comment]
Things are being done differently in 1.16.  There are no longer decorations in the villages.  What we have done is add two new villagers, beekeepers and lumberjacks.  Both have their own custom houses which also vary depending on the biome they are located in.
