### ISSUE TITLE
Turn on damage for tamed animals?

### ISSUE THREAD

**Issue by DrSnijder** [svenhjol/Charm#538]
Versions
* Charm version - e.g. `2.3.2`
* Minecraft version 1.16.5

Description
I need to be able to damage my pets for the Bewitchment mod and respawnable pets. Is there a way to fix this?

Thanks!

**Comment by FynnWaelsing** [comment]
In the Charm config file, set "TamedAnimalsNoDamage enabled" to false.

**Comment by DrSnijder** [comment]
> In the Charm config file, set "TamedAnimalsNoDamage enabled" to false.

Hey thank you! I have been looking for the config file but can't find it. Could you tell me where it is?

**Comment by FynnWaelsing** [comment]
Wherever your minecraft instance is installed, there should be a folder called "config" that contains the config files for all the mods you have installed. Charm's file will be a TOML file called "charm-common." You can open it in any basic text editor, like Notepad.

**Comment by DrSnijder** [comment]
It worked! Me and my server thanks you!
