### ISSUE TITLE
Crimson and warped crates in mineshafts

### ISSUE THREAD

**Issue by saltyseadoggo** [svenhjol/Charm#541]
Versions
* Charm version - 2.3.2
* Minecraft version - 1.16.5

Description
Abandoned Mineshafts can generate crimson and warped crates. This doesn't make sense, as crimson and warped are nether woods which are never seen in the overworld. One would expect that they would only generate overworld wood crates- at best, regular mineshafts would have only oak crates, and badlands mineshafts only dark oak, to match the wood their supports and bridges are made out of.

Optional: Steps To Reproduce
- Create a Caves type world of any biome.
- Run `/locate mineshaft`
- Enter spectator mode and explore the mineshaft. If you don't find any crimson or warped crates, repeat steps one and two.

Optional: Stacktrace/Screenshots
![2021-04-24_18 26 37](https://user-images.githubusercontent.com/69029346/115977324-b5f76c00-a52b-11eb-8a5a-dacd37b00f4d.png)
![2021-04-24_18 29 07](https://user-images.githubusercontent.com/69029346/115977325-b7c12f80-a52b-11eb-86cd-0591487a2155.png)
![2021-04-24_18 36 32](https://user-images.githubusercontent.com/69029346/115977366-2e5e2d00-a52c-11eb-9172-e8b98c89340e.png)

**Comment by svenhjol** [comment]
Agree this is out of place.
It's working in 1.17 and this ticket will be added to the 1.16 support board.
