### ISSUE TITLE
Charm overrides enchantment glint texture? 

### ISSUE THREAD

**Issue by BerkeTurkey** [svenhjol/Charm#542]
**Charm v2.3.2 Minecraft 1.16.5**
Normally I have a resource pack that changes the texture of the enchantment glint, but whenever I add in Charm it always reverts it back to the default texture. I've tried to disable removing potion glint and the tint enchantment but the texture is still the same regardless. Does Charm override the texture regardless of whether you have a resource pack or not?
![WithCharm](https://user-images.githubusercontent.com/83320283/116495217-794fab80-a870-11eb-9c90-55511fd494b7.png)
![Without Charm](https://user-images.githubusercontent.com/83320283/116495220-79e84200-a870-11eb-8d2b-5d0bd5b8d345.png)

**Comment by Teletin123** [comment]
i have the same problem (im using forge version but in the reforged github didnt fin any answers) did you find a solution? what did you do?
