### ISSUE TITLE
Compatibility Issue with Fabric API 0.34.1 ?

### ISSUE THREAD

**Issue by BrekiTomasson** [svenhjol/Charm#545]
Running `Charm Fabric v2.3.2` in Minecraft `v1.16.5`. Everything was working fine with `Fabric API v0.33.1`. Earlier today, I upgraded Fabric API to the latest release, `v0.34.1` and started getting crashes on launch. Changing back to `v0.33.1` fixed the crashing issue.

https://paste.ee/p/w2FM2 for the crashlog.

**Comment by RDKRACZ** [comment]
This is caused by Cardinal Components API. Update it as they already fixed the issue.

**Comment by BrekiTomasson** [comment]
I don't have that installed, so it must be included through one of my other mods. I'll see if I can figure out which one. Thanks!
