### ISSUE TITLE
Charm's MusicImprovements causes players to get stuck when going through a Nether Portal

### ISSUE THREAD

**Issue by itsNordLord** [svenhjol/Charm#548]
**Versions**
* Charm version - 2.3.2
* Charmonium version - 2.3.2
* Minecraft version - 1.16.5

**Description**
Sometimes, when going through a Nether Portal, players will get stuck and become unable to move. Disconnecting and reconnecting fixes them. Going into the client's `latest.log` shows only an error related to Charm's MusicImprovements. 

**Stacktrace/Screenshots**
https://paste.gg/p/anonymous/7c65751633e7480cbb41df1ec5c7672f

**Comment by PkunkArilou** [comment]
Getting exactly the same problem, same line of code causing the issue. 
However, only when I'm running the Music Duration Reducer mod.

Here: https://www.curseforge.com/minecraft/mc-mods/music-duration-reducer
