### ISSUE TITLE
zombie villagers displaying missing textures

### ISSUE THREAD

**Issue by Armokthespideroverlord** [svenhjol/Charm#560]
Versions
* Charm version - latest fabric 1.16.5 version
* Minecraft version - 1.16.5

Description
For some reason some zombie villagers are displaying missing textures, from what I can tell this is the only mod that touches them here. It's probably whatever the other villager this mod adds in besides the beekeeper, as the beekeeper seems to work fine

Optional: Steps To Reproduce
assuming this isn't an issue exclusive to me only, you should also notice this when spawning in zombie villagers/encountering them

Optional: Stacktrace/Screenshots
![missing texture](https://user-images.githubusercontent.com/30275515/119590834-85f9ed80-bda3-11eb-97e7-a0777a9d16dc.PNG)

**Comment by svenhjol** [comment]
Tested, working in 1.17. Moving to 1.16 support

**Comment by Armokthespideroverlord** [comment]
if it's of any help, I'm also running this mod with optifine, but I find it doubtful that it's behind this

**Comment by Coranthes** [comment]
The only other villager Charm adds is the lumberjack, and it doesn't have a hat, like in the image.
