### ISSUE TITLE
Modmenu options support.

### ISSUE THREAD

**Issue by The-Gmann** [svenhjol/Charm#562]
Please add support for customizing the mod, i really like it, but i wish i could disable the mob variety feature and a couple of others. This is even a bigger bummer since i had to get rid of Charmonium as well. Talking about 1.16.5 Fabric version of the mod.

**Comment by Coranthes** [comment]
Charm is modular, so every feature can be disabled as you desire.  You can find the charm.toml file in the config folder.

**Comment by Emerbot284** [comment]
I cannot find this config folder, several people have mentioned there is one but I don't seem to have it.

**Comment by Emerbot284** [comment]
You know what never mind I found it (feel a bit stupid for this one). now here is a better question how do I change it for aa server.

**Comment by The-Gmann** [comment]
> Charm is modular, so every feature can be disabled as you desire. You can find the charm.toml file in the config folder.

It'd be more user-friendly if it could be accessed through modmenu.

**Comment by Coranthes** [comment]
@svenhjol  I'll take a look at this for 1.17 and see what it would take for me to do it, but I make no promises.
