### ISSUE TITLE
Charm Fabric Crash w/o report issue

### ISSUE THREAD

**Issue by emeraldran** [svenhjol/Charm#574]
Read me first!
1. Is your issue about the Forge version of Charm? Please report your issue here: https://github.com/svenhjol/CharmForge/issues
2. We don't support OptiFabric! Please check that the problem still occurs if you remove OptiFabric from your mods.
3. Don't use the bug report to suggest new features or behavior.

Versions
* Charm version - e.g. `2.2.0` 2.2.1
* Minecraft version - e.g. `1.6.4` 1.17

Description
Write a clear description about what is going wrong.
So I downloaded and put it in mods folder. the instance it loads on the play bar it crashes. 
but then I look into crash reports and no reports show. so I have a paste bin launcher log report.
I don't know if the other mods impact it
Optional: Steps To Reproduce
This helps us to repeat the issue you're having.

Optional: Stacktrace/Screenshots 
![image](https://user-images.githubusercontent.com/83981272/121567628-6b02bc80-c9e4-11eb-8581-03b065abf20c.png)
![image](https://user-images.githubusercontent.com/83981272/121568064-e1072380-c9e4-11eb-81eb-6f846e4a42f0.png)

By adding a stacktrace (e.g. pastebin link) and/or screenshots it helps us understand and fix the problem.
https://pastebin.com/Q1YCqufs

**Comment by FynnWaelsing** [comment]
Are you playing on a 1.17 snapshot, or the full release? The version of Charm that you are using is a snapshot, not the final release version.

**Comment by Magnetron64** [comment]
I have the same issue too on the final release

**Comment by FynnWaelsing** [comment]
Do you mean the final release of 1.17 or the final release of Charm? Because the version of Charm you noted above is not the final version for 1.17

**Comment by FynnWaelsing** [comment]
That version of Charm is not compatible with the final version of 1.17 MC, only that snapshot. Please wait until a new version of Charm is released
