### ISSUE TITLE
Placing a modded sign on top of a barrel crashes the game and locks the world

### ISSUE THREAD

**Issue by BlueDemonTR** [svenhjol/Charm#576]
Versions
* Charm version - -3.1.1-beta
* Minecraft version - 1.17

Description
If you place a sign on top of a barrel the game crashes and you can no longer access the world
Couldn't reproduce but after the crash happened the compass texture seemed to be corrupted too as I couldn't see the search icon on the creative search button and everytime I would try to open the search menu my game would crash

Reproduce:
Place down a barrel looking up
Get an ebony sign
Shift-Click and try to place that sign on top the barrel

[crash-2021-06-16_23.51.27-client.txt](https://github.com/svenhjol/Charm/files/6665817/crash-2021-06-16_23.51.27-client.txt)
[crash-2021-06-16_23.52.00-client.txt](https://github.com/svenhjol/Charm/files/6665818/crash-2021-06-16_23.52.00-client.txt)
[crash-2021-06-16_23.52.09-client.txt](https://github.com/svenhjol/Charm/files/6665819/crash-2021-06-16_23.52.09-client.txt)
[crash-2021-06-16_23.52.51-client.txt](https://github.com/svenhjol/Charm/files/6665820/crash-2021-06-16_23.52.51-client.txt)
[crash-2021-06-16_23.53.00-client.txt](https://github.com/svenhjol/Charm/files/6665821/crash-2021-06-16_23.53.00-client.txt)

**Comment by BlueDemonTR** [comment]
Upon further inspection I've realized this glitch is caused by https://www.curseforge.com/minecraft/mc-mods/expanded-storage-fabric. But the crash doesn't happen with vanilla signs on barrels

**Comment by svenhjol** [comment]
Thanks. Cannot repeat on Charm alone, flagging this as a compatibility issue with expanded storage

**Comment by svenhjol** [comment]
Please replace your local Charm jar with this version and try opening your world: https://github.com/svenhjol/Charm/releases/download/3.1.2/charm-fabric-1.17-3.1.2.jar

**Comment by NinjaPhenix** [comment]
Fix works using AoF4 0.0.2 + Charm
