### ISSUE TITLE
Instant Damage and Instant Healing potions can be duplicated using Casks

### ISSUE THREAD

**Issue by BlueDemonTR** [svenhjol/Charm#579]
Charm version - -3.1.2
    Minecraft version - 1.17

Description
If you put one Instant Harming/Health Potion and then put 63 water bottles inside you can get 64 Instant Health/Harming Potions out of it. This also allows you to add any potion Instant Health/Harming with 100% power just by losing 1/64 of the other potions' duration

**Comment by svenhjol** [comment]
Yeah, good catch. Instant effect potions make no sense with the cask dilution system.

**Comment by svenhjol** [comment]
Could you try this jar? I've changed cask behavior to disallow instant effect potions. https://github.com/svenhjol/Charm/releases/download/3.1.3/charm-fabric-1.17-3.1.3.jar
