### ISSUE TITLE
Always creating charm.backup.cfg

### ISSUE THREAD

**Issue by BrisingrAerowing** [svenhjol/Charm#58]
The mod always creates the backup config file, even if it is not needed (i.e. already generated the new version). Having unneeded files in the config directory triggers my OCD a bit.

**Comment by svenhjol** [comment]
Odd. Can you confirm that in your charm.cfg you see a `~CONFIG_VERSION` please?

**Comment by BrisingrAerowing** [comment]
Yup. There is.

**Comment by svenhjol** [comment]
This has been fixed (I hope) in Charm 1.1.5. No longer does backup check.
