### ISSUE TITLE
Charm Causing Issues Server Side

### ISSUE THREAD

**Issue by MrSaturn07** [svenhjol/Charm#580]
Versions
* Charm version - 1.17 -3.1.2
* Minecraft version - 1.17

Description
Charm works perfectly on client side, but when I try to launch my server with Charm installed it won't work. I keep getting an error in the terminal saying "Caused by: java.lang.NoClassDefFoundError: net/minecraft/class_4722" Its running on a Debian server if that makes a difference. I am running a couple of mods other than charm and those are REI,  The Fabric API, and Architecture API.  I am also running Lithium on the side for server performance.
![Issue 1](https://user-images.githubusercontent.com/66644553/122429522-757b0400-cf58-11eb-8a83-b58ca2493ad5.PNG)
![Issue 2](https://user-images.githubusercontent.com/66644553/122429558-7b70e500-cf58-11eb-9823-c98bc614865e.PNG)

**Comment by svenhjol** [comment]
Thanks, please try this jar and let me know if it fixes the problem: https://github.com/svenhjol/Charm/releases/download/3.1.3/charm-fabric-1.17-3.1.3.jar

**Comment by MrSaturn07** [comment]
> Thanks, please try this jar and let me know if it fixes the problem: https://github.com/svenhjol/Charm/releases/download/3.1.3/charm-fabric-1.17-3.1.3.jar

Thank you, the server is now running. And I can connect to the server without any issue. Thanks.
