### ISSUE TITLE
Crash with optifabric 1.17

### ISSUE THREAD

**Issue by Magnetron64** [svenhjol/Charm#581]
Version:
- Charm 3.1.2-beta
- Optifabric 1.11.1
- Minecraft 1.17

Description:
Game crashes on launch.

Reproduce:
Install the two mods and attempt to launch instance

Crash log;
[crash.txt](https://github.com/svenhjol/Charm/files/6671473/crash.txt)

**Comment by FynnWaelsing** [comment]
As per the readme in the issue report template: "2. We don't support OptiFabric! Please check that the problem still occurs if you remove OptiFabric from your mods."
