### ISSUE TITLE
Coral Squid Animation Error

### ISSUE THREAD

**Issue by CosmicParticl** [svenhjol/Charm#582]
Versions
* Charm version - 3.1.3
* Minecraft version -1.17

Description
Coral Squids are not animated correctly, and are always facing upward

Steps To Reproduce: Spawn a Coral Squid

![2021-06-17_18 53 50](https://user-images.githubusercontent.com/54153712/122482534-bdbd1500-cf9e-11eb-8c03-7ead83246a34.png)

**Comment by svenhjol** [comment]
Please test in https://github.com/svenhjol/Charm/releases/download/3.1.6/charm-fabric-1.17-3.1.6.jar
