### ISSUE TITLE
Enchanting Table level not increasing on server

### ISSUE THREAD

**Issue by Watersfall** [svenhjol/Charm#586]
Versions
* Charm version - 3.0.7
* Minecraft version - 1.17

Description
The wood variant bookshelves don't affect the enchanting table on a dedicated server

**Comment by svenhjol** [comment]
Please test in https://github.com/svenhjol/Charm/releases/download/3.1.6/charm-fabric-1.17-3.1.6.jar

**Comment by Pretender8** [comment]
I've experienced this issue using 3.1.6. If there's anything needed to try and solve this, I'd be willing to try it.

**Comment by Watersfall** [comment]
Seems to work for me now

**Comment by Koota647** [comment]
Can you fix this in Fabric, version 2.3.2 to Minecraft 1.16.5? 
on my server I had to make a separate enchantment room with original bookshelves... Would like to take advantage of enchanting with your bookshelves.
