### ISSUE TITLE
Crate sealing has a number of issues

### ISSUE THREAD

**Issue by build2stone** [svenhjol/Charm#59]
Sealing a crate will return a sealed crate of a random wood-type
The resulting sealed crate is named the item name of the input crate.
Using shift-click to seal multiple crates at once always results in one sealed crate, but still uses up the input crates and iron ingots.

Additionally, a crate or sealed crate can be combined with any other item in an anvil, resulting in that same crate.

Mods used:
Charm 1.1.0
Forge 14.23.5.2838

**Comment by svenhjol** [comment]
Wow, I must have been drunk when I built this code. Thanks for the report

**Comment by svenhjol** [comment]
Will deploy fix in 1.1.1
