### ISSUE TITLE
Bookshelves dont increase enchantment level

### ISSUE THREAD

**Issue by Magnetron64** [svenhjol/Charm#591]
Versions
* Charm version - 3.1.6
* Minecraft version - 1.17

Description
Bookshelves dont increase the enchantment level on a server

**Comment by svenhjol** [comment]
Please test in https://github.com/svenhjol/Charm/releases/download/3.1.6/charm-fabric-1.17-3.1.6.jar

**Comment by Magnetron64** [comment]
Thank you ! It works perfectly fine now.
