### ISSUE TITLE
Error in currently selected datapack because of Charm

### ISSUE THREAD

**Issue by Bazyliii** [svenhjol/Charm#593]
Versions
* Charm version - 3.1.6 Beta
* Minecraft version - 1.17

Description
After saving a world I can't join back into that world, because it is showing datapack error. I am not using any datapacks so that is strange.

Optional: Steps To Reproduce
1. Install fabric
2. Add Charm and Fabric Api to mods folder
3. Create world and save it
4. Leave world and try to come back

Optional: Stacktrace/Screenshots
There is a log from launcher:
https://pastebin.com/iLwQCqjG

**Comment by svenhjol** [comment]
Hi, please attach your `charm.toml` config file

**Comment by Bazyliii** [comment]
[charm.zip](https://github.com/svenhjol/Charm/files/6697190/charm.zip)

I couldn't send directly so there is an zip containing carm.toml file

**Comment by svenhjol** [comment]
Unable to repeat. Could you try removing Charm and see if creating a new world crashes when just using the fabric API? Also did you add the CavesAndCliffsPreview zip to datapacks when you created the world?

**Comment by Bazyliii** [comment]
I'm not using any datapacks, also I can create world but I cant access it after I log out. After removing Charm everything works good.

**Comment by svenhjol** [comment]
Could you send a zip file of your world save that is crashing and attach here please?

**Comment by Bazyliii** [comment]
[New World (1).zip](https://github.com/svenhjol/Charm/files/6705317/New.World.1.zip)

In addition I was only trying creative mode on flat world without structures. When I made normal Survival world everything was working fine. Soo bug only happens on superflat world types I think. Anyway I have send you a world that is crashing.

**Comment by svenhjol** [comment]
I didn't know it was superflat where it was occurring. I'm able to repeat it now.

**Comment by svenhjol** [comment]
@Bazyliii please test this jar https://github.com/svenhjol/Charm/releases/download/3.2.0/charm-fabric-1.17-3.2.0.jar

Should be able to open the world that no longer opens with datapack error, and also test that creating a new superflat world does not cause an error.

**Comment by Bazyliii** [comment]
Now it is working fine!
