### ISSUE TITLE
Regular bookshelfs/chests problem

### ISSUE THREAD

**Issue by s2pid0** [svenhjol/Charm#598]
Сan't create a regular bookshelf for crafting shelving

**Comment by FynnWaelsing** [comment]
Vanilla chests and bookshelves can be crafted by using more than one type of wood in the recipe.

**Comment by svenhjol** [comment]
There's a feature coming in 3.1.7 where you can convert a variant chest/bookshelf/barrel to a vanilla one on the crafting grid.

**Comment by s2pid0** [comment]
Thanks for the help!

ср, 23 июн. 2021 г. в 04:05, Clint ***@***.***>:
