### ISSUE TITLE
Totem of Preserving  Floats More Than It Should

### ISSUE THREAD

**Issue by KristenStuffs** [svenhjol/Charm#599]
Versions
* Charm version -  `3.1.6`
* Minecraft version - `1.7`

Description
When you die while in a boat (in my case guardians) the totem of preserving floats more than it should normally.

Steps To Reproduce
1) Go inside a boat
2) Die

![unknown](https://user-images.githubusercontent.com/37006202/123494542-37cc4a00-d5ee-11eb-859b-d67c27ffa266.png)

**Comment by svenhjol** [comment]
Yep I can repeat this. No idea why it spawns so high up!

**Comment by svenhjol** [comment]
Please test this version: https://github.com/svenhjol/Charm/releases/download/3.2.0/charm-fabric-1.17-3.2.0.jar
