### ISSUE TITLE
Unable to enchant items on anvil

### ISSUE THREAD

**Issue by Flaguna2** [svenhjol/Charm#601]
Title is self-explanatory. All item types with it's respective enchantments, even on creative.
MC ver. 1.17
Charm 3.2.0 (latest)
superflat world
mods installed: cloth config 5.0.34, modmenu 2.0.2, fabric kotlin 1.6.1+kotlin 1.5.1, fabri API 0.35.2+1.17
![Minecraft_ 1 17 - Singleplayer 26_06_2021 00_36_58](https://user-images.githubusercontent.com/86506105/123500849-4da23500-d617-11eb-8659-96afd6c0e582.png)

tell me if something's wrong

**Comment by svenhjol** [comment]
Confirmed
