### ISSUE TITLE
Open door crash the game

### ISSUE THREAD

**Issue by crest1993** [svenhjol/Charm#603]
Versions
* Charm version - 3.2.1
* Minecraft version - Fabric 1.17

Description
Opening a door give me this crash. works fine with previous version (3.1.6)

log:

https://pastebin.com/WaefCXpv

**Comment by jaded33** [comment]
same here

**Comment by svenhjol** [comment]
Please test this build: https://github.com/svenhjol/Charm/releases/download/3.2.2/charm-fabric-1.17-3.2.2.jar

**Comment by zakman9797** [comment]
3.2.2 works fixed the issue.
