### ISSUE TITLE
Adult sheep spawning with baby sheep wool

### ISSUE THREAD

**Issue by Flaguna2** [svenhjol/Charm#604]
Spawned sheep (naturally, via command or spawn egg) are spawned with baby sheep wool. Baby sheep spawn normally though.
Minecraft 1.17
Charm 3.2.2 (latest)
Refer to screenshot:
![Minecraft_ 1 17 - Singleplayer 26_06_2021 20_29_31](https://user-images.githubusercontent.com/86506105/123528448-682ee980-d6bd-11eb-800c-8c7b7041e501.png)

**Comment by Flaguna2** [comment]
After removing Charm, entering the same world on the SS, re-adding it and entering said world the issue seems to be fixed(?), even on new worlds.

**Comment by svenhjol** [comment]
That is weird

**Comment by svenhjol** [comment]
I can't repeat this. I'll leave the issue open and if you provide steps to repeat it, I'll fix it

**Comment by Flaguna2** [comment]
I'll write every step of exactly what happened. Keep in mind that no mod was neither added nor removed from the test.
1. Updated Charm to 3.2.2
2. Started a new world and played as usual
3. Noticed that sheep spawned sheared
4. Took a closer look and noticed that the adult sheeps had baby sheep wool model below them (refer to screenshot above)
5. Decided to remove Charm from the mod list.
6. Started the same world and noticed that the sheeps had normal wool around them.
7. Re-added Charm and started the same world.
8. Sheeps had normal wool.
9. Created about 5~ worlds to test if the issue was fixed.
10. Yes it was.
11. Now I'm unable to replicate said issue. Checked the latest.log to see if there was something wrong on it, but found nothing

**Comment by TBiscuit1** [comment]
it seems to be random, sometime when I load a world the sheep are ok, sometime they have baby wool model... strange

**Comment by BruhBruhBruhMoment** [comment]
apparently i just found this now but optifabric seems to be the problem. i wish sodium was out already

**Comment by RDKRACZ** [comment]
> i wish sodium was out already

Sodium is available for 1.17 for weeks now. It just hasn’t been uploaded to CF because Jelly has issues with her account.

**Comment by stop-x13** [comment]
If optifabric is installed, reloading the resources will cause this to happen
