### ISSUE TITLE
Azalea Wood Broken, When destroyed with Axe or hand on the recent update it does not give the block back.

### ISSUE THREAD

**Issue by Purdyboi** [svenhjol/Charm#606]
Read me first!
1. Is your issue about the Forge version of Charm? Please report your issue here: https://github.com/svenhjol/CharmForge/issues
2. We don't support OptiFabric! Please check that the problem still occurs if you remove OptiFabric from your mods.
3. Don't use the bug report to suggest new features or behavior.

Versions
* Charm version - e.g. `2.2.0`
* Minecraft version - e.g. `1.6.4`

Description
Write a clear description about what is going wrong.

Optional: Steps To Reproduce
This helps us to repeat the issue you're having.

Optional: Stacktrace/Screenshots
By adding a stacktrace (e.g. pastebin link) and/or screenshots it helps us understand and fix the problem.

**Comment by svenhjol** [comment]
Confirmed, will be fixed in 3.2.3
