### ISSUE TITLE
Bug on craft of other mods.

### ISSUE THREAD

**Issue by Gustavo891** [svenhjol/Charm#608]
* Charm version - charm-fabric-1.17-3.2.2-beta.jar

When I try to craft items from other mods with the Charm ones it doesn't work, like using the mod's chests to craft them, since when I try to craft the normal minecraft chest it doesn't work. Also with the copper nugget, I try to craft an Industrial Revolution item, but it doesn't work. If you can solve it, I appreciate it.

**Comment by Gustavo891** [comment]
The Industrial Revolution mod owner say this: This has to be fixed on Charm's end, they don't put their copper nugets on common tags

**Comment by svenhjol** [comment]
@Gustavo891 could you let me know in which common tag you need the copper nuggets?  I'm guessing `c:nuggets` but the owner of the IR mod should be able to confirm

**Comment by Sinapsa** [comment]
@svenhjol it's `c:copper_nuggets` as per [tutorial:tags [Fabric Wiki]](https://fabricmc.net/wiki/tutorial:tags)
