### ISSUE TITLE
Can't add filled maps to Atlas

### ISSUE THREAD

**Issue by erikabourque** [svenhjol/Charm#609]
Versions
* Charm version - 3.1.6
* Minecraft version - 1.17
* Fabric-loader version - 0.11.6-1.17
* Note: I tested on a clean installation (no other mods, only Charm and Fabric)

Description
When opening the Atlas menu (GUI), I am unable to add any maps except specifically empty maps.  It seems like a bug because you can remove maps from the atlas, and place them back immediately

Steps To Reproduce
1. Craft an atlas
2. Craft a map
3. Use the map so it is no longer blank (can be default scale size map)
4. Right click with Atlas in hand to open GUI
5. Cannot drop filled map into Atlas inventory or empty map image (see red rectangles)
![image](https://user-images.githubusercontent.com/15221081/123686030-56645800-d81d-11eb-8063-ebfeb4c77fa9.png)

**Comment by svenhjol** [comment]
It seems to be working for me following your steps. To eliminate a version problem could you download and test the latest jar? https://github.com/svenhjol/Charm/releases/download/3.2.2/charm-fabric-1.17-3.2.2.jar

**Comment by erikabourque** [comment]
I just finished testing with the jar you mentioned, and I still can't get it to work.  I can put in empty maps just fine, its the filled maps that it won't let me.  I'm using curseforge to launch minecraft with mods (Fabric API is 0.36.0+1.17) , if that changes anything (i dropped your jar into the mods folder manually)

**Comment by svenhjol** [comment]
Are you available on discord?

**Comment by erikabourque** [comment]
Yes I am, what's your discord?

**Comment by svenhjol** [comment]
@erikabourque svenhjol#5732

**Comment by erikabourque** [comment]
I made a group DM, i can't seem to add you as a friend to DM:
https://discord.gg/2HgYVWmr

**Comment by krokots** [comment]
How atlases are supposed to work?  I have the same problem (on charm-forge-1.16.5-2.3.2). I crafted an atlas and tried to put filled map at scale 4. It won't accept any filled maps, only empty ones. Then they are automatically converted to maps at scale 0 inside it, and atlas is at scale 0 too, can you scale it out?

**Comment by NonRidiculousAdjective** [comment]
Did this get a fix/solution? I still encountered this bug in Charm v4.4.4 on Fabric
