### ISSUE TITLE
Bound compass cannot be un-bound

### ISSUE THREAD

**Issue by build2stone** [svenhjol/Charm#61]
Binding a compass to a beacon seems to be permanent and makes it unusable in recipes that use compasses. A simple conversion recipe should work for now.

Mods used:
Charm 1.1.0
Forge 14.23.5.2838

**Comment by svenhjol** [comment]
Problem with conversion recipe because of NBT tags on the bound compass not being properly detected. Tried to implement another ingredient type but it's too complex for a quick fix, so instead I've added an XP-free anvil recipe of bound compass + iron = vanilla compass
