### ISSUE TITLE
this isn't a bug report, i just have no clue what tinted does and when i try and look up what it does, nothing has the answer, there is also no comment section on curse forge and there isn't a discord that i know of so i can't ask there, the wiki doesn't recognize that it is in the game, so i just want answers

### ISSUE THREAD

**Issue by Theiromia** [svenhjol/Charm#612]
Read me first!
1. Is your issue about the Forge version of Charm? Please report your issue here: https://github.com/svenhjol/CharmForge/issues
2. We don't support OptiFabric! Please check that the problem still occurs if you remove OptiFabric from your mods.
3. Don't use the bug report to suggest new features or behavior.

Versions
* Charm version - e.g. `2.2.0`
* Minecraft version - e.g. `1.6.4`

Description
Write a clear description about what is going wrong.

Optional: Steps To Reproduce
This helps us to repeat the issue you're having.

Optional: Stacktrace/Screenshots
By adding a stacktrace (e.g. pastebin link) and/or screenshots it helps us understand and fix the problem.

**Comment by BrekiTomasson** [comment]
When an item has the Tinted enchant, you can combine that item with a Dye in an Anvil in order to change the color of the Enchantment tint.
