### ISSUE TITLE
Can only craft vanilla chests

### ISSUE THREAD

**Issue by smiith72** [svenhjol/Charm#614]
Whenever i try to make a new chest with jungle or oak planks in the crafting table the only end result is the vanilla chest. I've tried using the recipe book to quick craft it and place the blocks manually. I do have a few mods installed but none that i can see that change chests. 
mods list: Charm, Simple Backpacks, Earth2Java, Vanilla Hammers, and Fabric API
MC Ver. 1.17
Fabric Ver. 1.17
Charm Ver. 1.17

**Comment by FynnWaelsing** [comment]
Can you please give the actual version of charm that you are using? Check the file itself. Same goes for the fabric version

**Comment by smiith72** [comment]
charm is 1.17-3.2.3
Fabric loader is 0.11.6-1.17

**Comment by smiith72** [comment]
ive gone into creative and i can make the following chests - Acacia, Spruce, Birch, and dark oak. The other planks give only give me the vanilla chest.

**Comment by wbsp9999** [comment]
I'm seeing the same problem w/ the 3.30 alpha you gave me yesterday. I saw that you've done a lot around the sorting in that branch though, so maybe that's taken care of this, but just wanted to give you a heads up.

**Comment by svenhjol** [comment]
Please try this beta2 and let me know if the recipes are fixed.
[charm-fabric-1.17-3.3.0-beta2.zip](https://github.com/svenhjol/Charm/files/6758986/charm-fabric-1.17-3.3.0-beta2.zip)

**Comment by wbsp9999** [comment]
Looks like that fixes it. One oddity...I have reveal all recipes config option turned off and it doesn't look like I'm getting any of the charm recipes when picking up the associated item (wood planks, etc). Manually crafting the item unlocks the recipe though.

**Comment by smiith72** [comment]
that update fixed it. Thanks for the help
