### ISSUE TITLE
Charm always crashes minecraft launcher when I try to run it

### ISSUE THREAD

**Issue by takoiiii** [svenhjol/Charm#616]
The title pretty much sums it up. I've redownloaded the mod several times, re-installed minecraft but nothing's working. I'm trying to use the mod with other mods, and for a few days before yesterday the mods altogether worked fine on a server I'm in. It started crashing when my screen was frozen while editing my minecraft controls (I think I accidentally changed the "inventory" control button into "=") and restarted the laptop via power button. There are four or five other people where the mods work together in a server, so I don't really know how to fix this or if its a bug or not

this is the message that pops up when it crashes:
![image](https://user-images.githubusercontent.com/86796981/124165331-a2a6d680-da6f-11eb-9446-2fb14fdbb5ad.png)

The mods I have: 
![image](https://user-images.githubusercontent.com/86796981/124166232-91aa9500-da70-11eb-9975-3e5cb628bf6a.png)

And this is the crash report:
![image](https://user-images.githubusercontent.com/86796981/124165433-c1a56880-da6f-11eb-90f0-d949a12a13a5.png)

**Comment by svenhjol** [comment]
Please could you attach your `charm.toml` config file?  I might be able to fix it up and send it back.

**Comment by takoiiii** [comment]
> Please could you attach your `charm.toml` config file? I might be able to fix it up and send it back.
Ooo thanks :0, the website says it doesn't support the file type- how do I attach it ? thanks

**Comment by svenhjol** [comment]
You can attach it to a comment here on the issue.  Drag the file to where it says at the bottom of the comment box.
![Screenshot from 2021-07-01 17-36-28](https://user-images.githubusercontent.com/26497903/124166908-ef4fd900-da92-11eb-9c64-63d99b7af131.png)

**Comment by takoiiii** [comment]
this message pops up when I do 
![image](https://user-images.githubusercontent.com/86796981/124168217-d6cfc680-da72-11eb-8fc9-29b1553f2b7c.png)

**Comment by svenhjol** [comment]
I think you might be able to add it to zip file and attach that?

**Comment by takoiiii** [comment]
thank you :D 
[charm.zip](https://github.com/svenhjol/Charm/files/6749963/charm.zip)

**Comment by svenhjol** [comment]
Unfortunately that file is 20kb of nothing!  I recommend deleting the `charm.toml` and letting it generate a new one, then try editing again.  We are thinking about adding ModMenu support in an upcoming version so hopefully making changes to config will be a bit easier.

![Uploading Screenshot from 2021-07-01 18-26-43.png…]()

**Comment by takoiiii** [comment]
okay, thank you. Do I send the new charms file ?

**Comment by svenhjol** [comment]
Delete the charm.toml config file and try restarting the game. If the game still crashes, then send your full crash log in the same way you attached the toml file - you might need to make a zip file.

**Comment by takoiiii** [comment]
Ohhh the game works now, thank you!
