### ISSUE TITLE
Compatibility issue with backslot (fabric)

### ISSUE THREAD

**Issue by ArkAngel-exe** [svenhjol/Charm#624]
Totem of preserving doesn't take into account items in other slots added by other mods. Backslot is one of these. Lost tools that were in the slots the mod adds.

Curseforge link for BackSlot: https://www.curseforge.com/minecraft/mc-mods/backslot

Charm Version - 3.2.3-beta
Minecraft Version - 1.17

**Comment by JRebella** [comment]
Also an issue with Inventorio https://www.curseforge.com/minecraft/mc-mods/inventorio
All items in the added slots are permanently lost, not even dropped to the ground
