### ISSUE TITLE
Question about achievement "Flower Power"

### ISSUE THREAD

**Issue by QiYiJun** [svenhjol/Charm#625]
Versions
* Charm version - 3.2.3
* Minecraft version - 1.17

Description
I want to complete the achievement "Flow Power".
I can use bucket on Moobloom to get milk, but i can't use bowl on Moobloom to get suspicious stew.
I don't know if that's how it was accomplished.

**Comment by svenhjol** [comment]
The moobloom must be pollinated by a bee before you can milk it.  You can tell when it's been pollinated because there will be a flower on its head
