### ISSUE TITLE
Compatibility issue with Grind Enchantment mod

### ISSUE THREAD

**Issue by Cntrldfusion** [svenhjol/Charm#630]
MC 1.17 Fabric API 0.36.0
Charm 3.3.0
Grind Enchantment 1.2.1 (also tested with 1.2.0)

I know that Charm includes code from the Grind Enchantment mod, but a conflict occurs when trying to use both.
Charm Extract Module enabled  / Grind Enchantment mod installed - grindstone acts like vanilla
Charm Extract Module disabled / Grind Enchantment mod installed - grindstone acts like vanilla
Charm Installed (extract enable) / Grind not installed - grindstone acts as Charm mod intended
Charm uninstalled / Grind installed - grindstone acts as Grind mod intended

Why is this important? Because the Grind Enchantment mod provides a feature which is not included in Charm which is being able to separate multiple enchantments on a book to separate books.  Sometimes you get enchanted items or books with multiple enchants that are not always wanted and the full Grind Enchantment mod allows them to be separated.

Not sure if you want to try and add the book feature from Grind Enchantment, or figure out why the grindstone defaults to vanilla actions when both mods are installed.

**Comment by svenhjol** [comment]
Can you test this jar please?  Charm disables its extract enchantment mixins when grindenchantments is present so it shouldn't conflict. https://github.com/svenhjol/Charm/releases/download/3.3.1/charm-fabric-1.17-3.3.1.jar

**Comment by Cntrldfusion** [comment]
That jar causes the client to crash on startup, even without Grind Enchantment installed.  Here's the log file.
[latest.log](https://github.com/svenhjol/Charm/files/6835584/latest.log)

**Comment by svenhjol** [comment]
Sorry, I left some dev tooling enabled in that build. Please try this one: https://github.com/svenhjol/Charm/releases/download/3.3.1/charm-fabric-1.17-3.3.1b2.jar

**Comment by Cntrldfusion** [comment]
Charm installed / Grind uninstalled - grindstone performs as intended by the Charm mod
Charm uninstalled / Grind installed - grindstone performs as intended by the Grind Enchantments mod
Charm installed / Grind installed  - grindstone will remove enchantments from items and books like vanilla, and it will allow a blank book now in the bottom slot, but it will not allow disenchant, as soon as a blank book is placed in the bottom slot an X appears on the process arrow, this happens when extract is set to either true or false in the Charm config file

So, at least now it allows a blank book to be placed in the bottom slot (which it did not allow before), but there is something blocking the disenchant (enchant blank book) process from occurring.

I tested it with extract being set to true, and extract being set to false, although I don't think that made a difference if Charm autodetects Grind Enchantment and disables extract.  Here are the 2 log files from that in case they are helpful.
[extractFalseGrindInstalled.log](https://github.com/svenhjol/Charm/files/6836359/extractFalseGrindInstalled.log)
[extractTrueGrindInstalled.log](https://github.com/svenhjol/Charm/files/6836360/extractTrueGrindInstalled.log)

**Comment by svenhjol** [comment]
Thanks for the feedback, will look into it further.

**Comment by Cntrldfusion** [comment]
So, I was trying to think outside the box a little bit.  Charm also uses the grindstone to make horse armor grindable.  So, using Charm 3.3.0 and Grind Enchantments 1.2.1, I thought what if I set ExtractEnachantments and GrindableHorseArmor both to false and test it.  And it worked.  Doing that allowed the grindstone to be used as the Grind Enchantments mod intended.

I also tested it with the Charm 3.3.1b2 file you gave me and setting GrindableHorseArmor to false allowed the Grind Enchantments mod to work with it as well.

So, its not something in your code with ExtractEnchantments that causes it, its the GrindableHorseArmor code that causes the conflict.

**Comment by svenhjol** [comment]
Excellent work tracking that down. I'll take a look at the grindable horse armor as there shouldn't be a reason that it can't live alongside the grindenchantments mod.

**Comment by svenhjol** [comment]
I tried tweaking the grindable horse armor. Can you test it again with this build? https://github.com/svenhjol/Charm/releases/download/3.3.1/charm-fabric-1.17-3.3.1b3.jar

**Comment by Cntrldfusion** [comment]
Tested with GrindableHorseArmor set to true and that build (3.3.1b3) works.  I'm not sure how grindable horse armor is intended to work, but normal horse armor cannot be placed in the grindstone.  Enchanted horse armor can and will return either a gem (for diamond) or an ingot (for iron and gold).  If that's how it is supposed to be then it looks like that build fixes the conflict.

**Comment by svenhjol** [comment]
This is how GHA is supposed to work in Charm without any other mods.

https://user-images.githubusercontent.com/26497903/126072677-825f8577-99b8-4906-9193-d6f70bf04964.mp4

If this isn't working for you while GHA module is enabled then it's still buggy.

**Comment by Cntrldfusion** [comment]
Yeah, its not working that way even without the Grind Enchantment mod.  I have to enchant the horse armor in order to place it in the grindstone.  Normal horse armor with no enchants can not be placed in the grindstone.

**Comment by svenhjol** [comment]
On further investigation it seems that GHA requires Extract Enchantments module to be enabled.  I'll look at fixing this dependency

**Comment by svenhjol** [comment]
Found the problem.  GHA piggybacks on the modded slot that Extract Enchantments adds, so when EE is disabled there isn't a modded slot on the grindstone any more and so you can't add horse armor.  Even if GHA modded the grindstone, it would conflict with grindenchantments in the same way that EE did.  Therefore I will have to disable the GHA module when grindenchantments is present.

I might look at moving the functionality of GHA to the anvil whenever grindenchantments is present, but that's outside the scope of this bugfix.  Thanks for testing this out.

**Comment by Cntrldfusion** [comment]
No problem, glad to help.  The guys on my server didn't even know they could grind horse armor so turning it off didn't really matter to them.  The problem is resolved to me so you can close this whenever you see fit.

**Comment by TobiPeterG** [comment]
Wouldn't it be possible for charm to add the functionality of the grindenchant mod as an extra option?

The only difference feature wise I saw was that grind enchant lets you keep your used item and the book, while charm removes the item and only returns the book with the enchantments. By this, the grind enchantment mod wouldn't be necessary to install anymore when charm is present.

Or does grind enchant add something I'm missing here?
