### ISSUE TITLE
[FABRIC] Crash whilst using version 2.3.2 in 1.16.5 with my modpack

### ISSUE THREAD

**Issue by OakBricks-old** [svenhjol/Charm#633]
Versions
Charm version - `2.3.2`
Minecraft version - `1.16.5`
Fabric loader - `0.11.6`
Fabric API - `0.37.0`

Description:
Crash, might be an incompat with an unknown mod

Optional: Stacktrace/Screenshots
[latest.log](https://github.com/svenhjol/Charm/files/6844472/latest.log)
[actual crash](https://pastebin.com/L9eaMgH9)

##### mod list will be given at request

**Comment by OakBricks** [comment]
crash has been fixed, seems like a mod was conflicting with other mods, not charms fault, will be closing

**Comment by OakBricks** [comment]
reopened, issue still presists
