### ISSUE TITLE
Conflict with Elytra Trinket mod

### ISSUE THREAD

**Issue by EpsilonWasTaken** [svenhjol/Charm#637]
Found a bug/conflict with the Elytra Trinket mod earlier today when playing on a modded server with some friends, and died with the Elytra in the Elytra Trinket Cape slot. Upon picking up my Totem of Preserving and obtaining my items again, my Elytra had disappeared from my inventory. Leaving the game didn't place it back in my inventory, either, so it seems that it was just "deleted" from my inventory upon death.

(Mod Link if needed: https://www.curseforge.com/minecraft/mc-mods/elytra-trinket-fabric)

**Comment by rozzythefuzzy** [comment]
The trinkets slots aren't saved with the totem, but they still drop. So the elytra should have dropped somewhere nearby.
