### ISSUE TITLE
Suspicious soup should be unstackable

### ISSUE THREAD

**Issue by build2stone** [svenhjol/Charm#64]
Because all other bowl-based foods are also unstackable
Additionally, this would prevent distinguishing between the different variants using stacking behaviour.

Mods used:
Charm 1.1.0
Forge 14.23.5.2838

**Comment by WarlordWossman** [comment]
Hm, always felt like the soup foods are pretty useless because they don't stack but I see what you mean about them not being suspicious anymore if you can stack them depending on nbt :D
