### ISSUE TITLE
What are totems of holding spawned as?

### ISSUE THREAD

**Issue by LordM4x** [svenhjol/Charm#642]
I recently died in my world due to a bug(not charm) and wanted to tp my stuff back to me but i couldnt because of  the totem of holding. What is it and how would i tp it to me?

**Comment by FynnWaelsing** [comment]
I'm not sure if you can tp the totem of holding, but the coordinates of where it spawned should appear in your log, so you can just tp yourself to it.

**Comment by LordM4x** [comment]
oh ty
