### ISSUE TITLE
Mod compatibility concerning "Totem of Preserving"

### ISSUE THREAD

**Issue by M3chaDoc** [svenhjol/Charm#648]
Versions
* Charm version - `3.3.2`
* Minecraft version - `1.17.1`

The totem completely deletes items held in modded slots.
One of which is "Backslot" mod, both of my weapons held in the two slots (a bow and a sword) were deleted
aswell as "trinkets"+"inmis" deleted the equiped backpack.
Although I'm unsure about trinkets mod itself as I have yet to obtain one.

**Comment by Verbina29** [comment]
Also deletes items in Inventorio slots! I made an issue there already. https://github.com/Lizard-Of-Oz/Inventorio/issues/70

**Comment by deftesthawk** [comment]
+1 trinket slots don't get saved upon death

**Comment by Verbina29** [comment]
Can confirm, trinkets just drop on the ground, but other modded slots seem to just get deleted.
