### ISSUE TITLE
Game crashes when loading world type Biospheres.

### ISSUE THREAD

**Issue by Mysteriaa** [svenhjol/Charm#649]
Versions
* Charm version - 3.3.2
* Minecraft version - e.g. 1.17.1

Description
When creating a world with the Biospheres mod ( https://www.curseforge.com/minecraft/mc-mods/biospheres-fabric ) installed and with its worldtype selected, the game crashes.

Optional: Steps To Reproduce
See description.
[crash-2021-08-16_12.51.14-server.txt](https://github.com/svenhjol/Charm/files/6994116/crash-2021-08-16_12.51.14-server.txt)

Optional: Stacktrace/Screenshots

**Comment by Veyrdite** [comment]
Does setting "Generate Structures" to off prevent this problem from occurring?

https://github.com/FarLanderCraft/Biospheres/issues/2
