### ISSUE TITLE
[Incompatibility] Charm & Inventorio (Fabric 1.17.1)

### ISSUE THREAD

**Issue by SylisMC** [svenhjol/Charm#658]
Versions
* Charm-fabric-1.17-3.3.2.jar
* Inventorio-1.17-fabric-1.6.2.jar

Description
The holding totem deletes toolbelt items on death

Optional: Steps To Reproduce
install both mods, place tools in sidebar on the right and kill yourself

**Comment by Coranthes** [comment]
Sorry, we don't have the time to support versions prior to 1.18 so this issue is being closed.
