### ISSUE TITLE
Redstone sand in creative menu

### ISSUE THREAD

**Issue by svenhjol** [svenhjol/Charm#66]
Reference: https://minecraft.curseforge.com/projects/charm?comment=139

I noticed 2 bugs: 1. in the creative menu and in the JEI the redstone sand have 2 versions, but they are the same, 2. when i turned off the redstone sand in the config and i tested with that, i found one of the 2 redstone sands in creative menu, in JEI too and it was craftable yet.

**Comment by svenhjol** [comment]
Struggling to repeat this issue. There seems to only be one redstone sand in creative menu

**Comment by WarlordWossman** [comment]
I tried to reproduce this today but can't either. 
As for JEI is there an addon that shows entities? I wonder if the entity used for gravity blocks could have been what he saw, but this is only a random guess ofc.

**Comment by svenhjol** [comment]
Thanks for testing. Since we can't reproduce this I'm going to close and get back to him.
