### ISSUE TITLE
Cant join my server

### ISSUE THREAD

**Issue by Ninjajoz** [svenhjol/Charm#660]
I just made a new fabric minecraft server, added all the mods i wanted, datapacks and client mods but it says something about failed id. What can i do to fix it?
![Charm mod fail](https://user-images.githubusercontent.com/89695228/131220473-c8203610-3269-4c1c-9d35-ab9e040ff1b9.png)

![Charm mod fail 2](https://user-images.githubusercontent.com/89695228/131220536-d4acf747-3444-4602-adc1-cf998b97e8d1.png)

**Comment by Coranthes** [comment]
Did you remember to add Charm to both the server and client?  It is needed on both sides.

**Comment by Ninjajoz** [comment]
Yes it worked but i had problems with pipe mod, i just removed the pipe mod
in the end
