### ISSUE TITLE
[1.17.1] [Latest Charm Fabric] "Watching ServeR" crash

### ISSUE THREAD

**Issue by red2blue** [svenhjol/Charm#663]
https://pastebin.com/kZcSDLeE

**Comment by FynnWaelsing** [comment]
As your crash report says right up top, 
"Do NOT report to mod authors if you encountered issues with the following mods: 
- betterend@0.11.0-pre
- charm@3.3.2
- betternether@5.1.3
You can try disabling compatibility modules for these mods in "c2me-compat.toml" and try reproduce again. 
Or try reproduce without C2ME."

Please follow these directions and post a new issue if you are continuing to have this error.

**Comment by red2blue** [comment]
Oh shit i forgot they added 'charm compatibility' I apologize. I'll try toggling off c2me charm compat.
