### ISSUE TITLE
Lumberjack and Beekeeper villagers lack proper gifts

### ISSUE THREAD

**Issue by Samarai** [svenhjol/Charm#665]
Versions:
* Charm version - `3.3.2`
* Minecraft version - `1.17.1`

Description:
When Lumberjack and Beekeeper villagers give a player with the "Hero of the Village" effect a gift, they will always give them wheat seeds (the default gift used for nitwit/unemployed villagers) instead of something pertaining to their profession.

Steps To Reproduce:
In survival: Successfully fend off an illager raid and approach either of the aforementioned villager types.

In creative: Use the /effect command to give yourself the HOTV status effect and spawn a villager next to a beekeeper or lumberjack worksite. (beehive and woodcutter respectively)

**Comment by FynnWaelsing** [comment]
Not quite a bug; those features simply have not been added/were forgotten for those villager professions. Thanks for catching this, though! I'll make a note to sven to consider adding proper gifts to those villagers.
