### ISSUE TITLE
Spelunking Potion and Potion fof Haste share same ingredients and outputs only haste

### ISSUE THREAD

**Issue by Shigoobee** [svenhjol/Charm#679]
Versions
* Charm version 3.3.2
* Minecraft version 1.17

Description
Trying to make Spelunking Potion but the same recipe is used for Haste potion. Can't seem get around making haste potion

Optional: Steps To Reproduce
1.Put awkward potion in the brewing stand
2. Put amythis shard on top
3. wait for output
4. Notice it is potion of haste instead of Potion of spelunking

**Comment by Coranthes** [comment]
Sorry, we don't have the time to support versions prior to 1.18 so this issue is being closed.
