### ISSUE TITLE
Totems of holding incompatible with Trinkets and other slot items

### ISSUE THREAD

**Issue by soldiumek** [svenhjol/Charm#686]
Game version: 1.17.1 | Fabric version: 0.11.7 | Fabric API version: 0.40.0 | Charm: charm fabric 1.17-3.3.2

**Description**
Upon death with items in extra slots such as trinkets from API of the same name, or slots from other mods - the items simply vanish upon death. The items from moded equipment slots simply vanish. This has been mostly a problem with trinkets, back slot and Campanion backpacks (which should spill their content upon death).

**Steps to reproduce**
Install mods (and their respective APIs): 
-Fabric 0.11.7
-Fabric API 0.40.0
-Sodium/Iris and Lithium
-Trinkets 
-Camapnion
-Backslot
-Charm
Create an SMP Fabric server and include everything but Sodium

Launch a creative world with cheats, fill a backpack with some items, fill your back slots with weapons/tools. Commit suicide with your chosen way and observe the results

**Expected Behavior**
Items from the Campanion backpack should be spiled on the ground or contained in the totem of holding, 
The tools on the Back/belt slots should be preserved in the totem of holding or dropped to the ground

**Observed behavior**
While the totem of holding works properly with Vanilla inventory, it ignores all extra slots in the inventory, causing the items to cease their exsistance in this world.

**Comment by ShinyRobotGod** [comment]
I had to disable the Totem of Preserving in the config because of this behavior.  Some of my best items are often stored in the trinket and backpack slots.  I miss the totem.
