### ISSUE TITLE
Incompatible with Roguelike Dungeons

### ISSUE THREAD

**Issue by SM9CC** [svenhjol/Charm#69]
So it breaks roguelike gen, the stacktrace is here: https://hastebin.com/ugavazekov.sql

As you can see the dungeon is completely empty of spawners and loot chests:
https://i.imgur.com/e9JW4wP.png
https://i.imgur.com/0G6KDmu.png

However, thanks for the awesome mod, I really like the direction it's going in but unfortunately I will have to hold off using it for now.

**Comment by svenhjol** [comment]
I think it’s a problem with one of the loot tables. I haven’t tested against Roguelike Dungeons yet, but I’m happy to look into this if it’s breaking treasure generation. Will keep you posted, thanks for the issue report.

**Comment by svenhjol** [comment]
I would be grateful if you could test the latest build here: https://github.com/svenhjol/Charm/releases/download/1.12.2-1.1.4/Charm-1.12.2-1.1.4.jar

It contains a fix for the error you posted in your ticket. Thanks!

**Comment by SM9CC** [comment]
Thanks will try now!

**Comment by SM9CC** [comment]
Sorry for the delay, I was about to test then something came up, I have tested it now though and it looks good to me, no more stracktrace and loot, spawners appear to be generating as normal.

Thanks for your fast fix!

**Comment by svenhjol** [comment]
Thank you for testing!
