### ISSUE TITLE
1.17.1 Crash

### ISSUE THREAD

**Issue by red2blue** [svenhjol/Charm#702]
Latest charm / fabric / 1.17.1

Player used a ritual and changed time to day from night and dedicated server lagged out and crashed. Modpack; Another Quality Modpack 2

Crash log; https://pastebin.com/YcGpXrbf

**Comment by Coranthes** [comment]
Read the top of the log where it says:

"C2ME Compatibility Module Notice: 
Do NOT report to mod authors if you encountered issues with the following mods: 
- betternether@5.1.3
- betterend@0.11.0-pre
- charm@3.3.2
- You can try disabling compatibility modules for these mods in "c2me-compat.toml" and try reproduce again. 
Or try reproduce without C2ME."

**Comment by red2blue** [comment]
Can we not jump to conclusions? 

```You can try disabling compatibility modules for these mods in "c2me-compat.toml" and try reproduce again.
Or try reproduce without C2ME."You can try disabling compatibility modules for these mods in "c2me-compat.toml" and try reproduce again.
Or try reproduce without C2ME."``` 

The module was disabled. This message shows regardless.
