### ISSUE TITLE
Oak Barrel incompatibility 

### ISSUE THREAD

**Issue by xanthian** [svenhjol/Charm#708]
Oak Barrel recipe overwrites the default Barrel breaking many recipes in other mods, please allow this to be an alternative recipe allowing users to chose which Barrel is created.

Versions
* Charm version - 3.3.3 (self built from github)
* Minecraft version - 1.17.1

Description
Write a clear description about what is going wrong.

Steps To Reproduce
Make a Vanilla Barrel, you get an Oak one

Screenshots
![image](https://user-images.githubusercontent.com/7688001/140802302-f730d96a-8d4f-4532-8683-adfc5b8ecc25.png)

**Comment by Micalobia** [comment]
You can craft Charm barrels into vanilla ones by just putting it in the table again

**Comment by xanthian** [comment]
nope you were correct, consider this closed :)
