### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by Kasia1403** [svenhjol/Charm#719]
Add more readable and more detailed configs descriptions.

MC 1.12.2

Charm 1.12.2-1.4.1

Forge 14.23.5.2855

**Comment by Kasia1403** [comment]
Modrinth, are You there ??? PLEASE HELP me !!!

**Comment by SpinHarmony** [comment]
First of all, this is GitHub, not Modrinth. Also, you’re using a version of Minecraft that is normally not supported by modders anymore, So it is unlikely that this problem will be fixed for that version. It is likely a conflict with another mod, as this works fine with just this mod. I recommend removing mods until you find the one that is causing the issue.

**Comment by Kasia1403** [comment]
I thought that Modrinth is a mod developer.
