### ISSUE TITLE
Any update for 18.1 ???

### ISSUE THREAD

**Issue by number117** [svenhjol/Charm#728]
Just asking, no hurry

**Comment by beautiful-lunatic** [comment]
I would like to know any updates too tbh. On curseforge it says the creator of the mod hasn't been online since July. Is the creator okay?

**Comment by HerrahStrings** [comment]
fam learn how branches work please https://github.com/svenhjol/Charm/tree/1.18.x

**Comment by number117** [comment]
OKAY, sorry  closing
