### ISSUE TITLE
flavored cakes colored sprinkles

### ISSUE THREAD

**Issue by WarlordWossman** [svenhjol/Charm#73]
Colored sprinkles on the flavored cakes based on what potion it is made of?
Would make it a bit more clear for people not using TOP/WAILA or F3 screen.

**Comment by SirSquidly** [comment]
I personally kinda like the mystery aspect a bit, like suspicious stew, but more likely to be helpful. Something like making the cake give appropriately colored potion particle affects would be cool though!

Here's a lil' concept for Potion Cake, with it just giving a slight purple to the frosting as you do basically just combine the potion with the finished cake. Also, the cherries are Nether Wart.
![2019-07-05_20 55 33](https://user-images.githubusercontent.com/13826553/60751245-4afc3000-9f67-11e9-8139-b3240c34de86.png)

**Comment by svenhjol** [comment]
@SirSquidly added this to the roadmap board: https://trello.com/c/Msxkecaa
