### ISSUE TITLE
A problem with the Beekeeper

### ISSUE THREAD

**Issue by Egon370** [svenhjol/Charm#730]
With the vanilla villagers and Lumberjack, trades start out giving tons of experience to the villager but decrease in value every time the villager levels up. However, with the Beekeeper, every trade acts as if it were a Novice trade on an Apprentice villager. This makes leveling up Beekeepers significantly harder than all other professions.

MC 1.17.1

Charm 1.17-3.3.2

Fabric 0.12,12

**Comment by FynnWaelsing** [comment]
1.18.2 is the only currently supported version of Charm. Please update to the 1.18.2 version and repost this issue if it persists.
