### ISSUE TITLE
No comments in Curseforge, where is the 1.18 Beta?

### ISSUE THREAD

**Issue by Kadynsr** [svenhjol/Charm#731]
My friend and I are about to start a modded server on twitch and would love to be able to have this for 1.18! Sorry for posting this as an issue, nowhere else to put it.

**Comment by FynnWaelsing** [comment]
1.18 is still in development. Please be patient.

**Comment by 3prm3** [comment]
You can build it

**Comment by 3prm3** [comment]
Download the 1.18x branch
extract the folder
open the command line in the folder (on windows you can right click in the folder)
 type ./gradlew build
the jar should be in build/libs

**Comment by 3prm3** [comment]
https://github.com/svenhjol/Charm/tree/04577564d3892ebc4ac94e805de4b38d5c23992e

**Comment by Kadynsr** [comment]
Ok i've tried building it where in the world is the built file supposed to show up? The code runs then nothing

**Comment by 3prm3** [comment]
> Ok i've tried building it where in the world is the built file supposed to show up? The code runs then nothing

I said build/libs

**Comment by 3prm3** [comment]
or lib

**Comment by Kadynsr** [comment]
I don’t see any new folders pop up, and this time I just tried it failed

**Comment by 3prm3** [comment]
> I don’t see any new folders pop up, and this time I just tried it failed

Oh, try the older commita

**Comment by Kadynsr** [comment]
I tried both 1.18 and they both failed

**Comment by Kadynsr** [comment]
Any way I could get a built version download?

**Comment by fintris** [comment]
> Any way I could get a built version download?

I would also like this

**Comment by 3prm3** [comment]
[charm-fabric-1.18-4.0.0.jar.zip](https://github.com/svenhjol/Charm/files/7964273/charm-fabric-1.18-4.0.0.jar.zip)
Extract it

**Comment by Plastogerm** [comment]
@3prm3 thank you so much!
I'm not sure what I'm doing wrong that made me unable to build the 1.18 branch of Charm and Charmonium. I have this now though and I'm thankful, but could you please help me with the latter?

**Comment by 3prm3** [comment]
> @3prm3 thank you so much! I'm not sure what I'm doing wrong that made me unable to build the 1.18 branch of Charm and Charmonium. I have this now though and I'm thankful, but could you please help me with the latter?

Will try

**Comment by 3prm3** [comment]
It failed
