### ISSUE TITLE
What happened to Bookcases?? x.x

### ISSUE THREAD

**Issue by Kadynsr** [svenhjol/Charm#732]
Where did the bookcases go in 1.18? That's one of my favorite features :(

**Comment by Coranthes** [comment]
I love them as well.  We discussed removing them from Charm and instead moving them to Covalent.  Promise Covalent is still alive, it's just...forever being worked on.

**Comment by sabybee** [comment]
Is there any ETA on the Covalent update to 1.18.2? Not trying to rush, just that the bookcases were one of the main reasons I installed Charm.

**Comment by Coranthes** [comment]
There isn't, unfortunately.  It's hard enough just keeping Charm up to date with all the updates.
