### ISSUE TITLE
advancements not working

### ISSUE THREAD

**Issue by JackijackDarth** [svenhjol/Charm#734]
Versions
* Charm version - 4.0.0`
* Minecraft version - e.g. `1.18.1`

Description
when I try to check my advancements  it tells me "there doesn't seem to be anything here..." i have a few advancements already and i can see them wen i get them in the chat.  

Steps To Reproduce : play and look the advancements 
![2022-02-14_19 58 36](https://user-images.githubusercontent.com/99698713/153972422-ee48ed87-ee96-4e21-91f8-edf69e11e49d.png)

**Comment by FynnWaelsing** [comment]
Please update to the 1.18.2 version of the mod and repost this issue if it persists.
