### ISSUE TITLE
Items despawning in crates (Forge 1.16.4)

### ISSUE THREAD

**Issue by Reael** [svenhjol/Charm#736]
For a while now I thought I'm just going nuts but it seems like things stored in crates do despawn every time I log back into Minecraft (singleplayer, not server).

I never got an error message of charm and another mod colliding or not working properly together but it could be due to another mod I guess. First I thought the villagers are stealing my things since I built in the middle of a town and they just come and go however they please, so I moved my crates downstairs and put them behind iron bars since I was still building my home and wanted to get enough chests and stuff before I'd clean up all the crates. But well... everything is just gone and every crate is as empty as can be (6 crates in total).

I tried googling this but can't find anything, I don't know if this is a bug or wanted, and if it's a bug if it's already known (or even fixed in another version). I'm using charm-forge-1.16.4-2.1.9

**Comment by FynnWaelsing** [comment]
1.18.2 is the only currently supported version, and support is not being offered for older versions of Charm.

**Comment by ridjack** [comment]
Please feel free to discontinue "supporting our mod." Your attitude towards other contributors is neither desired nor necessary.

Additionally, if a template response like @FynnWaelsing gave you is enough to offend you... you might want to reconsider spending a lot of time on the Internet.
