### ISSUE TITLE
Server Tags

### ISSUE THREAD

**Issue by TardisKing40** [svenhjol/Charm#739]
Loading Minecraft 1.17.1 with Fabric Loader 0.13.1

`[18:46:38] [Render thread/WARN]: Incomplete server tags, disconnecting. Missing: {ResourceKey[minecraft:root / minecraft:block]=[charm:immovable_by_pistons, charm:barrels, charm:nether_portal_frames, c:provides_enchanting_power], ResourceKey[minecraft:root / minecraft:item]=[charm:crafting_tables]}`

-- System Details --
Details:
	Minecraft Version: 1.17.1
	Minecraft Version ID: 1.17.1
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 16.0.1, Microsoft
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft
	Memory: 2672536048 bytes (2548 MiB) / 4261412864 bytes (4064 MiB) up to 5368709120 bytes (5120 MiB)
	CPUs: 12
	Processor Vendor: AuthenticAMD
	Processor Name: AMD Ryzen 5 5500U with Radeon Graphics         
	Identifier: AuthenticAMD Family 23 Model 104 Stepping 1
	Microarchitecture: unknown
	Frequency (GHz): 2.10
	Number of physical packages: 1
	Number of physical CPUs: 6
	Number of logical CPUs: 12
	Graphics card #0 name: AMD Radeon(TM) Graphics
	Graphics card #0 vendor: Advanced Micro Devices, Inc. (0x1002)
	Graphics card #0 VRAM (MB): 512.00
	Graphics card #0 deviceId: 0x164c
	Graphics card #0 versionInfo: DriverVersion=30.0.14023.3004
	Memory slot #0 capacity (MB): 8192.00
	Memory slot #0 clockSpeed (GHz): 3.20
	Memory slot #0 type: DDR4
	Memory slot #1 capacity (MB): 8192.00
	Memory slot #1 clockSpeed (GHz): 3.20
	Memory slot #1 type: DDR4
	Virtual memory max (MB): 24438.23
	Virtual memory used (MB): 19189.48
	Swap memory total (MB): 8704.00
	Swap memory used (MB): 801.79
	JVM Flags: 10 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx5G -Xms3G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	Fabric Mods: 
		advanced_runtime_resource_pack: Runtime Resource Pack 0.2.9
		advancednetherite: Advanced Netherite 1.2.0-1.17.1
		appleskin: AppleSkin mc1.17-2.1.3
		architectury: Architectury 2.10.6
		armorchroma: Armor Chroma 1.2.0
		attributefix: AttributeFix 11.0.4
		autofish: Autofish 0.9.3
		balm-fabric: Balm 1.9.0+0
		better_wandering_trader: Better Wandering Trader 1.7.0
		blur: Blur (Fabric) 2.4.0
		campingsticks: Camping Sticks 1.17.1-1
		cardinal-components: Cardinal Components API 3.1.1
		cardinal-components-base: Cardinal Components API (base) 3.1.1
		cardinal-components-block: Cardinal Components API (blocks) 3.1.1
		cardinal-components-chunk: Cardinal Components API (chunks) 3.1.1
		cardinal-components-entity: Cardinal Components API (entities) 3.1.1
		cardinal-components-item: Cardinal Components API (items) 3.1.1
		cardinal-components-level: Cardinal Components API (world saves) 3.1.1
		cardinal-components-scoreboard: Cardinal Components API (scoreboard) 3.1.1
		cardinal-components-util: Cardinal Components API (utilities) 3.1.1
		cardinal-components-world: Cardinal Components API (worlds) 3.1.1
		carrier: Carrier 1.8.2
		charm: Charm 3.3.2
		charmonium: Charmonium 3.3.0
		cherishedworlds: Cherished Worlds 2.0.1-1.17.1
		clienttweaks: Client Tweaks 6.0.0+0
		cloth-api: Cloth API 2.0.54
		cloth-basic-math: cloth-basic-math 0.6.0
		cloth-client-events-v0: Cloth Client Events v0 2.0.54
		cloth-common-events-v1: Cloth Common Events v1 2.0.54
		cloth-config2: Cloth Config v5 5.2.47
		cloth-datagen-api-v1: Cloth Datagen v1 2.0.54
		cloth-scissors-api-v1: Cloth Scissors API v1 2.0.54
		cloth-utils-v1: Cloth Utils v1 2.0.54
		clumps: Clumps 7.0.10
		com_electronwill_night-config_core: core 3.6.5
		com_electronwill_night-config_toml: toml 3.6.2
		com_electronwill_night-config_yaml: yaml 3.6.5
		com_fasterxml_jackson_core_jackson-annotations: jackson-annotations 2.13.0
		com_fasterxml_jackson_core_jackson-core: jackson-core 2.13.0
		com_fasterxml_jackson_core_jackson-databind: jackson-databind 2.13.0
		com_fasterxml_jackson_dataformat_jackson-dataformat-yaml: jackson-dataformat-yaml 2.13.0
		com_github_reviversmc_modget-lib: modget-lib 3.0.0
		com_github_reviversmc_modget-manifest-api_compat: compat 0.2.1
		com_github_reviversmc_modget-manifest-api_spec3: spec3 0.2.1
		com_github_reviversmc_modget-manifest-api_spec4: spec4 0.2.1
		com_moandjiezana_toml_toml4j: toml4j 0.7.2
		com_velocitypowered_velocity-native: velocity-native 1.1.0-SNAPSHOT
		craftpresence: CraftPresence 1.8.8
		crops: Fabric Crops 1.2.1
		dankstorage: Dank Storage 2.2.2-1.17.1
		dynamicfps: Dynamic FPS 2.0.6
		easiervillagertrading: EasierVillagerTrading 1.17.1-fabric0.36.1-1.5.4
		eatinganimationid: Eating Animation 1.2
		elytratrinket: Elytra Trinket 3.0.0-1.17.1
		enchantmentdescriptions: Enchantment Descriptions 4.0.1
		entityculling: EntityCulling-Fabric 1.4.0
		fabric: Fabric API 0.46.1+1.17
		fabric-api-base: Fabric API Base 0.4.0+cf39a74318
		fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.5.0+e821752d18
		fabric-biome-api-v1: Fabric Biome API (v1) 3.2.2+cf39a74318
		fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.6+cf39a74318
		fabric-command-api-v1: Fabric Command API (v1) 1.1.4+cf39a74318
		fabric-commands-v0: Fabric Commands (v0) 0.2.3+cf39a74318
		fabric-containers-v0: Fabric Containers (v0) 0.1.13+cf39a74318
		fabric-content-registries-v0: Fabric Content Registries (v0) 0.4.1+3447790d18
		fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.1.6+cf39a74318
		fabric-dimensions-v1: Fabric Dimensions API (v1) 2.0.15+b556f28c18
		fabric-entity-events-v1: Fabric Entity Events (v1) 1.4.1+377137cc18
		fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.12+e99fbe1218
		fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.4+cf39a74318
		fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.8+cf39a74318
		fabric-item-api-v1: Fabric Item API (v1) 1.3.0+6617390918
		fabric-item-groups-v0: Fabric Item Groups (v0) 0.3.2+cf39a74318
		fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.6+2a2bb57318
		fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.4+cf39a74318
		fabric-language-kotlin: Fabric Language Kotlin 1.7.1+kotlin.1.6.10
		fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 1.4.6+0392f3a618
		fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.0.5+cf39a74318
		fabric-mining-level-api-v1: Fabric Mining Level API (v1) 1.0.3+cf39a74318
		fabric-mining-levels-v0: Fabric Mining Levels (v0) 0.1.7+cf39a74318
		fabric-models-v0: Fabric Models (v0) 0.3.1+cf39a74318
		fabric-networking-api-v1: Fabric Networking API (v1) 1.0.14+cf39a74318
		fabric-networking-blockentity-v0: Fabric Networking Block Entity (v0) 0.2.12+cf39a74318
		fabric-networking-v0: Fabric Networking (v0) 0.3.3+cf39a74318
		fabric-object-builder-api-v1: Fabric Object Builder API (v1) 1.11.1+f907116918
		fabric-object-builders-v0: Fabric Object Builders (v0) 0.7.8+cf39a74318
		fabric-particles-v1: Fabric Particles (v1) 0.2.5+cf39a74318
		fabric-permissions-api-v0: fabric-permissions-api 0.1-SNAPSHOT
		fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.8.0+ea29b33318
		fabric-renderer-api-v1: Fabric Renderer API (v1) 0.4.6+ce16ae5918
		fabric-renderer-indigo: Fabric Renderer - Indigo 0.4.10+ce16ae5918
		fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.6+cf39a74318
		fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.1.6+cf39a74318
		fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 0.2.1+cf39a74318
		fabric-rendering-v0: Fabric Rendering (v0) 1.1.7+cf39a74318
		fabric-rendering-v1: Fabric Rendering (v1) 1.10.1+377137cc18
		fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1) 1.0.1+591a0f2118
		fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.4.10+f09604ce18
		fabric-screen-api-v1: Fabric Screen API (v1) 1.0.5+cf39a74318
		fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.1.9+cf39a74318
		fabric-structure-api-v1: Fabric Structure API (v1) 1.2.0+48a9ad8918
		fabric-tag-extensions-v0: Fabric Tag Extensions (v0) 1.2.3+cf39a74318
		fabric-textures-v0: Fabric Textures (v0) 1.0.7+cf39a74318
		fabric-tool-attribute-api-v1: Fabric Tool Attribute API (v1) 1.3.3+3b96517518
		fabric-transfer-api-v1: Fabric Transfer API (v1) 1.5.4+cf39a74318
		fabricloader: Fabric Loader 0.13.1
		ferritecore: FerriteCore 3.1.0
		gbfabrictools: GBfabrictools 1.3.4+1.17
		goblintraders: Goblin Traders 1.4.1
		grindenchantments: Grind Enchantments 1.4.0+1.17.1
		inventoryhud: Inventory HUD + 3.4.1
		iris: Iris 1.2.0-pre
		java: OpenJDK 64-Bit Server VM 16
		krypton: Krypton 0.1.4
		lambdynlights: LambDynamicLights 2.1.0+1.17
		lapisreserve: Lapis Reserve 1.0.8
		libzoomer: LibZoomer 0.3.0+1.17.1
		litematica: Litematica 0.9.0
		lithium: Lithium 0.7.5
		malilib: MaLiLib 0.10.0-dev.26
		midnightlib: MidnightLib 0.3.0
		minecraft: Minecraft 1.17.1
		minihud: MiniHUD 0.20.0
		modget: Modget 0.4.3+1.17
		modget-core: Modget Core 0.4.3
		modmenu: Mod Menu 2.0.14
		mousetweaks: Mouse Tweaks 2.15
		notenoughcrashes: Not Enough Crashes 4.1.4+1.17.1
		okzoomer: Ok Zoomer 5.0.0-beta.3+1.17.1
		org_anarres_jcpp: jcpp 1.4.14
		org_apache_commons_commons-text: commons-text 1.9
		org_aperlambda_lambdajcommon: lambdajcommon 1.8.1
		org_jetbrains_kotlin_kotlin-reflect: kotlin-reflect 1.6.10
		org_jetbrains_kotlin_kotlin-stdlib: kotlin-stdlib 1.6.10
		org_jetbrains_kotlin_kotlin-stdlib-jdk7: kotlin-stdlib-jdk7 1.6.10
		org_jetbrains_kotlin_kotlin-stdlib-jdk8: kotlin-stdlib-jdk8 1.6.10
		org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm: kotlinx-coroutines-core-jvm 1.5.2
		org_jetbrains_kotlinx_kotlinx-coroutines-jdk8: kotlinx-coroutines-jdk8 1.5.2
		org_jetbrains_kotlinx_kotlinx-serialization-cbor-jvm: kotlinx-serialization-cbor-jvm 1.3.1
		org_jetbrains_kotlinx_kotlinx-serialization-core-jvm: kotlinx-serialization-core-jvm 1.3.1
		org_jetbrains_kotlinx_kotlinx-serialization-json-jvm: kotlinx-serialization-json-jvm 1.3.1
		org_joml_joml: joml 1.10.2
		org_quiltmc_quilt-json5: quilt-json5 1.0.0
		org_slf4j_slf4j-api: slf4j-api 1.7.12
		org_yaml_snakeyaml: snakeyaml 1.29
		phosphor: Phosphor 0.8.0
		pling: Pling 1.5.0
		pride: Pride Lib 1.1.0+1.17
		rad: Reload Audio Driver 1.0.1
		roughlyenoughitems: Roughly Enough Items 6.4.426
		satin: Satin 1.6.4
		skinlayers: 3d Skin Layers 1.4.0
		slotlock: SlotLock 1.0.4-BETA+1.17
		sodium: Sodium 0.3.4+build.13
		spark: spark 1.6.3
		spruceui: SpruceUI 3.3.0+1.17
		thonkutil: ThonkUtil 1.3
		trinkets: Trinkets 3.0.4
		tweakeroo: Tweakeroo 0.11.0
		worldedit: WorldEdit 7.2.7+9f3e795
	Launched Version: fabric-loader-0.13.1-1.17.1
	Backend library: LWJGL version 3.2.2 build 10
	Backend API: AMD Radeon(TM) Graphics GL version 3.2.14802 Core Profile Forward-Compatible Context 22.1.2 30.0.14023.3004,

**Comment by FynnWaelsing** [comment]
1.18.2 is the only currently supported version of Charm. Please update to the 1.18.2 version and repost this issue if it persists.

**Comment by TardisKing40** [comment]
Yes, but how does this fix 1.17.1?

**Comment by FynnWaelsing** [comment]
As I said above, 1.18.2 is the only supported version. We will not be providing support for issues with versions older than that at this time.

**Comment by TardisKing40** [comment]
But I would like to use the 1.17 version
I have a modpack that only uses 1.17

**Comment by TardisKing40** [comment]
does 1.18 work on 1.17?

**Comment by Coranthes** [comment]
No, it does not.
