### ISSUE TITLE
request for Charm for 1.18.1

### ISSUE THREAD

**Issue by Killakilla2** [svenhjol/Charm#748]
Any chance to make a 1.18.1 version of Charm?  I have a modpack that has many mods that have not updated to 1.18.2 yet so we can't update to 1.18.2 yet and charm only works on 1.18 with 1.18.2. 

We used charm in our modpack for 1.17 and we loved it and our players have been missing it in our 1.18 version and were excited to add it in but for now we still cant.

thanks!

**Comment by FynnWaelsing** [comment]
Backports for older versions are not planned, unfortunately.
