### ISSUE TITLE
Runed Portals still destroyed by Blue Wither Skulls

### ISSUE THREAD

**Issue by SiliconEnt** [svenhjol/Charm#75]
This is followup for issue #68. (Rune portals allow easy destruction of end portals.)

The recently released fix apparently omitted the Vanilla portal frame's special handling for Blue Wither Skulls. Runed Portal frames are still destroyed by them. 

I haven't been able to determine whether the portal interior blocks are similarly destroyed; I know no way to isolate a portal block from its frame to test in in my wither cage, as unlike Vanilla end portals, Charm's quite sensibly disappear when their frame is broken.

**Comment by svenhjol** [comment]
Thanks for the report - I'll look into it.
