### ISSUE TITLE
Crash with Bewitchment 1.18.2

### ISSUE THREAD

**Issue by Alec153** [svenhjol/Charm#751]
When launching Bewitchment 1.18-16 and related dependencies with Charm 1.18-4.0.0 the game crashes. Log is attached and an issue has been reported to Bewitchment. [MoriyaShiine/bewitchment/issues/270](https://github.com/MoriyaShiine/bewitchment/issues/270)
[latest.log](https://github.com/svenhjol/Charm/files/8346906/latest.log)

**Comment by MoriyaShiine** [comment]
Fixed as of bewitchment-1.18-17
