### ISSUE TITLE
Suggestion:

### ISSUE THREAD

**Issue by YumatanGames** [svenhjol/Charm#755]
Hi. I know you're probably very busy, but I was thinking... Have you considered creating a fork of Charm to be used server-side only? I love some of those changes this mod allows, but since I'm running a server that I want vanilla clients to connect to, I can't have it there. And I assume others would like it too... 

Anyway this is just a suggestion from someone who doesn't know how to mod, and don't have any clue how hard would be to do it... Love your mods!

**Comment by Coranthes** [comment]
Charm makes so many changes to the game and adds so much content that it simply wouldn't be possible.
