### ISSUE TITLE
Acquisition enchantment duplicates Storage Drawer (from Storage Drawers mod)

### ISSUE THREAD

**Issue by KnightCa** [svenhjol/Charm#756]
**Minecraft** version: Forge 1.16.5
**Charm** version: forge-1.16.4-2.1.9
**Storage Drawers** version: 1.16.3-8.5.1 (latest version)
**Life in the Village 2** modpack version: 1.32 (latest version)

**Singleplayer or Multiplayer**: Happens in both
**Mode**: Issue happens in Survival mode. Does not occur in Creative mode.

**Enchantment**: Acquisition (from Charm mod) interacting with Storage Drawer (from Storage Drawers mod)

**Expected behavior**: When breaking a Storage Drawer with a Axe enchanted with Acquisition in Survival mode, the Storage Drawer should be removed and end up in the inventory.

**Actual behavior**: When breaking a Storage Drawer with a Axe enchanted with Acquisition in Survival mode, the Storage Drawer is left in place (while a duplicate ends up in the inventory).

**Impact**: The player can duplicate the Storage Drawers contents multiple times by continuing to break the same Storage Drawer.

**Comment by Coranthes** [comment]
This is something that has been addressed many times, you can search closed issues to see everything.  I will also tell you, as is also stated on the github, we are unfortunately unable to support versions earlier than 1.18.2.
