### ISSUE TITLE
Acquisition enchantment cannot be placed on Tools

### ISSUE THREAD

**Issue by KnightCa** [svenhjol/Charm#757]
**Minecraft** version: Forge 1.16.5
**Charm** version: forge-1.16.4-2.1.9
**Life in the Village 2** modpack version: 1.32 (latest version)

**Singleplayer or Multiplayer**: Happens in both
**Mode**: Issue happens in Survival mode. Does not occur in Creative mode.

**Enchantment**: Acquisition (from Charm mod)

**Expected behavior**: When placing a tool on a Anvil with the Acquisition enchantment, we should be able to enchant it. It used to work this way.

**Actual behavior**: When placing a tool on a Anvil with the Acquisition enchantment, we are unable to enchant it.

**Comment by WarlordWossman** [comment]
I downloaded the modpack and checked the config: Acquisition was disabled by the packdev so that would explain why you cannot apply it in survival.
