### ISSUE TITLE
Withers can still destroy Runed Portals in 1.1.5

### ISSUE THREAD

**Issue by SiliconEnt** [svenhjol/Charm#76]
### Followup for #68 and #75. 

The fix for #75 doesn't seem to have stuck in release 1.1.5. Blue wither skulls still ignore the blast resistance of runed portals and runed portal frames. 

### Steps to reproduce:
1. Create blank instance with Forge 14.23.5.2838, Charm 1.1.5, AutoRegLib 1.3-30, and Quark r1.5-156
2. Generate a world and build a giant bedrock/barrier box out of entity processing range of any naturally spawning animals (so the wither fires blue skulls instead of black).
3. Place a bunch of runed portal frames and interiors inside the box.
4. Spawn a wither inside the box. Make sure player is in creative/spectator mode and the wither doesn't have any other entity targets to attack.
5. Wait for idle wither to shoot blue skulls out of "boredom". The skulls will ignore the blast resistance of the portals just like they do with normal blocks, despite the fix for #75 released in 1.1.5. 

### Logs – No idea if they'll help, but they cost nothing, so here you are.
Debug log: 
https://gist.github.com/SiliconEnt/06d665f3482d24ecb787c0d9b5c9e8b8

Latest log:
https://gist.github.com/SiliconEnt/b53b8ce2512c4b39ed03f34c71aa1bad

### Screenshots
Setup:
![Setup](https://user-images.githubusercontent.com/46073934/59152755-6e2ed080-89f7-11e9-9fe0-750a160d5326.png)

Consequences: (sorry about the giant night vision particle...)
![Consequences](https://user-images.githubusercontent.com/46073934/59152758-76870b80-89f7-11e9-8fbe-e6ce1da169f0.png)

**Comment by svenhjol** [comment]
I spent about two hours in a small tube portal room with 4 withers last night. This makes me very sad.

**Comment by svenhjol** [comment]
Can you open up your charm_asm.cfg file and confirm that EntityWither is set to true please?

**Comment by SiliconEnt** [comment]
Protecting a block from blue skulls requires a patch to the Wither? What.

I just checked the wither entry in the asm config, and it's definitely set to true. In three separate game instances. Which is unfortunate – one of those instance was created from scratch for testing, so if the entry were false, that'd mean that it was just a config defaults issue. But noooooo. 

I really can't imagine fixing this being anything less than a small personal hell, and I'm starting to feel pretty bad about opening this issue and the previous one.

**Comment by svenhjol** [comment]
Don’t worry, it needs fixing and I’m glad for the report. It’s just that vanilla hardcodes the block that the wither can break, so needs ASM to patch it. I’ve obviously not found all the places that it needs patching.

**Comment by SiliconEnt** [comment]
That seems... kinda dumb on Mojang's part. If only because it seems like it would damage maintainability. Determining resistance within block classes might have been less sphaghettiesque.

**Comment by WarlordWossman** [comment]
So the thing you patched might have been the blocks withers can destroy by just flying through them, for the blue skulls there might be another spot where those check against a blacklist.
If you can't find it there are some people on the eigencraft discord who looked into withers I think, might be worth asking there.

**Comment by svenhjol** [comment]
Thinking the same. I’ll have a crack after coffee ☺️

**Comment by svenhjol** [comment]
![blueskull](https://user-images.githubusercontent.com/26497903/59159041-9ed44000-8ab3-11e9-8e53-a041b349d1f4.jpg)
![code](https://user-images.githubusercontent.com/26497903/59159043-a398f400-8ab3-11e9-93a8-26f46266bda9.jpg)

Definitely a blue skull hitting a rune portal frame and caught it in the debugger. Returning false seems to do the trick.

**Comment by svenhjol** [comment]
I'll release this in 1.1.6 along with the crate inventory hover. Hopefully today.

**Comment by SiliconEnt** [comment]
I can confirm this fix is working in the wild.
