### ISSUE TITLE
ClientSpawnEntityMixin injection error result in crash?

### ISSUE THREAD

**Issue by ImAK9** [svenhjol/Charm#762]
**Minecraft:** 1.18.2
**Charm:** 4.0.0
**Fabric API:** 0.48.0

**Crashlog:** https://aofpaste.com/ajuquregag.yaml

**Comment by WarlordWossman** [comment]
@ImAK9 still crashing as of 4.1.2? (And updated Fabric API ofc)?
Will close otherwise in a few days, let us know if this still happening!
