### ISSUE TITLE
Incompatible with TheBoxTrot

### ISSUE THREAD

**Issue by Footage2-Amply-Pounce** [svenhjol/Charm#763]
**MC** 1.18.2
**Fabric API** 0.48.0
**[TheBoxTrot](https://modrinth.com/mod/the-box-trot)** 1.1
**Charm** 4.0.0

When both mods are present, the game will crash on init.

Logs: https://gist.github.com/Footage2-Amply-Pounce/c3793bc221b67063a8cfbe93b1b3cb9c

My Charm config in case it's relevant: https://gist.github.com/Footage2-Amply-Pounce/1558186d650c4d1f908f36dffddb873b

**Comment by Sunconure11** [comment]
Can confirm the same error.

https://pastebin.com/9Ms72Ph4

@svenhjol

**Comment by Sunconure11** [comment]
https://github.com/CammiePone/The-Box-Trot/issues/1

**Comment by Footage2-Amply-Pounce** [comment]
No clue when this got fixed, but Charm 4.4.4 and TheBoxTrot 1.4 on 1.19.2 no longer causes a crash.
