### ISSUE TITLE
Internal Server Lag

### ISSUE THREAD

**Issue by FluffyBumblebees** [svenhjol/Charm#778]
Charm causes severe internal server lag upon initial world creation. Idk what else to say. The console has 0 information when it happens.

**Comment by FluffyBumblee** [comment]
[B#744]  java.lang.UnsupportedOperationException: null
[B#744]  	at Not Enough Crashes deobfuscated stack trace.(1.18.2+build.3) ~[?:?]
[B#744]  	at com.google.common.collect.ImmutableMap.remove(ImmutableMap.java:851) ~[guava-31.0.1-jre.jar:?]
[B#744]  	at svenhjol.charm.helper.AdvancementHelper.lambda$filterAdvancements$4(AdvancementHelper.java:45) ~[charm-fabric-1.18-4.1.0.jar:?]
[B#744]  	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183) ~[?:?]
[B#744]  	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179) ~[?:?]
[B#744]  	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179) ~[?:?]
[B#744]  	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1625) ~[?:?]
[B#744]  	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509) ~[?:?]
[B#744]  	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499) ~[?:?]
[B#744]  	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150) ~[?:?]
[B#744]  	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173) ~[?:?]
[B#744]  	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?]
[B#744]  	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596) ~[?:?]
[B#744]  	at svenhjol.charm.helper.AdvancementHelper.lambda$filterAdvancements$5(AdvancementHelper.java:43) ~[charm-fabric-1.18-4.1.0.jar:?]
[B#744]  	at java.util.ArrayList.forEach(ArrayList.java:1511) ~[?:?]
[B#744]  	at svenhjol.charm.helper.AdvancementHelper.filterAdvancements(AdvancementHelper.java:26) ~[charm-fabric-1.18-4.1.0.jar:?]
[B#744]  	at net.minecraft.advancement.AdvancementManager.handler$ddf000$hookAdd(AdvancementManager:534) ~[?:?]
[B#744]  	at net.minecraft.advancement.AdvancementManager.load(AdvancementManager:57) ~[?:?]
[B#744]  	at net.minecraft.client.network.ClientAdvancementManager.onAdvancements(ClientAdvancementManager:40) ~[?:?]
[B#744]  	at net.minecraft.client.network.ClientPlayNetworkHandler.onAdvancements(ClientPlayNetworkHandler:1211) ~[?:?]
[B#744]  	at net.minecraft.network.packet.s2c.play.AdvancementUpdateS2CPacket.apply(AdvancementUpdateS2CPacket:51) ~[?:?]
[B#744]  	at net.minecraft.network.packet.s2c.play.AdvancementUpdateS2CPacket.apply(AdvancementUpdateS2CPacket:16) ~[?:?]
[B#744]  	at net.minecraft.network.NetworkThreadUtils.method_11072(NetworkThreadUtils:22) ~[?:?]
[B#744]  	at net.minecraft.util.thread.ThreadExecutor.redirect$ccb000$redirectExecuteTask(ThreadExecutor:1021) ~[?:?]
[B#744]  	at net.minecraft.util.thread.ThreadExecutor.runTask(ThreadExecutor:131) ~[?:?]
[B#744]  	at net.minecraft.util.thread.ThreadExecutor.runTasks(ThreadExecutor:116) ~[?:?]
[B#744]  	at net.minecraft.client.MinecraftClient.render(MinecraftClient:1085) ~[?:?]
[B#744]  	at net.minecraft.client.MinecraftClient.run(MinecraftClient:737) ~[?:?]
[B#744]  	at net.minecraft.client.main.Main.main(Main:236) [client-intermediary.jar:?]
[B#744]  	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
[B#744]  	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
[B#744]  	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
[B#744]  	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
[B#744]  	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:452) [fabric-loader-0.14.3.jar:?]
[B#744]  	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) [fabric-loader-0.14.3.jar:?]
[B#744]  	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) [fabric-loader-0.14.3.jar:?]

**Comment by FluffyBumblee** [comment]
This bug has been fixed in a pull request for 1.18.1 but is yet to be integrated.

**Comment by WarlordWossman** [comment]
@FluffyBumblebees is this also a case fixed by turning off the auto recipe unlock?
If so this should fix it: a5b25f96492d11b05a4c01102b861a1f971372ea
Gonna wait a couple days for confirmation otherwise close, if this keeps happening please let us know.
