### ISSUE TITLE
What happened to bookcases?

### ISSUE THREAD

**Issue by DankMachine** [svenhjol/Charm#788]
First I would like to apologize for asking this on GitHub, but it seems to be the only place available to ask questions.
I was just curious as to why the bookcases were removed? It seemed to be like a great, working feature that allowed you to use a bookshelf for actual books, so I couldn't help but wonder what happened to cause them to be removed?
Excellent mod, lots of wonderful features! I was just curious on what happened.

**Comment by Coranthes** [comment]
We're thinking about adding them to Covalent instead, if we ever get the time to get it updated to 1.19,  but at the moment it's a little up in the air as to what to do with them. As it turns out, they're more popular than anyone realized.

**Comment by DankMachine** [comment]
Ah, that makes sense, I'll keep that mod on my watchlist! Thanks for the response!
