### ISSUE TITLE
Discord / how to contact devs

### ISSUE THREAD

**Issue by Shadowrs** [svenhjol/Charm#789]
I was about to open a PR to remove the Discord links from the Github page, but I thought you might want to replace that information with how the devs can be contacted alternatively today.

**Comment by Gl0wstone** [comment]
I also want to contact them but mainly to donate $ for appreciation of this as well as Charmonium (ambient sounds mod)

**Comment by WarlordWossman** [comment]
Link has been updated in the readme.

**Comment by Sinuce** [comment]
Link (https://discord.gg/sYWnVtd8) stopped working as of July 2022.

**Comment by WarlordWossman** [comment]
https://discord.gg/S649dvZ9Ma
try this one, I set it to never expire in discord so I hope it stays more permanent
