### ISSUE TITLE
Texture of Wolf and cat (ocelot) work not in newest version

### ISSUE THREAD

**Issue by Titoo8899** [svenhjol/Charm#8]
Hi,
I have the newest version of your mod and have one problem. The texture of the cat (ocelot) work not and the wolf texture was the same. I have 2 questions. 
1. Is this a bug and the textures of the thinks load not? 
2. Or give it spawn eggs from cats and wolf extra and the other thinks was the normal spawn eggs?

Why then I this see have I the Ocelot spawnegg for the cats.

**Comment by svenhjol** [comment]
Hi,

When you spawn a wolf using an egg theres a 1 in 4 chance of the wolf being the default white texture. The other possibilities are grey, brown or black. Try spamming with a spawn egg to see if you get different wolf colors?

The cat needs a summon command to test the different textures, use this: 

> /summon Ocelot ~ ~ ~ {Owner: YOURNAME, CatType: 1}

. Sometimes the cat can spawn with the default texture, Spam summon to see different cats and try different cat types.  if you still have a problem please get back to me.

**Comment by Titoo8899** [comment]
Hi,
yes it work but I can tame the cats more as 1x. And the cats have the sit position and this status of position is lock. The cats run not on the world. Only sit is the position of the cats. Please make a animation of running by the cats or find the bug of not running
