### ISSUE TITLE
crates with no items show GUI

### ISSUE THREAD

**Issue by WarlordWossman** [svenhjol/Charm#80]
Once you place a crate and break it the GUI gets displayed even if there are no items in it.
Quark's shulkerbox GUI for example only shows the GUI if there is at least one item in the shulkerbox and I would say that behavior makes a lot of sense.

![2019-06-10_13 46 11](https://user-images.githubusercontent.com/16925725/59193610-8b45d980-8b86-11e9-80ad-fb47578bc9ca.png)

**Comment by svenhjol** [comment]
Does it show after it’s been crafted? It’s only when it’s placed then broken?

**Comment by WarlordWossman** [comment]
Only when placed and broken, pretty sure it's because of an nbt tag.
The name is also not _cursive_ until you place and break.

**Comment by svenhjol** [comment]
Ok thanks
