### ISSUE TITLE
Inventory disappears from chest boat in 1.19

### ISSUE THREAD

**Issue by shaffera777** [svenhjol/Charm#800]
The inventory in the chest boat disappears if you quit the game.

**Comment by Inurosen** [comment]
I can confirm this. My rare loot gone now. :(

**Comment by wise-io** [comment]
Can confirm on `Charm 4.1.2`. 

**Tested with the following mods:**
```
Fabric API 0.56.3
Charm 4.1.2
```
I also tested with `Fabric API 0.57.0`.

**Steps to reproduce:**
```
1. Put any item in boat chest.
2. Logout of world.
3. Login to world.
4. Check for items in boat chest.
```

**Comment by Inurosen** [comment]
Charm 4.2.0
Still not fixed. Frustrating.

**Comment by HelpComputr** [comment]
Yeah, boat chests are still broken on the latest update.

**Comment by WarlordWossman** [comment]
@Inurosen @HelpComputr should be fixed in 4.2.1 from what we could test so far! Let us know if that holds true.

**Comment by Inurosen** [comment]
I can confirm this bug is fixed now. Many thanks!

**Comment by WarlordWossman** [comment]
> I can confirm this bug is fixed now. Many thanks!

thanks to everybody reporting and commenting/confirming bugs, this one def went under the radar because it was reported when everybody was busy - gotta work through some other issues when there is time
