### ISSUE TITLE
[Charm version 1.1.10] Infinite Armor Duping with Salvage

### ISSUE THREAD

**Issue by WD200019** [svenhjol/Charm#83]
**Describe the issue**: Right-clicking armor in-hand to equip it, while said armor is enchanted with Salvage, will both equip the armor, and drop a clone of the item on the ground. The cloned item will be identical to the original, but with 0 durability.

**How to reproduce**:

1. Enter survival mode.

2. Obtain an armor piece that can be right-clicked to be equipped. Confirmed to occur with Diamond Helmet, Chestplate, Leggings and Boots.

3. Enchant the armor piece with Salvage.

4. Right-click with the item in hand to equip it.

The item will be equipped on your player, and an identical copy of the item with 0 durability will be created and drop on the ground.

&nbsp;

In case it is a compatibility issue, here is my [list of mods installed](https://pastebin.com/wMHggZZe) (taken from `latest.log`, may not represent actual mod names)

I can also upload my `charm.cfg` if necessary.

**Comment by svenhjol** [comment]
Thanks for the report. No need to upload config, I can repeat it here.

**Comment by svenhjol** [comment]
This is closed as it fixes the dupe issue in the latest release. I'm opening another one related to Salvage not working on armor. Thanks for testing this.
