### ISSUE TITLE
Charm Incompatibility with Forestry

### ISSUE THREAD

**Issue by Elwood0** [svenhjol/Charm#84]
Hi, first I want to say that I have tremendously enjoyed the mod you have created thus far...

That being said, I have found a Bug involving The Current version of Foresty (forestry_1.12.2-5.8.1.322) & and the recently updated Charm version (Charm-1.12.2-1.1.10)

**How to Replicate** This current Incompatibility causes the game to crash anytime a new world is created

Attached is a Log I have from one of my modpacks that had this issue, but I have also tested and Isolated the issue to be between only these two mods.

[Log.txt](https://github.com/svenhjol/Charm/files/3279456/Log.txt)

Note: This issue is not present with the older versions of Charm.

Hope this helps and that 
the issue is fixed soon!

**Comment by angelnc1989** [comment]
[crash-2019-06-12_06.59.42-server.txt](https://github.com/svenhjol/Charm/files/3280461/crash-2019-06-12_06.59.42-server.txt)
Similar crash with Refined Storage

**Comment by svenhjol** [comment]
Thanks for the report. Here's a new build that I would be grateful if you could test. Once confirmed I will upload to CF.

https://github.com/svenhjol/Charm/releases/download/1.12.2-1.1.11/Charm-1.12.2-1.1.11.jar

**Comment by Elwood0** [comment]
Tested with both the latest version of Foresty & Refined Storage (Separately):

Refined Storage works fine with the given version

However, Foresty is still not compatible. :(

**Comment by svenhjol** [comment]
Please try this build:

https://github.com/svenhjol/Charm/releases/download/1.12.2-1.1.12/Charm-1.12.2-1.1.12.jar

**Comment by Elwood0** [comment]
Latest Build works to the best of my knowledge. :)

**Comment by svenhjol** [comment]
Thank you very much for testing!

**Comment by Elwood0** [comment]
Thank you for fixing. Have a good day.
