### ISSUE TITLE
some stuff magnetic doesn't work on

### ISSUE THREAD

**Issue by WarlordWossman** [svenhjol/Charm#85]
In the middle of testing a few things I noticed that magnetic doesn't work on some blocks, this is the list so far:
- vines (with shears)
- cobwebs (with shears)
- extended pistons and sticky pistons (only when you mine the piston head not the base)
- iron doors
- doors
- grass and tall grass (with shears / seed drops when broken with another tool do work tho)
- fern and large fern (with shears)
- 2 tall flower types only work if you break the bottom block
- shulkerboxes
- beds
- leaves (with shears / saplings work when broken with another tool)

**Comment by svenhjol** [comment]
I think that the randomthings solution for catching harvested items has a flaw. I can't be sure, but looking at the code there's a chance that if more than one player breaks blocks with magentic-enchanted tools at the exact same tick, only one of the players will receive their drops. I'll try and work around it for safety.

**Comment by svenhjol** [comment]
Some success, will bake into alpha2 and link here :)

**Comment by svenhjol** [comment]
https://github.com/svenhjol/Charm/releases/download/1.12.2-1.1.13alpha2/Charm-1.12.2-1.1.13-alpha2.jar

**Comment by svenhjol** [comment]
https://github.com/svenhjol/Charm/releases/tag/1.12.2-1.1.13alpha5

**Comment by WarlordWossman** [comment]
works with almost all things in the list of items, will close that and eventually reopen update if I run into new issues again
