### ISSUE TITLE
I lost my backpack

### ISSUE THREAD

**Issue by GoldenXGamerZ** [svenhjol/Charm#853]
So I was playing 1.19.2 with the charm and inmis backpacks mod installed, when i got my endless backpack I went to the nether but died from a fall, when I return to take my things with the totem of preserving I notice the backpack I was wearing in the back slot wasnt there.

**Comment by djsimmonds** [comment]
confirmed that this is an issue for me as well. occurs with any version of backpack in trinket backpack slot (if in inventory, drops like normal). sounds similar to issue #648 (https://github.com/svenhjol/Charm/issues/648) which was for an older version of the mod, which was marked completed in february.

**Comment by ryleu** [comment]
this is not completed, why did you close it?
