### ISSUE TITLE
Crash with "Quark Odditie" Pipe block

### ISSUE THREAD

**Issue by QuerrixTU** [svenhjol/Charm#86]
---- Minecraft Crash Report ----
// Uh... Did I do that?

Time: 2019-06-12 10:49:14 CEST
Description: Ticking block entity

java.lang.ClassCastException: pl.asie.foamfix.common.TileEntityFasterHopper cannot be cast to net.minecraft.tileentity.TileEntityShulkerBox
    at svenhjol.charm.base.ASMHooks.canInsertItemIntoShulkerBox(ASMHooks.java:102)
    at net.minecraftforge.items.ItemHandlerHelper.insertItem(ItemHandlerHelper.java:40)
    at vazkii.quark.oddities.tile.TilePipe.putIntoInv(TilePipe.java:286)
    at vazkii.quark.oddities.tile.TilePipe.canFit(TilePipe.java:266)
    at vazkii.quark.oddities.tile.TilePipe$PipeItem.getTargetFace(TilePipe.java:374)
    at vazkii.quark.oddities.tile.TilePipe$PipeItem.tick(TilePipe.java:344)
    at vazkii.quark.oddities.tile.TilePipe.update(TilePipe.java:109)
    at net.minecraft.world.World.redirect$tileEntityUpdate$zbj000(World.java:4132)
    at net.minecraft.world.World.updateEntities(World.java:1835)
    at net.minecraft.world.WorldServer.updateEntities(WorldServer.java:613)
    at net.minecraft.server.MinecraftServer.updateTimeLightAndEntities(MinecraftServer.java:767)
    at net.minecraft.server.MinecraftServer.tick(MinecraftServer.java:668)
    at net.minecraft.server.integrated.IntegratedServer.tick(IntegratedServer.java:256)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
    at java.lang.Thread.run(Unknown Source)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Block entity being ticked --
  Name: quark:pipe // vazkii.quark.oddities.tile.TilePipe
  Block type: ID #883 (tile.pipe // vazkii.quark.oddities.block.BlockPipe // quark:pipe)
  Block data value: 0 / 0x0 / 0b0000
  Block location: World: (-484,65,-2508), Chunk: (at 12,4,4 in -31,-157; contains blocks -496,0,-2512 to -481,255,-2497), Region: (-1,-5; contains chunks -32,-160 to -1,-129, blocks -512,0,-2560 to -1,255,-2049)
  Actual block type: ID #883 (tile.pipe // vazkii.quark.oddities.block.BlockPipe // quark:pipe)
  Actual block data value: 0 / 0x0 / 0b0000
  Block Entity NBT: {x:-484,pipeItems:[{rngSeed:2056242582908540793L,timeInWorld:45,incomingFace:4,outgoingFace:4,id:"minecraft:wheat_seeds",Count:1b,Damage:0s,ticksInPipe:5},{rngSeed:3203822352947946502L,timeInWorld:63,incomingFace:4,outgoingFace:4,id:"minecraft:wheat_seeds",Count:1b,Damage:0s,ticksInPipe:3}],y:65,z:-2508,id:"quark:pipe"}

-- Affected level --
  Level name: Fucked - UP !!!!
  All players: 1 total; [EntityPlayerMP['Querrix'/91, l='Fucked - UP !!!!', x=-486.60, y=73.00, z=-2512.37]]
  Chunk stats: ServerChunkCache: 291 Drop: 0
  Level seed: -1459824593
  Level generator: ID 06 - quark_realistic, ver 0. Features enabled: true
  Level generator options: 
  Level spawn location: World: (-204,64,-220), Chunk: (at 4,4,4 in -13,-14; contains blocks -208,0,-224 to -193,255,-209), Region: (-1,-1; contains chunks -32,-32 to -1,-1, blocks -512,0,-512 to -1,255,-1)
  Level time: 1786612 game time, 36037 day time
  Level dimension: 0
  Level storage version: 0x04ABD - Anvil
  Level weather: Rain time: 152542 (now: false), thunder time: 15590 (now: false)
  Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: true

-- System Details --
  Minecraft Version: 1.12.2
  Operating System: Windows 10 (amd64) version 10.0
  Java Version: 1.8.0_211, Oracle Corporation
  Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
  Memory: 1306702624 bytes (1246 MB) / 2214592512 bytes (2112 MB) up to 4294967296 bytes (4096 MB)
  JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx4G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
  IntCache: cache: 0, tcache: 0, allocated: 13, tallocated: 95
  FML: MCP 9.42 Powered by Forge 14.23.5.2838 Optifine OptiFine_1.12.2_HD_U_E4_pre1 142 mods loaded, 141 mods active
       States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
       
       | State  | ID                                   | Version           | Source                                      | Signature                                |
       |:------ |:------------------------------------ |:----------------- |:------------------------------------------- |:---------------------------------------- |
       | LCHIJA | minecraft                            | 1.12.2            | minecraft.jar                               | None                                     |
       | LCHIJA | mcp                                  | 9.42              | minecraft.jar                               | None                                     |
       | LCHIJA | FML                                  | 8.0.99.99         | forge-1.12.2-14.23.5.2838.jar               | e3c3d50c7c986df74c645c0ac54639741c90a557 |
       | LCHIJA | forge                                | 14.23.5.2838      | forge-1.12.2-14.23.5.2838.jar               | e3c3d50c7c986df74c645c0ac54639741c90a557 |
       | LCHIJA | foamfixcore                          | 7.7.4             | minecraft.jar                               | None                                     |
       | LCHIJA | dsurroundcore                        | 3.5.4.3           | minecraft.jar                               | None                                     |
       | LCHIJA | fistful_of_hay                       | 1.0.1             | a_fistful_of_hay-1.0.1.jar                  | None                                     |
       | LCHIJA | salwayseat                           | 1.0               | alwayseat-1.1.jar                           | None                                     |
       | LCHIJA | ambientenvironment                   | 1.0.1             | AmbientEnvironment-1.0.1.jar                | None                                     |
       | LCHIJA | anvilfix                             | 1.0.3             | AnvilFix-1.12.2-1.0.3.jar                   | None                                     |
       | LCHIJA | toughasnails                         | 3.1.0.141         | ToughAsNails-1.12.2-3.1.0.141-universal.jar | None                                     |
       | LCHIJA | applejuiceskin                       | 1.0.0.4           | applejuiceskin-1.12.2-1.0.0.4.jar           | None                                     |
       | LCHIJA | jei                                  | 4.15.0.280        | jei_1.12.2-4.15.0.280.jar                   | None                                     |
       | LCHIJA | appleskin                            | 1.0.9             | AppleSkin-mc1.12-1.0.9.jar                  | None                                     |
       | LCHIJA | armiger                              | 1.0.0             | Armiger-1.12.2-1.0.0.jar                    | None                                     |
       | LCHIJA | carrots                              | 1.0.0b1           | carrotslib-mc1.12.2-1.0.0b1.jar             | None                                     |
       | LCHIJA | armorunder                           | 1.0.0             | armorunder-mc1.12.2-1.0.0.jar               | None                                     |
       | LCHIJA | artemislib                           | 1.0.4             | ArtemisLib-1.12.2-v1.0.4.jar                | None                                     |
       | LCHIJA | astikorcarts                         | 1.12.2-0.1.2.7    | astikorcarts-1.12.2-0.1.2.7.jar             | None                                     |
       | LCHIJA | attributefix                         | 1.0.7             | AttributeFix-1.12.2-1.0.7.jar               | d476d1b22b218a10d845928d1665d45fce301b27 |
       | LCHIJA | quark                                | r1.5-158          | Quark-r1.5-158.jar                          | None                                     |
       | LCHIJA | autoreglib                           | 1.3-30            | AutoRegLib-1.3-30.jar                       | None                                     |
       | LCHIJA | baubles                              | 1.5.2             | Baubles-1.12-1.5.2.jar                      | None                                     |
       | LCHIJA | bettercombatmod                      | 1.5.6             | BetterCombat-1.12.2-1.5.6.jar               | None                                     |
       | LCHIJA | forgelin                             | 1.8.2             | Forgelin-1.8.2.jar                          | None                                     |
       | LCHIJA | betterfoliage                        | 2.2.0             | BetterFoliage-MC1.12-2.2.0.jar              | None                                     |
       | LCHIJA | betternether                         | 0.1.8.3           | betternether-0.1.8.3.jar                    | None                                     |
       | LCHIJA | blockdrops                           | 1.4.0             | blockdrops-1.12.2-1.4.0.jar                 | None                                     |
       | LCHIJA | blur                                 | 1.0.4-14          | Blur-1.0.4-14.jar                           | None                                     |
       | LCHIJA | boneappetit                          | 1.0.0.4           | BoneAppetit-1.0.0.4.jar                     | None                                     |
       | LCHIJA | bookshelf                            | 2.3.584           | Bookshelf-1.12.2-2.3.584.jar                | d476d1b22b218a10d845928d1665d45fce301b27 |
       | LCHIJA | bottledmilk                          | 1.0.0             | BottledMilk-1.12-1.1.0.jar                  | None                                     |
       | LCHIJA | brownmooshrooms                      | 1.0.0             | brownmooshrooms-1.0.0.jar                   | None                                     |
       | LCHIJA | bullseye                             | 3.0.7             | Bullseye-1.12.2-3.0.7.jar                   | None                                     |
       | LCHIJA | carryon                              | 1.12.1            | CarryOn+MC1.12.2+v1.12.1.jar                | 55e88f24d04398481ae6f1ce76f65fd776f14227 |
       | LCHIJA | champions                            | 1.12.2-1.0.9      | champions-1.12.2-1.0.9.jar                  | 5d5b8aee896a4f5ea3f3114784742662a67ad32f |
       | LCHIJA | charm                                | 1.12.2-1.1.10     | Charm-1.12.2-1.1.10.jar                     | None                                     |
       | LCHIJA | colytra                              | 1.2.0             | colytra-1.12.2-1.2.0.jar                    | 5d5b8aee896a4f5ea3f3114784742662a67ad32f |
       | LCHIJA | combatrefined                        | 1.4.1             | combatrefined-1.4.2.jar                     | None                                     |
       | LCHIJA | comforts                             | 1.4.1.2           | comforts-1.12.2-1.4.1.2.jar                 | 5d5b8aee896a4f5ea3f3114784742662a67ad32f |
       | LCHIJA | cosmeticarmorreworked                | 1.12.2-v4         | CosmeticArmorReworked-1.12.2-v4.jar         | aaaf83332a11df02406e9f266b1b65c1306f0f76 |
       | LCHIJA | cosmeticarmorreworked|tombmanygraves | 1.12.2-v4         | CosmeticArmorReworked-1.12.2-v4.jar         | aaaf83332a11df02406e9f266b1b65c1306f0f76 |
       | LCHIJA | craftablechainmail                   | 1.0               | craftablechainmail-1.0.jar                  | None                                     |
       | LCHIJA | craftablehorsearmour                 | 1.3               | CraftableHorseArmour-1.3.0-1.12.jar         | None                                     |
       | LCHIJA | crowmap                              | 1.1.1             | crowmap-1.1.1.jar                           | None                                     |
       | LCHIJA | ctm                                  | MC1.12.2-0.3.3.22 | CTM-MC1.12.2-0.3.3.22.jar                   | None                                     |
       | LCHIJA | dawnoftime                           | 0.1               | dawnoftime-alpha-1.0.2.jar                  | None                                     |
       | LCHIJA | disenchanter                         | 1.6               | disenchanter-[1.12]1.6.jar                  | None                                     |
       | LCHIJA | dynamictrees                         | 1.12.2-0.9.5      | DynamicTrees-1.12.2-0.9.5.jar               | None                                     |
       | LCHIJA | mod_lavacow                          | 1.0.3             | Fishs_Undead_Rising-1.0.3.jar               | None                                     |
       | LCHIJA | foamfix                              | 0.10.5-1.12.2     | foamfix-0.10.5-1.12.2.jar                   | None                                     |
       | LCHIJA | gamblingstyle                        | 1.0.1             | GamblingStyle-v1.0.1-1.12.2.jar             | 12d137bcc36051a1c2c8ea7211cfc1da1c6e9dea |
       | LCHIJA | gargoyles                            | 1                 | Gargoyles+mod+1.12.2+patch+1.jar            | None                                     |
       | LCHIJA | giacomosfoundry                      | 1.3.13            | GiacomosFoundry-1.12.2-1.3.13.jar           | None                                     |
       | LCHIJA | glassential                          | 1.1.0             | glassential-1.12.2-1.1.0.jar                | None                                     |
       | LCHIJA | grapplemod                           | 1.12.2-v11.1      | grapplemod-v11.1-1.12.2.jar                 | None                                     |
       | LCHIJA | guardillagers                        | 1.0.1             | guardillagers-1.12.2-1.0.1.jar              | None                                     |
       | LCHIJA | hgp                                  | Release           | hgp-1.0.jar                                 | None                                     |
       | LCHIJA | hunterillager                        | 1.2               | hunterillager-1.12.2-1.2.jar                | None                                     |
       | LCHIJA | waila                                | 1.8.26            | Hwyla-1.8.26-B41_1.12.2.jar                 | None                                     |
       | LCHIJA | llibrary                             | 1.7.19            | llibrary-1.7.19-1.12.2.jar                  | b9f30a813bee3b9dd5652c460310cfcd54f6b7ec |
       | LCHIJA | iceandfire                           | 1.7.1             | iceandfire-1.7.1-1.12.2.jar                 | None                                     |
       | LCHIJA | mantle                               | 1.12-1.3.3.55     | Mantle-1.12-1.3.3.55.jar                    | None                                     |
       | LCHIJA | inspirations                         | 1.12.2-0.2.4      | Inspirations-1.12.2-0.2.4.jar               | None                                     |
       | LCHIJA | jaff                                 | 1.7_for_1.12      | JustAFewFish-1.7_for_1.12.jar               | None                                     |
       | LCHIJA | justenoughbuttons                    | 1.12-1.2          | justenoughbuttons-1.12.2-1.2.3.jar          | None                                     |
       | LCHIJA | jeresources                          | 0.9.2.58          | JustEnoughResources-1.12.2-0.9.2.58.jar     | None                                     |
       | LCHIJA | keywizard                            | 1.12.2-1.6        | keywizard-1.12.2-1.6.jar                    | None                                     |
       | LCHIJA | leatherworks                         | 1.78.0            | LeatherWorks-1.12-1.78.0.42.jar             | None                                     |
       | LCHIJA | lex                                  | 1.0.8             | LibEx-1.12.2-1.0.8.jar                      | None                                     |
       | LCHIJA | linear                               | 1.2.2             | Linear+MC1.12.2+v1.2.2.jar                  | None                                     |
       | LCHIJA | magicalsculpture                     | 0.99              | magicalsculpture-1.0.0.jar                  | None                                     |
       | LCHIJA | wumpleutil                           | 2.12.6            | wumpleutil-1.12.2-2.12.6.jar                | 1e57901a90acd4a3a54295b6decff5397be51a31 |
       | LCHIJA | megamap                              | 1.1.0             | megamap-1.12.2-1.1.0.jar                    | 1e57901a90acd4a3a54295b6decff5397be51a31 |
       | LCHIJA | mirageorb                            | 1.1.0             | mirageorb-1.12.2-1.1.0.jar                  | None                                     |
       | LCHIJA | modnametooltip                       | 1.10.0            | modnametooltip_1.12.2-1.10.0.jar            | None                                     |
       | LCHIJA | mowziesmobs                          | 1.5.4             | mowziesmobs-1.5.4.jar                       | None                                     |
       | LCHIJA | multimob                             | 1.0.5             | multimob-1.0.5.jar                          | None                                     |
       | LCHIJA | multithreadednoise                   | 0.0.2             | MultithreadedNoise-1.12.2-0.0.2.jar         | None                                     |
       | LCHIJA | naturalbabyanimals                   | 1.2.0             | naturalbabyanimals-1.2.0-mc1.12.x.jar       | None                                     |
       | LCHIJA | netherchest                          | 1.1.1             | netherchest-1.1.1.jar                       | None                                     |
       | LCHIJA | nex                                  | 2.0.8             | NetherEx-1.12.2-2.0.8.jar                   | None                                     |
       | LCHIJA | rustic                               | 1.1.0             | rustic-1.1.0.jar                            | None                                     |
       | LCHIJA | ore_stone_variants                   | 4.3               | ore_stone_variants-4.4.jar                  | None                                     |
       | LCHIJA | overpoweredarmorbar                  | @VERSION@         | overloadedarmorbar-1.0.4g.jar               | None                                     |
       | LCHIJA | packingtape                          | 0.7.6             | PackingTape-1.12.2-0.7.6.jar                | None                                     |
       | LCHIJA | paraglider                           | 1.0.1.4           | Paraglider-1.12.2-1.0.1.4.jar               | None                                     |
       | LCHIJA | particlefixes                        | 1.0.2             | ParticleFixes-v1.0.2-1.12.2.jar             | 12d137bcc36051a1c2c8ea7211cfc1da1c6e9dea |
       | LCHIJA | patchouli                            | 1.0-19            | Patchouli-1.0-19.jar                        | None                                     |
       | LCHIJA | pillagers                            | 1.0.4             | Pillagers-1.12.2-1.0.4.jar                  | d476d1b22b218a10d845928d1665d45fce301b27 |
       | LCHIJA | prettybeaches                        | 1.0.4             | PrettyBeaches_1.12.2-1.0.4.jar              | None                                     |
       | LCHIJA | primitivemobs                        | 1.2.3a            | primitivemobs-1.2.3a.jar                    | None                                     |
       | LCHIJA | quarkoddities                        | 1                 | QuarkOddities-1.12.2.jar                    | None                                     |
       | LCHIJA | rats                                 | 1.0.1             | rats-1.0.1.jar                              | None                                     |
       | LCHIJA | realisticbrewingstand                | 3.1.0             | realisticbrewingstand-3.1.0.jar             | None                                     |
       | LCHIJA | realistictorches                     | 2.1.1             | RealisticTorches-1.12.2-2.1.1 (1).jar       | None                                     |
       | LCHIJA | xreliquary                           | 1.12.2-1.3.4.786  | Reliquary-1.12.2-1.3.4.786.jar              | None                                     |
       | LCHIJA | resize                               | 2.1.1             | resizingpotion-2.1.1.jar                    | None                                     |
       | LCHIJA | respawnablepets                      | 1.0.4.1           | respawnablepets-1.0.4.1.jar                 | None                                     |
       | LCHIJA | rbeacons                             | 1.0.0             | responsivebeacons-1.0.0-1.12.2.jar          | None                                     |
       | LCHIJA | roost                                | 2.0.10            | roost-1.12.2-2.0.10.jar                     | None                                     |
       | LCHIJA | saltmod                              | 1.12.6.0          | SaltyMod-1.12.2-1.12.6.0.jar                | None                                     |
       | LCHIJA | sereneseasons                        | 1.2.16            | SereneSeasons-1.12.2-1.2.16-universal.jar   | None                                     |
       | LCHIJA | ilja615shamanism                     | 0.3               | shamanism-0.3.jar                           | None                                     |
       | LCHIJA | shouldersurfing                      | 1.16              | ShoulderSurfing-1.12.2-1.15.1.jar           | d6261bb645f41db84c74f98e512c2bb43f188af2 |
       | LCHIJA | simpleflax                           | 1.2.1             | SimpleFlax-1.2.1.jar                        | None                                     |
       | LCHIJA | simulatednights                      | 1.12-2.1.0        | simulatednights-1.12-2.1.0.jar              | None                                     |
       | LCHIJA | smarthud                             | 2.0.2             | smarthud-2.0.2.jar                          | None                                     |
       | LCHIJA | smoothwater                          | 0.1.4             | SmoothWater-0.1.4.jar                       | None                                     |
       | LCHIJA | soundfilters                         | 0.10_for_1.12     | SoundFilters-0.10_for_1.12.jar              | None                                     |
       | LCHIJA | spartanweaponry                      | beta 1.2.3        | SpartanWeaponry-1.12.2-beta-1.2.3.jar       | None                                     |
       | LCHIJA | stacksize                            | 1.1               | stacksize-1.12.2-1.0.jar                    | None                                     |
       | LCHIJA | strawgolem                           | 1.3               | strawgolem-1.3.jar                          | None                                     |
       | LCHIJA | surge                                | 2.0.77            | Surge-1.12.2-2.0.77.jar                     | d476d1b22b218a10d845928d1665d45fce301b27 |
       | LCHIJA | swampland                            | 2.2               | Swamp-2.2.jar                               | None                                     |
       | LCHIJA | tanspit                              | 1.12.2-1.3        | tanspit-1.12.2-1.3.jar                      | None                                     |
       | LCHIJA | thesummoner                          | 1.0.1-beta        | thesummoner-1.0.1.jar                       | None                                     |
       | LCHIJA | toolhelper                           | 1.0               | toolhelper-1.0b.jar                         | None                                     |
       | LCHIJA | twilightforest                       | 3.9.948           | twilightforest-1.12.2-3.9.948-universal.jar | None                                     |
       | LCHIJA | unenchanting                         | 1.1.1             | unenchanting-1.1.1.jar                      | None                                     |
       | LCHIJA | vanillafix                           | 1.0.10-SNAPSHOT   | VanillaFix-1.0.10-99.jar                    | None                                     |
       | LCHIJA | wailaharvestability                  | 1.1.12            | WailaHarvestability-mc1.12-1.1.12.jar       | None                                     |
       | LCHIJA | watercontrolextreme                  | 1.0.0             | WaterControlExtreme-1.0.2.jar               | None                                     |
       | LCHIJA | wawla                                | 2.5.273           | Wawla-1.12.2-2.5.273.jar                    | d476d1b22b218a10d845928d1665d45fce301b27 |
       | LCHIJA | waystones                            | 4.0.67            | Waystones_1.12.2-4.0.67.jar                 | None                                     |
       | LCHIJA | wearablebackpacks                    | 3.1.3             | WearableBackpacks-1.12.2-3.1.3.jar          | None                                     |
       | LCHIJA | wings                                | 1.1.5             | wings-1.1.5-1.12.2.jar                      | None                                     |
       | LCHIJA | bauble_wings                         | 1.0.0             | wings-1.1.5-1.12.2.jar                      | None                                     |
       | LCHIJA | wolfarmor                            | 3.3.0.279         | wolfarmor-1.12.2-3.3.0.279-SNAPSHOT-all.jar | None                                     |
       | LCHIJA | wooltostring                         | 1.12.2            | WoolToString-1.12.2-1.0.0.jar               | None                                     |
       | LCHIJA | xpfromharvest                        | 1.1.0             | xpfromharvest-1.12.2-1.1.0.jar              | None                                     |
       | LCHIJA | xpholder                             | 2.0.4             | XpHolder-2.0.4-mc1.12.x.jar                 | None                                     |
       | LCHIJA | zenny3d.saturationoverflow           | 1.1.1             | zenny3d.saturationoverflow-1.1.1.jar        | None                                     |
       | LCHIJA | lemonlib                             | 1.3.0             | lemonlib-1.12.2-1.3.0.jar                   | None                                     |
       | LCHIJA | arcaneworld                          | 0.0.11            | arcaneworld-1.12.2-0.0.11.jar               | None                                     |
       | LCHIJA | orelib                               | 3.5.2.2           | OreLib-1.12.2-3.5.2.2.jar                   | 7a2128d395ad96ceb9d9030fbd41d035b435753a |
       | LCHIJA | dsurround                            | 3.5.4.3           | DynamicSurroundings-1.12.2-3.5.4.3.jar      | 7a2128d395ad96ceb9d9030fbd41d035b435753a |
       | LCHIJA | nimble                               | 0.0.2             | Nimble-0.0.2.jar                            | None                                     |
       | LCHIJA | phosphor-lighting                    | 1.12.2-0.2.4      | phosphor-1.12.2-0.2.4+build46-universal.jar | f0387d288626cc2d937daa504e74af570c52a2f1 |
       | LCHIJA | snowrealmagic                        | 0.3.1             | SnowRealMagic-0.3.1.jar                     | None                                     |
       | LCHIJA | worldsretold                         | 1.0.5             | Worlds+Retold-+(v1.0.5)+14.23.5.2784.jar    | None                                     |
       | UD     | mobends_wings                        | 1.0.0             | wings-1.1.5-1.12.2.jar                      | None                                     |
  Loaded coremods (and transformers): wings (wings-1.1.5-1.12.2.jar)
                                        me.paulf.wings.server.asm.WingsRuntimePatcher
                                        me.paulf.wings.server.asm.mobends.WingsMoBendsRuntimePatcher
                                      Do not report to Forge! (If you haven't disabled the FoamFix coremod, try disabling it in the config! Note that this bit of text will still appear.) (foamfix-0.10.5-1.12.2.jar)
                                        pl.asie.foamfix.coremod.FoamFixTransformer
                                      Particle Fixes (ParticleFixes-v1.0.2-1.12.2.jar)
                                        com.fuzs.particlefixes.asm.ClassTransformer
                                      ShoulderPlugin (ShoulderSurfing-1.12.2-1.15.1.jar)
                                        com.teamderpy.shouldersurfing.asm.ShoulderTransformations
                                      ForgelinPlugin (Forgelin-1.8.2.jar)
                                        
                                      CTMCorePlugin (CTM-MC1.12.2-0.3.3.22.jar)
                                        team.chisel.ctm.client.asm.CTMTransformer
                                      llibrary (llibrary-core-1.0.11-1.12.2.jar)
                                        net.ilexiconn.llibrary.server.core.plugin.LLibraryTransformer
                                        net.ilexiconn.llibrary.server.core.patcher.LLibraryRuntimePatcher
                                      Realistic Brewing Stand (realisticbrewingstand-3.1.0.jar)
                                        mjaroslav.mcmods.realisticbrewingstand.gloomyfolken.hooklib.minecraft.PrimaryClassTransformer
                                      PhosphorFMLLoadingPlugin (phosphor-1.12.2-0.2.4+build46-universal.jar)
                                        
                                      BlurPlugin (Blur-1.0.4-14.jar)
                                        com.tterrag.blur.BlurTransformer
                                      VanillaFixLoadingPlugin (VanillaFix-1.0.10-99.jar)
                                        
                                      SSLoadingPlugin (SereneSeasons-1.12.2-1.2.16-universal.jar)
                                        sereneseasons.asm.transformer.EntityRendererTransformer
                                        sereneseasons.asm.transformer.WorldTransformer
                                      SurgeLoadingPlugin (Surge-1.12.2-2.0.77.jar)
                                        
                                      BetterFoliageLoader (BetterFoliage-MC1.12-2.2.0.jar)
                                        mods.betterfoliage.loader.BetterFoliageTransformer
                                      WolfArmorCore (wolfarmor-1.12.2-3.3.0.279-SNAPSHOT-all.jar)
                                        
                                      SmoothWaterCore (SmoothWater-0.1.4.jar)
                                        pl.asie.smoothwater.SmoothWaterTransformer
                                      ColytraLoadingPlugin (colytra-1.12.2-1.2.0.jar)
                                        c4.colytra.asm.ElytraTransformer
                                      Quark Plugin (Quark-r1.5-158.jar)
                                        vazkii.quark.base.asm.ClassTransformer
                                      DynamicSurroundingsCore (DynamicSurroundings-core-1.12.2-3.5.4.3.jar)
                                        org.orecruncher.dsurround.asm.Transformer
                                      Snow! Real Magic! Core Mod (SnowRealMagic-0.3.1-coremod.jar)
                                        snownee.snow.asm.ASMTransformer
                                      ParagliderLoadingPlugin (Paraglider-1.12.2-1.0.1.4.jar)
                                        com.tictim.paraglider.asm.TransformerModelBiped
                                      CharmLoadingPlugin (Charm-1.12.2-1.1.10.jar)
                                        svenhjol.charm.base.CharmClassTransformer
  GL info: ~~ERROR~~ RuntimeException: No OpenGL context found in the current thread.
  Pulsar/inspirations loaded Pulses: - InspirationsShared (Enabled/Forced)
                                     - InspirationsBuilding (Enabled/Not Forced)
                                     - InspirationsUtility (Enabled/Not Forced)
                                     - InspirationsTools (Enabled/Not Forced)
                                     - InspirationsRecipes (Enabled/Not Forced)
                                     - InspirationsTweaks (Enabled/Not Forced)
                                     - InspirationsShared (Enabled/Forced)
                                     - ToughAsNailsPlugin (Enabled/Not Forced)
                                     - WailaPlugin (Enabled/Not Forced)
  Suspected Mods: Charm (charm), Quark (quark)
  Profiler Position: N/A (disabled)
  Player Count: 1 / 8; [EntityPlayerMP['Querrix'/91, l='Fucked - UP !!!!', x=-486.60, y=73.00, z=-2512.37]]
  Type: Integrated Server (map_client.txt)
  Is Modded: Definitely; Client brand changed to 'fml,forge'

**Comment by WarlordWossman** [comment]
Thanks for the report! 
Please use pastebin or github gist next time for the crashlog, it's a bit easier to work with.

**Comment by svenhjol** [comment]
Here's a new build that I would be grateful if you could test. Once confirmed I will upload to CF. Thank you.

https://github.com/svenhjol/Charm/releases/download/1.12.2-1.1.11/Charm-1.12.2-1.1.11.jar
