### ISSUE TITLE
Charm + akashic tome of tools crash

### ISSUE THREAD

**Issue by DanMeadWasTaken** [svenhjol/Charm#860]
Here's the log.

https://paste.ee/p/YnbVM

**Comment by DanMeadWasTaken** [comment]
As a side note, I updated to 1.3.7 of akashic tome of tools mod, and It still spits out the same exact error

**Comment by DanMeadWasTaken** [comment]
Well, the author of the akashic tome of tools has said he'll look into it this weekend, so I'm keeping my fingers crossed that it get's fixed if they can fix it on their end

**Comment by AndreAugustoAAQ** [comment]
I also confirm that it causes crashes
https://mclo.gs/qigtWDs
See vlad2305m/AkashicTomeOfToolsFabric#9

**Comment by vlad2305m** [comment]
Use plugin to not apply "stackable_enchanted_books.FixAnvilBookStackMixin" when akashictomeoftools is loaded (like https://github.com/vlad2305m/AkashicTomeOfToolsFabric/blob/d5ceeae9014090586159eff52fb2f5d52ed3fa51/src/main/java/vazkii/akashictomeoftools/mixin/plugin/ModCompatPlugin.java#L49)
