### ISSUE TITLE
charm causes my particular mod pack to crash after a short while...

### ISSUE THREAD

**Issue by gravysamich** [svenhjol/Charm#9]
i am not sure what causes it, but i am certain the mod responsible is charm. it is the one mod i removed and suddenly it stopped crashing.

here is a link to a pastebin of the crash report.

https://pastebin.com/4rwaCjDz

**Comment by svenhjol** [comment]
Thanks for the crash report. It seems to be something happening when mystcraft is profiling and a village is constructed. I’ll do some debugging with mystcraft.

**Comment by svenhjol** [comment]
Fixed in alpha4 https://github.com/svenhjol/Charm/commit/8d7c5e320f70d27850a6fcd38eb7f2131e12c367

**Comment by gravysamich** [comment]
awesome!
