### ISSUE TITLE
[Enhancement] Enchantment Descriptions support

### ISSUE THREAD

**Issue by angelnc1989** [svenhjol/Charm#90]
It would be nice if you could add [Enchantment Descriptions](https://minecraft.curseforge.com/projects/enchantment-descriptions?gameCategorySlug=mc-mods&projectID=250419) support for the enchantments Charm adds. It's easy to implement. Just one key in the localization file.

**Comment by svenhjol** [comment]
Yep this looks good, will fit it in soon

**Comment by svenhjol** [comment]
Will be in 1.2.1
