### ISSUE TITLE
Cursing should respect item's canApplyAtEnchantingTable method

### ISSUE THREAD

**Issue by Drullkus** [svenhjol/Charm#91]
Related to TeamTwilight/twilightforest#748

https://github.com/svenhjol/Charm/blob/master/src/main/java/svenhjol/meson/helper/EnchantmentHelper.java#L70

One of our armors in the Twilight Forest has an inherent ability to persist on the player, and as such we've disabled adding Curse of Vanishing on that armor in the `canApplyAtEnchantingTable`. The anvil also checks this method to see if an enchantment can be anviled onto an item.

I recommend adding a `canApplyAtEnchantingTable` check in the code above that I linked for these kinda situations. Thanks!

**Comment by svenhjol** [comment]
Something like this (at line https://github.com/svenhjol/Charm/blob/619e3df5617905978af1f7222126e4c3da24a640/src/main/java/svenhjol/meson/helper/EnchantmentHelper.java#L127) 

`if (itemToCurse != null && curse.canApplyAtEnchantingTable(itemToCurse)) {` 

?

**Comment by svenhjol** [comment]
I've created an alpha build of the next release of Charm that tests the item against the curse. Could you give this a test please and let me know if it works how you expect? Anything else I can do give me a shout
[Charm-1.12.2-1.1.13-alpha.zip](https://github.com/svenhjol/Charm/files/3288112/Charm-1.12.2-1.1.13-alpha.zip)

**Comment by svenhjol** [comment]
This change will be in the next release, please comment here if there is still a problem with 1.1.13. Closing now
