### ISSUE TITLE
Crash when applying stair texture to Blood Magic mimic block

### ISSUE THREAD

**Issue by Aphyxia** [svenhjol/Charm#93]
Tried applying a stair block texture to ethereal mimic opaque block from Blood Magic and game crashed. Tried normal blocks and it worked.
For some reason it references charm and that new ender portal feature in the tracelog so I figure its probably Charm. Also, clicking or trying to mine the block afterwards causes a crash.

Crashlog: https://paste.dimdev.org/gukumufocu.mccrash

Newest versions of all.

**Comment by svenhjol** [comment]
Thanks, I'll take a look.

**Comment by svenhjol** [comment]
Please test https://github.com/svenhjol/Charm/releases/download/1.12.2-1.1.13alpha2/Charm-1.12.2-1.1.13-alpha2.jar and see if you get the crash

**Comment by Aphyxia** [comment]
Tested it and seems to be fixed. Worked on both single player and multiplayer now.
Tried for fun to insert a thermal expansion machine to the mimic block and got another crash but since this time Charm wasn't mentioned in the error log I'm guessing it's just the way the Blood Magic mod is programmed. I'll abstain from using those blocks from now on since Botania has a block that does the same thing but without crashes.

**Comment by svenhjol** [comment]
Thanks for testing. There's something definitely non-standard about the way the mimic thing is working.
