### ISSUE TITLE
[Enhancement]Disable vanilla tools on WorldGen

### ISSUE THREAD

**Issue by SjetCraft** [svenhjol/Charm#94]
Not sure how feasible this is but a config option to disable vanilla tools from generating in villages would be spectacular.
If you use an alternative tool mod, such as Adventurer's Toolbox, you don't want vanilla tools generating in game.

Currently vanilla tools generate in both item frames and armor stands in villages. At the moment those can be disabled but then you loose the other things that generate in those items.

Alternatively, a much more difficult approach would be to open the item frame and armor stands to a CraftTweaker or json importer to customize what gets generated with them.

**Comment by svenhjol** [comment]
It’s cool, this can be done.

**Comment by svenhjol** [comment]
Will be in 1.2.1
