### ISSUE TITLE
Crash with Metamorph

### ISSUE THREAD

**Issue by WenXin20** [svenhjol/Charm#97]
Minecraft v1.12.2
Forge v14.253.5.2838
[Better Animals Plus](https://minecraft.curseforge.com/projects/betteranimalsplus) v6.0.3
[Metamorph](https://minecraft.curseforge.com/projects/metamorph) v1.1.8
Charm v1.1.12

I got this crash after killing a badger from Better Animals Plus along with having Metamorph installed. It seems to be related to tamed animals, although the badger wasn't tamed.
[Crash Log](https://gist.github.com/WenXin20/c2ae4e484f84287f62cfb6594a306868)

**Comment by svenhjol** [comment]
Please attach a crash report, or there's nothing I can do.

**Comment by svenhjol** [comment]
Ignore me :) I'll look at it now

**Comment by svenhjol** [comment]
Please can you try this build and let me know if it still happens?
[Charm-1.12.2-1.1.13-alpha3.zip](https://github.com/svenhjol/Charm/files/3306816/Charm-1.12.2-1.1.13-alpha3.zip)

**Comment by WenXin20** [comment]
I don't have time right now, but I should be able to try later tonight.

**Comment by svenhjol** [comment]
New build: https://github.com/svenhjol/Charm/releases/tag/1.12.2-1.1.13alpha5

**Comment by svenhjol** [comment]
Were you able to test the build?

**Comment by WenXin20** [comment]
Sorry, just now got back to it. Yes Alpha 5 seems to have worked. :)-----------------------Sincerely, David NewvilleOn Jun 21, 2019 12:46 PM, Sven H <notifications@github.com> wrote:Were you able to test the build?

**Comment by svenhjol** [comment]
Fixed in https://github.com/svenhjol/Charm/releases/tag/1.12.2-1.1.13
