### ISSUE TITLE
Iron duplication with rails

### ISSUE THREAD

**Issue by Vazkii** [svenhjol/Charm#98]
If FurnacesRecycleMore is enabled, rails smelt to 18 iron nuggets. This produces enough iron ingots for an infinite loop.

**Comment by svenhjol** [comment]
Willdo, thanks for spotting.

**Comment by WarlordWossman** [comment]
This is probably a more fundamental flaw that applies to all the recipes that output multiple items.
If I recall correctly you check (or define) how many ingots a recipe uses, realistically that number would have to be devided by the number of output items to make sense, on fractals rounding down.

**Comment by svenhjol** [comment]
There is a config syntax for it, and the defaults probably need reviewing. I’ll check over it with you soon.

**Comment by WarlordWossman** [comment]
yeah we just need to do
>ingots in recipe / output items

and use that to update the standard config, I am afraid some items don't work anymore, for rails you get 16 from 6 ingots so the updated config would be 6/16 ingots which is less than 1 and thus doesn't work with the current system.

Personally I don't think you should be able to recycle items without durability at all, kinda what I did with my config in Gluon.

**Comment by svenhjol** [comment]
Changing `minecraft:rail` to `minecraft:rail->minecraft:iron_ingot->6` yields 18 nuggets for each piece of rail, so 2 full ingots. That seems like a reasonable return for rails and ok for stopgap solution. I get what you're saying about the formula for using output item stack size.

**Comment by WarlordWossman** [comment]
>That seems like a reasonable return for rails and ok for stopgap solution.

I am a bit confused, isn't that the problem since you can make 16 rails from only smelting 3 rails right now?

![rails](https://user-images.githubusercontent.com/16925725/59969349-894b2580-954b-11e9-86ba-b07298c01274.PNG)

**Comment by svenhjol** [comment]
Yes. Yes it is. I should get more sleep I reckon

**Comment by svenhjol** [comment]
Ok, this seems to work in terms of return:
```
            minecraft:rail->minecraft:iron_ingot->1
            minecraft:detector_rail->minecraft:iron_ingot->1
            minecraft:activator_rail->minecraft:iron_ingot->1
            minecraft:golden_rail->minecraft:gold_ingot->1
            minecraft:iron_door->minecraft:iron_ingot->2
            minecraft:iron_bars->minecraft:iron_ingot->1
```

With rails being equivalent to having 1 ingot per rail, that's 3 nuggets per rail, so 48 ingots per stack of 16. Yields 5.3 ingots, which isn't enough iron to allow an entirely new stack of 16 to be created.

I also changed the iron bars because they suffer from the same issue.

In future I might revisit this feature but it solves the duplication problem for now.

**Comment by svenhjol** [comment]
Please update local charm.cfg with above values where appropriate.  Fixed in https://github.com/svenhjol/Charm/releases/tag/1.12.2-1.1.13
